### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#10]
I would like to have a button to read an article in the full-screen mode. This will be good especially if you're using midnight theme. If you can add the possibility to use "up" & "down" or "left" & "right" button to change the article, that would be awesome!

**Comment by jangernert** [comment]
feature pretty much done in the [fullscreen-branch](https://github.com/jangernert/FeedReader/commits/fullscreen)
Watching fullscreen videos currently breaks (exits) the fullscreen mode for articles. No idea if it is possible to work around this issue: https://lists.webkit.org/pipermail/webkit-gtk/2016-June/002694.html

**Comment by jangernert** [comment]
branched 1.6 and merged this to master
