### ISSUE TITLE
Add support for "the old reader"

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#11]
https://github.com/theoldreader/api

**Comment by kanishkablack** [comment]
Hai,

https://github.com/kanishkablack/FeedReader/tree/oldreader

- [x] Login

- [x] Sync Subscriptions

- [x] Sync Unread Articles

- [x] Sync Streams Articles

- [ ] Mark As Read (Article and Categories)

- [ ] Mark Stared

**Comment by jangernert** [comment]
good job
But still, after you finish the old reader backend I would prefer not to add any more backends to the code for now. I still have things planned that will need some work on all existing backends. So having too many only makes it more complicated to land the other features ;)

**Comment by kanishkablack** [comment]
@jangernert  i understand the issue, any way when you decided to work on integrating additional services, please do let me know, i already built code for FeedHQ and other compliant services.

**Comment by jangernert** [comment]
Hey,
If you want to continue to work on this, now would be a good time to sync your branch with master and finish the backend.
When 1.6 is released we can start merging stuff into master again.

**Comment by kanishkablack** [comment]
Sure, will update the integration will update in next coming days.

**Comment by kanishkablack** [comment]
@jangernert hey, just pushed theoldreader api into beta stages, once tested the features

https://github.com/kanishkablack/FeedReader/tree/BazQux

there few things , that are beyond my domain like icon

**Comment by jangernert** [comment]
merged
