### ISSUE TITLE
Graphic glitch on Ubuntu 16.04 when minimizing the window

### ISSUE THREAD

**Issue by ContactFront** [jangernert/FeedReader#118]
Ubuntu 16.04 LTS
Gnome 3.18
Latest version of FeedReader from stable ppa

When clicking the minimize button, entire desktop would disappear for a second with only wallpaper left. When everything comes back on, would need to click the button again to minimize the window.

**Comment by ContactFront** [comment]
Tested a bit more. Seems that this happens when the window is maximized. When it's not, it minimizes without issue.

**Comment by jangernert** [comment]
Can you install another desktop-environment-package and test there? For example gnome-shell with mutter.
My guess is either the ubuntu radiance/ambiance-theme or compiz. Both are causing trouble all the time and are old, obsolete and kept on life support until unity 8 is ready (wasn't it supposed to come with 12.10? :D)

**Comment by ContactFront** [comment]
Thanks I'll give it a try. I'm also suspecting it could be an issue with my desktop as this just happened with Corebird as well :(
