### ISSUE TITLE
Transparent line

### ISSUE THREAD

**Issue by kamiszczu** [jangernert/FeedReader#120]
Transparent line on TopBar.
Version: 1.4.3.
OS: Ubuntu 16.04

![a](https://cloud.githubusercontent.com/assets/5055672/15269518/571508d8-1a01-11e6-9373-eb56ca46cb48.png)

**Comment by bil-elmoussaoui** [comment]
@kamiszczu Can you try using the 1.6 beta version and check if you still have this problem? We have reworked the gtk theme and it should be fixed!

**Comment by kamiszczu** [comment]
Version: 1.6 Beta looks like this

![1](https://cloud.githubusercontent.com/assets/5055672/15274962/ab637186-1abf-11e6-99ea-789dcba07d65.png)

**Comment by bil-elmoussaoui** [comment]
Alright, i will take a closer look. Does it happen with other themes too or only with the default theme on Ubuntu?

**Comment by kamiszczu** [comment]
This is Paper theme so bug is only default theme

![2](https://cloud.githubusercontent.com/assets/5055672/15274993/6eba57da-1ac0-11e6-9285-971999cbab8b.png)

**Comment by bil-elmoussaoui** [comment]
The application is using the default color variables defined on the theme css files. There's no way to check if a variable exists on CSS :( 
I will see if i can do something to fix that, but no promisses. One more thing, which gtk version is used by default on Ubuntu 16.04?

**Comment by kamiszczu** [comment]
In my Ubuntu 16.04 is 3.18.9-1ubuntu3

**Comment by bil-elmoussaoui** [comment]
Well i think i've found the solution but as i'm using Gtk 3.20 i can't try it.
Can you open your default text editor as root and go to `/usr/share/FeedReader/gtk-css/pre320` and open `basics.css`. After that, go to  `.headerbar_pane.pane-separator` and add this line `color: mix(@theme_bg_color, @theme_fg_color, 0.5);` it should be like that after the modification 
```css
.headerbar_pane.pane-separator {
	border-radius: 0;
	border-width: 0 1px 1px 0;
	color: mix(@theme_bg_color, @theme_fg_color, 0.5);
}
```
Save the file, and  `pkill feedreader` in order to close the application. Open the application again and it should be fixed i hope!

**Comment by kamiszczu** [comment]
Still is transparent line :/

**Comment by bil-elmoussaoui** [comment]
Ok, thanks i will fix that soon!-

**Comment by lcapalbo** [comment]
Changing .titlebar .pane-separator  to:

.titlebar .pane-separator {
    background-color:  @dark_bg_color;
    background-image: none;
}

worked better for me (not perfect, as there's no gradient, but looks fine on ambience & radience)

**Comment by jangernert** [comment]
I think this is a good compromise.

```
.titlebar .pane-separator {
    background-color: shade(@theme_bg_color, 0.4);
    background-image: none;
}
```

What do you think?
The plain dark_bg_color screws with other themes.

**Comment by lcapalbo** [comment]
Looks nice, tried a few other themes and they all look fine with that. Thanks

**Comment by jangernert** [comment]
Thank you for moving this into the right direction ;)
