### ISSUE TITLE
Text not selectable in Article View

### ISSUE THREAD

**Issue by elya5** [jangernert/FeedReader#123]
With the 1.6 beta it is not possible to select text in the article view. This is probably the case because you connected to the the button events for the scrolling and clicking on images.
However, it would be cool if text selection would be possible as well e.g. for looking up words or copy-and-pasting  code snippets.

**Comment by jangernert** [comment]
It's available as a tweak in gsettings:
Open up dconf-editor and go to org->gnome->feedreader->tweaks and check "article-select-text"

**Comment by jangernert** [comment]
Oh, no nothing to do with the popup, I wanted to make the header unselectable but screwed up and made the whole article unselectable by default. I just didn't notice since I don't activate the tweak "article-select-text" on my machine. Thx for noticing ;)

**Comment by lightonflux** [comment]
Using Version: 1.6 beta
Git Commit: 65a910e34e19d6ec310b54226da4a4b3a1ebbda5

And i can't select the text. :(

**Comment by jangernert** [comment]
Do you have "article-select-text" activated in the tweaks section of gsettings?

**Comment by lightonflux** [comment]
No i had not. Activated and it works.
