### ISSUE TITLE
daemon crashes on prosessing gimp.org

### ISSUE THREAD

**Issue by haeckle** [jangernert/FeedReader#124]
OS: Arch Linux
Version: 1.6 Beta (installed via AUR "feedreader-git" on commit 1adba4af95a80aedc64741066a22d00b0ca74cf6)
Backend: tt-rss
commandline ouptput:
> [ DEBUG ] Grabber: process article: //www.gimp.org/news/2016/05/23/gimp-2-10-docs-update-call/
> [ DEBUG ] Grabber: no config (.txt) found for article: //www.gimp.org/news/2016/05/23/gimp-2-10-docs-update-call/
> [ DEBUG ] Grabber: no config (.txt) - cutSubdomain - found for article: //www.gimp.org/news/2016/05/23/gimp-2-10-docs-update-call/
> Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by jangernert** [comment]
The good news is, I can reproduce the issue.
So now I can start to figure out why :P

**Comment by haeckle** [comment]
Thanks for the quick fix!
