### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#127]
https://github.com/jangernert/FeedReader/blob/af59378c9c433628c18b2b2ddd48993c7f4f38a2/src/Widgets/ArticleList.vala#L954

This code generate untranslatable string: "No unread articles could be found"
![2016-05-25 16-54-14](https://cloud.githubusercontent.com/assets/4980269/15542411/562f276e-2299-11e6-85dd-64c7758144ca.png)

**Comment by horosgrisa** [comment]
Also, update translation from transifex

**Comment by bil-elmoussaoui** [comment]
@horosgrisa Which language should be updated? I only update the `po` files from transifex when the translation is complete.

**Comment by horosgrisa** [comment]
@jangernert Please, update translation. For example. I can't find 'Media Player' string at transifex. Also, import russian translation in to repository.

**Comment by bil-elmoussaoui** [comment]
I will do asap

**Comment by bil-elmoussaoui** [comment]
@horosgrisa I updated the pot file on Transifex! Please ping me next time instead of @jangernert as i'm the maintainer of the FeedReader account on Transifex. Thanks!

**Comment by horosgrisa** [comment]
@bil-elmoussaoui OK

**Comment by horosgrisa** [comment]
@bil-elmoussaoui Hi, please add posibility to translate to Romanian

**Comment by bil-elmoussaoui** [comment]
@horosgrisa Done for the Romanian language. I will update all the translations later (before the next release of course)! Still waiting for Transifex to create a bot to push the translations to Github automatically :(

**Comment by horosgrisa** [comment]
OK. I found issue in shorcuts window. 
![screenshot_20160811_012834](https://cloud.githubusercontent.com/assets/4980269/17573481/41c4deca-5f63-11e6-97da-372d981d7501.png)

**Comment by bil-elmoussaoui** [comment]
What's the issue? Can you please open new issues instead of commenting on old ones. To keep the issues tracker clean and help us refrence the issue on each commit.

**Comment by ZanderBrown** [comment]
@bil-elmoussaoui  Maybe he's referencing the fact the shortcut labels are in English whilst the window title clearly is not? Still unclear and almost certainly should be separate

**Comment by bil-elmoussaoui** [comment]
@ZanderBrown The window title is generated by Gtk so it's translated to all languages. The rest of the window is translated by our translation team. And we didn't update russian translation yet. Hope it's clear now :)

**Comment by ZanderBrown** [comment]
@bil-elmoussaoui I'm aware if this. I was trying to understand what @horosgrisa's new issue was from the rather cryptic 'OK. I found issue in shorcuts window. '

**Comment by bil-elmoussaoui** [comment]
@ZanderBrown Sorry i tagged you instaed of @horosgrisa! Thanks :)

**Comment by horosgrisa** [comment]
@bil-elmoussaoui You can remove language `ro_RO`  from transifex? Leave only `ro` and make me an translator for this language.

**Comment by bil-elmoussaoui** [comment]
You need to click on the language, theres somewhere a link to ask to join
the translators of this language, once its done i will accept your request
