### ISSUE TITLE
Menu in headerbar under GNOME Wayland

### ISSUE THREAD

**Issue by haeckle** [jangernert/FeedReader#128]
As title says, in a wayland session the menu doesn't appear in the GNOME-way but in the elementary-way. With X it works as expected.
Version: git-master
OS: Arch Linux with GNOME 3.20.2

**Comment by jangernert** [comment]
Can you tell me what the output of
`echo $DESKTOP_SESSION`
under the gnome-wayland-session is?
I use that variable to determine what way to display the menu.

**Comment by haeckle** [comment]
The output of

> echo $DESKTOP_SESSION

is indeed

> gnome-wayland

and thanks for the fix! I can confirm it works.

**Comment by gnumdk** [comment]
@jangernert You may need to check for XDG_CURRENT_DESKTOP => always GNOME

**Comment by bil-elmoussaoui** [comment]
@gnumdk Thanks! changed that :+1:
