### ISSUE TITLE
[Compilation] error: invalid character literal

### ISSUE THREAD

**Issue by dsboger** [jangernert/FeedReader#130]
Several of these errors are output when compiling from master:

```
ArticleList.vala:1038.75-1038.75: error: invalid character literal
							message = _('No marked articles in the category "%s" could be found').printf(name);
							                                                                   ^
```

EDIT: It seems single quotes do not work for strings in vala. Should be triple-double quotes, I think.

**Comment by bil-elmoussaoui** [comment]
My bad it's my fault! gonna fix that right now

**Comment by bil-elmoussaoui** [comment]
Fixed

**Comment by dsboger** [comment]
It seems you introduced a typo (foundd) with latest fix?

**Comment by bil-elmoussaoui** [comment]
saw that just after commiting, already fixed too! thanks for reporting
