### ISSUE TITLE
Stay up to date with the upstream repo of ftr-site-config

### ISSUE THREAD

**Issue by nmabhinandan** [jangernert/FeedReader#131]
Keep the the grabber configurations up to date with the upstream repo. Currently the configs repo is 26 commits behind the upstream.

App site configs: (https://github.com/jangernert/ftr-site-config)

Upstream site configs (https://github.com/fivefilters/ftr-site-config)

**Comment by bil-elmoussaoui** [comment]
The configs are stored in the same repo and they're up to date : https://github.com/jangernert/FeedReader/tree/master/data/GrabberConfig
