### ISSUE TITLE
Fullscreen 

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#133]
Please, integrate fulscreen mode with Gnome fullscreen api
![2016-06-13 08-53-14](https://cloud.githubusercontent.com/assets/4980269/15998301/ef53cc1e-3145-11e6-8e67-1e26a8a681a0.png)
Sorry for russian. This option in Gnome Settings->Keyboard->Windows->Toogle fullscreen

https://www.dropbox.com/s/bxykuc2rw8i1aj1/Screencast_13.06.2016_09%3A02%3A49.webm.webm?dl=0

**Comment by horosgrisa** [comment]
![2016-06-13 12-27-32](https://cloud.githubusercontent.com/assets/4980269/16002821/3ee5aa9c-3162-11e6-8ed2-3807bcffa8fe.png)

**Comment by jangernert** [comment]
Does this solve the issue as expected?

**Comment by horosgrisa** [comment]
@jangernert It Works!!! Thank you
