### ISSUE TITLE
Zooming article view zooms whole pane instead of the article

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#134]
![auswahl_002](https://cloud.githubusercontent.com/assets/10520767/16097720/a1cdca9c-334f-11e6-9979-35106ed5d836.png)

**Comment by bil-elmoussaoui** [comment]
How did you zoom on the article?

**Comment by fb87** [comment]
Touchscreen :p

**Comment by bil-elmoussaoui** [comment]
Alright! Thanks, i have a touchscreen and i can confirm that. We will add a zoom out limit

**Comment by jangernert** [comment]
Okay^^
So someone with a touchscreen has to implement this. Since I have no touchscreen myself, there is no way I can test this.

**Comment by bil-elmoussaoui** [comment]
@jangernert I will do :)

**Comment by jangernert** [comment]
I looked through the public API of and found nothing about multi-touch gestures. So afaik there is no way for FeedReader to react to those and update the background color.
So I will close this and link the bug I opened on the webkit-tracker:
https://bugs.webkit.org/show_bug.cgi?id=160503
