### ISSUE TITLE
YouTube cannot be played

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#136]
Feedreader 1.6 beta
Fedora 24

Problems:
• When trying to play a YouTube video, the player hangs
• Selecting another article doesn't work because the article with the video is obviously blocking

Console output:
```bash
[ DEBUG ] ArticleView: load FINISHED
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
intel_do_flush_locked failed: No such file or directory

<trying to switch article>

[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_14817a8c56d:9b5c0b1:7762fa0c
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article ygGkFqsR3YrUMIkx3akw4oFOPngcRELxznXMxxmY8VY=_1481865e718:9f9cf2f:7762fa0c
[ DEBUG ] ArticleView: still busy loading last article. will cancel loading and load new article
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_14817a8c56d:9b5c0b1:7762fa0c
[ DEBUG ] ArticleView: still busy loading last article. will cancel loading and load new article
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article 6v3bsRSs/0QViBXqoAJH7nV9d/YspxCmEG+0c0JTti4=_148171ffcbc:63abe3:feb3a37e
[ DEBUG ] ArticleView: still busy loading last article. will cancel loading and load new article
```

**Comment by jangernert** [comment]
This seems to be a issue with VA-API the intel video acceleration API. Can you play embedded youtube videos in other webkitgtk+ based applications like epiphany?

**Comment by fb87** [comment]
Just tried the browser yet... but such problems shouldn't affect the main program (hence my 2nd problem entry).

**Comment by jangernert** [comment]
If the webview does is taking too long to load a page I cancel the loading and wait for the load-failed-event. But it seems like the webview does not even respond to that anymore.
Just ignoring everything and tell the webview to load a new article caused some bugs in the past, since signals of the old and new load request got mixed up.

**Comment by fb87** [comment]
Ok, I just found out that just _starting_ Totem produces exactly the same output – maybe an issue due to having Fedora beta. So no bug there, sorry. But would be nice if the whole application won't get blocked due to such an error. ;)

**Comment by jangernert** [comment]
Once the user requests to load a new article and the webview is still busy loading (or encountered issues like here) I ask the webview to stop loading and start loading the new article once the webview tells me it successfully stopped the current loading process. Without doing this I ran into multiple issues with race-conditions. And since the webview does not appear to respond to the stop_loading() function, I'm not really sure what to do here. As far as I can see there is also no signal that gets emitted after something went wrong in webkitgtk+. Will ask in irc if someone knows how to deal with this.

**Comment by jangernert** [comment]
Okay, I now use the signal "web_process_crashed" and if triggered, the webview will be able to load a new page even if the the current page appears to be still loading.
However if the gstreamer stuff is not part of the address space of the web-process I'm afraid there is nothing I can do.

> If it's some gstreamer bug that causes the page to load forever, though, I don't think there's anything to be done but to fix the bug. But if it's a web process crash, use that signal. :)

can you build the latest code in master and see if you get the error "ArticleView: webview crashed"?

**Comment by fb87** [comment]
The article view hangs. I can select different articles, but the article view then gets cleared and remains empty. After maybe half a minute I get 4 timeouts but nothing happens:

libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
intel_do_flush_locked failed: No such file or directory

(feedreader:11261): Gtk-WARNING **: Allocating size to GtkStack 0x1c72190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed

(feedreader:11261): Gtk-WARNING **: Allocating size to GtkStack 0x1c72190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed

(feedreader:11261): Gtk-WARNING **: Allocating size to GtkStack 0x1c72190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed

(feedreader:11261): Gtk-WARNING **: Allocating size to GtkStack 0x1c72190 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed

** (feedreader:11261): WARNING **: ArticleView.vala:209: Zeitüberschreitung wurde erreicht

** (feedreader:11261): WARNING **: ArticleView.vala:209: Zeitüberschreitung wurde erreicht

** (feedreader:11261): WARNING **: ArticleView.vala:209: Zeitüberschreitung wurde erreicht

** (feedreader:11261): WARNING **: ArticleView.vala:209: Zeitüberschreitung wurde erreicht
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article /7hUuNFyp3hz1K2aAm/VsbCmTznhEju/akrUyXMz/t0=_149a3dbd566:26b5590:8340a896
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article nvWNk70hGk3y3NH6AHxagVCEXCxqZMzRH8UbWmFup00=_155303e63e4:1fbe7df:3821b62d
[ DEBUG ] ArticleView: still busy loading last article. will cancel loading and load new article
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article 6v3bsRSs/0QViBXqoAJH7nV9d/YspxCmEG+0c0JTti4=_14815315656:29099:409e16c9
[ DEBUG ] ArticleView: still busy loading last article. will cancel loading and load new article

**Comment by jangernert** [comment]
Then I'm afraid that I can't do anything about this, since I have no way of knowing if webkit/gstreamer crashed  and  the webview is not even responding to stop_loading() anymore =/
But I read that disabling DRI3 fixes the VA-API bug.
