### ISSUE TITLE
Articles aren't properly sorted into all/unread/marked

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#138]
![feedreader_001](https://cloud.githubusercontent.com/assets/10520767/16098978/25fb9a1e-3356-11e6-8f92-678910adda6f.png)

Like you see in the screenshot, none of the displayed articles is marked, same happened to me in the unread list earlier.

Feedreader 1.6 beta
Fedora 24

Console output:
http://pastebin.com/iwKd32gH

Massive output for 20 seconds runtime... took me two minutes for scrolling. Can't you shrink that? xD

**Comment by jangernert** [comment]
Something seems to be COMPLETELY messed up for you. The sql-query has a offset every time. Usually the offset is only applied after the UI was started so the article in the viewport can be loaded first and afterwards lazy-load the rest of the articles above.
Also createArticleList and updateArticleList get triggered like a million times =/

**Comment by fb87** [comment]
Where can I find it?

**Comment by jangernert** [comment]
First kill the currently running "feedreader-daemon" process. Then start it inside a terminal. Then open the ui and perform at least one sync. I would like to know if the daemon is sending all these signals to update the artille list. ;)

**Comment by fb87** [comment]
[ INFO  ] Everything is logged. Used to debug!
[ ERROR ] CREATE VIRTUAL TABLE fts_table USING fts4 (content='articles', articleID, preview, title, author)
[ ERROR ] table fts_table already exists
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 1.6 beta
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type 1
[ DEBUG ] feedly backend: login
[ INFO  ] feedly: userID = 641223e2-a2c7-4a65-b927-29782a529edb
[ DEBUG ] feedly: login success
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] daemon: bus aquired
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] last clean: 2016-06-14 21:53:47
[ DEBUG ] now: 2016-06-17 21:15:06
[ DEBUG ] difference: 2.000000
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ INFO  ] daemon: sync started
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews
[ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] SELECT articleID, feedID FROM main.articles WHERE date <= datetime('now', '-24 months') AND marked = 10 AND rowid BETWEEN 1 AND 428 
[ INFO  ] daemon: sync finished

**Comment by jangernert** [comment]
okay, so the daemon is triggering all the updates in the UI. This message here should only be displayed once:

> [ DEBUG ] FeedServer: new articles: 0
[ DEBUG ] Utils: generatePreviews

**Comment by jangernert** [comment]
I fixed up feedreader-debug again, so maybe you can use it to figure out how to reproduce some of your issues with the article-list (that's what I initially wrote it for).
So after you have built master again and killed the running "feedreader-daemon", you can start "feedreader-debug". This will spawn a litte window that allows you to simulate all kinds of stuff.
This is all happening in a separate debug database and will not affect your current database.
First you fill the FeedList with some feeds and categories, then put in some articles with a simulated sync. You can start the ui either with the button in the debugger or in the terminal with "feedreader --debug"

https://plus.google.com/109974726829108083807/posts/Jqjb7Vq5cZT

**Comment by fb87** [comment]
Happened never again since. Think you can close this bug, thanks!
