### ISSUE TITLE
Feature: Display number of comments

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#140]
Feedly does this in the overview e.g. Showing these would be perfect!

**Comment by jangernert** [comment]
How would I know the number of comments? :P

**Comment by fb87** [comment]
Extracting from the website ^^

**Comment by bil-elmoussaoui** [comment]
We use https://github.com/fivefilters/ftr-site-config to extract the content from the website; If you can ask for this feature there, we will add it ^^

**Comment by jangernert** [comment]
Even then, the number of comments would be fetched at the time the article is downloaded. So it could already be totally outdated once the user reads the article. Constantly monitoring the number of comments is way out of the scope of FeedReader. Maybe feedly with their big server-farms can do that ... but not a desktop client.
