### ISSUE TITLE
Article list is scrolling down spontaneously

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#141]
Fedora 24
FeedReader 1.6 beta

Sometimes the article list spontaneously scrolls down by maybe around 10-20 articles, maybe due to newly aggregated articles (this happened 4 times during a period of about 5 minutes, then I got a notification about new articles).

Here's the log:
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 1.6 beta
[ INFO  ] FeedReader: start daemon
[ ERROR ] CREATE VIRTUAL TABLE fts_table USING fts4 (content='articles', articleID, preview, title, author)
[ ERROR ] table fts_table already exists
[ INFO  ] Everything is logged. Used to debug!
[ ERROR ] CREATE VIRTUAL TABLE fts_table USING fts4 (content='articles', articleID, preview, title, author)
[ ERROR ] table fts_table already exists
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 1.6 beta
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type 1
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] menu
[ DEBUG ] minimize,maximize,close
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: load content
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] ArticleList: delete HeadlineList
[ DEBUG ] ArticleList: createHeadlineList
[ DEBUG ] ArticleList: offset 0
[ DEBUG ] limit: 20
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 20 OFFSET 0
[ DEBUG ] actual articles loaded: 20
[ DEBUG ] HeaderBar: updatebutton status true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] menu
[ DEBUG ] minimize,maximize,close
[ DEBUG ] feedly backend: login
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleView: size changed
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row
[ DEBUG ] ArticleList: createHeadlineList finished
[ DEBUG ] ArticleList: restore ScrollPos
[ INFO  ] feedly: userID = 641223e2-a2c7-4a65-b927-29782a529edb
[ DEBUG ] feedly: login success
[ DEBUG ] FeedServer: setOnline
[ DEBUG ] FeedServer: server is available again
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] daemon: bus aquired
[WARNING] daemon: Could not aquire name (already running). Will shut down!
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15552d3c6c5:5edda87:3821b62d
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15552d3c6c5:5edda88:3821b62d
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 389,302130
[ DEBUG ] scrollpos 83,302130
[ DEBUG ] offset 3
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 389,302130
[ DEBUG ] scrollpos 83,302130
[ DEBUG ] offset 3
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 335)  ORDER BY rowid ASC LIMIT 335 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 116
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 135 OFFSET 0
[ DEBUG ] actual articles loaded: 117
[ DEBUG ] ArticleList: 99 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article jF7jVEe/yvZDjBGWeWE8nizmukpqnxO3Na1FH2PsUj8=_155536b3ca6:6297d99:818adeed
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] state changed
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article 2+YGH8ApBcx2mYoyeMehC3JsrYXU3uA66nl5ktBaQeE=_15556d3502d:c944a:c3f7604e
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15557616ac7:297a71:818adeed
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 668,525535
[ DEBUG ] scrollpos 56,525535
[ DEBUG ] offset 6
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 668,525535
[ DEBUG ] scrollpos 56,525535
[ DEBUG ] offset 6
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 345)  ORDER BY rowid ASC LIMIT 345 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 123
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 238 OFFSET 0
[ DEBUG ] actual articles loaded: 124
[ DEBUG ] ArticleList: 10 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15557cfbe5c:403a10:5e49e1a
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15557eba19e:461433:5e49e1a
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] contentPage: set headerbar
[ DEBUG ] ArticleView: load article tT3i6dsoywzp72U4xl/JYQ5TX1571A8EO85JDgtBI+Q=_15557eba19e:461434:5e49e1a
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: load FINISHED
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 661,789852
[ DEBUG ] scrollpos 49,789852
[ DEBUG ] offset 6
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 661,789852
[ DEBUG ] scrollpos 49,789852
[ DEBUG ] offset 6
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 355)  ORDER BY rowid ASC LIMIT 355 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 130
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 252 OFFSET 0
[ DEBUG ] actual articles loaded: 131
[ DEBUG ] ArticleList: 10 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 490,456175
[ DEBUG ] scrollpos 82,456175
[ DEBUG ] offset 4
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 490,456175
[ DEBUG ] scrollpos 82,456175
[ DEBUG ] offset 4
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 365)  ORDER BY rowid ASC LIMIT 365 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 140
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 272 OFFSET 0
[ DEBUG ] actual articles loaded: 141
[ DEBUG ] ArticleList: 10 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 694,246448
[ DEBUG ] scrollpos 82,246448
[ DEBUG ] offset 6
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 694,246448
[ DEBUG ] scrollpos 82,246448
[ DEBUG ] offset 6
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 375)  ORDER BY rowid ASC LIMIT 375 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 150
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 292 OFFSET 0
[ DEBUG ] actual articles loaded: 151
[ DEBUG ] ArticleList: 10 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 1818,246448
[ DEBUG ] scrollpos 6,246448
[ DEBUG ] offset 17
[ DEBUG ] ArticleList: updateArticleList
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 1818,246448
[ DEBUG ] scrollpos 6,246448
[ DEBUG ] offset 17
[ DEBUG ] selectedRow 0: feed
[ DEBUG ] selectedRow 1: -4
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9 AND articleID in (SELECT articleID FROM main.articles ORDER BY rowid DESC LIMIT 385)  ORDER BY rowid ASC LIMIT 385 OFFSET 0
[ DEBUG ] updateArticleList: new articles: 160
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE unread = 9  ORDER BY rowid ASC LIMIT 312 OFFSET 0
[ DEBUG ] actual articles loaded: 161
[ DEBUG ] ArticleList: 10 articles have been added
[ DEBUG ] ArticleList: updateArticleList finished
[ DEBUG ] sync finished -> update ui
[ DEBUG ] MainWindow: show content
[ DEBUG ] HeaderBar: updatebutton status true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] menu
[ DEBUG ] minimize,maximize,close
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true

**Comment by jangernert** [comment]
The article list scrolls down when new ones are added and there is no article currently selected. If you did have one selected, this could be for the same reason the other 2 bugs were happening. So please respond to these first instead of opening up countless new ones that probably are due to the same cause.

**Comment by fb87** [comment]
So now I read the topmost (=> oldest) article (which was of course selected) and received a single new one. The the article list scrolled down almost to the bottom. Could it be that the sorting method (oldest or newest first) isn't distincted by the scolling down action?

**Comment by fb87** [comment]
Still happening. While reading some news, arriving articles always scroll the article overview pane down by some amount while having sorted them oldest first.

**Comment by jangernert** [comment]
Could be. Having the oldest article first doesn't really make sense to me anyway. Maybe I'll just remove this feature, since I don't ever use it and test it properly.

**Comment by fb87** [comment]
Can you explain to me, why it doesn't make sense, reading articles from top to bottom in historical order? Reading from bottom to top makes no sense for me, as well as reading the latest news without knowing what's happened before.

**Comment by jangernert** [comment]
You need to scroll ALL the way to the bottom through all of the old stuff every time you want to read the new articles.

Have you ever gotten an email and scrolled all the way through all you mails just to get to the new one? Or visited a website and scrolled all the way down (or maybe even went back a few pages if they limit the amount of articles per page) to see if a new article was posted? New stuff just goes on the top of the stack. Probably the same way on your desk. I don't think I know people that have a stack of papers and lift it up every time to put a new sheet of paper beneath, you just put it on top.

Also FeedReader saves your position in the articleList, so you are just where you left of and can slowly scroll upwards to catch up to the new stuff ;)

**Comment by fb87** [comment]
That's why you're supposed to read the old stuff, then you can always read the news of today in chronological order. ;p
The article list is supposed to be worked through and articles to be marked as read and disappear – in contrast to e.g. a blog, where the old stuff doesn't disappear after being read and thus isn't of particular interest.
So you see, everybody likes things in a different way and I would be happy with this feature not getting deleted but corrected. ;)

**Comment by jangernert** [comment]
I will mark this as fixed for now. Regarding the missing option, discussion can continue in #155
