### ISSUE TITLE
Can't update via git because of GitSHA1.vala

### ISSUE THREAD

**Issue by lightonflux** [jangernert/FeedReader#144]
Hi there,

for the second or third time i had to remove GitSHA1.vala. My automatic git updating only works when there are no local conflicts. But agin there was a problem with this file.

What does GitSHA1.vala and can we add it to gitignore or otherwise stop it from messing up git pulls?

**Comment by jangernert** [comment]
Actually this file should not be needed at all. It is generated before compiling the source and only holds the current git-commit-hash for the "feedreader --version" command.
