### ISSUE TITLE
Feature: Selectable text in the article view

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#145]
Don't know if it's possible with the renderer you use, but would be nice if text could be selected for copying. :)

**Comment by jangernert** [comment]
duplicate of #123
it is available as a tweak for advanced users. I want to keep the defaults simple and clean. That's why this is only available via gsettings/dconf
just open dconf-editor and navigate to org->gnome->feedreader->tweaks and check article-select-text

**Comment by fb87** [comment]
Thx
