### ISSUE TITLE
debian compilation issue

### ISSUE THREAD

**Issue by Gijs-Koot** [jangernert/FeedReader#149]
I'm following the steps for compilation from source, but the `make` command fails with 

    /home/gijs/Desktop/FeedReader/src/Widgets/ArticleView.vala:584.17-584.50: error: The name `set_background_color' does not exist in the context of `WebKit.WebView'
                m_currentView.set_background_color(background);

I've installed the dependencies. I did uninstall the default browser in favor of a binary install of Firefox, perhaps that has something to do with it? Thanks.

**Comment by jangernert** [comment]
What version of webkit2gtk do you have installed? 4.0 or 3.0?

**Comment by Gijs-Koot** [comment]
$ dpkg-query -l '*' | grep webkit
    un  gir1.0-webkit-3.0                     <none>                               <none>       (no description available)
    ii  gir1.2-webkit-3.0:amd64               2.4.9-1~deb8u1                       amd64        Web content engine library for GTK+ - GObject introspection data
    ii  gir1.2-webkit2-4.0:amd64              2.6.2+dfsg1-4                        amd64        Web content engine library for GTK+ - GObject introspection data
    un  libwebkit2gtk-3.0-25                  <none>                               <none>       (no description available)
    ii  libwebkit2gtk-4.0-37:amd64            2.6.2+dfsg1-4                        amd64        Web content engine library for GTK+
    ii  libwebkit2gtk-4.0-dev:amd64           2.6.2+dfsg1-4                        amd64        Web content engine library for GTK+ - development files
    un  libwebkitgtk-1.0-0                    <none>                               <none>       (no description available)
    ii  libwebkitgtk-3.0-0:amd64              2.4.9-1~deb8u1                       amd64        Web content engine library for GTK+
    ii  libwebkitgtk-3.0-common               2.4.9-1~deb8u1                       all          Web content engine library for GTK+ - data files

**Comment by jangernert** [comment]
Okay, looks like your version of webkit2gtk (2.6) is new enough to have the 4.0 API-version, but not new enough to have the "set_background_color"-function (that came with 2.8).
I added a check to the version of webkitgtk. If you are below 2.8 the 3.0 API-version will be used from now on. Can you test the newest commit of master and see if it compiles for you?

**Comment by Gijs-Koot** [comment]
With this new master it works. Had to install `libwebkit2gtk-3.0`, not `libwebkit2gtk-3.0-25`. Thanks, the app looks awesome.
