### ISSUE TITLE
Share to Wallabag 2.0

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#15]
Wallabag 2.0 (currently in alpha) will have an API.
It's a self hostet, open source alternative to Pocket/Instapaper
https://www.wallabag.org/
http://v2.wallabag.org/api/doc

**Comment by jangernert** [comment]
Initial implementation is now in master.
However to work with self-hosted instances of wallabag (right now it works with v2.wallabag.org), 3 more entries for url, clientID and clientSecret need to be added. So in total 5 different things the user has to enter before he can log into his account =/

**Comment by tcitworld** [comment]
>  However to work with self-hosted instances of wallabag (right now it works with v2.wallabag.org), 3 more entries for url, clientID and clientSecret need to be added. So in total 5 different things the user has to enter before he can log into his account =/

This will change.

**Comment by 1O1O** [comment]
Just for information,
On fedora 27, feedreader Version: 2.0.2
I added to /usr/share/glib-2.0/schemas/org.gnome.feedreader.share.wallabag.gschema.xml
```
      <key name="wallabag" type="as">
            <default>[]</default>
            <summary>wallabag accounts</summary>
            <description>
                all the wallabag account ids
            </description>
        </key>
```
and
```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```
After that I can open feedreader, connect it to wallabag (on https://framabag.org) and save things
(Really not sure about the form of the key but it works)
