### ISSUE TITLE
Can't connect to local Tiny Tiny RSS instance

### ISSUE THREAD

**Issue by cryzed** [jangernert/FeedReader#150]
Hey, I'm running a local Tiny Tiny RSS instance on http://localhost:8083/. The only account available is the admin account, API access is enabled in the preferences. I can easily connect and use the API using the [ttrss-python](https://github.com/Vassius/ttrss-python) library.

However when using the same credentials, i.e. URL: "http://localhost:8083/"; Username: "admin" and my password, I keep getting the "Please enter a valid password" error. [Here](https://gist.github.com/anonymous/f80cb3244884b36c132a4a11e68549a6) is the associated stdout/stderr output. Please note that I closed the window at the end.

**Comment by jangernert** [comment]
If anything, I need the log of the daemon, not the UI.

**Comment by cryzed** [comment]
I was just about to provide it, [here](https://gist.github.com/anonymous/96c7a4a6b7bd9dba8704c1cb1db9f983). Looks like the password isn't sent for some reason?

**Comment by jangernert** [comment]
Looks like libsecret can't save your password because the dbus-service for it is not running

**Comment by jangernert** [comment]
You can use the programm "D-Feet" to check if the dbus-server is running. There should be a "org.freedesktop.secrets" server on the session-bus provided by the "/usr/bin/gnome-keyring-daemon"-binary

**Comment by cryzed** [comment]
That seems to have worked, I wasn't aware that gnome-keyring was a dependency, as it seemingly is the only thing that implements the [secret service standard](https://specifications.freedesktop.org/secret-service/), I would have assumed KWallet would do that...

Thank you.
