### ISSUE TITLE
Wrong spacing in feed list

### ISSUE THREAD

**Issue by fturco** [jangernert/FeedReader#151]
There's a strange spacing issue with my feed list (left sidebar). It seems there are some "hidden" feeds which take up some space and cannot be removed:

![screenshot from 2016-07-16 14-35-57](https://cloud.githubusercontent.com/assets/5459866/16894834/ddd8aa4e-4b63-11e6-815a-dcf2d777bae8.png)

For example in the previous screenshot there is an FSF "hidden" feed between folders Altro and Parabola.

Is there a way to remove such "hidden" feeds?

I'm using Feed Reader 1.4.3 on Parabola GNU/Linux-libre.

**Comment by bil-elmoussaoui** [comment]
This is due to GTK 3.20. The current version you're using does not have a support to the new Gtk theming standards. This was fixed on the latest version of FeedReader (still on beta) but you can build it from source code to fix your issue.

**Comment by fturco** [comment]
Yeah. There is no such issue with feedreader-git (from AUR).

**Comment by bil-elmoussaoui** [comment]
Thanks for testing it ! don't hesitate to report any other issues :+1:
