### ISSUE TITLE
Cannot connect to TT-RSS via SSL

### ISSUE THREAD

**Issue by fturco** [jangernert/FeedReader#153]
I successfully added SSL support on my webserver with Let's Encrypt. Now I'd like to connect to my Tiny Tiny RSS instance using SSL. But I get the following error message:

> No valid CA certificate available!

Tiny Tiny RSS URL is https://fturco.net/tt-rss/.

When connecting via the web interface everything seems to be OK. The api_feedreader extension has been enabled. I'm using feedreader-git-1.6.beta.1.r103.g6b5eb93-1 on a Parabola GNU/Linux-libre system.

Is there something obvious I am missing?

**Comment by jangernert** [comment]
You have to add the certificate to your system first.

**Comment by fturco** [comment]
Thank you, it now works. But it seems the procedure for adding the certificate has changed, at least for Arch Linux: https://www.archlinux.org/news/ca-certificates-update/

**Comment by fturco** [comment]
It seems the real cause of the problem was another one.

I simply forgot to add the following option in Apache configuration file on the server where Tiny Tiny RSS is located:

    SSLCertificateChainFile "/etc/letsencrypt/live/fturco.net/chain.pem"

Now Feed Reader is able to connect via SSL even if I don't touch `/usr/local/share/ca-certificates` or `/etc/ca-certificates/trust-source/anchors/`.
