### ISSUE TITLE
Switching from „unread“ to „all“ doesn't display all articles

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#154]
I just clicked over an article and wanted to read it again, thus switched to the „all“ view. But the article isn't showed – in fact just articles until 26.06. are showed... although the feed gets new articles almost every day.
[logs.tar.gz](https://github.com/jangernert/FeedReader/files/368178/logs.tar.gz)

/ Restarting solved that issue.

**Comment by jangernert** [comment]
Looking at the log you did way more than just switch from "unread" to "all". You switched between several different feeds. I have no idea at what point you were experiencing missing articles.
Also all the sql-queries and the number of articles loaded are printed in the log. So you can easily execute the queries yourself and see if the expected result is returned.
Fixing this will be much easier if I know which query goes wrong.

**Comment by fb87** [comment]
Of course I did read some other articles, but how the hell should I know which one has gone wrong? I experienced missing articles at switching the view to „all“, of course, as in „unread“ no read (missing or not) articles are displayed.
