### ISSUE TITLE
The Oldest First option removal

### ISSUE THREAD

**Issue by CharoSW** [jangernert/FeedReader#155]
When I updated the program today I noticed that my feeds were suddenly newest first and that the option to reverse that had been removed.  Now while it's not an absolute deal breaker of feature it is the way I am used to reading my RSS feeds and would preferably like to still have it there.  Reading you commit message on it was also a little confusing, surely simply loading a test feed and seeing if it reversed properly would be a good enough test.  Either way I hadn't had any problems with it and don't quite see why it needed to be removed.

**Comment by bil-elmoussaoui** [comment]
Can you share a screenshot of the settings widget? I don't remember that we have removed any feature..

**Comment by jangernert** [comment]
I removed it because it was causing problems with the scroll-position-management during the updates. I just don't ever use this feature and can't really maintain it because of this.
But if anyone wants to re-add the feature and fix the bugs, he is more than welcome.

**Comment by fb87** [comment]
Better leave it with the scrolling-bug, than delete the whole thing.
