### ISSUE TITLE
Cannot build Feed Reader from git

### ISSUE THREAD

**Issue by fturco** [jangernert/FeedReader#157]
I tried to update feedreader-git but it cannot be built due to an error.

The error message is (repeated 3 times):
> error: Argument 1: Cannot convert from `GLib.TimeSpan' to `int'

[makepkg.log.txt](https://github.com/jangernert/FeedReader/files/378727/makepkg.log.txt)

**Comment by jangernert** [comment]
I changed `difference/GLib.TimeSpan.DAY` to `difference.DAY` to simplify the code a bit. Compiles just fine here on Fedora 24. So maybe you need a pretty recent version of glib, valac or whatever.
I reverted the change for now.

**Comment by fturco** [comment]
Strange, because I upgraded my system just before trying building feedreader-git.

Package versions:
- glib2-2.48.1-1
- vala-0.32.1-1
