### ISSUE TITLE
Default CMAKE_INSTALL_PREFIX to /usr/local

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#158]
I'm don't know why the default is /share, but it would be nice if the default value would be what most people need. By git fetching the latest files and seeing CMakeLists.txt, I sometimes automatically do a cmake .. in build without remembering to fix the CMAKE_INSTALL_PREFIX.

**Comment by jangernert** [comment]
> This variable defaults to /usr/local on UNIX and c:/Program Files on Windows.

https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html
