### ISSUE TITLE
Install prefixes other than /usr aren't applicable

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#160]
FR doesn't work when installed into e.g. /usr/local prefix. Do you have hard coded paths?

Occurring issues:
• Daemon isn't started automatically
• Articles cannot be viewed

**Comment by jangernert** [comment]
Jup, there are some hard-coded paths. I will fix this when I find the time.

**Comment by jangernert** [comment]
I think I fixed all the issues.

**Comment by jangernert** [comment]
Tested and works now
