### ISSUE TITLE
FR-crash at sync-complete

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#162]
I was reading some articles and FR synced in parallel. UI crashed at switching to another article while the daemon remained running (though having deactivated this behaviour per dconf). The daemon displayed that new articles were fetched just as the UI crashed. Don't know if it's due to switching the article or completing the sync, both happened at almost the same time.

[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/380281/feedreader.tar.gz)

**Comment by jangernert** [comment]
Can you provide a backtrace of the crash?

**Comment by fb87** [comment]
Can you please tell me how to get it?

**Comment by jangernert** [comment]
start feedreader with gdb

> gdb feedreader

then run by typing

> run

then make it crash and then type

> backtrace

http://www.unknownroad.com/rtfm/gdbtut/gdbsegfault.html

**Comment by fb87** [comment]
Roger

**Comment by jangernert** [comment]
Did this ever happen again?

**Comment by fb87** [comment]
Yes, about once a week.

**Comment by jangernert** [comment]
I just learned about [`coredumpctl`](https://www.freedesktop.org/software/systemd/man/coredumpctl.html)
This should make it possible to get a back-trace of a crash after the crash happened. Pretty useful :)

**Comment by jangernert** [comment]
So, will I ever get that back-trace?

**Comment by fb87** [comment]
Didn't happen again in the last time. Now the article list just jumps down by some amount when articles get inserted at the top – but I'm not sure if this is a consequence of a newly finished sync, or if selecting the article reloads it and puts it at the top (this is my feeling, since this happened three times in the last hour).
