### ISSUE TITLE
Syncing with my ttrss instance doesn't work

### ISSUE THREAD

**Issue by afranke** [jangernert/FeedReader#163]
I use Feedreader 1.6beta from Fedora 24. I configure my account, but then after a bit of a loading time all I get is "No articles could be found". The list of feeds is also empty.

**Comment by jangernert** [comment]
I think I need a bit more information than "doesn't work! lol".
First off you should try again with the current master branch, since a lot of fixes already landed there.

Can you post the log of the daemon and the ui? Is there anything special about your tt-rss setup? Were there unread or marked articles on your tt-rss instance during the sync? Can you check the database of FeedReader to see if no articles were synced or if the just didn't show up on the ui?

**Comment by afranke** [comment]
I'm very well aware that this was not enough info, I was expecting you to guide me through debugging.

I'll see what i can do about building master. In the meantime here are answers.

My ttrss instance is version 1.7.0 so not the latest but apart from that I don't think there's anything special about it.

The logs: https://paste.gnome.org/p2sxq7gg6/q98neg

**Comment by jangernert** [comment]
Almost forgot: did you read the note about the required tt-rss addon? Sadly there are many API calls missing to manage your categories, feeds and tag (called labels in tt-rss). So I had to write a small plugin for tt-rss to provide them:

> NOTE: If you run FeedReader with the TinyTinyRSS-backend please install the "api_feedreader"-extension. Running FeedReader with the TinyTinyRSS-backend and without the extension is NOT supported.

Also I read the logs. But the dameon-log seems to be of a second instance of the feedreader-daemon and does not contain the information of the sync process. If you want to make absolutely sure you can simply kill the running daemon and start it up in the cli and then perform a sync.

**Comment by afranke** [comment]
Just tried with master, same result.

**Comment by afranke** [comment]
I did NOT see the note. Where was it?

**Comment by jangernert** [comment]
http://jangernert.github.io/FeedReader/#install

It's not the biggest and most attention grabbing text, but I didn't want to overshadow all the other information with this "minor detail".

**Comment by afranke** [comment]
Maybe you can add a warning or something in the UI if the user configures a ttrss instance? If someone installs it from their distro directly they will never see that message.

I'll try to install it now and report back.

**Comment by jangernert** [comment]
Good idea, will look into that!

**Comment by afranke** [comment]
I installed the plugin and enabled it in my config.php and now I get a blank page on the web UI. I'm investigating why this is happening.

**Comment by afranke** [comment]
Could it be that 1.7.0 is too old?

**Comment by jangernert** [comment]
Like I said, I developed it on 1.12. No idea if it will work on older versions =/

**Comment by afranke** [comment]
Ok. I guess I can closed this as invalid for now, I'll reopen if I still get issues with an up to date instance. Thanks for the support.

**Comment by jangernert** [comment]
Hey @afranke,
do you have by any chance not updated your tt-rss instance, yet?
If so, can you test master real quick and see if you get a error message for missing the api_feedreader plugin on login now? (You can go "change account" from the gmenu to go to the login page again)
