### ISSUE TITLE
Can't login to Tiny Tiny RSS: "Please install the "api_feedreader"-plugin

### ISSUE THREAD

**Issue by m3adow** [jangernert/FeedReader#165]
Hi all,

I just recently installed Feedreader from the Ubuntu repos (version 1.6 beta), but it can't connect to my tt-rss instance (v16.3 (9e38b6c)). I installed and activated the api_feedreader-plugin, but Feedreader doesn't detect it.

Daemon logs:
```
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader Daemon 1.6 beta
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type -1
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_NO_BACKEND
[ DEBUG ] daemon: update badge count 0
[ DEBUG ] daemon: bus aquired
[ DEBUG ] daemon: update badge count 0
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] FeedServer: setOffline
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type 0
[ DEBUG ] TTRSS: login
[ DEBUG ] ttrss URL: https://ttrss.example.org/api/
[ DEBUG ] {"op":"login","user":"user1","password":"password1"}
[ DEBUG ] {"seq":0,"status":0,"content":{"session_id":"udsvm95865d5qnvd02dm8i34d2","api_level":13}}
[ INFO  ] TTRSS Session ID: udsvm95865d5qnvd02dm8i34d2
[ INFO  ] TTRSS API Level: 13
[ ERROR ] ttrss api error
[ DEBUG ] {"sid":"udsvm95865d5qnvd02dm8i34d2","op":"removeLabel"}
[ DEBUG ] {"seq":0,"status":1,"content":{"error":"INCORRECT_USAGE"}}
[ DEBUG ] FeedServer: setOffline
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_PLUGIN_NEEDED
[ ERROR ] ttrss api error
[ DEBUG ] {"sid":"udsvm95865d5qnvd02dm8i34d2","op":"removeLabel"}
[ DEBUG ] {"seq":0,"status":1,"content":{"error":"INCORRECT_USAGE"}}
```

I'm using another api plugin as well, [api_newsplus plugin](https://github.com/hrk/tt-rss-newsplus-plugin/). Could there be conflicts between those two?

**Comment by jangernert** [comment]
Fixed it!
But I will wait to collect a few bugfixes to release 1.6.1.
In the meantime you can build from source ;)

**Comment by m3adow** [comment]
Thanks. :-)

**Comment by hyOzd** [comment]
I'm having a similar issue. I've tried the latest version from unstable ppa but it didn't work.

@m3adow  where can I find the "daemon logs" you mentioned? I don't see any errors in the logs that I check from "System" tab of the web interface.

**Comment by m3adow** [comment]
I randomly found the log location in another [comment](https://github.com/jangernert/FeedReader/issues/163#issuecomment-235375165), it's `$HOME/.local/share/feedreader/`.

Perhaps this should be mentioned somewhere.

**Comment by hyOzd** [comment]
@m3adow thanks a lot for responding. I see the same errors as yours. Have you tried installing unstable ppa version, did it work for you?

**Comment by bil-elmoussaoui** [comment]
@hyOzd is unstable ppa uses git a source or just download the latest beta ?

**Comment by hyOzd** [comment]
@bil-elmoussaoui  I have no idea. But since commit de7caf4 was 22 hours ago, and latest package in ppa was 20 hours ago, I've thought that it should contain the fix.

By the way I've used this ppa: https://launchpad.net/~eviltwin1/+archive/ubuntu/feedreader-daily

**Comment by bil-elmoussaoui** [comment]
Ah i see! Have you killed the daemon after installing the latest daily version? You can do so using `pkill feedreader-daemon && pkill feedreader` Open feedreader again and see what happens?

**Comment by hyOzd** [comment]
@bil-elmoussaoui thanks a lot : ) stopping the daemon fixed it. But I had to stop feedreader-daemon from the system monitor. Maybe I was being impatient.

**Comment by bil-elmoussaoui** [comment]
@hyOzd You're welcome! Happy to be able to help you:)

**Comment by jangernert** [comment]
Version 1.6.1 with the bugfix should now (in a few minutes) be available in the stable ubuntu ppa :)

**Comment by m3adow** [comment]
Awesome! Good work.
