### ISSUE TITLE
add appdata to po files

### ISSUE THREAD

**Issue by Jibec** [jangernert/FeedReader#166]
hi there,

can you please make appdata file translatable ?
if needed, one blog post talking about how to do it with gettext : https://blogs.gnome.org/mclasen/2016/07/21/using-modern-gettext/

btw : where should we translate FeedReader ? Transifex link doesn't work on http://jangernert.github.io/FeedReader/ and commit history talk about launchpad ?

**Comment by jangernert** [comment]
Btw: if you know how to make these files translatable please open a pull request

**Comment by bil-elmoussaoui** [comment]
Fixed in 9f9dc950403f1aa0c6bc19d29f0cf033106f628c
@jangernert I used this command to update `.pot` file
```bash
find . -name "*.vala" ! -name "FeedServer.vala" ! -name "grabber.vala" ! -name "grabberUtils.vala" ! -name "DebugUtils.vala" -o -name "*.ui" -o -name "*.appdata.xml" | xargs xgettext -o po/FeedReader.pot
```

**Comment by jangernert** [comment]
Just a few things I don't understand:
Why the need for the specific "FeedServer.vala", "grabber.vala" and "grabberUtils.vala" when you have "*.vala"?
And how do the translated strings get back into the appdata and desktop files upon installation?

**Comment by bil-elmoussaoui** [comment]
@jangernert I use `!` to not look at those files. As their content shouldn't be translated. xgettext will show an error message because it can detects the strings correctly... so i just added those file to an ignore list.
I didn't make the desktop file translatable yet. I just did for the shortcuts ui file & appdata file. It's done by the software center that shows the application information. It detects the current language and use the mo file to get the right strings. 
Just one question, after runing my command, the dirs changed from `../src` to `src/` . I built the application and everything works fine. Do you know why it was `../src` ? :)

**Comment by jangernert** [comment]
No not really. All the translation stuff was handled by the cmake "make pot"-target

**Comment by bil-elmoussaoui** [comment]
The appdata is not used by the application itself, just by the software center to show the related informations of the app. See Terminix pot file https://github.com/gnunn1/terminix/blob/master/po/terminix.pot . The appdata file is translated the same way. We just need to rename the file from `appdata.xml` into `appdata.xml.in`

**Comment by jangernert** [comment]
go for it

**Comment by bil-elmoussaoui** [comment]
Will do in a PR soon with the desktop file translation too

**Comment by bil-elmoussaoui** [comment]
@jangernert Done! You can update pot files in the future using `find . -name "*.vala" ! -name "FeedServer.vala" ! -name "grabber.vala" ! -name "grabberUtils.vala" ! -name "DebugUtils.vala" -o -name "*.ui" -o -name "*.appdata.xml.in" -o -name "*.desktop.in" | xargs xgettext -o po/FeedReader.pot 
`

**Comment by jangernert** [comment]
Can you add a little script into the main folder so we don't have to memorize the command?^^

**Comment by Jibec** [comment]
thank you @bil-elmoussaoui 

@jangernert : I'm Fedora Translator, I help to promote your software by helping making it understandable (even if I don't use it myself) because you took the time to produce an appdata file, I'll take the time to translate it. If I know some useful resources (I hope they are), I don't really know how does this work in the details. You have all info you need, please just finish the work ;)

Please note that sending a message to your translator and/or community about all the new strings would be really appreciated (and be ready to publish minor version for each locale reaching 100%)

**Comment by bil-elmoussaoui** [comment]
@Jibec You're welcome :) btw, the pot file was updated on transifex with the latest modifications. I hope you can help making FeedReader available on other languages too. Thanks :+1:

**Comment by Jibec** [comment]
hi, waiting from approval, but no idea from who ;)

**Comment by bil-elmoussaoui** [comment]
Done, sorry for the delay

**Comment by Jibec** [comment]
thanks for your work! I just did mine :)

one comment : we have this to translate "Categories=Network;Feed;" as it is coming from this file, I assume Categories should not be translated, I had a look to Romanian translation and it is translated. Can you please be explicit about what is correct what isn't ?

**Comment by bil-elmoussaoui** [comment]
I don't think that categories should be translatable but it's xgettext who
grab its content. And im using the latest version.. its either a bug or a
feature. I will investigate more later.

**Comment by Jibec** [comment]
kind remember, have you had the time to look this issue ?

**Comment by bil-elmoussaoui** [comment]
Not really. Sorry for the delay, my laptop was borken, i'm going to check soon.

**Comment by Jibec** [comment]
no problem, I'll keep an eye :)

**Comment by bil-elmoussaoui** [comment]
I just figured out how to fix this issue! i will push an update this evening!

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by Jibec** [comment]
looks good to me, thank you, I took the opportunity to review french translation.

**Comment by bil-elmoussaoui** [comment]
Perfect! thank you ;)
