### ISSUE TITLE
Can't compile on Arch Linux

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#176]
I try to compile [feedreader-git](https://aur.archlinux.org/packages/feedreader-git) on Arch, but I obtain error:
```
error: Package `goa-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
```

**Comment by jangernert** [comment]
Master depends on a few new libraries now:
 * ibgstreamer1.0-dev
 * libgstreamer-plugins-base1.0-dev (gstreamer-pbutils-1.0)
 * libgoa-1.0-dev (>= 3.20)

But that is already mentioned in the readme and install-file.
It should be not too surprising that things can change in master ;)

**Comment by horosgrisa** [comment]
I have installed 
```
gst-plugins-base gst-plugins-base-libs gnome-online-accounts
```
But I cant complie feedreader.

**Comment by jangernert** [comment]
Did you install the develpment-versions of the packages?
On fedora the package is called "gnome-online-accounts-devel" and includes the file
"/usr/share/vala/vapi/goa-1.0.vapi"

**Comment by jangernert** [comment]
Looks like the gnome-online-accounts package for arch is built without the vala-bindings.
The vapi-file is not present in the package while all the other development files are.
Fedora enabled them in this commit here:
http://pkgs.fedoraproject.org/cgit/rpms/gnome-online-accounts.git/commit/?h=f24&id=286fd73ba2dc8a7b3818f1d0df084c0610ec104c
Maybe you can report a bug for the gnome-online-accounts package in arch.
In the meantime I guess you can get the vapi-file from the fedora package and put it in your /usr/share/vala/vapi/-directory.

**Comment by horosgrisa** [comment]
@jangernert I rebuild gnome-online-accounts with --enable-vala. But now I obtain another error
```
error: Package `webkit2gtk-web-extension-3.0' not found in specified Vala API directories or GObject-Introspection GIR directories
```

**Comment by jangernert** [comment]
That's an actual bug. I removed support for the old webkitgtk-3.0 API. Seems like there were a few lines left over. But should be fixed now in master ;)

**Comment by horosgrisa** [comment]
@jangernert It works, but only with patched `gnome-online-accounts`

**Comment by jangernert** [comment]
What do you mean by "patched"? If you mean just the enabled vala-support, then I think this is a crucial feature missing in the arch-package and should be added there.

**Comment by horosgrisa** [comment]
@jangernert Sorry, I mean recompiled with enabled vala. Now feedreader can't be compiled on Arch without this.

**Comment by jangernert** [comment]
Like I said, you can open up a bug-report for the gnome-online-accounts-package.
Arch is always pretty quick with updating their packages, right?

**Comment by bil-elmoussaoui** [comment]
Reported this upstream https://bugs.archlinux.org/task/51526
