### ISSUE TITLE
Nextcloud support

### ISSUE THREAD

**Issue by okias** [jangernert/FeedReader#177]
can someone confirm that also Nextcloud News is supported?

Thank you

**Comment by jangernert** [comment]
I don't have a nextCloud instance set up. But why wouldn't it? It has the exact same API.
But haven't tested myself.

**Comment by okias** [comment]
So, after depressing experience with Owncloud, I switched to NextCloud and except re-entering credentials and reloading feedreader DB (I guess) it seems it works OK.

**Comment by jangernert** [comment]
Good to hear it works.
