### ISSUE TITLE
mark as read/unread with 'm'-key

### ISSUE THREAD

**Issue by gorrila** [jangernert/FeedReader#179]
Most feedreaders use the 'm'-key to mark an article as read/unread. It would be great to be able to switch between keyboard configs or to be able to set your own shortcuts.

**Comment by gorrila** [comment]
Feedly shortcuts: https://blog.feedly.com/feedly-keyboard-shortcuts/

**Comment by matthewdias** [comment]
How do you configure shortcuts? sorry if this isn't an appropriate place to ask.

**Comment by brendanlong** [comment]
I think you might be able to do it in gconf but right now they're not really configurable.
