### ISSUE TITLE
Pluggable backends using libpeas

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#181]
This is something I wanted to do for a long time, but it always seemed like more work than just putting all the back-ends into the code directly.
With the number of back-ends increasing and more and more new back-ends being requested, things were getting to a point where adding support for plugins seemed like the easier solution.

Work is happening in the "peas"-branch.

To add a new back-end to FeedReader one will most likely have to write 2 plugins. One that implements the API of the service and plugs into the feedreader-daemon. And one that provides the login-widget and plugs into the UI.

The underlying changes are imo big enough to justify the version number 2.0
This will also make it way easier for other people to add new services, since relevant functions are not scattered around the whole project any more. And plugins can be written in vala, C, gjs and python.

**Comment by bil-elmoussaoui** [comment]
I think we can do the same for sharing article back-end. This way the user can only get facebook back-end for example instead of having all of unneeded stuff.

**Comment by jangernert** [comment]
one thing after the other...

**Comment by ZanderBrown** [comment]
I don't think you would need to split them because a plugin is just a class implementing a specific interface so if you have functions starting `daemon_` for the plugins daemon related activities and `ui_` for well the UI required in the interface you only have to write one plugin it's just not all methods will be used in each part of the program

otherwise things get even more complicated to write a backend.

**Comment by jangernert** [comment]
The problem is, I can't use Gtk+-widgets in the interface for the daemon, otherwise the daemon would suddenly need gtk+ to compile. Not sure yet. I might do it.
Still WIP

**Comment by ZanderBrown** [comment]
have 2 interfaces one for ui other for daemon, plugins implement both but the component programs only know about their functions (as declared in there interface) and related data types

**Comment by jangernert** [comment]
@ZanderBrown already tried that (in like 100 different variations). The UI can't load the plugins because of undefined references. The other way around works though, the daemon can load the plugin with the gtk-stuff without any problems.

**Comment by jangernert** [comment]
The peas-branch is now merged to master. I added a demo-plugin with some commentary and a very brief overview in the wiki

https://github.com/jangernert/FeedReader/tree/master/plugins/demo
https://github.com/jangernert/FeedReader/wiki/Add-new-Backend
