### ISSUE TITLE
Keep read articles in unread tab temporarily

### ISSUE THREAD

**Issue by gorrila** [jangernert/FeedReader#182]
In the unread tab when I skip an article it immediately gets thrown out of the list. If I want to go back to an article I read 2 seconds ago I have to switch to the all tab.

So don't throw articles in the unread tab out immediately or make it an option to keep them temporarily. In other feedreaders the articles I skip in unread get greyed out and won't be displayed the next time the list gets loaded.

**Comment by gorrila** [comment]
example feedly:
![screenshot at 2016-08-15 14 55 10](https://cloud.githubusercontent.com/assets/7779514/17665022/7f1c4824-62f8-11e6-8d7c-b074c5572adb.png)

read articles are greyed out until list is loaded again

**Comment by jangernert** [comment]
Just use the "All Articles"-view. That's what it is for.

**Comment by gorrila** [comment]
This would also lead to better performance in the unread tab. Due to the removing of read articles from the list there's a lot of stuttering on my work computer.

**Comment by gorrila** [comment]
If you don't want to change this, would you accept a pull request for this? Seems to be an easy fix
