### ISSUE TITLE
No way to go back when adding new feedly user

### ISSUE THREAD

**Issue by gorrila** [jangernert/FeedReader#183]
When I add a new feedly account there is no way to go back. Probably because it's a webview.
Add back button.

Example:
Add new feedly account -> login with feedly account -> No way to go back if you want to login via google account instead

**Comment by jangernert** [comment]
In that case complete the login and change your account afterwards. All your data will get deleted and you will find yourself at the login-page again ;)

**Comment by gorrila** [comment]
Well I can't login :D I clicked on the wrong link (login with feedly account) but I have to login with my google account. The only way I found is closing the application and reopen it

**Comment by jangernert** [comment]
That DOES make sense. I'll add it to the to-do-list.
