### ISSUE TITLE
integrate with Ubuntu messaging menu, minimize to Ubuntu messaging menu

### ISSUE THREAD

**Issue by mateomiguel** [jangernert/FeedReader#186]
Like Liferea does, keep FeedReader running in the ubuntu messaging menu and notify when new RSS items show up. Also keep it running without showing its icon in the Unity menu.

**Comment by ZanderBrown** [comment]
Great if your on Unity. But most users are not

**Comment by jangernert** [comment]
The daemon is always running in the background, even if you close the UI. So no need to hide the window in the messaging menu. If you don't want to show the badge in the unity-sidebar you can compile without libunity or deactivate the badge in the tweaks.
