### ISSUE TITLE
Centos/Fedora: Cannot login to Feedly

### ISSUE THREAD

**Issue by VietTPham** [jangernert/FeedReader#187]
I cannot login to Feedly from Centos and Fedora.

What I did. Select Feedly -> click Login -> click "continue with feedly" -> filled out login -> click login -> screen goes back to "Where are your feeds?" screen.
I know my username and password work on Feedly if I go to feedly.com

On Centos, I compiled it from source.
On Fedora, I installed from "dnf" command.

Log is below, x-ed out the api key.

>[92m[ INFO  ] [0mEverything is logged. Used to debug!
>[92m[ INFO  ] [0mFeedReader 1.6 beta
>[94m[ DEBUG ] [0mMainWindow: setupCSS
>[94m[ DEBUG ] [0mContentPage: setup FeedList
>[94m[ DEBUG ] [0mUpdateButton: update status
>[94m[ DEBUG ] [0mUpdateButton: setSensitive true
>[94m[ DEBUG ] [0mMainWindow: determining state
>[94m[ DEBUG ] [0mSELECT count(*) FROM main.articles
>[94m[ DEBUG ] [0mcount 0
>[94m[ DEBUG ] [0mSELECT count(*) FROM main.categories
>[94m[ DEBUG ] [0mcount 0
>[94m[ DEBUG ] [0mSELECT count(*) FROM main.feeds
>[94m[ DEBUG ] [0mcount 0
>[94m[ DEBUG ] [0mSELECT count(*) FROM main.tags
>[94m[ DEBUG ] [0mcount 0
>[94m[ DEBUG ] [0mMainWindow: show login
>[94m[ DEBUG ] [0mMainWindow: show error bar - errorCode = 6
>[94m[ DEBUG ] [0mMainWindow: dont show error bar
>[94m[ DEBUG ] [0mHeaderBar: updatebutton status false
>[94m[ DEBUG ] [0mUpdateButton: setSensitive false
>[94m[ DEBUG ] [0mDBusConnection: setOffline
>[94m[ DEBUG ] [0mFeedList: new FeedList
>[94m[ DEBUG ] [0minitCollapseCategories
>[94m[ DEBUG ] [0mFeedList: restore selected row: 
>[94m[ DEBUG ] [0mFeedList: restoreSelectedRow: no selected row found, selectin default
>[94m[ DEBUG ] [0mArticleList: newList
>[94m[ DEBUG ] [0mArticleList: create
>[94m[ DEBUG ] [0mArticleList: offset 0
>[94m[ DEBUG ] [0mArticleList: newList
>[94m[ DEBUG ] [0mArticleList: create
>[94m[ DEBUG ] [0mArticleList: offset 0
>[94m[ DEBUG ] [0mlimit: 20
>[94m[ DEBUG ] [0mload articles from db
>[94m[ DEBUG ] [0mSELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles ORDER BY rowid DESC LIMIT 20 OFFSET 0
>[94m[ DEBUG ] [0mactual articles loaded: 0
>[94m[ DEBUG ] [0mlimit: 20
>[94m[ DEBUG ] [0mload articles from db
>[94m[ DEBUG ] [0mSELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles ORDER BY rowid DESC LIMIT 20 OFFSET 0
>[94m[ DEBUG ] [0mactual articles loaded: 0
>[94m[ DEBUG ] [0mArticleList: insert new rows
>[94m[ DEBUG ] [0mArticleList: create finished
>[94m[ DEBUG ] [0mArticleList: insert new rows
>[94m[ DEBUG ] [0mArticleList: create finished
>[94m[ DEBUG ] [0mwrite login data
>[94m[ DEBUG ] [0mhttp://cloud.feedly.com/v3/auth/auth?client_secret=FE012EGICU4ZOBDRBEOVAJA1JZYH&client_id=boutroue&redirect_uri=http://localhost&scope=https://cloud.feedly.com/subscriptions&response_type=code&state=getting_code
>[94m[ DEBUG ] [0mWebLoginPage: load URL: http://cloud.feedly.com/v3/auth/auth?client_secret=FE012EGICU4ZOBDRBEOVAJA1JZYH&client_id=boutroue&redirect_uri=http://localhost&scope=https://cloud.feedly.com/subscriptions&response_type=code&state=getting_code
>[94m[ DEBUG ] [0mMainWindow: show weblogin
>[94m[ DEBUG ] [0mHeaderBar: updatebutton status false
>[94m[ DEBUG ] [0mUpdateButton: setSensitive false
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent STARTED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent COMMITED
>[92m[ INFO  ] [0mArticleView: webextension-message: onDocLoaded
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent FINISHED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent STARTED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent COMMITED
>[92m[ INFO  ] [0mArticleView: webextension-message: onDocLoaded
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent FINISHED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent STARTED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent REDIRECTED
>[94m[ DEBUG ] [0mWebLoginPage: set feedly-api-code: xxxxxx
>[94m[ DEBUG ] [0mWebLogin: success
>[94m[ DEBUG ] [0mMainWindow: login failed -> go back to login page
>[94m[ DEBUG ] [0mMainWindow: show login
>[94m[ DEBUG ] [0mMainWindow: show error bar - errorCode = 6
>[94m[ DEBUG ] [0mMainWindow: dont show error bar
>[94m[ DEBUG ] [0mHeaderBar: updatebutton status false
>[94m[ DEBUG ] [0mUpdateButton: setSensitive false
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent FINISHED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent STARTED
>[94m[ DEBUG ] [0mWebLoginPage: set feedly-api-code: xxxxxx
>[94m[ DEBUG ] [0mWebLogin: success
>[94m[ DEBUG ] [0mMainWindow: login failed -> go back to login page
>[94m[ DEBUG ] [0mMainWindow: show login
>[94m[ DEBUG ] [0mMainWindow: show error bar - errorCode = 6
>[94m[ DEBUG ] [0mMainWindow: dont show error bar
>[94m[ DEBUG ] [0mHeaderBar: updatebutton status false
>[94m[ DEBUG ] [0mUpdateButton: setSensitive false
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent COMMITED
>[94m[ DEBUG ] [0mWebLoginPage: webView redirection
>[94m[ DEBUG ] [0mWebLoginPage: LoadEvent FINISHED
>[94m[ DEBUG ] [0mDBusConnection: setOffline
>[94m[ DEBUG ] [0mFeedList: new FeedList
>[94m[ DEBUG ] [0minitCollapseCategories
>[94m[ DEBUG ] [0mFeedList: restore selected row: feed -4
>[92m[ INFO  ] [0mArticleView: webextension-message: onDocLoaded
>[94m[ DEBUG ] [0mDBusConnection: setOffline
>[94m[ DEBUG ] [0mFeedList: new FeedList
>[94m[ DEBUG ] [0minitCollapseCategories
>[94m[ DEBUG ] [0mFeedList: restore selected row: feed -4
>[94m[ DEBUG ] [0mArticleList: get State
>[94m[ DEBUG ] [0mscrollpos 0.000000
>[94m[ DEBUG ] [0mscrollpos 0.000000
>[94m[ DEBUG ] [0moffset 0
>[94m[ DEBUG ] [0mShutdown!

**Comment by jangernert** [comment]
I need the log of the feedreader-daemon. The UI-log is not helpful since it only does the website-part of the login process.

**Comment by VietTPham** [comment]
Here is the daemon output

>$ feedreader-daemon
>[ INFO  ] Everything is logged. Used to debug!
>[ INFO  ] FeedReader Daemon 1.6 beta
>[ DEBUG ] daemon: constructor
>[ DEBUG ] daemon: new FeedServer and login
>[ DEBUG ] FeedServer: new with type -1
>[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_NO_BACKEND
>[ DEBUG ] daemon: bus aquired
>[ DEBUG ] Daemon: checkOnlineAsync
>[ DEBUG ] Daemon: checkOnline
>[ DEBUG ] FeedServer: setOffline
>[ DEBUG ] daemon: new FeedServer and login
>[ DEBUG ] FeedServer: new with type 1
>[ DEBUG ] Ping: trying ip-address 104.20.59.241
>[ DEBUG ] feedly backend: login
>[ DEBUG ] Feedly: getToken apiCode:
>[ ERROR ] Feedly: getToken response - missing code
>[ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
>[ DEBUG ] refresh token
>[ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
>[ DEBUG ] FeedServer: setOffline
>[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
>[ DEBUG ] daemon: new FeedServer and login
>[ DEBUG ] FeedServer: new with type 1
>[ DEBUG ] Ping: trying ip-address 104.20.60.241
>[ DEBUG ] feedly backend: login
>[ DEBUG ] Feedly: getToken apiCode:
>[ ERROR ] Feedly: getToken response - missing code
>[ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
>[ DEBUG ] refresh token
>[ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
>[ DEBUG ] FeedServer: setOffline
>[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR

**Comment by jangernert** [comment]
```
[ DEBUG ] Feedly: getToken apiCode:
[ ERROR ] Feedly: getToken response - missing code
```
Well, since you edit out the apiCode, I have no way of knowing if it is really missing or you just deleted it from the log =/
Is the apiCode present in gsettings under org.gnome.feedreader.feedly.api-code?

**Comment by VietTPham** [comment]
That is weird, because the feedreader program itself gives me the api key
>[ DEBUG ] WebLoginPage: set feedly-api-code: A1nrE6mgY3svxxxxxxx

**Comment by jangernert** [comment]
Yes, that's what I'm talking about. Is the key set in your gsettings? You can use dconf as a graphical editor for gsettings.

**Comment by jangernert** [comment]
?

**Comment by VietTPham** [comment]
Looks like adding the api key manually works.

**Comment by jangernert** [comment]
Any idea why it wasn't there anymore?
Because the UI read it from gsettings and printed it to the logs (the part where you X-ed out the apiCode)
https://github.com/jangernert/FeedReader/blob/stable/src/Widgets/WebLoginPage.vala#L94
