### ISSUE TITLE
Support Pantheon/Ubuntu Online Accounts

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#19]
Support Pantheon (identical to Ubuntu) Online Accounts to simplify Account setup where it makes sense.
Only use it if it is available.

**Comment by ZanderBrown** [comment]
Quite why the plan was to target Ubuntu rather that GNOME Online Accounts I don't know but after decisions at Canonical it would seem sensible to change this to GOA

**Comment by bil-elmoussaoui** [comment]
Ubuntu is now going to use Gnome with Gnome Online Accounts; Pantheon online accounts don't have any providers that we can use and I don't think that will change anytime sooner.
