### ISSUE TITLE
Would it be possible to add a text only mode for the content grabber

### ISSUE THREAD

**Issue by CharoSW** [jangernert/FeedReader#193]
One of the few problems I have with the internal content grabber is that it can take ages to do a full sync on my connection because some of the feeds I have are unnecessarily image heavy.  When one of my feeds is also a major news provider, which I usually just scroll through the headlines and read the ones which interest me, it ends up being a lot of download wasted on images which I never even see.  Thus i would like an option to turn off image grabbing and/or a way to only load images when you click into the article.  Just an option mind you, I don't want to change a default that probably works fine for most.

**Comment by ZanderBrown** [comment]
Should be easy enough to do just check against a gsettings boolean before fetching images.

**Comment by jangernert** [comment]
Sounds not too hard at first. But:
more options -> bigger testing matrix -> more bugs
So maybe at some point. But there are other things I want to get done for 2.0 first.
