### ISSUE TITLE
Can't compile. Not found mrss.h

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#194]
I can't compile mrss.h because `mrss.h` file missing
```
/tmp/yaourt-tmp-grisa/aur-feedreader-git/src/FeedReader/plugins/backend/local/rss-glib/rss-document-private.h:26:10: fatal error: 'mrss.h' file not found                     │··································
```
What package contain this file?

**Comment by jangernert** [comment]
Oh, I see.
You shouldn't have to install anything since the file is included in the repository. But since I had the package installed on my system during development I didn't notice it tries to pick up the file from /usr/include instead of the FeedReader-repo. Will fix...

**Comment by jangernert** [comment]
Should work now
