### ISSUE TITLE
Feed list is sorted from upside down when „sort feedlist by: alphabetically“

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#196]
Sorted from z till a.

**Comment by jangernert** [comment]
Not for me...

**Comment by fb87** [comment]
![feedreader_011](https://cloud.githubusercontent.com/assets/10520767/18214537/c3b72f04-714d-11e6-8df3-496d831fd61f.png)

**Comment by jangernert** [comment]
Well, you didn't say you had "only show feeds" active as well...
I can't read minds.
Now I can reproduce.

**Comment by fb87** [comment]
Forgot that this option existed. But the categories aren't sorted alphabetically either:

![auswahl_011](https://cloud.githubusercontent.com/assets/10520767/18214642/4c6e81bc-714e-11e6-8f53-a2cd68b0702b.png)

**Comment by jangernert** [comment]
Fixed with "only show feeds" active. Can't reproduce without this option turned on:
![screenshot from 2016-09-02 20-53-40](https://cloud.githubusercontent.com/assets/12012494/18214933/5b7cc6d6-714f-11e6-914b-35ab03213535.png)

**Comment by fb87** [comment]
Yeah of course, all your feed categories start with capital letters, here all upper case feeds are sorted alphabetically, then all lower case feeds are sorted alphabetically. ;)

**Comment by jangernert** [comment]
Oh, didn't even realize that.
Well, in that case I have to see if sqlite offers an option to not sort case-sensitive.

**Comment by fb87** [comment]
Thanks

**Comment by jangernert** [comment]
Luckily there is such a function. Changes are in master.
