### ISSUE TITLE
GOA as optional while building

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#198]
GOA is not available to openSUSE.

Few of the libraries are not yet fully implemented.
Is there any option to make GOA an optional ?

**Comment by ZanderBrown** [comment]
Really good point this. Understand why GOA is being added but it does limit use of FeedReader

**Comment by jangernert** [comment]
It's just the client-library [libgoa](https://software.opensuse.org/package/libgoa-1_0-0) that is required. So this should work on every desktop, not just gnome. Gnome-online-accounts does not have to be running.
If your distro has gnome >= 3.20 in the repo's (which is required for gtk+ and gstreamer anyways) then I am pretty sure there is also libgoa available.
Having lots of optional dependencies always makes the whole project more complex.
So if possible I want to keep the dependency.

**Comment by ViniciusBRodrigues** [comment]
I'm using opensuse 42.3 and the libgoa suggested by @jangernert is already installed, but I still geting this error:

`--   No package 'goa-1.0' found
`

**Comment by brendanlong** [comment]
Do you have `libgoa-devel` installed? (Or `libgoa-dev` -- I don't know how SUSE names the development packages).

**Comment by ViniciusBRodrigues** [comment]
There is no devel packages for `libgoa` in the openSUSE offical repos. I'm searching outside the official ones, but I didn't find.
