### ISSUE TITLE
A couple of design suggestions

### ISSUE THREAD

**Issue by aleksandar-todorovic** [jangernert/feedreader#2]
Here are a couple of suggestions on what I would do with the `gh-pages` branch:

1. In the first section, I would replace the RSS icon with one of the screenshots from the screenshot section. 
* I would keep the screenshots section, but reduce the number of pictures down to three. Five is a bit too much in my opinion, so I would remove the bottom two screenshots since they're not really showing anything new and important.
2. I would put the Get It section above the changelog (or _maybe_ even put it right after the "home" section).
3. I would rename the "home" section to FeedReader (in the top menu)
4. There's really no need to point the `this site is open source` label at the footer section to the Launchpad repository since this site is actually hosted here. I'd point it to this repository instead.

Let me know if you agree with some of them (and if so, which ones work for you) and I'll send a pull request.

**Comment by jangernert** [comment]
I don't know about 3.
People should know what they are downloading and not have false expectations and go complain afterwards. (for example someone sees the news about owncloud support and does not realize it is not included in the stable version yet) So at least put it after the features entry.
But the rest sounds fine to me ;)
