### ISSUE TITLE
Support Gnome Online Accounts  [$45]

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#20]
Support Gnome Online Accounts to simplify Account setup where it makes sense.
Only use it if it is available.

https://developer.gnome.org/goa/stable/

**Comment by kanishkablack** [comment]
Hai

What sort of integration are you looking into GOA, since most of the services used in Feedreader are not part of GOA.

Is the to integrate plugins to goa or just grab the available plugins to feedreader ?
