### ISSUE TITLE
fails to connect to owncloud news instance

### ISSUE THREAD

**Issue by divico** [jangernert/FeedReader#200]
While connecting to a owncloud news instance, I'm getting this error

[ INFO  ] Everything is logged. Used to debug!
[ DEBUG ] Share: refreshAccounts
[ INFO  ] FeedReader 2.0-dev
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] OwnCloud URL: https://xxx/index.php/apps/news/api/v1-2/
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 6
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: updatebutton status false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL: https://xx/index.php/apps/news/api/v1-2/
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList

** (feedreader:5979): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Widgets/ServiceInfo.vala: line 66: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)

** (feedreader:5979): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/UtilsUI.vala: line 132: uncaught error: Timeout was reached (g-io-error-quark, 24)

** (feedreader:5979): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/UtilsUI.vala: line 132: uncaught error: Timeout was reached (g-io-error-quark, 24)

**Comment by jangernert** [comment]
AGAIN: I need the logs from the daemon to get helpful information ...

**Comment by divico** [comment]
Sorry for that.

I killed the daemon and the gui. Here are the logs from a fresh start.

**Daemon:**
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 2.0-dev
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] OwnCloud: login
[ DEBUG ] OwnCloud URL: https://xxx/index.php/apps/news/api/v1-2/
[ DEBUG ] OwnCloud URL: https://xxx/index.php/apps/news/api/v1-2/
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_MISSING_PASSWD
[ DEBUG ] daemon: bus aquired
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ INFO  ] TLS errors: BAD_IDENTITY 
[ DEBUG ] daemon: new FeedServer and login

** (feedreader-daemon:6224): CRITICAL **: feed_reader_feed_server_interface_login: assertion 'self != NULL' failed
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.OfflineActions
[ DEBUG ] count 0
[ DEBUG ] OfflineManager - goOnline: no actions to perform
[WARNING] resetOfflineActions

** (feedreader-daemon:6224): CRITICAL **: feed_reader_feed_server_interface_symbolicIcon: assertion 'self != NULL' failed

(feedreader-daemon:6224): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
Segmentation fault (core dumped)

**and here the corresponding log from the gui:**

[ INFO  ] Everything is logged. Used to debug!
[ DEBUG ] Share: refreshAccounts
[ INFO  ] FeedReader 2.0-dev
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] OwnCloud URL: https://xxx/index.php/apps/news/api/v1-2/
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 6
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: updatebutton status false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] FeedList: new FeedList

** (feedreader:6229): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Widgets/ServiceInfo.vala: line 66: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -4
[ DEBUG ] FeedList: restoreSelectedRow: no selected row found, selectin default
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: create
[ DEBUG ] ArticleList: offset 0
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: create
[ DEBUG ] ArticleList: offset 0
[ DEBUG ] limit: 20
[ DEBUG ] load articles from db
[ DEBUG ] limit: 20
[ DEBUG ] load articles from db
[ DEBUG ] [ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles ORDER BY rowid COLLATE NOCASE DESC LIMIT 20 OFFSET 0

** (feedreader:6229): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Logger.vala: line 101: uncaught error: Stream has outstanding operation (g-io-error-quark, 20)
[ DEBUG ] actual articles loaded: 0
[ DEBUG ] actual articles loaded: 0

** (feedreader:6229): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Logger.vala: line 101: uncaught error: Stream has outstanding operation (g-io-error-quark, 20)
[ DEBUG ] [ DEBUG ] ArticleList: create finished
[ DEBUG ] ArticleList: insert new rows
[ DEBUG ] ArticleList: create finished
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL: https://xxx/index.php/apps/news/api/v1-2/
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList

** (feedreader:6229): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Widgets/ServiceInfo.vala: line 66: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed 1
[ DEBUG ] HeaderBar: updatebutton status true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed 1
[ DEBUG ] ArticleView: size changed
[ DEBUG ] DBusConnection: syncStarted
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0.000000
[ DEBUG ] scrollpos 0.000000
[ DEBUG ] offset 0
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] FeedList: new FeedList

** (feedreader:6229): CRITICAL **: file /tmp/packerbuild-1000/feedreader-git/feedreader-git/src/FeedReader/src/Widgets/ServiceInfo.vala: line 66: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed 1

I can provide access the to the server if you need. Thank you

**Comment by jangernert** [comment]
If I would need to guess, I'd say this seems to be the problem here:
```
[ INFO ] TLS errors: BAD_IDENTITY 
```

> The certificate does not match the expected identity of the site that it was retrieved from.

Also the password did not get saved correctly on your first try to log in (probably because of the TLS error).

**Comment by jangernert** [comment]
Did you fix the certificate of your server, or is this still an issue?

**Comment by divico** [comment]
Yes the problem was from the server. Its fixef. Sorry for that and thank you for looking into this!
