### ISSUE TITLE
 add windows 10 support

### ISSUE THREAD

**Issue by midpoint** [jangernert/FeedReader#202]
Hi,
Is that possible to add windows 10 support?

**Comment by jangernert** [comment]
Troll?

**Comment by midpoint** [comment]
I can't found a tiny tiny rss desktop client for windows 10.
welcome any ideas.

**Comment by jangernert** [comment]
Well, then don't use windows. Sounds pretty simple to me.

**Comment by ZanderBrown** [comment]
Actually could be possible

**Comment by jangernert** [comment]
1. afaik webkitgtk+ 4.0 api is [not available on windows](https://github.com/vinszent/gnome-twitch/issues/131)
2. I do certainly not want to make the lives of windows users any easier. If they want to use all the shiny free open source stuff, then ditch that proprietary os you are using ...

**Comment by ZanderBrown** [comment]
never said it would be easy or a good idea

**Comment by ZanderBrown** [comment]
Modern Reader is a fairly good free app that should solve @midpoint 's "issue"

**Comment by midpoint** [comment]
Thank ZanderBrown.
I will try it.

**Comment by midpoint** [comment]
I tried Modern Reader.It was good, but not for me.I need a desktop RSS client that supports TTS（tiny tiny rss）
