### ISSUE TITLE
Use GtkListBox to list services to select

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#204]
![screenshot from 2016-09-13 20-37-00](https://cloud.githubusercontent.com/assets/769861/18486563/dcd89bc4-79f1-11e6-9ebb-319de2d72745.png)

Instead of a drop-down menu. There's tons of room on the "empty state"/"first run" dialogue, so you could list all the services in a GtkListBox, with a check image next to the selected item, similarly to item selection in gnome-initial-setup.

**Comment by hadess** [comment]
The additional setup info needed could be in a separate GtkStack. Again, see gnome-initial-setup for how a multi-step configuration would look like.

**Comment by jangernert** [comment]
![1](https://cloud.githubusercontent.com/assets/12012494/18806067/aec667a8-821f-11e6-93ff-7159c1d33a88.png)

No, it's not finished. But at least it's already functional. The rest should be trivial.
