### ISSUE TITLE
Add option for different font sizes for the article list aswell

### ISSUE THREAD

**Issue by mnmlguy** [jangernert/FeedReader#207]
When using a smaller default system font like 9, feed titles, time and excerpts in the article list can get really small.

**Comment by jangernert** [comment]
I already said multple times that I don't want to overload the application with thousands of options. If you want to configure every aspect of everything I recommend using a new application. Or increase your system fontsize

**Comment by mnmlguy** [comment]
Sorry I'm a new user. This is just something I've noticed. If you won't implement an option for it that's fine, It's your project. This was just a suggestion.

**Comment by jangernert** [comment]
Sorry, meant "KDE" application not "new".
Typing on the phone
