### ISSUE TITLE
Add BazQux Reader support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#21]
https://github.com/bazqux/bazqux-api

**Comment by kanishkablack** [comment]
Any interested users can start testing the and start submitting any bugs regarding this plugin
 
https://github.com/jangernert/FeedReader/pull/210

**Comment by jangernert** [comment]
merged with commit 3802cb5428e8507d33df487364252270685e0e9a
still needs some work
