### ISSUE TITLE
Missing Local UI

### ISSUE THREAD

**Issue by alex285** [jangernert/FeedReader#213]
Built from AUR
https://aur.archlinux.org/packages/feedreader-git/

$ feedreader

(feedreader:20164): libpeas-WARNING **: Failed to load module 'localUI': /usr/share/FeedReader/pluginsUI//liblocalUI.so: undefined symbol: curl_easy_setopt

(feedreader:20164): libpeas-WARNING **: Error loading plugin 'localUI'

Curl:         curl-7.50.3-1
LibPeas:   libpeas-1.20.0-1

**Comment by ZanderBrown** [comment]
curl is apparently not being linked

**Comment by jangernert** [comment]
Was there a similar issue during built-time? The rest of the build should still have worked because they are separate projects. But it's weird for this issue only showing up at run-time.

**Comment by alex285** [comment]
@jangernert Here is the full output of make
https://gist.github.com/alex285/e8b37829f98363c297dbf99141c53f4d

**Comment by jangernert** [comment]
Btw: do you have just 'curl' installed or 'libcurl' as well? There are tons of different versions in the arch-repos. And I have no clue what are the exact differences.
https://www.archlinux.org/packages/?sort=&q=libcurl

@horosgrisa did you experience similar problems on arch?

**Comment by alex285** [comment]
@jangernert Just curl. I dont have idea what is libcurl-compat

**Comment by jangernert** [comment]
No idea either. Fedora just has 'libcurl' and 'libcurl-devel'.
But both 'libcurl-compat' and 'libcurl-gnutls' have the same upstream-url. Only difference is: one has the description '(without versioned symbols)'
My guess is, just install one of them. And if it doesn't work install the other one :D :D

**Comment by alex285** [comment]
@jangernert n installed both libcurl-compat and libcurl-gnutls. Same issue. Btw I'm using the [unstable-gnome] in case @horosgrisa check on Arch and it work for him!

**Comment by bil-elmoussaoui** [comment]
@alex285 I'm using unstable-gnome repo too and everything works fine here.

**Comment by jangernert** [comment]
But did you compile from source or did you use feedreader-git aur?

**Comment by alex285** [comment]
@jangernert You are right, It works from Github, but it doesn't work from AUR. How's that possible?!
Should I close that issue? It seems it affects only AUR package

**Comment by jangernert** [comment]
I think we can wait a few days for a response from the package maintainer. And I will close this when he figured out what's wrong. And if he doesn't respond the next few days I will close this.
Thx for your report.
