### ISSUE TITLE
Extremely Slow Syncing

### ISSUE THREAD

**Issue by rmad17** [jangernert/FeedReader#217]
I am running Linux Mint 18. The feeds are extremely slow to sync. Sync goes on forever and some categories don't sync at all.

**Comment by jangernert** [comment]
How many feeds are you subscribed to?
FeedReader tries to download the full content of each article. So if you have hundreds of feeds with thousands of articles, of course it will take some time.
You can deactivate the content grabber in the settings if you don't like it and restart the daemon afterwards.
In master branch you can also deactivate the downloading of any images which should speed up things even more.

... or maybe you should think about if you really read all the feeds you subscribed to :P

**Comment by rmad17** [comment]
This is a really bad response. If instead of asking more questions on how to solve the problem you will make assumptions that I have subscribed to 1000s of feed then I hardly feel anybody is going to be encouraged to report issues. Also this is my assumption most people on github know the difference between `normally slow` and `abnormally slow` syncing and would report slowness only when its abnormal. 
As for me I am done using this tool. Will keep on using the chrome plugin until another community desktop reader comes up that is willing to listen and enquire into issues.

**Comment by jangernert** [comment]
Have fun

**Comment by weddi-eddy** [comment]
Can we reopen this issue?  I am also running Linux Mint 18 and I have noticed significant slowdown in the time it takes to synchronize articles.  It does eventually load but not as fast as I can read or ignore.

I have read above that you can deactivate the content grabber in the settings but perhaps with a little creativity and some development, there is a better way.

I'm wondering if it makes sense to have a third (default?) option to pull just the Titles only and as you click on each article, you pull the information then.  That way, you can easily get your full list and wait to load the articles you want to read.  I'm sure this would cut down on load time.

I'm a little confused on why it does take forever to load.  On Windows, I use an application from their store called Nextgen Reader and generally loads everything fairly quickly (let's say about 250+ articles a day).  I'm not too sure what their model or approach is to loading articles.

When the articles do load however, this is the best reader for Linux. I'm hoping we can make it better.

**Comment by jangernert** [comment]
@weddi-eddy The Content Grabber downloads the whole article from the website and then tries to figure out what part of the website belong to the article and what parts can be thrown out. Then all the images of the article are downloaded. This takes a while. If you deactivate the Content Grabber you will still have text in your articles. But most websites only release the first few lines of their articles in the rss-feed to force the user to click the website and generate ad-revenue. That's what the Content Grabber is for. If you don't care for that you can safely deactivate it without any drawback.
In master the process of downloading stuff is already reworked. All the articles are loaded from the rss-server and displayed in FeedReader. This should be quite fast. Then afterwards every article will be processed by the Content Grabber in the background. While this is happening you can already browse all the new articles (with cut off text in some cases).

**Comment by weddi-eddy** [comment]
Ok. What do you mean by, "In mater the process of downloading stuff is already reworked"? Is that the version I downloaded using the PPA in the Ubuntu instrucitons?

**Comment by jangernert** [comment]
Nope. Launchpad chokes on master for some reason (cmake variable). Also Mint is based on 16.04, right? That's already pretty outdated. Master requires at least gnome 3.20 stack.
