### ISSUE TITLE
Daemon logging sensitive session information to syslog

### ISSUE THREAD

**Issue by gitkrax** [jangernert/FeedReader#224]
The daemon crashed and I was trying to figure out what happened, and looked at my syslog. I noticed that the daemon seems to log the password as debug information.

Example line with sensitive information removed: 

`Sep 30 07:50:48 MACHINENAME gnome-session[2322]: #033[94m[ DEBUG ] #033[0m{"op":"login","user":"USERNAME","password":"PASSWORD"}`

**Comment by jangernert** [comment]
Yes, should probably remove it already.
It was useful at the beginning, when I was originally implementing the ttrss-API.

**Comment by jangernert** [comment]
done in master
