### ISSUE TITLE
FeedReader daemon crashes on a segfault

### ISSUE THREAD

**Issue by gitkrax** [jangernert/FeedReader#226]
The FeedReader daemon seems to segfault regularly. It is running in the backgrounds, so I can't be sure what triggers it. I've included the apport crash report in a gist:

https://gist.github.com/gitkrax/d3705781ffa4f91ada662465c628f8ae

**Comment by jangernert** [comment]
Can you provide a backtrack?
You can use coredumpctl to get it after the process already crashed. https://www.freedesktop.org/software/systemd/man/coredumpctl.html

**Comment by gitkrax** [comment]
Sorry, but coredumptcl seems to clash with apport, and I'd rather not mess up my system. I tried getting the trace with apport, but ran into problems. I will look into it again and try to get the trace. This seems to happen regularly, so there is no shortage of crash reports to try.

**Comment by jangernert** [comment]
Well, then just use plain gdb. Kill the running daemon 'killall feedreader-daemon', start it with gdb 'gdb feedreader-daemon' and type 'run'.
Now make it crash.
Once it crashed type 'backtrace' and post the log of the daemon as well as the 'backtrace'. ;)

**Comment by jangernert** [comment]
So?

**Comment by gitkrax** [comment]
Couldn't get it to work, sorry. Moved onto other reader that I could get to work on my OS.

**Comment by jangernert** [comment]
I thought that was the whole point? :D Making it crash so you can upload the backtrace.
But since you won't investigate further I'll close this.
