### ISSUE TITLE
Feature request: sort articles from oldest to newest

### ISSUE THREAD

**Issue by gitkrax** [jangernert/FeedReader#227]
Currently, there are two options for sorting articles: received and date. It seems they result in a roughly equal order: newest articles are shown first, then older articles. Most frequently, I would like to read feeds sorted from oldest to newest articles.

**Comment by jangernert** [comment]
Already in master

**Comment by gitkrax** [comment]
Any chance of pushing a new build to the ubuntu-repo?

**Comment by jangernert** [comment]
I tried to get the ppa to build a new package for 16.10, but somehow launchpad.net messed up the build.
Ubuntu 16.04 and earlier is out of question because master needs at least Gnome 3.20.

**Comment by gitkrax** [comment]
That is not even out yet. Thanks for the info, I'll remove the ppa and try some other reader.

**Comment by jangernert** [comment]
Yes, sadly Ubuntu 16.04 is shipping a gnome stack that is by now over 1 year old.

**Comment by jangernert** [comment]
@gitkrax can you still provide the log of 'feedreader-daemon' and a backtrace for issue #226 ?
