### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#228]
## Please do not close this issue

**Comment by horosgrisa** [comment]
- [ ] Some strings have disappeared: Change account, Report a bug, Bounties, Shorcuts, About

![2016-10-02 20-23-01](https://cloud.githubusercontent.com/assets/4980269/19022309/2d0ce1f4-88de-11e6-8e75-5fb645bf9844.png)

**Comment by jangernert** [comment]
Updated the pot file. f27e90df72c13c44238b996536b32bb59ca991ed
But during development lots of strings and position of string-definitions can change. So if you're using master-branch translations will not always be up to date ...

**Comment by horosgrisa** [comment]
@jangernert https://www.transifex.com/dev-feedreader/feedreader/translate/#ru/rssreaderpot/94170627?q=Shortcuts

**Comment by horosgrisa** [comment]
@jangernert This strings dispensar from transifex.

**Comment by jangernert** [comment]
Well, the pot-file has to be submitted to transifex as well. Let's see when @bil-elmoussaoui has time to do that.
Like I said, don't expect 100% perfect translations during development. The code is constantly changing, so it makes no sense to update the translations every other day.

**Comment by bil-elmoussaoui** [comment]
I updated the pot file. I've configured the auto-update of pot file but it's not working correctly.. I will try to contact Transifex team as soon as possible to fix this
