### ISSUE TITLE
Add FeedHQ support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#23]
http://feedhq.readthedocs.org/en/latest/api/index.html

**Comment by kanishkablack** [comment]
Hai, team i have been working on this module,
- [x] Login
- [x] Sync Subscriptions
- [] Sync Unread Articles
- [] Sync Streams Articles
- [] import OPML
- [] Mark Stared
- [ ] Icon
- [x] delete category
- [x] rename category
- [x] create category
- [ ] move feed to new category
- [x] rename feed
- [x] remove feed
- [] add feed
- [] mark feed as read
- [] Mark As Read (Article and Categories)
- [ ] mark category as read
- [ ] mark all articles as read

Tags is not supported
- [ ] if one feed can be part of multiple categories: remove feed only from one category
- [ ] if multiple category-levels are allowed: move category
- [ ] rename tag
- [ ] create tag
- [ ] delete tag
- [ ] remove/add tag to article

**Comment by kanishkablack** [comment]
Any interested users can start testing the and start submitting any bugs regarding this plugin
 
https://github.com/jangernert/FeedReader/pull/209

**Comment by jscurtu** [comment]
if anyone is interested, this can also be easily tested from the master flatpak branch. 
once the FeedReader was installed like in our instructions, a simple : 

`flatpak install org.gnome.FeedReader-origin org.gnome.FeedReader//master`

"org.gnome.FeedReader-origin" is the repo that has been added ..
