### ISSUE TITLE
username/password not saved after reboot on kubuntu 16.04

### ISSUE THREAD

**Issue by driminicus** [jangernert/FeedReader#232]
If I use 'change account' everything works as expected. If I then close feedreader and open again everything is fine. If I kill feedreader-daemon and restart it, everything is fine, but if I reboot the pc feedreader-daemon gives:

[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 1.6.2
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] FeedServer: new with type 0
[ DEBUG ] TTRSS: login
[ DEBUG ] ttrss URL: https://serverurlhere/tt-rss/api/
[ DEBUG ] FeedServer: setOffline
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_MISSING_PASSWD
[ DEBUG ] daemon: update badge count 22
[ DEBUG ] daemon: bus aquired
[ ERROR ] invalid ttrss session id

Creating a new account (obviously) fixes this, as long as I don't log out.

**Comment by jangernert** [comment]
You can check seahorse (aka Gnome Passwords and Keys) and see if your old password got deleted and a new one was successfully created.
The whole process was refactored in master, so not even sure if that problem is still there.
Btw: did you re-register the exact same account or a totally different one?

**Comment by driminicus** [comment]
I re-registered the same account, on the same server. I do have gnome-keyring installed, but not seahorse, so I'll look at that when I get home tonight.
Are there other gnome dependencies than gnome-keyring required? I installed through the ubuntu ppa repo, so I assumed that would fix dependencies issues.

I did notice there is no entry for feedreader in kwallet, but I'm fairly sure gnome-keyring and kwallet don't play nice with each other just yet, so I guess that's expected.

**Comment by jangernert** [comment]
Seahorse is just a viewing-application for all the stored passwords, so not actually needed to use libsecret-applications.
No idea about other dependencies. Tbh, I didn't even know about gnome-keyring until someone encountered [issues](https://github.com/jangernert/FeedReader/issues/150) without it in arch. I use libsecret and always assumed that would pull in all the necessary dependencies.
So once you have Seahorse installed, can you do everything again and see at which point the password disappears from the gnome-keyring-database?
Also I am not quite sure what exactly you mean here:

> Creating a new account (obviously) fixes this, as long as I don't log out.

Creating a new account? So you mean once you rebooted and your password was lost, you entered your username and password again, and after that the password doesn't disappear after a reboot?
And with "log out" here you mean logging out of the FeedReader-account, not your kde-session, right?

**Comment by driminicus** [comment]
Sorry, I wasn't clear. To fix the issue I use the option 'change account' which is what I meant by 'creating a new account.' There I fill in the same tt-rss login credentials (so I don't create a new ttrss account). This works for the whole kde-session, closing feedreader works fine, and as far as I can tell I can kill feedreader-daemon, restart it and then feedreader still works.
But as soon as I end the kde-session in some way (logging out or rebooting) and start feedreader it gives the 'offline' error, and feedreader-deamon gives the error pasted above.

I'll be able to look at the contents of the gnome-keyring with seahorse in a few hours, so I'll report back then.

**Comment by jangernert** [comment]
Ah okay, now I get it.
And this only started to occur after you changed your account for the first time?
What I mean by that:
When you first installed FeedReader and logged in to your tt-rss account, you could reboot the pc without having to login again afterwards?

**Comment by driminicus** [comment]
I found the problem. The gnome-keyring did indeed contain the username and password (mutiple even) but for some reason the default keyring does not get unlocked when I log in. Using seahorse I can manually unlock the keyring, which doesn't even require a password (I assume that's because it's coupled to my login) and after unlocking everything works as expected.

I'll have to look in to why the keyring doesn't get unlocked. Thanks for helping me and thanks for this project!

**Comment by jangernert** [comment]
Glad I could help out.
The unlocking seems to be coupled with the display-manager. GDM automatically unlocks gnome-keyring.
Does kubuntu still use KDM or the new SSDM?
For KDM there is a package kdm-gdmcompat that unlocks gnome-keyring. Or maybe this trick does help: http://tuxrocket.com/2013/01/03/getting-gnome-keyring-to-work-under-kde-and-kdm/
For SSDM this seems to be fixed in master. But the fix only went in half-way through march according to the ticket: https://github.com/sddm/sddm/issues/356
So I guess it didn't made it into 16.04.
