### ISSUE TITLE
Showing feed fetching progress

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#235]
Since fetching feeds takes some minutes, it would be nice if the progress could be shown.

**Comment by jangernert** [comment]
There is no way of knowing the the exact progress. Some articles take 1s, other articles with lots of assets take 20s or more.
And showing a progress-bar that randomly jumps forward is not what I would call useful.
Btw: if you would use the daemon as intended (not only running when the UI is running), you wouldn't need to care that much since the snyc happens in the background ;)

**Comment by fb87** [comment]
Thought that a progress status like 7 feeds out of 51 would be useful – without information about articles. Now it's running like 10+ minutes and I'm really missing some feedback. One could assume that it's hanging because of such a long duration. So some information is better than none… and I know no status bar that's processing linear, all status bars jump around.

I sometimes tether over my phone, that's why I don't want to waste traffic volume by an always-running daemon. ;)

**Comment by fb87** [comment]
Downloading updates in the background is one of the main critics of Win10, and therefore the reason why many people are switching to Linux by the way. ;)

**Comment by fb87** [comment]
Maybe it's a good idea to first load the feed table, that the list can be shown, and then show a spinner next to the currently updated feed (and category, when visible). If you update the feeds from top to bottom (regardless of the sorting order) one can see that progress is done and estimate when it's finished.

**Comment by jangernert** [comment]
I am about to refactor the way the content-grabber gets used internally. That is something that has been on my list for a long time.
So first the articles are written to the database 'as is', so they can be displayed in the UI.Then afterwards all new articles are processed by the content-grabber and image-downloader. This way the sync will feel faster, but roughly take the same amount of time total.

**Comment by jangernert** [comment]
I think I'll show the general state of the sync. Like: "getting feeds & categories" then "getting articles" and finally "grabbing full article content 13/21".

**Comment by fb87** [comment]
Yes, please add some counter, doesn't matter if feeds or articles, but at least some progress information. Would be nice if you could implement the grabber in a way, that the articles of the current shown feed are first to be grabbed and like sort order, so that one can sift through the articles as fast as possible. :)

**Comment by jangernert** [comment]
For the actual syncing from the server there will be no "counter". That's not how the process works.
Like I said there will be rough information. For the content-grabber however I can print exactly how many articles are done and how many are left. That should be the more time-consuming process anyways.

![screenshot from 2016-10-09 02-32-26](https://cloud.githubusercontent.com/assets/12012494/19216734/08f905f0-8dc9-11e6-836a-979bcedf38ed.png)

This is how it looks right now in master. Looks could be improved at some point.

**Comment by fb87** [comment]
I sometimes saw a counter like "fetching 1897/4501 articles", which is very nice!

While syncing, could you please provide an option for cancelling (e.g. byb showing a cross symbol when hovering with the mouse above the spinner)? Because in normal mode, the daemon isn't killed by closing the application and still continues to run – but the normal user doesn't recognize.

**Comment by jangernert** [comment]
No, this is getting further and further away from the original intended use.
This is not a KDE-application. Even the option to kill and start the daemon together with the UI is not really what the whole design is supposed to to.
I'm really starting to think FeedReader might not be the application for you :P

**Comment by fb87** [comment]
I don't understand what the toolkit has to do with functionality, but I assume you mean the very restricted functionality of the Gnome people's software. The problem I see, is that you give the user some program, he/she cannot really quit. Except the user knows that there is a feedreader-daemon and how to kill it – both cannot be taken for granted for most of the users.

So when someone wants to quit the application due to saving traffic volume (not everybody has a fiber link) or energy (FR needs a noticable amount of cpu power sometimes), the user has to reboot the machine for making sure, FR is killed. And btw: Fetching lasted 40 minutes a few days ago. And without some information about fetching status, no one knows if the program hangs or not.
