### ISSUE TITLE
Article preview rows are a little bit too small

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#236]
Maybe an issue due to my UHD resolution. The boxes should be made a tad taller. When selecting a box, it automatically gets rendered taller to fit the content, but the others stay too small.

![auswahl_008](https://cloud.githubusercontent.com/assets/10520767/19216437/0a27827e-8dbc-11e6-9fc6-d8e8827757b7.png)

**Comment by jangernert** [comment]
Looks okay on gdk_scaling = 1 imo
![screenshot from 2016-10-09 01-09-44](https://cloud.githubusercontent.com/assets/12012494/19216466/2f630c74-8dbd-11e6-83d1-b321f630a520.png)

**Comment by fb87** [comment]
Right, then I was right with it maybe occurring because of UHD. But this wasn't the case in the older version, somehow. I edited my text above that they get rerendered at being selected, don't know if I was fast enough for you to see the edit.

**Comment by fb87** [comment]
This happens just when titles are comprised of two lines, can you test this at your machine?

**Comment by jangernert** [comment]
![screenshot from 2016-10-11 19-46-15](https://cloud.githubusercontent.com/assets/12012494/19281632/71ad58d4-8feb-11e6-8357-c554b682b573.png)

2 lines and still unread (bold font takes up a few pixels more than normal) and still no issue.
Even if the widgets are too big for the listboxrow, gtk should just make the row expand.

**Comment by fb87** [comment]
Maybe it's my GTK…

**Comment by jangernert** [comment]
I can reproduce this by blowing up the font-size super huge (>12).
But like I said, this should be handled by gtk afaik.

**Comment by fb87** [comment]
Could you reference the appropriate code passage, please? Then I'll open a bug report there.

**Comment by jangernert** [comment]
https://github.com/jangernert/FeedReader/blob/master/src/Widgets/ArticleRow.vala
I allocate a default height of 100 for the row.
At first the row is filled with a Gtk.Stack with a Gtk.Spinner. Then later the actual content of the row is loaded and also put into Gtk.Stack and the stack switches to the new widget. Somehow the row is not expanded when the stack switches to the newly loaded widget and the widget is bigger than the originally allocated 100 units of height.
As far as I know Gtk should just expand the parent widget to fit the child.

**Comment by fb87** [comment]
The rows are resizing when hovering over either the star or the read/unread button. Does this maybe help you? Maybe due to some other child-parent-relationships?
