### ISSUE TITLE
Starting FR via CLI and closing it per titlebar doesn't kill the application

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#239]
Branch: master

• Daemon continues running and pgrep lists two processes, but killing the daemon is selected per dconf. FR was syncing at the time I clicked close.
• Starting FR per dock again leads to a segfault and kills one process
• The daemon is still running

Have you implemented your program as GtkApplication? Maybe this helps managing running instances.
https://developer.gnome.org/gtk3/stable/GtkApplication.html

**Comment by ZanderBrown** [comment]
Yes:
https://github.com/jangernert/FeedReader/blob/master/src/FeedReader.vala#L23

**Comment by jangernert** [comment]
Did you get a message like this upon quitting?
```
** (feedreader:2887): CRITICAL **: void webkit_web_view_run_javascript(WebKitWebView*, const gchar*, GCancellable*, GAsyncReadyCallback, gpointer): assertion 'WEBKIT_IS_WEB_VIEW(webView)' failed
```

**Comment by fb87** [comment]
Yes, I receive this message.
