### ISSUE TITLE
[FR] Export saved stories to epub (offline read-it-later alternative)

### ISSUE THREAD

**Issue by ptvyqmnq** [jangernert/FeedReader#241]
To complement local and offline feeds, offer export to ePub similar to the [GrabMyBooks](http://www.grabmybooks.com/) browser extension.

Ex. use case: User is offline but has saved articles. User chooses some to be made into an epub file which can be read on any device that supports the format.

**Comment by jangernert** [comment]
I dedicated the whole day to implementing this. But without real success. The html of the articles is just not suitable sometimes. Different eBook-readers display the content differently or not at all sometimes. So I implemented the next best thing: Save as PDF.

**Comment by ptvyqmnq** [comment]
Thanks for working on it and i'm glad the request interested you. 

It's hard for me to test it since I don't have a supported RSS service, but what about exporting the feed HTML for viewing in a browser or processing by a different tool?

Can saved stories be opened in a web browser reading the local content instead of visiting the parent site directly? Then users could use any html converter.

**Comment by jangernert** [comment]
Why is it so important to have epub? Doesn't PDF do pretty much the same?

**Comment by ptvyqmnq** [comment]
PDF is really only good for printing or viewing on a desktop. The benefit would be on devices that don't have FeedReader installed like an e-ink ebook reader or smartphone. ePub allows text to be reflowed to fit a smaller screen.

**Comment by jangernert** [comment]
But there are also tools available to convert PDF to epub.
To export the HTML directly would be more work, because the img-paths had to be rewritten and all the images had to be properly exported as well.

**Comment by ZanderBrown** [comment]
Adobe Reader for Pocket PC 2003 could re-flow a PDF.

Most eReaders either have PDF support built in or have the ability to 'import' them into a format they like.

ePub would have been nice but PDF gives 98% of it's benefits.
