### ISSUE TITLE
Second to last article is disappearing instead of the last

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#242]
As you see in the screencast, it can happen, that the current article doesn't disappear after being read. Then reading the next article make the prevous article disappear, with this next one to become the former not-disappeared-article. Looks like some bug in your linked list or some missing lock. Can be stopped when the faulty article is selected again.

![peek 2016-10-13 18-34](https://cloud.githubusercontent.com/assets/10520767/19358553/94ee4fec-9176-11e6-859e-c96bf005aba6.gif)

**Comment by fb87** [comment]
Not 100% sure, but I think this happens at articles from the Curved feed.

**Comment by jangernert** [comment]
Just a weird idea: Can you add a second login to your feedly account (feedly supports multiple logins for a single account) with my email and a random password? So I can see if there is anything that could cause all the issues you are having.
Apart from modifying a few articles (un/read or un/star) I will not modify any data. And you can remove the additional login a few days after.

**Comment by fb87** [comment]
Here are my settings:

![auswahl_012](https://cloud.githubusercontent.com/assets/10520767/19396757/ec89b59c-9244-11e6-9ecb-d499e5952c1b.png)
![auswahl_012](https://cloud.githubusercontent.com/assets/10520767/19396793/1012bcf2-9245-11e6-85a8-dfc74d627510.png)
![auswahl_013](https://cloud.githubusercontent.com/assets/10520767/19396796/1220cbce-9245-11e6-8f4e-c56f490c9ef1.png)

I'll check Feedly-logins tomorrow, no time atm.

**Comment by fb87** [comment]
Branch: master

Now it happened again on Ars Technica. What you see is, that it doesn't end if there is no (unread) article below, and I have to select the article on top for the read articles to disappear.

![peek 2016-10-18 01-07](https://cloud.githubusercontent.com/assets/10520767/19458871/39c239ec-94cf-11e6-82e0-54f6f9ca28c1.gif)

**Comment by fb87** [comment]
I think this is connected with single news appearing multiple times. Here are the logs of my instance, which I opened and right the first feed got shown and diplayed the first article two times (in a former session, it got shown for far more times – about every second appeared a new duplicate, but I couldn't reproduce this).

**Comment by fb87** [comment]
[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/559404/feedreader.tar.gz)
