### ISSUE TITLE
no yakkety yak version in ubuntu ppa

### ISSUE THREAD

**Issue by driminicus** [jangernert/FeedReader#243]
As per title, there is no version for ubuntu 16.10 available yet.

**Comment by jangernert** [comment]
Launchpad.net messes up the path of a dynamically created vapi-file and fails the build.
If someone can resolve the problem with launchpad.net he/she is welcome to create a new build.
https://launchpadlibrarian.net/289455962/buildlog_ubuntu-yakkety-amd64.feedreader_2.0.0~r1347+pkg25~ubuntu16.10.1_BUILDING.txt.gz

Also I wanted to discontinue the ppa for a long time now to let someone with more knowledge and time for it take over. Packaging is not something I'm interested in. All the packages for other distributions are already maintained by other people.

**Comment by skewty** [comment]
I don't see any mention of a commit that fixed or resolved anything so are we to assume that this is a WILL NOT FIX?  I don't see that mentioned clearly either.

If PPA support ended at 16.04 then the [Installation section of the webpage](https://jangernert.github.io/FeedReader/) should be updated as it still currently leads people to believe that 16.10 is supported through the PPA.

**Comment by jangernert** [comment]
Pretty much. Theoretically launchpad.net should be able to build master on 16.10.
But I will not put my energy into solving the issue with launchpad.
Manual building works fine. So FeedReader is still supported on 16.10, there is just no package.

**Comment by thenitai** [comment]
Yeah, an update on the ReadMe/Installation page would be helpful. IIt would save some time... like hunting down why it doesn't work, etc....
