### ISSUE TITLE
Fix goa head file error

### ISSUE THREAD

**Issue by PterX** [jangernert/FeedReader#254]
I think there is a issue

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6563e29..70506d5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -54,7 +54,8 @@ set(MODULES
        gstreamer-1.0
        gstreamer-pbutils-1.0
        libpeas-1.0
\-       libcurl)
\+       libcurl
\+    goa-1.0)
 
 if(LIBUNITY_FOUND)
        list(APPEND MODULES unity)

**Comment by jangernert** [comment]
Why would you think libgoa should be added to the modules here?
Afaik all the goa-calls are now moved into the plugins (only pocket at this point). So there is no reason to keep it as a dependency for libfeedreader.
Does master currently not build on your machine?

**Comment by dsboger** [comment]
I'm not sure it is related, but on my machine I cannot build using feedreader-git from AUR. The following error occurs:

```
[ 93%] Building C object plugins/share/Pocket/CMakeFiles/pocket.dir/PocketAPI.c.o
/home/dsboger/.cache/pacaur/feedreader-git/src/FeedReader/build/plugins/share/Pocket/PocketAPI.c:27:21: fatal error: goa/goa.h: Arquivo ou diretório não encontrado
 #include <goa/goa.h>
                     ^
compilation terminated.
```

**Comment by jangernert** [comment]
Like I said, libgoa isn't a dependency of libfeedreader anymore, but it is a dependency of the pocket-plugin. Do you have the develpment package of libgoa installed?
Alternativly you can just deactivate pocket support with -DPOCKET=OFF

**Comment by dsboger** [comment]
Yes, I have the development headers of libgoa installed. I'd like to include pocket support, if possible. I think there is an actual issue here with the build system. I'm on Arch Linux, so maybe there is a distro-related problem? 

These are the build instructions I'm using (from current master):

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DUSE_WEBKIT_4=ON -DGSETTINGS_COMPILE=OFF -DWITH_LIBUNITY=OFF ..
make
```

**Comment by dsboger** [comment]
I'm not too knowledgeable of CMake, but I checked the `build/plugins/share/Pocket/CMakeFiles` directory with `grep -iR goa .` and saw no mention of `-I` for goa headers.

**Comment by jangernert** [comment]
You can drop the USE_WEBKIT_4 and WITH_LIBUNITY if you compile master ;)
As you can see the goa-1.0 is a dependency for the pocket-plugin
https://github.com/jangernert/FeedReader/blob/master/plugins/share/Pocket/CMakeLists.txt
Once I'm home I will do a clean build of master and see if it just works on my end because of old build-files that are still around.

**Comment by dsboger** [comment]
I experimented a little and found that compilation finishes if I manually append `-I/usr/include/goa-1.0 -I/usr/lib/goa-1.0/include` to the `C_FLAGS` variable in file `build/plugins/share/Pocket/CMakeFiles/pocket.dir/flags.make` and call `make` again. 

Now, I suppose that file is generated by CMake, that should have added those includes. I think my system is properly configured, considering that calling `pkg-config --cflags goa-1.0` results in `-pthread -I/usr/include/goa-1.0 -I/usr/lib/goa-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include`.

**Comment by dsboger** [comment]
I figured the problems. There are two issues with `plugins/share/Pocket/CMakeLists.txt`:
- It is using the same prefix `DEPS` as the main CMakeLists.txt. I didn't go verify it, but it seems the variables are not updated once they are set. I changed the prefix to `POCKET_DEPS`
- It is also missing the following, after `pkg_check_modules(POCKET_DEPS REQUIRED goa-1.0)` (I saw similar lines in the root CMakeLists.txt and decided to give it a try. It worked):
```
add_definitions(${POCKET_DEPS_CFLAGS} -DGOA_API_IS_SUBJECT_TO_CHANGE)
link_libraries(${POCKET_DEPS_LIBRARIES} -lm)
link_directories(${POCKET_DEPS_LIBRARY_DIRS})
```

I'll make a PR with the changes in a minute.

**Comment by jangernert** [comment]
Wow, that was more in-depth than I expected, thx.
Also I can confirm it only worked on my machine because I did and incremental build and not a fresh one. I guess this was too much copy&paste :P 
Thx for your pull request, I'll take a look at it in just a minute ;)
