### ISSUE TITLE
[Inoreader] Could not connect: Connection refused

### ISSUE THREAD

**Issue by dsboger** [jangernert/FeedReader#256]
I'm using FeedReader from master, but I cannot connect to my Inoreader account. I get the message "Could not connect: Connection refused". I'm attaching the output of both the feedreader-daemon and feedreader. Let me know if I can provide more information. Thanks!

[feedreader-daemon-output.txt](https://github.com/jangernert/FeedReader/files/567630/feedreader-daemon-output.txt)
[feedreader-output.txt](https://github.com/jangernert/FeedReader/files/567631/feedreader-output.txt)

**Comment by dsboger** [comment]
I modified InoReaderAPI.vala to print the response of the Inoreader API and it is "AppId required! Contact app developer. See http://www.inoreader.com/developers". Seems like there may be a problem with the request.

**Comment by jangernert** [comment]
Can you please explain exactly what you did?
So you started FeedReader and selected InoReader. What method of login did you use? User/PW, Google or Facebook?
Where did the "Could not connect: Connection refused" appear?
Can you open up dconf-editor and go to org->gnome->feedreader and reset the plugin-key to it's original value 'none' and try to log in again and attach the log of logging in?

**Comment by dsboger** [comment]
I updated from stable to master. When I opened FeedReader I had to choose a service. I picked Inoreader, the same I was using beforehand, logged with e-mail and password and authorized FeedReader to access my account (i.e. my login worked). Then the error message was presented on the screen and nothing else happened.

I tried to do what you said. Did the same steps, got the same error. New output logs attached below.

[feedreader-daemon-output.txt](https://github.com/jangernert/FeedReader/files/567872/feedreader-daemon-output.txt)
[feedreader-output.txt](https://github.com/jangernert/FeedReader/files/567873/feedreader-output.txt)

**Comment by jangernert** [comment]
Hm, looks like you still have a "access-token"-key in org->gnome->feedreader->inoreader, so FeedReader doesn't try to get a new token but instead uses the refresh-token to refresh the current token. But that does not seem to work.
Can you try the latest commit in master?
If that does not work I suggest using the "change account" option the gmenu. This should reset all the account data including the "access-token".

**Comment by dsboger** [comment]
That seems to have solved the problem. Thanks!

**Comment by jangernert** [comment]
What solved your problem? The latest commit or resetting your account?

**Comment by dsboger** [comment]
I did both. But I had reset the account before and that didn't work. I guess the commit did it, then.
