### ISSUE TITLE
Links of articles don't work

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#258]
[master]
I can click on text-inside links, but nothing happens – whereas clicking on the header works. Isn't influenced by the dconf setting "article-select-text".

**Comment by fb87** [comment]
Ok, resolved now. No clue if it happended due to FR or due to some other package update…

**Comment by jangernert** [comment]
I'm pretty sure the html-code of the article is responsible for this. What does the html-code of the articles that do not work look like?

**Comment by fb87** [comment]
I tried it on several feeds. It seems to me that https links work without a problem and http links don't. But I can't imagine why.

**Comment by jangernert** [comment]
So the overlay shows an actual link, but it won't open in the browser?...

**Comment by fb87** [comment]
Yup, I can see the link target at the bottom in a bubble.

**Comment by jangernert** [comment]
This is the code that handles the external URL's

```
case WebKit.LoadEvent.STARTED:
	Logger.debug("ArticleView: load STARTED");
	string url = m_currentView.get_uri();
	if(url != "file://" + GLib.Environment.get_home_dir() + "/.local/share/feedreader/data/images/")
	{
		Logger.debug("ArticleView: open external url: %s".printf(url));
		try
		{
			Gtk.show_uri(Gdk.Screen.get_default(), url, Gdk.CURRENT_TIME);
		}
		catch(GLib.Error e)
		{
			Logger.debug("could not open the link in an external browser: %s".printf(e.message));
		}
		m_currentView.stop_loading();
	}
	break;
```
So if the URL does not begin with 'file://' you should see the URL in the logs and if something goes wrong with Gtk.show_uri you'll get an error.

**Comment by fb87** [comment]
Ok, now Phoronix links work (maybe due to git pull), but images still don't (the article image is opened in a little popup when clicked, but in-text images show their URL, but don't load in my browser) [http://feedproxy.google.com/~r/Phoronix/~3/I3KM55gbVpY/vr.php].

On my OMGubuntu feed absolutely no link works and no output is produced in ui.log [http://feedproxy.google.com/~r/d0od/~3/ycyzTjwR_94/cinnamon-3-2-available-stable-ppa-ubuntu].

**Comment by jangernert** [comment]
No, nothing changed in the code regarding the articleView.
The popup is for images that are scaled down more than 20% in the articleView so one can look at them in full size.

**Comment by fb87** [comment]
I recognized this issue mostly in articles of Golem and UMG-Ubuntu, like this one:
http://feedproxy.google.com/~r/d0od/~3/Sn1KIs7QJL4/fedora-25-makes-ridiculously-easy-type-emoji
Here the „there's a nerdy terminal app“-link doesn't work. But I don't know why… Do you need more examples?
