### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by HoratiuMl** [jangernert/FeedReader#259]
Hello.

I recently started using this great piece of software (yesterday) on my Arch Linux machine at home, as well as on my Ubuntu laptop.
However, at work I'm stuck on Windows (W7) and I would like to use this app there as well. At the moment I have to use the Feedly chrome app from the Chrome Web Store but this is not a long term solution because AFAIK Google will stop chrome app support on all OSes (except ChromeOS of course).

If you can't release a Windows binary, could you please give us a little bit of information as to why is that? AFAIK there are a were some issues with GTK3 on Windows for quite a while. Is that still the case, or is it something else now?

**Comment by jangernert** [comment]
1. I don't use windows myself (don't even have a license)
2. Developing on windows is a pain in the ...
3. I don't want to encourage people to keep using windows
4. afaik Webkit2gtk is still not available on windows

But if someone else forks FeedReader and somehow makes it work: It's free software after all.

**Comment by HoratiuMl** [comment]
Thanks for the answer.

**Comment by ZanderBrown** [comment]
No promises but I *might* actually look into this

**Comment by DOFfactory** [comment]
Any news on this?

**Comment by ZanderBrown** [comment]
I didn't have much luck and I don't believe anyone else was working on it

**Comment by HoratiuMl** [comment]
Oh, ok.

**Comment by DOFfactory** [comment]
That's a pity. I am struggling to find a **good** client for my local tt-rss. If FeedReader could be made available for Windows, I believe it would win this part of the market. Is it possible to re-open this issue maybe?

**Comment by brendanlong** [comment]
@jangernert If Web2GTK got Windows support and someone wrote a (reasonable) patch for Windows support, would you be willing to accept that patch?

I also don't have a Windows license but I want to be clear to potential contributors on whether we would or wouldn't accept that patch if they wrote it.

**Comment by ZanderBrown** [comment]
> But if someone else forks FeedReader and somehow makes it work: It's free software after all.

Sort of implies it but it would be nice to have this explicitly stated

**Comment by DOFfactory** [comment]
Honestly, I tried to look up yesterday what this Web2GTK is, and Google knows almost nothing about it. Any references?

**Comment by jangernert** [comment]
@DOFfactory https://webkitgtk.org/ It's the current port of webkit2 to gtk. The package is simply called webkitgtk.

@brendanlong If the changes are not too intrusive and someone with a windows installation would look after them from time to time, sure why not.

**Comment by DOFfactory** [comment]
Ah, I see. Would this be of any help?: [http://www.codepasta.com/site/cpp/webkitgtk-build/](http://www.codepasta.com/site/cpp/webkitgtk-build/)

**Comment by jangernert** [comment]
@DOFfactory 
Don't think so. This is from 2014 with very old version of webkitgtk 1
