### ISSUE TITLE
glib-gio-error

### ISSUE THREAD

**Issue by markybob** [jangernert/FeedReader#261]
just built master and i'm getting this error (debian xfce)

markybob@bethany:/usr/local$ feedreader
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0-dev

(feedreader:8941): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ INFO  ] FeedReader: start daemon
[ ERROR ] FeedListFooter.constructor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'supportFeedManipulation'
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 2.0-dev
[ DEBUG ] daemon: constructor

(feedreader-daemon:8970): GLib-GIO-ERROR **: Settings schema 'org.gnome.feedreader' does not contain a key named 'plugin'
[ DEBUG ] MainWindow: determining state
[ ERROR ] dbErrorLog: 283: recovered 22 frames from WAL file /home/markybob/.local/share/feedreader/data/feedreader-04.db-wal
[ DEBUG ] database already initialized
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 6
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline

(feedreader:8941): GLib-GIO-ERROR **: Settings schema 'org.gnome.feedreader' does not contain a key named 'plugin'
Trace/breakpoint trap
markybob@bethany:/usr/local$ 

any thoughts? thanks

**Comment by jangernert** [comment]
Seems like your gsetting schemas were not compiled. You can use dconf-editor to check if they're there. Maybe you need to move the schema into another folder on your system and recompile the schemas.
