### ISSUE TITLE
Spinner in article list misscaled

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#262]
[master]
Here's how it normally looks with my theme:
![peek sync normal](https://cloud.githubusercontent.com/assets/10520767/20112779/046ed5ae-a5ee-11e6-82c7-b630ae95b62b.gif)

And here is how it looks in the artlicle list:
![peek sync](https://cloud.githubusercontent.com/assets/10520767/20112812/16fcb574-a5ee-11e6-8eef-d15559f6d02c.gif)

The vertical smaller the window is, the smaller the bar gets. So the vertical scaling should match the horizontal scaling instead of being streched.

// Btw.: There already is the global spinner in the header bar, so I think the spinner in the article list could be removed eventually.

**Comment by jangernert** [comment]
That's not really an issue. Just because some themes keep them strictly rectangular, does not mean other themes can't fill the whole allocation of the widget.

**Comment by fb87** [comment]
Ok thanks
