### ISSUE TITLE
Website/documentation: add missing dependencies

### ISSUE THREAD

**Issue by lightonflux** [jangernert/FeedReader#267]
I tried to compile on Ubuntu 16.04 server. These were lacking:

* libcurl-dev (e.g. libcurl4-gnutls-dev)
* libpeas-1.0 (same name but path problems)
* gstreamer-1.0 (no idea which ubuntu or debian package)
* gstreamer-pbutils-1.0 (same here)

Would be nice to have a complete dependency list. I would like to build feedreader using LXC container (Ubuntu 16.04 or Debian 8).

**Comment by lightonflux** [comment]
Found them for Ubuntu 16.04: 

 * libpeas-dev
 * libgstreamer-plugins-base1.0-dev
 * libcurl4-gnutls-dev

**Comment by boggad** [comment]
Did you have any success building from master branch?

**Comment by lightonflux** [comment]
Not yet. Will try again later and document it, so we can have easier instructions on the site. I might even get the snap running. But no promise on that. :)

Am 20. November 2016 13:07:04 MEZ, schrieb Timofey Klyubin <notifications@github.com>:
>Did you have any success building from master branch?

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by boggad** [comment]
I'm still trying to figure it out, but here's what I've found out so far:
building fails because it can't find few classes: `Gtk.ShortcutsGroup`,`Gtk.ShortcutsShortcut` and `Gtk.ShortcutsWindow`.
I've found them in `gtkmm` package that was missing on my system. Also it seems like `gtk-3.0.vapi` doesn't include them even after installing `gtkmm`. So currently I'm stuck...

**Comment by jangernert** [comment]
@boggad ShortcutsWindow was added with Gtk+ 3.20
Sounds like your distro ships an out of date version of Gtk+.

**Comment by boggad** [comment]
@jangernert Looks like I have 3.20.8 on my system:
```
$ dpkg -l | grep 'gtk-3'
ii  gir1.2-gtk-3.0:amd64                            3.20.8-1ubuntu0~ppa1                       amd64        GTK+ graphical user interface library -- gir bindings
ii  libgtk-3-0:amd64                                3.20.8-1ubuntu0~ppa1                       amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                                    3.20.8-1ubuntu0~ppa1                       amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                                 3.20.8-1ubuntu0~ppa1                       all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64                              3.20.8-1ubuntu0~ppa1                       amd64        development files for the GTK+ library
ii  libjavascriptcoregtk-3.0-0:amd64                2.4.11-0ubuntu0.1+xenial1                  amd64        JavaScript engine library from WebKitGTK+
ii  libwebkit2gtk-3.0-25:amd64                      2.4.11-0ubuntu0.1+xenial1                  amd64        WebKit2 API layer for WebKitGTK+
ii  libwebkitgtk-3.0-common                         2.4.11-0ubuntu0.1                          all          Web content engine library for GTK+ - data files
```

**Comment by boggad** [comment]
@jangernert Maybe I gotta somehow generate new Vala bindings to have it working? Would be great if you assist me in this :)

**Comment by jangernert** [comment]
I have no idea how the gtk+-3 package of this ppa was built. All I know is: compiling FeedReader master branch works on Ubuntu 16.10.
What exactly is the error you're getting?

**Comment by boggad** [comment]
Here's full console log: http://pastebin.com/aFhdqhkf

versions of tools:
```
$ cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jangernert** [comment]
If gtk 3.20 was correctly built and installed your vapi-file should include these types.

**Comment by boggad** [comment]
Can you send me correct vapi file? I'l try to change the file with your one.

**Comment by jangernert** [comment]
http://pastebin.com/XbnzHvei

**Comment by boggad** [comment]
@jangernert Thanks, those errors gone, but there's new: http://pastebin.com/reFv0tjn
I think I'm gonna try rebuild gtk tomorrow

**Comment by jangernert** [comment]
Now you're getting gdk-errors.
Why not simply upgrade your system? :P

**Comment by boggad** [comment]
I use this computer at work too, so I'm afraid to mess something up... default Kubuntu upgrade app offers me to upgrade a lot of stuff like mysql while in fact I need exact versions of it and don't want to upgrade it. 
So I think rebuilding gtk is my best shot :)

**Comment by jangernert** [comment]
I think you'll have to rebuild gdk as well. Anyways, here is the gdk-vapi first. You can give it a shot.
http://pastebin.com/tt4xbCu2

**Comment by boggad** [comment]
Thank you, that helped! I got it working. But it doesn't connect to The Old Reader.
```
 INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 2.0-dev
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin none
[ DEBUG ] feedserver: load plugin "oldreader"
[ DEBUG ] feedserver: engine load TheOldReader
[ DEBUG ] feedserver: plugin loaded TheOldReader
[ DEBUG ] OldReader Connection: getToken()
[ DEBUG ] Error=BadAuthentication

[ ERROR ] getUserID: getting user info
[ ERROR ] getUserID: Could not load message response
[ ERROR ] <data>:1:1: Parse error: unexpected character `<', expected value
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin oldreader
[ DEBUG ] feedserver: plugin removed TheOldReader
[ DEBUG ] feedserver: engine unload TheOldReader
[ DEBUG ] feedserver: load plugin "oldreader"
[ DEBUG ] feedserver: engine load TheOldReader
[ DEBUG ] feedserver: plugin loaded TheOldReader
[ DEBUG ] OldReader Connection: getToken()
[ DEBUG ] Error=BadAuthentication
```
is it know issue? If yes, I guess it's candidate for a new issue.

**Comment by lightonflux** [comment]
Needed goa and tried it on 16.10. Compiles. But snap does not work. Will add the goa package name later and continue on snap in a different issue.

Am 20. November 2016 19:45:23 MEZ, schrieb Timofey Klyubin <notifications@github.com>:
>Thank you, that helped! I got it working. But it doesn't connect to The
>Old Reader.
>```
> INFO  ] Everything is logged. Used to debug!
>[ INFO  ] daemon: Notification actions supported
>[ INFO  ] FeedReader Daemon 2.0-dev
>[ DEBUG ] daemon: constructor
>[ DEBUG ] daemon: new FeedServer and login
>[WARNING] feedserver.unloadPlugin: no plugin loaded
>[ DEBUG ] feedserver: load plugin "none"
>[ ERROR ] feedserver: couldn't load plugin none
>[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
>[ DEBUG ] daemon: bus aquired
>[ DEBUG ] daemon: new FeedServer and login
>[ DEBUG ] feedserver: unload plugin none
>[ DEBUG ] feedserver: load plugin "oldreader"
>[ DEBUG ] feedserver: engine load TheOldReader
>[ DEBUG ] feedserver: plugin loaded TheOldReader
>[ DEBUG ] OldReader Connection: getToken()
>[ DEBUG ] Error=BadAuthentication
>
>[ ERROR ] getUserID: getting user info
>[ ERROR ] getUserID: Could not load message response
>[ ERROR ] <data>:1:1: Parse error: unexpected character `<', expected
>value
>[ DEBUG ] daemon: login status =
>FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
>[ DEBUG ] daemon: new FeedServer and login
>[ DEBUG ] feedserver: unload plugin oldreader
>[ DEBUG ] feedserver: plugin removed TheOldReader
>[ DEBUG ] feedserver: engine unload TheOldReader
>[ DEBUG ] feedserver: load plugin "oldreader"
>[ DEBUG ] feedserver: engine load TheOldReader
>[ DEBUG ] feedserver: plugin loaded TheOldReader
>[ DEBUG ] OldReader Connection: getToken()
>[ DEBUG ] Error=BadAuthentication
>```
>is it know issue? If yes, I guess it's candidate for a new issue.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by lightonflux** [comment]
Here the entire requirement list for 16.10. Didn't test 16.04 because of potential GTK issues.

**Comment by lightonflux** [comment]
`build-essential cmake valac pkg-config libgirepository1.0-dev libgtk-3-dev libsoup2.4-dev libjson-glib-dev libwebkit2gtk-4.0-dev libsqlite3-dev libsecret-1-dev libnotify-dev libxml2-dev  librest-dev libgee-0.8-dev libcurl4-gnutls-dev libgstreamer-plugins-base1.0-dev libpeas-dev  libgoa-1.0-dev`

**Comment by lightonflux** [comment]
That's without unity support. You need to install the unity-something-dev package if you want to have that. 

(`cmake -DUSE_WEBKIT_4=ON -DWITH_LIBUNITY=OFF`)

**Comment by jangernert** [comment]
@boggad oldReader works for me. What kind of account do you use?

**Comment by boggad** [comment]
@jangernert Not sure, just normal free account. Or you mean something else?

**Comment by jangernert** [comment]
What I meant was, did you register a new account or did you log in with facebook/Google?

**Comment by boggad** [comment]
I did register a new account

**Comment by jangernert** [comment]
Weird, so did I. Are you sure you entered your email and password correctly and they do not contain weird characters that could mess with strings (no idea what characters are allowed for oldreader accounts)

**Comment by jangernert** [comment]
I added some additional debug information to the function that fails on your end. You can check out master and try again ;)
At least this time you'll get some more information in the logs.

**Comment by boggad** [comment]
Thanks! I'm trying real soon

**Comment by boggad** [comment]
Alright, now the error makes sense. Here's some logs first:
```
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin oldreader
[ DEBUG ] feedserver: plugin removed TheOldReader
[ DEBUG ] feedserver: engine unload TheOldReader
[ DEBUG ] feedserver: load plugin "oldreader"
[ DEBUG ] feedserver: engine load TheOldReader
[ DEBUG ] feedserver: plugin loaded TheOldReader
[ ERROR ] The name org.freedesktop.secrets was not provided by any .service files
[ DEBUG ] OldReader Connection: getToken()
[ DEBUG ] Email=boggad@gmail.com&Passwd=&service=reader&accountType=HOSTED_OR_GOOGLE&client=FeedReader
[ ERROR ] Error=BadAuthentication

[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_WRONG_LOGIN
```

Somehow `Passwd` is empty.

**Comment by jangernert** [comment]
Did you reset the old account before trying to log into a new one first (change account from gmenu)?
You can use the application "seahorse" to see all the libsecret passwords that are stored on your system.
There should be one called "FeedReader: oldreader login".
If not please try to log in from FeedReader again and this time post the log of the UI this time :)
The password obviously gets grabbed in the UI and then written to the gnome-keyring.

**Comment by boggad** [comment]
Yep, restarting and logging in helped! Thank you!

**Comment by lightonflux** [comment]
You also need "gettext" which is usually installed but not always. (especially when building within a container).

**Comment by boggad** [comment]
Already got it:
```
$ LANG=C gettext --version
gettext (GNU gettext-runtime) 0.19.7
Copyright (C) 1995-1997, 2000-2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

**Comment by lightonflux** [comment]
Sorry that wasn't in reply to [your comment](https://github.com/jangernert/FeedReader/issues/267#issuecomment-262352913) but in reply to the initial post about documentation on the website.
