### ISSUE TITLE
[master] Spacing issue in artcle list

### ISSUE THREAD

**Issue by dsboger** [jangernert/FeedReader#270]
I'm having this issue that articles with long titles spanning multiple lines are "clipped" on the top. The image below shows the problem. I've tested both Adwaita and Arc themes, but the result is the same. Interestingly, when I switch themes the spacing is momentarily fixed, only to come back when I choose a different category.

![article_list](https://cloud.githubusercontent.com/assets/2356842/20606627/5dcac988-b259-11e6-9816-a72945884087.png)

**Comment by jangernert** [comment]
This seems to be a gtk issue. The listboxrow is allocated first and later filled with the widgets. Normally the listboxrow should expand to fit all the widgets. But somehow his does not work in this case. I can only reproduce this if I increase the font size from my standard 10pt.
The minimal height of the rows is 100px. And larger fonts cause the content to exceed this limit (like I said gtk should make the row expand afaik)
I don't think I can do anything about this in the FeedReader codebase.
A workaround would be to set your fonts to 10pt =/
