### ISSUE TITLE
Restore column widths at resizing

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#273]
When assigning FR e.g. to the left half of the monitor, all columns get squeezed – OK. But when I make it full screen again, column widths aren't restored and retain the width ratios of the squeezed state. In my opinion, the widths of the feed and article panes should just be enlarged until reaching the former width instead.

Plus, changing the width of the article list, shouldn't affect the width of the feed list. :)

**Comment by jangernert** [comment]
1. What you call "full-screen" is actually called maximized. (full-screen mode doesn't even have feed- and article-pane)
2. How would an application know if has "normal" aspect ratio or if it is resized by the window manager similar to windows edge-snap? This is information only the window manager has access to. With wayland windows don't even know where they are positioned. All they know is the size of the surface they are allowed to paint to.
3. What if FeedReader is not run inside Mutter but Gala or Kwin? Different window-managers handle things differently ...

**Comment by fb87** [comment]
I thought maybe it's possible to store the manual adjusted width of the two lists, and when FR is resized so that the widths are adapted automatically, they get back to the manually set width, if the window is large enough again – if this would be possible?
