### ISSUE TITLE
Read articles are reappearing

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#275]
[master]
• I opened the news list of a feed and selected the articles, but after the news count getting from 15 to 14, every article is reappearing and thus the counter didn't go further down.
• Several articles are listed multiple times
[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/629909/feedreader.tar.gz)

• Sometimes (in this second record) I can „read“ all articles but the count doesn't go down at some point – whereas the article list is empty. Switching to another feed and back again lets the articles the counter showed) reappear.
• Here I killed the daemon after the program start, but before starting reading the articles for trying to not get making them reappear.
[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/629911/feedreader.tar.gz)

• At every feed, just the first article can be marked sucessfully as read. With marking an article explicitly as read, the count goes down for more articles than one – but at some point stops again (not reproducable).
[ui.log.tar.gz](https://github.com/jangernert/FeedReader/files/629918/ui.log.tar.gz)

• Sometimes, selecting an article by mouse „reads“ it, while selections via arrow keys do not – sometimes this doesn't apply…?!

**Comment by Dan-Theriault** [comment]
I am experiencing a similar issue- selecting by mouse will always mark an article as read properly, but selection via the keyboard (either arrow keys or j/k)  will only superficially mark the article as read- removing it if I am in unread-only view, removing the blue dot, etc.

I'm using Debian Stretch and compiled from source.

**Comment by jangernert** [comment]
Thx, that's the kind of specific information that I need :)
Could reproduce the bug and was easy to fix.
