### ISSUE TITLE
Wrong error message on login

### ISSUE THREAD

**Issue by lightonflux** [jangernert/FeedReader#277]
I setup a new account and got a "wrong password" notification, which was wrong.

* URL input: example.tld/tt-rss
* User input: lightonflux
* Password input: therightpassword

I then added `https://` to the URL and it work (without reentering the password). So feedreader displayed the wrong error message.

Maybe it should check for https first, if not available http and then fallback on other assumptions?!

Current git version.

**Comment by jangernert** [comment]
If you don't type https://, http:// is assumed the lowest common denominator.
But the error-message is indeed confusing. Actually ttrss is reporting an API-error. So I fixed the message.
