### ISSUE TITLE
Disable notifications option

### ISSUE THREAD

**Issue by theSoenke** [jangernert/FeedReader#279]
FeedReader works really great but i would like to have an option to disable notifications. Notifications are distracting and i don't need to get immediately notified about new articles. I know it's possible to increase the synchronization time to get fewer notifications but i still would like to update the feeds in the background so i don't need to sync first when i open FeedReader

**Comment by jangernert** [comment]
That's the job of the DE, gnome and pantheon both support disabling notifications from specific applications. Maybe your DE does so, too.
