### ISSUE TITLE
Missing call to m_window.present() on FeedReader.activate()

### ISSUE THREAD

**Issue by dsboger** [jangernert/FeedReader#280]
Method activate() of FeedReader calls `m_window.show_all()`, but not `m_window.present()`. This causes the issue of not bringing the window upfront when launching the app if it is already running (in GNOME Shell, at least). The situation that led me to investigate was that clicking a notification does not bring the window up if FeedReader is already running. I can confirm that adding the `m_window.present()` fixes this.

**Comment by bil-elmoussaoui** [comment]
Can you open a PR to fix this? 
Thanks for bringing this up!

**Comment by jangernert** [comment]
Thx for finding and fixing this issue :)
