### ISSUE TITLE
Flatpak file

### ISSUE THREAD

**Issue by yotamN** [jangernert/FeedReader#283]
Is there a plan to create a flatpak file? That way you can support mroe distros (for example I'm on Debian usntable and can't install it without compiling from source)

**Comment by jangernert** [comment]
If someone wants to create and maintain one, sure. But I myself do not plan to work on it right now.

**Comment by bil-elmoussaoui** [comment]
Someone already started this here https://github.com/jscurtu/feedreader-flatpak; Don't know if he/she will keep updating it..

**Comment by jangernert** [comment]
Then lets hope he keeps working on it and proposes a merge once it works well enough :)

**Comment by jscurtu** [comment]
Then I guess I will do that.. :-) 
Here you can already download a flatpak'd feedreader from the 1.6.2 release:

https://github.com/jscurtu/feedreader-flatpak/releases

Will look at it again, could be I haven't updated it.. 
Version 2.0 work is in progress .... 

I use the flatpak'd feedreader daily and it works, so who ever feels like helping and testing, feel free to do so and report any flatpak related issues to me.. 
Keep in mind that you need xdg-portal installed on the host to get links to open in browser.. 

install in your distribution:

    xdg-desktop-portal
    xdg-desktop-portal-gtk

When clicking on a link, a little window will open:

![bildschirmfoto vom 2016-12-22 08-59-22](https://cloud.githubusercontent.com/assets/590307/21419000/53302356-c825-11e6-8522-e3385ba1cd0d.png)
