### ISSUE TITLE
problem compilation in archlinux yaourt aur

### ISSUE THREAD

**Issue by benoitldr** [jangernert/FeedReader#285]
Hi
I have an issue with installing feedreader via yaourt on archlinux...
<https://framabin.org/?122a00fe38f8e500#fabcxiWsTB0VL+quN3YlbX69hvQwymI+NvU5/pdxAB8=>
I didn't find the solution yet...

**Comment by jscurtu** [comment]
The AUR package is community maintained and distribution specific, I see you already notified the maintainer so please wait and for the maintainer to reply.
Alternatively, you may try out the new experimental platform-agnostic flatpak bundle and see if that works for you.
See here for instructions:
https://github.com/jangernert/FeedReader
