### ISSUE TITLE
Building with Ninja

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#288]
Since building lasts quite some seconds, I think it'll be good to accelerate compilation with ninja. This is normally done by
`cmake -GNinja`
and
`ninja-build`
or directly
`sudo ninja-build install`,
but your CMakeLists.txt is more complicated than my scripts, so I'm not that sure where to put it. Maybe some distinction needs to be made for users not having ninja installed.

**Comment by jangernert** [comment]
You are aware of the fact that by default 'make' is just using a single thread. To speed up compilation just pass the number of threads. For example with 4 'Jobs':
```
make -j4
```

**Comment by fb87** [comment]
Oh thanks. Can this be automated by e.g. `make -jN_CORES`?

**Comment by jangernert** [comment]
What do you mean with automated? IMO this is something the users have to decide themselves. E.g. I have a quad core CPU (8 threads) and usually compile with 6 or 7 jobs depending on what else is currently running on the PC. But nothing stops you from writing your own little bash-script to automate compilation on your machine ;)

**Comment by fb87** [comment]
Ok, thanks for advice. I just thought Ninja could provide a huge speed improvement, but I didn't know that `make` can work in parallel.

**Comment by jangernert** [comment]
Maybe it IS a little faster. I just think the current t build process is "fast enough". Maybe at some point I'll dive into meson and ninja to see what the hype is all about. But for now CMake and make is good enough =)

**Comment by fbruetting** [comment]
When I do `rm -rf * && cmake .. && make -j8`, execution is always stopped at 60% like shown below, but if I build with 1/4/6 thread(s), it works fine, while with 7 threads it sometimes works and sometimes doesn't (I own a 4-core CPU with hyperthreading). Do you know what the reason could be? Maybe some dependency not being correctly configured in CMakeLists.txt?

```
[ 58%] Building C object CMakeFiles/feedreader.dir/src/Widgets/ArticleList/ArticleListScroll.c.o
[ 58%] Building C object CMakeFiles/feedreader.dir/src/Share/share.c.o
[ 59%] Building C object CMakeFiles/feedreader.dir/src/Share/ServiceSetup.c.o
[ 59%] Building C object CMakeFiles/feedreader.dir/src/Share/ShareAccountInterface.c.o
[ 60%] Building C object CMakeFiles/feedreader.dir/data/feedreader.gresource.c.o
[ 60%] Linking C executable feedreader
[ 60%] Built target feedreader
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```
