### ISSUE TITLE
Add Feedbin support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#29]
https://github.com/feedbin/feedbin-api#readme

**Comment by jangernert** [comment]
Implemented with 0c00524fb1e85cff820b896339964e86f638261c
However the API is IMO extremely awkward. And without significant changes to the internals of FeedReader there is no way to support manipulation of feeds and categories (add/remove/rename).
So I just disabled the features for feedbin.
Also in about 10 days my trial for feedbin ends. After that I can't support the back-end without creating a new trial account every time.
So, use at own risk.
Would be great to find someone who uses feedbin regularly to maintain this.
