### ISSUE TITLE
add a symbolic icon for gnome shell

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#292]
Gnome Shell uses a symbolic icon which shown in the top bar. And when the symbolic icon is not found, a normal application is not used. Adding this icon won't harm any other distro :+1: 
I have to assume that I don't like those scalable icons anyway, but it's just to give a better experience for Gnome users.

The icon name must be named `feedreader-symbolic.svg` and must be placed in `hicolor/scalable`

**Comment by jangernert** [comment]
added
