### ISSUE TITLE
Hide the article until it's fully loaded

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#293]
I think that is better to "replace" the normal article view with just a spinner and the load progress and show the article once it's done. 
An alternative idea is to use the headerbar to show the the spinner of the loading article. 
This will make it more visible to the user, as i've been using FeedReader for two days and i just noticed this new feature, because it was all the time not correctly visible within the article image. 
Btw,I do prefer the first idea

**Comment by jangernert** [comment]
I don't really like the idea. The spinner should only be visible if things take longer than expected.
Currently it is only shown if the ArticleView takes longer than 0.3s to load (maybe tweak that value a little). And even then, if most of the article is already rendered it shouldn't be too distracting. Most of the time it's just some youtube-video that has to be loaded to let the progress jump to 100%.
The only case where the overlay is useful is when loading is taking forever for some reason.

**Comment by bil-elmoussaoui** [comment]
@jangernert Why not just using a different background for the text? so that the progress is really useful, otherwise, the same information can be just logged instead... Also, some text might be useful too! (loading article x%...)
Again, this is not for me, it just to make the UI looks more friendly and beautiful ;)
