### ISSUE TITLE
Make FeedReader available in the Debian repository

### ISSUE THREAD

**Issue by fredddii** [jangernert/FeedReader#294]
I myself have no packaging and submission experience, but it would be great to have this available in the Debian repositories. If anyone with experience would be up for the job.

**Comment by jangernert** [comment]
I as well am not in any relationship with the Debian project and never done any packaging other than the automatic ppa from launchpad.
So I'm not going to create and maintain a Debian package. But if someone comes along and creates one I would be more than happy to list it here and on the website.
In the meantime there is a new flatpak. And as far as I know Debian supports flatpaks.
