### ISSUE TITLE
can't install on ubuntu mate yakkety

### ISSUE THREAD

**Issue by pcause** [jangernert/FeedReader#296]
When I try to install on ubuntu mate yakkety feedreader won't install.  Says:

Depends: libwebkit2gtk-3.0-25 (>= 2.3.2) but it is not installable

when i go an apt-cache search fpr libwebkit2gkt, all results are for libwebkit2gtk-4.0-*

**Comment by jangernert** [comment]
The unstable ppa is super out of date. Launchpad.net fails to build master-branch because it messes up a path-variable.
I just updated the description of the ppa so this confusion can be avoided in the future.
Only way on Ubuntu right now is to build from source.
