### ISSUE TITLE
Save articles as pdf does not work

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#297]
I tried to save an article as pdf but it does not work at all, there's no error message or anything at all. it's just not saved :p 
Also, the default save location is in `~/.local/share/` which shouldn't be the case? and i think that the default file name should be the article title.pdf instead of article.pdf

**Comment by bil-elmoussaoui** [comment]
Alright, i got an error message saying that the printer was not found :p so either this was supposed to be a print dialog or a save dialog? by looking at the code in UtilsUI and ColumnView it's more of a printing code?

**Comment by jangernert** [comment]
It's print to PDF. The data-folder is shown since a commit from Jason. It was home before, but that required the flatpaks to have access to all of home.

**Comment by bil-elmoussaoui** [comment]
So the article should be saved as PDF? in this case, why a printer is required?

**Comment by jangernert** [comment]
There is no actual printer required. But I guess the "print to PDF" is a printer internally. Do you have cups and the printing stack installed? Can you print a PDF from gnome document viewer to PDF?

**Comment by bil-elmoussaoui** [comment]
@jangernert I have everything installed on my system; I have never managed to use gnome documents so i can't try that :( but i can save files as pdf using epiphany browser (the files are saved on documents folder) i guess it should be the case for FeedReader too?

**Comment by jangernert** [comment]
For the documents-folder FeedReader would need to have access to all of HOME, so unless there is a way to only expose Documents with Flatpak I guess that's not an option.
I changed the file-name to the article-name by default.
What is the exact error message you get?

**Comment by bil-elmoussaoui** [comment]
@jangernert It must be that! i'm using a french as my main language on Gnome. Is there a way to detect the print to file name automatically ?

**Comment by bil-elmoussaoui** [comment]
For the whole access to the home folder, i think this might be fixed on later versions of Flatpak (i hope) until then, we keep it that way ;)

**Comment by jangernert** [comment]
Googling right now. But didn't find anything, yet.

**Comment by jangernert** [comment]
There is 'gtk_enumerate_printers' and the 'GtkPrinter'-class. But there are no bindings for vala as it seems.

**Comment by bil-elmoussaoui** [comment]
Is there any vala code that can create a PDF file from an html one ? Otherwise you can use wkhtmltopdf http://wkhtmltopdf.org/  the library is wrote using C and it can be used  to  convert html file to extensions other than pdf

**Comment by jangernert** [comment]
I changed the save-icon to an print-icon and hooked up the native printing dialog. That way you still have the option to print-to-file but also the option to print it right there.

**Comment by jangernert** [comment]
@bil-elmoussaoui integrating the library into the CMake build system, writing a custom vapi-file and then converting the HTML with it seems a bit overkill for such a minor feature.
I did it with vilistextum to generate previews. But that was a integral part of FeedReader.

**Comment by bil-elmoussaoui** [comment]
@jangernert Perfect for me, i really don't use the feature. It was more as a bug report ;) hope the other classes will have vala bundles in the near future ;)

**Comment by bil-elmoussaoui** [comment]
+ Out of topic, can you run ./update-pot.sh whenever you want to push a new commit ? this way transifex will be always up to date ;)

**Comment by jangernert** [comment]
I'll try to remember :D

**Comment by jscurtu** [comment]
I will look in to that with the default folder..
