### ISSUE TITLE
Shortcut Cheatsheet

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#30]
Use the Gtk+ help overlay to display all short-cuts of FeedReader
https://blogs.gnome.org/chergert/2015/08/31/keyboard-shortcuts/

**Comment by moriwaka** [comment]
+1. I hope '?' key to show this pop-up.

**Comment by jangernert** [comment]
I will try to list them from the top of my head (could be that I'll miss some):
- arrow keys to navigate the feed-list (left/right to collapse/expand categories)
- page up/down to scroll the article list all the way up or down
- j/k to go to next/prev article
- r to toggle the selected article un/read
- m to toggle the selected article un/marked (= starred)
- o to open the url of the selected article in the default browser
- A (Shift + a) to mark the currently selected in the feed-list as read (so when you have "All Articles" selected, all articles will be marked as read, when you have a single feed selected all articles of the feed will be marked as read and so on)
- F5 to sync
- s to center the currently selected article in the article-list (this is useful when you scrolled a lot and want to find your selected article again)
- ctrl + q to quit
- ctrl + f to search

**Comment by mcg** [comment]
Can you clarify (shift+a)?  Looking for a "mark all read" for a feed/category and can't find it.

**Comment by jangernert** [comment]
shift+a always marks the thing that is selected in the right pane as read. So if you have "All Articles" selected it will mark all unread articles in your database as read. If you have a specific category selected it will mark all articles of all the feeds that belong to that category as read. Same with feeds, if you have a feed selected shift+a will mark all the articles of that feed as read.
If there are still questions: just try&error. The worst you can do is mark all your articles as read :D

**Comment by mcg** [comment]
shift+a seems to work inconsistently. I had it work once, cannot get it to work again.

**Comment by jangernert** [comment]
I need more detailed information. What exactly are you doing? Does your selected feed/category have unread articles? What back-end are you using?

**Comment by mcg** [comment]
I have unread articles, with show unread selected. I've tried with the focus on the category/feed and with focus on an article. Backend is TTRSS. Still trying to reliably have it work/fail.

**Comment by jangernert** [comment]
With "show unread" you mean the settings "ONLY show unread"? That is a big difference :P

**Comment by mcg** [comment]
Settings->Feed List->Show Unread->On and "Unread" in the window title bar set. Tried now with both settings flipped and still seems inconsistent. Possibly user err :-)  

Love the app btw, good stuff!

**Comment by jangernert** [comment]
@mcg edited the comment above. I tried with all the things you mentioned (I'm on tt-rss as well) and it works every time for me. There is a slight delay when categories have lots of feeds and when marking ALL articles as read since not all backends support that kind of action. So I have to iterate through all the feeds and mark them as read one after another.

**Comment by mcg** [comment]
I think I've figured out my issue and user error. Thanks for the help.

**Comment by bil-elmoussaoui** [comment]
I've pushed the fix to a new branch, until the confirmation of @jangernert and then we merge it :+1: 

![capture du 2016-06-03 21-01-27](https://cloud.githubusercontent.com/assets/7660997/15789946/14d0f152-29cf-11e6-8f28-af7b6e7a3320.png)

**Comment by jangernert** [comment]
I committed the code to master but changed the run-time check to a build-time check to also make it build on systems without gtk+ 3.20.
