### ISSUE TITLE
Overflowing headline with newest css-patches

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#300]
@bil-elmoussaoui I guess your fix had some side-effects =/

![screenshot from 2017-01-03 14-25-32](https://cloud.githubusercontent.com/assets/12012494/21609081/a818fdda-d1c0-11e6-84c5-ba58c4b28b3e.png)

**Comment by bil-elmoussaoui** [comment]
@jangernert i will take a look right now

**Comment by jangernert** [comment]
Just look for articles with long headlines
