### ISSUE TITLE
Switching from favorite to non read does not work

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#301]
In the latest git version, switching from non read to favorite shows only the categories and feeds that have a favorite article which works just fine! but switching back to non-read does not work as expected, it does not show the rest of categories but the only the categories/feeds that have favorites articles but with the non-read counter 
Step 1
![capture d ecran de 2017-01-03 15-08-33](https://cloud.githubusercontent.com/assets/7660997/21610113/8d094436-d1c6-11e6-93c9-ff0e9cb49aca.png)
Step 2
![capture d ecran de 2017-01-03 15-08-36](https://cloud.githubusercontent.com/assets/7660997/21610114/91475b14-d1c6-11e6-8270-b7fff341fef9.png)
Step 3
![capture d ecran de 2017-01-03 15-08-39](https://cloud.githubusercontent.com/assets/7660997/21610119/95910968-d1c6-11e6-8cd7-e6a0fd6bb829.png)

**Comment by jangernert** [comment]
Confirmed, but only if "only show feeds" is active in the settings.

**Comment by bil-elmoussaoui** [comment]
Yes, I can confirm it works fine if the "only show feeds" is disabled. There are too many options to test them all :p

**Comment by bil-elmoussaoui** [comment]
I've just noticed the the "all articles" count is showing the same number as on "only unread", it should show all articles count on the database no?

**Comment by jangernert** [comment]
No, the number behind the "all articles" row is supposed to be the total unread count of all articles. And if you are in starred-mode it's the total starred count of all articles.

**Comment by bil-elmoussaoui** [comment]
Well, in this case there's no difference between "all articles" and "unread" except that "unread" will show only unread articles. In this case, i think "all articles %counter" should be replaced with a proper string as it's a little bit confusing :p
