### ISSUE TITLE
Tooltip to show the article title

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#302]
When you hover the article list, sometimes the article title is so long or just when the article list is resized to be so small... 
I think it's a good idea to show a tooltip with the article title  when you hover the article on the article list

**Comment by jangernert** [comment]
I just added a tooltip and tried it. But at least to me the tooltips are super annoying =/

**Comment by bil-elmoussaoui** [comment]
Will keep this open and will see if people that use FeedReader would love to have it or not ;)
