### ISSUE TITLE
Links cause new line

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#303]
Another issue since the css-fix. Links cause line-breaks
![screenshot from 2017-01-03 22-11-05](https://cloud.githubusercontent.com/assets/12012494/21623217/b3165bc4-d201-11e6-9a8b-cf04023686a9.png)

**Comment by jangernert** [comment]
It's caused by `display:block;`. Is this really needed to fix #240 ?

**Comment by bil-elmoussaoui** [comment]
@jangernert not really, it can be removed ;) the most important is the overflow
