### ISSUE TITLE
Size of YouTube videos too small

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#304]
I recognized several times that YouTube videos are displayed very small in FR. On [1] you see the picture and the video having the same width, but in FR the video is about half the size. I don't know if that also could be an issue due to my UHD screen.

[1] https://www.heise.de/newsticker/meldung/AMD-verspricht-Ausblick-auf-Vega-Grafikchips-3585671.html?wt_mc=rss.ho.beitrag.rdf

![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21628436/cbbd408e-d21f-11e6-98b7-e88c4100f057.png)

**Comment by jangernert** [comment]
That is because the HTML defines the size of the iframe:
```
<iframe class="yt_video" width="400" height="246" src="http://www.youtube.com/embed/9R8F-aN6W4g?wmode=transparent" frameborder="0" allowfullscreen=""></iframe>
```

**Comment by jangernert** [comment]
3da9fd65182653da0db149376c9ac543e1e82e12
only works for new articles (html gets fixed while grabbing the content)
