### ISSUE TITLE
Ubuntu 16.10 repository broken

### ISSUE THREAD

**Issue by pladijs** [jangernert/FeedReader#305]
On ubuntu 16.10 I get the following error when adding the repository. It worked fine on 16.04.
W: The repository 'http://ppa.launchpad.net/eviltwin1/feedreader-stable/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/eviltwin1/feedreader-stable/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jangernert** [comment]
There are no builds available for 16.10.
You'll either have to wait for the snap-package #268 or build from source.

**Comment by Resonanz** [comment]
Ubuntu 16.10 Failed to fetch http://ppa.launchpad.net/eviltwin1/feedreader-stable/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
