### ISSUE TITLE
Unwanted scrolling in article list

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#307]
• When I open a larger article list, the list gets scrolled down pretty much (sadly, you hardly see this in my screencast at opening the article list "All articles", but you see my mouse arrow showing up the fader afterwards).
• One further issue appears as i scroll to the top: As I can't, because the list scrolls down automatically all the time. In my screencast I scroll up to the top one time, then you see the unwanted downscrolling.

![peek 2017-01-05 06-59](https://cloud.githubusercontent.com/assets/10520767/21670703/af4b79e6-d316-11e6-9af7-698e1391fe6d.gif)

**Comment by jangernert** [comment]
4708f91c384ef7cfa0549c8092c5a9f0ba61a734

**Comment by fbruetting** [comment]
Now this appears again – but just if oldest articles are shown first!
