### ISSUE TITLE
Changing the width of the article list affects the width of the feed list and vice versa

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#308]
Both should be alterable separately (like in Geary mail).

By the way: The search function could be done by providing a magnifier symbol instead, which opens the search box at the top of both lists, like e.g. in Geary mail, if you'd like this. This would also hide the search when not needed and de-clutter the top bar. :)

![peek 2017-01-05 07-22](https://cloud.githubusercontent.com/assets/10520767/21670914/3f774a1c-d318-11e6-9509-1222ec910fba.gif)

![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21671084/4d8c5ed4-d319-11e6-9ec2-e91f8a0bfc7d.png)

**Comment by jangernert** [comment]
This will have to wait for:
https://bugzilla.gnome.org/show_bug.cgi?id=747581
