### ISSUE TITLE
FeedReader website

### ISSUE THREAD

**Issue by skmlcd** [jangernert/FeedReader#31]
What happened to your website? http://jangernert.github.io/feedreader/

Did you delete the repo?

**Comment by bil-elmoussaoui** [comment]
Works again! Thanks

**Comment by skmlcd** [comment]
The result from Google is still http://jangernert.github.io/feedreader/ instead of http://jangernert.github.io/FeedReader/.

I'm only adding this in case someone else is also confused before google result updates. Thanks for resolving this issue.

**Comment by bil-elmoussaoui** [comment]
Thanks for reporting that! i will see what can i do about that
