### ISSUE TITLE
Spinner spins for about 10 seconds after clicking on a browser link

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#312]
Since months, the mouse arrow spinner long continues spinning, even after the browser loaded the full article.

**Comment by jangernert** [comment]
?!?
No idea what you are trying to say here ...

**Comment by fbruetting** [comment]
No other program behaves like this when opening a link, does this also happen wih your Arch(?) distribution? This happens in Fedora 24 and 25.

![peek 2017-01-06 02-39](https://cloud.githubusercontent.com/assets/10520767/21704387/61cd6ca8-d3b9-11e6-8b72-06267e2ad158.gif)

**Comment by bil-elmoussaoui** [comment]
@fbruetting FeedReader does not control the mouse spinner as far as i know...it's due to the web browser not fully loaded yet...

**Comment by jangernert** [comment]
I just call `Gtk.show_uri`
I have no influence on the cursor icon here...

**Comment by fbruetting** [comment]
Ok, then it seems to be Firefox-related…
