### ISSUE TITLE
Font Settings

### ISSUE THREAD

**Issue by mimf** [jangernert/FeedReader#313]
I find the default font too hard to read. It would be nice to either have a different default font or be able to easily change font settings.

**Comment by bil-elmoussaoui** [comment]
I would love to have this too! i will get it to work by the next week/weekend :+1:

**Comment by bil-elmoussaoui** [comment]
@jangernert Before I start working on this, would you rather prefer having a Gtk.FontButton for that or a list of fonts that user have to choose from. I prefer the first option, to avoid having to add few fonts as dependencies of FeedReader...

**Comment by jangernert** [comment]
I guess a fontbutton would be okay. The only concern I have is: it enables users to make bad decisions and makes it harder to find the objectively good fonts for reading long articles.

**Comment by bil-elmoussaoui** [comment]
Don't worry about that, i was going to add that on settings ;)
