### ISSUE TITLE
Mercury support 

### ISSUE THREAD

**Issue by gochev** [jangernert/FeedReader#314]
Since readability is no longer available it will be very good enhancement if Mercury is added in place of Readability.

**Comment by jangernert** [comment]
If you are talking about this right here: https://mercury.postlight.com/reader/
adding support to FeedReader does not really make sense. Readability-support was to send the articles to the readability account so it could be synced and later read on the smartphone or other devices.
This is just an API to parse articles and extract the content. FeedReader already does exactly that.
So I see no reason to add support for mercury.
