### ISSUE TITLE
Different sort order for categories „all/starred“ and „unread“

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#315]
While it makes pretty much sense, displaying unread news in chronological order, this isn't as true for searches in read/starred category. For example if you stepped over an article by accident and want to make it visible again, you have to either scroll through the whole bunch of all past articles or set the „newest first“ setting and set it back afterwards. Therefore it would be nice, if this setting could be split in „all/starred“ and „unread“. What do you think?

**Comment by jangernert** [comment]
In that case it would make sense to limit the "newest first" option to the unread-column and have all other columns show the newest articles first no matter what.
OR
Remove the setting all together and have the unread-column in reverse order and the other columns show the newest articles first by default.

**Comment by fbruetting** [comment]
You're right. Since some like to see the newest news first and other prefer to read in historical order, I vote on your first proposal. :)
