### ISSUE TITLE
Unread Articles are neither shown in „unread“ nor can be marked read

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#320]
[master]
I let three OMGUbuntu articles about KDE Connect remain unread. After restarting FR at a later time, only the count 1 is shown in „unread“. Switching to all and searching for „connect“ displays all three, with the two missing ones marked unread (correct here). Now I can click on all three of em and the article gets loaded in the article pane fine, but I cannot mark the articles read (and if: marking them unread again for trying to make them appear in the unread list). You see I can star and unstar them, but the blue icon doesn't work. Restarting FR and the daemon doesn't solve the problem.

[ui.zip](https://github.com/jangernert/FeedReader/files/700498/ui.zip)

![peek 2017-01-12 02-19](https://cloud.githubusercontent.com/assets/10520767/21873397/87942fda-d86e-11e6-8d1a-3830183bc9fc.gif)

**Comment by fbruetting** [comment]
No bug and intended?

**Comment by jangernert** [comment]
Looking at the picture I would say the articles are not really unread but somehow the blue dot is shown.
The headline is not bold. You can try to set them unread and read again using the "r" key.
Additionally please check the database $HOME/.local/feedreader/data/feedreader-04.db if said article is really unread (the "unread"-field should be 9, 8 means read).

**Comment by fbruetting** [comment]
Oh yes, didn't recognize the missing boldness. I encountered this bug three times, then I deleted my whole database and FR and installed FR again. This happened after compiling FR with more threads – and since issues arose there, maybe this was a consequence?
I update from master every few days – if you didn't change anything related, maybe it's really due to those make threads. I'll keep an eye on it.

**Comment by fbruetting** [comment]
Here it is again. Always compiled with just one core. All articles are marked unread, although you see I've read almost all.

All I've done is checking out and installing some older versions, because of the current WebKit bug – this happened at installing the most recent version again. But I must admit, I've deleted the whole git directory, so maybe it's because CMake didn't know anymore what was installed? Don't know if this could be.

[FR.zip](https://github.com/jangernert/FeedReader/files/721420/FR.zip)


![feedreader_001](https://cloud.githubusercontent.com/assets/10520767/22177181/5885541e-e019-11e6-8e17-320312297340.png)

**Comment by jangernert** [comment]
What do you mean because of "the current WebKit bug"?
I didn't change anything in the articleView code ... Was there a webkit update or something?

**Comment by fbruetting** [comment]
No article gets displayed, as you see in the screenshot. I checked out older versions, but this didn't solve the problem, so I assume this is WebKit-related. There's already the corresponding bug report #327 filed.

**Comment by jangernert** [comment]
But what is the WebKit version on your system? Was there an update recently?

**Comment by fbruetting** [comment]
2.4.11, not that sure, but I think there was an update yesterday.

**Comment by jangernert** [comment]
The 2.4 series is super old. I'm not even sure if it has the webkit2 API already. Or did you mean 2.14?

**Comment by fbruetting** [comment]
You're right, on the webpage, there's 2.15 available, but Fedora has the older one shipped… maybe some LTS thing? But as far as I see, [Arch ships the same](https://www.archlinux.org/packages/extra/x86_64/webkitgtk/). Aren't you running Arch?


``` 
$ dnf info webkitgtk
Letzte Prüfung auf abgelaufene Metadaten: vor 17:34:53 am Sat Jan 21 19:56:12 2017.
Installierte Pakete
Name        : webkitgtk
Arch        : x86_64
Epoch       : 0
Version     : 2.4.11
Release     : 3.fc25
Größe       : 44 M
Paketquelle : @System
Aus Paketqu : @commandline
Zusammenfas : GTK+ Web content engine library
URL         : http://www.webkitgtk.org/
Lizenz      : LGPLv2+ and BSD
Beschreibun : WebKitGTK+ is the port of the portable web rendering engine WebKit
            : to the GTK+ platform.

Verfügbare Pakete
Name        : webkitgtk
Arch        : i686
Epoch       : 0
Version     : 2.4.11
Release     : 3.fc25
Größe       : 13 M
Paketquelle : fedora
Zusammenfas : GTK+ Web content engine library
URL         : http://www.webkitgtk.org/
Lizenz      : LGPLv2+ and BSD
Beschreibun : WebKitGTK+ is the port of the portable web rendering engine WebKit
            : to the GTK+ platform.
```

**Comment by jangernert** [comment]
Support for webkitgtk3 API was removed after the FeedReader 1.6.2 release.
I'm on Fedora 25 as well, and received an update from webkitgtk4 2.14.2 to 2.14.3 but haven't noticed anything not working since then. Maybe I need to reboot first.

**Comment by fbruetting** [comment]
I have WebKitGtk4 also, but is this used already?

```
$ dnf info webkitgtk4
Letzte Prüfung auf abgelaufene Metadaten: vor 23:56:30 am Sat Jan 21 19:56:12 2017.
Installierte Pakete
Name        : webkitgtk4
Arch        : x86_64
Epoch       : 0
Version     : 2.14.3
Release     : 1.fc25
Größe       : 42 M
Paketquelle : @System
Aus Paketqu : updates
Zusammenfas : GTK+ Web content engine library
URL         : http://www.webkitgtk.org/
Lizenz      : LGPLv2
Beschreibun : WebKitGTK+ is the port of the portable web rendering engine WebKit
            : to the GTK+ platform.
            : 
            : This package contains WebKitGTK+ for GTK+ 3.
```

**Comment by jangernert** [comment]
Btw: did you already check out if the articles are actually marked as unread in the database? (use SQLite Manager for Firefox or "DB Browser for SQLite" in the repos)

**Comment by fbruetting** [comment]
I deleted and reloaded my DB, I'll check if it happens again.

**Comment by jangernert** [comment]
I think you're missing the point here. Deleting the DB doesn't help me much to figure this out.

**Comment by fbruetting** [comment]
Indeed, but it helps me making it usable again. I thought my logs are sufficient.

**Comment by jangernert** [comment]
The logs don't magically contain all the I formation of every part of the application.

**Comment by fbruetting** [comment]
I'm not stupid, but how often is this required? I'll keep it next time, which I expect to be soon, since I already encountered this issue three times.

**Comment by jangernert** [comment]
Appearantly this issue can be caused by an invalid article-status in the DB. SQLite doesn't support booleans, so integers have to be used. I think the unread flag somehow is something different than the two allowed numbers.
No idea why though.
I added some warnings if the state is invalid. Maybe this will help to investigate.

**Comment by fbruetting** [comment]
Can you implement bools through ints by `x == 0` and `x != 0`?

**Comment by jangernert** [comment]
Yes, but why would that help? Obviously something went wrong. A check for != would only hide the error. Or flip the read-status without being noticable.
With 2 exact numbers I at least know everything other than the 2 states is invalid.
Of course the numbers get mapped to enums internally. So 8 becomes ArticleStatus.READ and 9 ArticleStatus.UNREAD. That's why I'm not sure how something else can end up in the database.

**Comment by fbruetting** [comment]
Never happened again since…
