### ISSUE TITLE
'The name org.gnome.feedreader was not provided by any .service files' error

### ISSUE THREAD

**Issue by winks** [jangernert/FeedReader#322]
I installed via flatpak on Debian testing today (as compiling didn't work and I just wanted to test it).

When opening via `flatpak run org.gnome.feedreader` I am presented with the `Change Account?` dialog.
When clicking on `New account` I get this error in the console:
```
[ ERROR ] ServiceInfo.refresh: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files
```

When clicking `I changed my mind` I see the main window, but when adding a feed I get:
```
[ ERROR ] AddPopover.addFeed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files
```

Sadly I have zero clue about dbus and if I can fix this manually

**Comment by jscurtu** [comment]
which one did you install? The beta?

**Comment by winks** [comment]
Yep, this one: https://github.com/jscurtu/feedreader-flatpak/releases/download/v2.0-beta-1/feedreader-v2.0-beta-1.x86_64.flatpak

**Comment by jscurtu** [comment]
That error is wierd, the package works for me and others on debian..  I will look in to this just to be sure.. What flatpak version is on debian?

flatpak --version

**Comment by winks** [comment]
```
$ flatpak --version
Flatpak 0.8.0
$ flatpak list     
org.gnome.feedreader
````

**Comment by winks** [comment]
1.6.2 looks a bit different: ( https://github.com/jscurtu/feedreader-flatpak/releases/download/1.6.2/feedreader-stable-20161229.x86_64.flatpak )
I could input my tt-rss url:
```
[ DEBUG ] write login data
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by jscurtu** [comment]
Just to be sure, did you uninstall? if not kill the daemon then run it with org.gnome.feedreader//master or org.gnome.feedreader//stable .

**Comment by winks** [comment]
same result with //stable (I uninstalled master before I installed stable)

Maybe I should state I am not running any version of Gnome. I do have some bits and pieces installed, and I peeked at d-feet and dconf-editor.
My window manage is xmonad and after I failed running master ( it builds fine, but basically result in #261 when starting ) I tried flatpak.

**Comment by jangernert** [comment]
So there are most likely some run-time-deps missing that every full blown DE ships by default.
Regarding the gsettings errors you face when compiling master: do you have 'gsettings-desktop-schemas' with all its deps like 'dconf-gsettings-backend' and 'dconf-service' installed?
And I'm just going to assume you have 'dbus-x11' and 'dbus' installed?

**Comment by winks** [comment]
Of all those you named, yes I have them installed.
```
ii  dconf-editor                                 3.22.1-1                             amd64        simple configuration storage system - graphical editor
ii  dconf-gsettings-backend:amd64                0.26.0-2                             amd64        simple configuration storage system - GSettings back-end
ii  dconf-service                                0.26.0-2                             amd64        simple configuration storage system - D-Bus service
rc  dconf-tools                                  0.12.1-3                             amd64        simple configuration storage system - utilities
rc  libdconf0:amd64                              0.12.1-3                             amd64        simple configuration storage system - runtime library
ii  libdconf1:amd64                              0.26.0-2                             amd64        simple configuration storage system - runtime library
ii  dconf-gsettings-backend:amd64                0.26.0-2                             amd64        simple configuration storage system - GSettings back-end
ii  gsettings-desktop-schemas                    3.22.0-1                             all          GSettings desktop-wide schemas
ii  at-spi2-core                                 2.22.0-5                             amd64        Assistive Technology Service Provider Interface (dbus core)
ii  dbus                                         1.10.14-1                            amd64        simple interprocess messaging system (daemon and utilities)
ii  dbus-x11                                     1.10.14-1                            amd64        simple interprocess messaging system (X11 deps)
```

cmake output: (so maybe when running it jsut can't find the schemas in this path?
```
-- checking for a minimum Vala version of 0.30
--   found Vala, version 0.34.4
/home/florian/code/misc/FeedReader/po
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Backend TTRSS:	ON
-- Backend OWNCLOUD:	ON
-- Backend INOREADER:	ON
-- Backend FEEDLY:	ON
-- Backend OLDREADER:	ON
-- Backend LOCAL:	ON
-- Backend FRESH:	ON
-- Backend FEEDBIN:	ON
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Plugin EMAIL:	ON
-- Plugin INSTAPAPER:	ON
-- Plugin POCKET:	ON
-- Plugin TWITTER:	ON
-- Plugin WALLABAG:	ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/florian/code/misc/FeedReader/build
```

```
ll /usr/local/share/glib-2.0/schemas/
total 56K
-rw-r--r-- 1 florian  327 Jan 11 13:28 org.gnome.feedreader.feedbin.gschema.xml
-rw-r--r-- 1 florian 1.1K Jan 11 13:28 org.gnome.feedreader.feedly.gschema.xml
-rw-r--r-- 1 florian  903 Jan 11 13:28 org.gnome.feedreader.fresh.gschema.xml
-rw-r--r-- 1 florian 4.3K Jan 11 13:28 org.gnome.feedreader.gschema.xml
-rw-r--r-- 1 florian 1.2K Jan 11 13:28 org.gnome.feedreader.inoreader.gschema.xml
-rw-r--r-- 1 florian 1.1K Jan 11 13:28 org.gnome.feedreader.keybindings.gschema.xml
-rw-r--r-- 1 florian  689 Jan 11 13:28 org.gnome.feedreader.oldreader.gschema.xml
-rw-r--r-- 1 florian  727 Jan 11 13:28 org.gnome.feedreader.owncloud.gschema.xml
-rw-r--r-- 1 florian 5.9K Jan 11 13:28 org.gnome.feedreader.saved-state.gschema.xml
-rw-r--r-- 1 florian 2.4K Jan 11 13:28 org.gnome.feedreader.share.gschema.xml
-rw-r--r-- 1 florian  737 Jan 11 13:28 org.gnome.feedreader.ttrss.gschema.xml
-rw-r--r-- 1 florian 2.2K Jan 11 13:28 org.gnome.feedreader.tweaks.gschema.xml
```

make output: https://gist.github.com/winks/59239f2046cb01cd4abe660181276dd6

**Comment by winks** [comment]
So does that mean it's not supposed to work without a full gnome install? without running gnome?

Also happy to accept a "won't fix" - thanks for your time anyway.

**Comment by jangernert** [comment]
No, people are running it under Unity, Budgie, Pantheon, Mate and so on. It's just that this is not an issue with the code itself, but rather a missing dependency of the flatpak or maybe even some different folders on your system (dbus was complaining it couldn't find the service file).

If you want to give it one last try I would recommend building the source again. I just finished cleaning up the app-ID and different dbus-service-names.
After the installation there should be a file called org.gnome.FeedReader.service in $INSTALL_PREFIX/share/dbus-1/services/ (the install-prefix will be most likely /usr/local or just /usr).

```
[D-BUS Service]
Name=org.gnome.FeedReader.Daemon
Exec=/usr/local/bin/feedreader-daemon
```

As you can see all it provides is a name and a binary to run if another process calls a function dbus that is provided by said name. You should also be able to see this interface in d-feet

![screenshot from 2017-02-04 16-24-27](https://cloud.githubusercontent.com/assets/12012494/22619535/800c16e8-eaf6-11e6-9b26-1f25aee40aa5.jpg)

If the UI is still complaining about a missing dbus-interface, I'm out of ideas for now =/

**Comment by jscurtu** [comment]
I will release a new build in a few minutes ..

**Comment by jscurtu** [comment]
Try this one:
https://github.com/jscurtu/feedreader-flatpak/releases/tag/snapshot-20170204

**Comment by winks** [comment]
Sorry for the late reply, the latest flatpak seems to work now.

Only error left is about compressed favicons.

Thanks!

**Comment by jscurtu** [comment]
@winks thanks..

**Comment by MichaelTunnell** [comment]
I just installed FeedReader via Flatpak today on KDE Neon (based on Ubuntu 16.04) and I received the same error about missing a daemon.

`[ ERROR ] ResetPage.resetAllData: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files`

FeedReader is the first flatpak I have installed with this system and therefore had to install Flatpak first.

I installed Flatpak via the PPA they recommended on the Flatpak website. I then ran the flatpak install command list on this project.

I checked to make sure I have all of the dependencies listed in this thread, and I do. 
`dbus/xenial-updates,now 1.10.6-1ubuntu3.3 amd64 [installed]
dbus-x11/xenial-updates,now 1.10.6-1ubuntu3.3 amd64 [installed,automatic]
dconf-gsettings-backend/xenial,now 0.24.0-2 amd64 [installed,automatic]
dconf-service/xenial,now 0.24.0-2 amd64 [installed,automatic]
gsettings-desktop-schemas/xenial,xenial,now 3.18.1-1ubuntu1 all [installed,automatic]`

I have Flatpak 0.8.3 and whatever default comes with:
`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref`

**Comment by jscurtu** [comment]
did you restart? Some people mentioned after a fresh flatpak install, rebooting helped.

**Comment by MichaelTunnell** [comment]
> did you restart? Some people mentioned after a fresh flatpak install, rebooting helped.

I had not restarted after install Flatpak. I have restarted and the app seems to find the service fine. I suppose Flatpak only loads the service in systemd on boot. That's interesting.
