### ISSUE TITLE
Spaces in titles and broken off feed names

### ISSUE THREAD

**Issue by arjan-s** [jangernert/FeedReader#325]
FeedReader-git: commit 6868080c
NextCloud: 11.0.1
NextCloud News: 10.1.0

The item titles have spaces or tabs in them, like in the screenshot below.
Feed names above the titles are broken off, "Tweakers Mixe" should be "Tweakers Mixed RSS Feed" and "A" should be "Android Authority" in the screenshot.
FeedReader 1.6.2 didn't have this problem.

![image](https://cloud.githubusercontent.com/assets/10400299/22066727/99ef8092-dd8e-11e6-9a2f-3c39df73169f.png)

Let me know if I can help test something or if you need more information.

**Comment by jangernert** [comment]
This was not the case with your little malloc 10x the needed size workaround?
If so could you give latest master another try?

Would be very helpful to know this issue was non-existent before this commit 1d3f1d3e5a7ca91af54a7eb70577e38b7917ef99

**Comment by arjan-s** [comment]
This issue seems to have resolved itself yesterday, I couldn't reproduce it anymore in the evening.
However, it has been replaced with another weird issue that I'll test before registering it here.
