### ISSUE TITLE
wallabag user password can't contain special caracters

### ISSUE THREAD

**Issue by tcitworld** [jangernert/FeedReader#326]
* try to login with a password containing a special character
* *Something went wrong*
Logs : 
```
[ DEBUG ] {"error":"invalid_grant","error_description":"Invalid username and password combination"}
[ ERROR ] WallabagAPI.getAccessToken: no member access_token in response
```
* change the password to remove this special character (I also removed an upper case character, but I guess it's not the issue here)
* login successful

**Comment by jangernert** [comment]
Just to be sure when I test this later, what kind of special character are we talking about? Something like '!'? :)

**Comment by tcitworld** [comment]
To be exact `&`.

**Comment by jangernert** [comment]
Jup, turns out I forgot to encode the strings.
Can you confirm the fix? :)

**Comment by tcitworld** [comment]
Confirmed, thanks.

By the way, wallabag takes no uppercase on first letter ;-)

**Comment by jangernert** [comment]
My mistake, will update it.
