### ISSUE TITLE
All Articles category has icon from one of the feeds

### ISSUE THREAD

**Issue by arjan-s** [jangernert/FeedReader#330]
Nextcloud News 10.1.0
FeedReader master

The icon of one of the feeds is used as the icon for All Articles after the initial synchronisation, and stays that way between restarts. I think the icon for All Articles should not be changed and just remain the monochrome RSS-icon.

**Comment by bil-elmoussaoui** [comment]
Do you have a screenshot ?

**Comment by jangernert** [comment]
I'm guessing you have a feed with the ID 1 in NextCloud? This could explain the behaviour.
I think the latest commit should fix this :)

**Comment by arjan-s** [comment]
Works like a charm. :) 
Thank you!
