### ISSUE TITLE
Spinner never goes away after refreshing a bunch of feeds (master)

### ISSUE THREAD

**Issue by Gert-dev** [jangernert/FeedReader#333]
Hello

After importing my infamous OPML, I started a refresh. The loading spinner at the top starts spinning and after a while, several unread articles appear. However, the spinner never seems to stop. Perhaps it's hanging up on a specific feed? Is there a way to debug that?

Terminal output shows this:

```
<-- I start the sync.
[ DEBUG ] DBusConnection: updateSyncProgress
<-- The loading spinner appeared and has worked for a while.
[ DEBUG ] DBusConnection: updateFeedList
[ DEBUG ] DBusConnection: updateArticleList
[ DEBUG ] ArticleList: updateArticleList()
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID39"  ORDER BY rowid COLLATE NOCASE DESC LIMIT 15 OFFSET 0
[ DEBUG ] actual articles loaded: 15
[ DEBUG ] DBusConnection: writeInterfaceState
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] offset 0
<-- Strange... I didn't request another sync?
[ DEBUG ] DBusConnection: updateSyncProgress
```

After a couple more seconds, the daemon crashed and dumped its core:

```
Stack trace of thread 9610:
#0  0x00000000004412c6 feed_reader_grabber_utils_saveImages (feedreader-daemon)
#1  0x00000000004470c2 n/a (feedreader-daemon)
#2  0x00000000004259bd feed_reader_feed_server_grabContent (feedreader-daemon)
#3  0x0000000000415786 n/a (feedreader-daemon)
#4  0x000000000041d280 n/a (feedreader-daemon)
#5  0x00007fcf7d19b0d5 n/a (libglib-2.0.so.0)
#6  0x00007fcf7ca0b454 start_thread (libpthread.so.0)
#7  0x00007fcf7ed857df __clone (libc.so.6)
```

Thanks in advance

**Comment by jangernert** [comment]
Well, I guess it's finally time to post your complete OPML.
Syncing takes some time since after grabbing the articles the content-grabber starts up in the background and downloads the full articles of all supported websites ([ftr-site-config](https://github.com/fivefilters/ftr-site-config)) and downloads all the images for offline-viewing later on.
Seems like downloading one of the images didn't work for you.
Optionally you can disable the content-grabber in the settings and even the downloading of images in the tweaks section of the gsettings.

**Comment by Gert-dev** [comment]
Hmmm... in that case this may not be a bug, it was likely just the content grabber still fetching the full content of the articles. The fact that it crashed a couple of seconds afterwards seems to confirm that, as it was downloading images. There are a 30ish feeds, so it is very well possible full indexing is still happening.

Since it's likely not an actual bug, I was wondering if maybe it's confusing that the spinner is still shown during full indexing? In a way it's correct, seeing as indexing is still occurring, but as a user having no knowledge of the background operations, I only linked the spinner to fetching of the unread counts and expected it to go away once those appeared.

Perhaps it would be interesting to, instead, make the spinner go away after fetching the unread counts and, if an article that is not yet indexed is accessed, show something like a "Please stand by, the full contents of this article are still being fetched"? Alternatively, turn the spinner into something else - or add a label to it - to indicate a post-fetch action is still being performed. What do you think?

**Comment by jangernert** [comment]
There is a label. Just click the spinner and you get detailed information what is currently happening.
Also you can start the feedreader-daemon in commandline and watch the output if you are unsure if something is going wrong.
Also what about the crash?

**Comment by Gert-dev** [comment]
Oh, you can actually click the spinner, I expected a tooltip or popover on hover and would expect clicking the spinner again to cancel the action :-).

Regarding the crash: I'll see if I can find the feed or article that was the culprit. Feel free to close this issue, I'll create a new issue with more details for your convenience as soon as I do :-).
