### ISSUE TITLE
2.0-beta-1 RPM won't build on open build service

### ISSUE THREAD

**Issue by megamaced** [jangernert/FeedReader#335]
Hi,

I'm trying to make an RPM of FeedReader 2.0-beta-1 on the openSUSE Build Service. I've already jumped through a few hurdles to get this to compile on Leap 42.2 and SLE 12 SP2 by recompiling gnome-online-accounts with vala. Now however the RPM won't create due 'exceeding badness'

https://build.opensuse.org/package/show/home:megamaced/feedreader

```[  158s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libttrss.so
[  158s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libfeedlyUI.so
[  158s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/libwebextension.so
[  158s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsShare/libinstapaper.so
[  158s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libowncloud.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsShare/libmail.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libfeedbinUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsShare/libpocket.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsShare/libtwitter.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libowncloudUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libttrssUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libinoreaderUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libfresh.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/liblocal.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/liblocalUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/libfreshUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libfeedly.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsUI/liboldreaderUI.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/liboldreader.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libfeedbin.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/plugins/libinoreader.so
[  159s] feedreader.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/FeedReader/pluginsShare/libwallabag.so
[  159s] This package installs an ELF binary in the /usr/share  hierarchy, which is
[  159s] reserved for architecture-independent files.
[  159s] 
[  159s] (none): E: badness 12980 exceeds threshold 1000, aborting.
[  159s] 2 packages and 0 specfiles checked; 22 errors, 110 warnings.```

**Comment by jangernert** [comment]
Never compiled anything with OBS. So no idea, sorry.

**Comment by megamaced** [comment]
I think it just complains because feedreader is putting libs in wrong place by default.

I think all i should need to do is move /usr/share/FeedReader/plugins* to /usr/lib64/FeedReader/plugins*. Is there a way to do that at compile?

Or if I just move those libs after %install and run ldconfig would that work?

**Comment by megamaced** [comment]
I am not a dev but I thought I would give it a go, learn a few new things etc.. but it doesn't work :-D

https://github.com/megamaced/FeedReader/tree/movelibs

I think the CMakelists.txt is OK. When I build the package all the libs now go to /usr/lib64/Feedreader.. But I think I make a mistake with the vala stuff.

When I compiled and opened the program the first run wizard was blank (I could not see a provider to select)

**Comment by megamaced** [comment]
![image](https://cloud.githubusercontent.com/assets/22581049/22351732/33a91a8a-e411-11e6-8b71-9e9a9a5bc445.png)

Thats what I get 

My SUSE package here https://build.opensuse.org/package/show?project=home%3Amegamaced&package=feedreader

**Comment by jangernert** [comment]
I merged your changes and fixed it up a little.
${CMAKE_INSTALL_LIBDIR} was just "lib64", so you needed to add the install prefix in front of it.
Also moved libwebextension.so to libdir.

**Comment by jangernert** [comment]
Just some things that I noticed with your spec-file
> BuildRequires:	gtk3-devel >= 3.12.0

That was true for everything before 2.0. Now >=3.20.0 is required.

> BuildRequires:	webkit2gtk3-devel

Support for webkit API v3 was removed. Only v4 is supported now.

> cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF -DUSE_WEBKIT_4=OFF ..

no need for unity and webkit options anymore.

**Comment by megamaced** [comment]
Good to know I wasn't too far off from getting it right :-D

Will make those amendments to the spec file and make a new RPM
Cheers
