### ISSUE TITLE
Importing YouTube feed causes SIGSEGV (master)

### ISSUE THREAD

**Issue by Gert-dev** [jangernert/FeedReader#336]
Hello

When I try to import [this feed](https://www.youtube.com/feeds/videos.xml?channel_id=UCDnEa2HC2eeT-cN3pAKnNTw) (random feed grabbed from YouTube) with a local account by clicking the plus button below, I get a SIGSEGV and the application closes.

```
(feedreader:11617): Gtk-WARNING **: Allocating size to GtkOverlay 0x179a130 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleView.setBackgroundColor()
[ DEBUG ] addFeed: https://www.youtube.com/feeds/videos.xml?channel_id=UCDnEa2HC2eeT-cN3pAKnNTw, null

(feedreader:11617): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
fish: 'feedreader' terminated by signal SIGSEGV (Address boundary error)
```

Strangely enough, I also have feeds like these in my OPML and they are added when I import it - but they are not fetched, but I'll create a separate issue if that still turns out to be the case after this one is solved :-).

Thanks in advance

**Comment by jangernert** [comment]
Both fixed: the first was my fault. Somehow dbus doesn't like 'null' arguments any more. I somehow thought this was possible. The second issue was because the youtube-feed does not provide any actual article-content. Now in that case I just put in the dummy-text "Nothing to read here."
