### ISSUE TITLE
Feed that won't seem to import (latest master)

### ISSUE THREAD

**Issue by Gert-dev** [jangernert/FeedReader#337]
Hello

Here I am again with [a feed that won't seem to import](http://vibed.org/blog/feed/rss) :-). `feedreader-daemon` lists the following output:

```
[ INFO  ] addFeed: ID = feedID1

** (feedreader-daemon:12125): CRITICAL **: feed_reader_feed_construct: assertion 'title != NULL' failed
[ DEBUG ] last clean: 2017-01-24 17:18:43
[ DEBUG ] now: 2017-01-25 18:11:50
[ DEBUG ] difference: 1.000000
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] Ping: https://www.google.com/
[ DEBUG ] Ping: modified URL www.google.com
[ DEBUG ] Ping: trying ip-address 216.58.212.228
[ DEBUG ] HTTP/1.1 302 Found
[ DEBUG ] Ping: success!
[ DEBUG ] SELECT count(*) FROM main.CachedActions
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.CachedActions
[ DEBUG ] count 0
[ DEBUG ] CachedActionManager - executeActions: no actions to perform
[WARNING] resetCachedActions
[ INFO  ] daemon: sync started
[ DEBUG ] Ping: https://www.google.com/
[ DEBUG ] Ping: modified URL www.google.com
[ DEBUG ] Ping: trying ip-address 216.58.212.228
[ DEBUG ] HTTP/1.1 302 Found
[ DEBUG ] Ping: success!
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] FeedServer: grabContent
[ INFO  ] daemon: sync finished
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
```

It may have something to do with the assertion.

Also, out of curiosity: why is there a ping to Google? As a check to see if internet connectivity is available?

Thanks in advance

**Comment by jangernert** [comment]
1. This is not the same issue you were describing in the other report. There the daemon was clearly crashing while trying to download an image.
2. Why don't you make this whole process easier and post your whole OPML, so I can test it in one go. And not peace by peace over the course of weeks. If there are some feeds in there you don't want people to know about and you're sure they are working fine, you can remove them before.
3. Yes, with other back-ends I ping the servers of said back-end, but with the local back-end I thought google was the most obvious thing to test the internet connection :D

**Comment by jangernert** [comment]
Fixed the issue. But the feed is pretty much broken.
It doesn't provide a title (that's why it couldn't be added) so I use the hostname of the url as a feed-name.
But even then, the GUID (Globally Unique Identifier) isn't as unique as the name would suggest. It's "xxyyzz" for each and every article. So it's impossible to properly tell which articles are already added to the database and which ones are new.
So my suggestion is to tell the operator of the blog to fix his rss-feed.

**Comment by Gert-dev** [comment]
Thanks for fixing it.

About your first point, I did say I was going to let you know about the crashing feed and article, but that wasn't this one. I was just testing something else and noticed that this wasn't working, but it's not at all related to the one that was crashing before. I realize now that my wording may have implied that, however.

About the OPML, there is no need to post it anymore, as by your explanations and fixes you've already done, it is now working properly.

Finally, regarding Google, I wanted to let you know some users may not be very fond of that because it's... well... Google 😄 ; in the world of privacy, they received somewhat of a tainted image. (Perhaps something like duckduckgo.com / gnome.org / fsf.org / gnu.org would be less controversial.)

**Comment by jangernert** [comment]
Regarding ping: I don't really care what server it is, as long it is pretty much guaranteed to always be available. I just changed the string to "https://duckduckgo.com/".
