### ISSUE TITLE
No such interface 'org.gtk.Actions'

### ISSUE THREAD

**Issue by megamaced** [jangernert/FeedReader#339]
Hi

I built a Feedreader 2.0-beta-1 RPM up to commit 059687c movelibs

The RPM builds and installs fine but FeedReader won't launch. The error is:

```Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gtk.Actions' on object at path /org/gnome/feedreader```

Build log is here:
https://build.opensuse.org/build/home:megamaced/openSUSE_Leap_42.2/x86_64/feedreader/_log

RPM Spec is here:
https://build.opensuse.org/package/view_file/home:megamaced/feedreader/feedreader.spec?expand=1

Cheers

**Comment by jangernert** [comment]
Should be fixed with latest commit. Can you confirm the fix?

**Comment by jscurtu** [comment]
this error is because the old daemon was still running.

after installing a new build, it makes sense to kill the old one with:

pkill feedreader-daem

**Comment by megamaced** [comment]
works now
