### ISSUE TITLE
Pop-up image viewer

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#34]
- [x] pop up image viewer widget
- [x] support scaling and zooming with [GtkImaveView](https://wiki.gnome.org/Projects/GTK%2B/GtkImageView) (hopefully in Gtk+ 3.20)
- [x] detect scaled down images (or images bigger than predefined size) in the article with js
- [x] style those images with a hover effect
- [x] deliver local image path, url and image size to the image viewer on click
- [x] need to remove the parrent element if its a a tag
- [x] never spawn multiple instances of the popup at once

**Comment by jangernert** [comment]
#84 describes a crash when spamming imagepopups. This is likely happening because the js code can spawn multiple instances of the popup at once. This should not be possible. I will add it to the to-do-list.

**Comment by bil-elmoussaoui** [comment]
I will fix that with a new commit soon!

**Comment by jangernert** [comment]
completed with c540db90dd6757bffedb024b79a68883aa521ec9
