### ISSUE TITLE
Add support for ubuntu 16.10

### ISSUE THREAD

**Issue by Hanzei** [jangernert/FeedReader#340]
After upgrading to ubuntu 16.10, it is not longer possible to install FeedReader via the PPA. After adding the PPA and running `apt update` I got the error message:
`W: The repository 'http://ppa.launchpad.net/eviltwin1/feedreader-stable/ubuntu yakkety Release' does not have a Release file.`

**Comment by jangernert** [comment]
#305
#245
#244
#243

Why is nobody even trying to check for duplicates? ...
