### ISSUE TITLE
Forced Fullscreen and no buttons.

### ISSUE THREAD

**Issue by radasbona** [jangernert/FeedReader#341]
Hello,
i installed FeedReader via PPA on my UbuntuMate 16.04.
The Reader is always on complete fullscreen mode. The bar on top with the buttons is not visible, also no one of the OS's bars. 
The only thing i was able to reach was the alt+space menu. 

![screensh](https://cloud.githubusercontent.com/assets/14041833/22594890/56f10268-ea25-11e6-9427-494a1a58e3a4.jpg)

**Comment by jangernert** [comment]
Does mate have a shortcut to Fullscreen windows? What does happen if you press it?

**Comment by jangernert** [comment]
Can't reproduce in fresh ubuntu-mate 16.04.1 installation. So something else has to be going on on your PC.

**Comment by radasbona** [comment]
Yes, Alt F10 (Alt F5 to restore). Nothing happens, except Alt F9 to minimize. And it is also grayed out in the menu.
My Installation is also just one day old and fresh. Changing Monitor resolution didn't help me out, too.

![screenshot](https://cloud.githubusercontent.com/assets/14041833/22618361/82469a76-eada-11e6-8a9c-62171d5dd68b.jpg)

**Comment by jangernert** [comment]
Like I said, I can't reproduce it on a fresh installation of ubuntu mate. And if I can't reproduce the issue (or at least have precise information in what circumstances it occurs) I can't really fix it...

![screenshot from 2017-02-04 15-13-24](https://cloud.githubusercontent.com/assets/12012494/22619084/8e30b65c-eaec-11e6-97f7-680968753da1.jpg)

**Comment by jangernert** [comment]
Would you mind testing the latest master code? I cleaned up the fullscreen-handling code a bit.
You would have to use a flatpak, since ubuntu 16.04 only ships Gtk+ 3.18 while Gtk+ >= 3.20 is required.

**Comment by radasbona** [comment]
Sure. Do you have a deb Package? I have no build dependences installed. 

I tried flatpak, but it doesn't work with Mate. Asks me for Gnome Runtime.

**Comment by jangernert** [comment]
Yes, you do have to install the gnome-runtime (version 3.22) first.
http://flatpak.org/getting.html
http://flatpak.org/runtimes.html
No, Anything newer than 1.6.2 is no longer supported on ubuntu 16.04. The Gtk+ library that ubuntu ships is way too old. So no deb-packages.

**Comment by radasbona** [comment]
(was a few days offline)
Sorry, but i can't install a ~300MB runtime for flatpack. (From Flatpak FAQ: "Is Flatpak tied to Gnome? No!" Lol) You should better use AppImage.

Btw: Mate 1.16 comes with Application and theme support for GTK+ 3.22.

**Comment by bil-elmoussaoui** [comment]
@radasbona Well, Flatpak is not really tied to Gnome; what do you install is the Gnome runtime, which will be used whenever you install another Flatpak package that uses Gnome libraries to run. If for example, you wanted to install Kdenlive as a Flatpak package, you will need the KDE runtime. Anyway, it's up to you to decide what to install and what to not :)
If someone wants to create an AppImage feel free to do so and we will put that on the README/Website. 

In that case, please try to compile from source code, everything is explained on the README/Website. We sadly can not continue packaging FeedReader PPA as @jangernert had few issues with it, and honestly, Launchpad sucks to lose your time trying to figure out how to work around their bugs. 
A snap package might be ready soon enough #268

**Comment by jscurtu** [comment]
@radasbona I dont think AppImage will be much smaller to tell you the truth..
@bil-elmoussaoui said it right, flatpak is not in anyway tied to GNOME, but FeedReader is to GNOME technologies/Platform that it depends on which is why it runs on the gnome sdk/plattform and not on an other (freedesktop, kde) . 

If we do a AppImage package then will would still need to pack all the GNOME technologies that FeedReader is using in a single binary and probably patch the hell out of it ... Thats not fun and a waste of time doing this all over and over.. 

Believe me, Flatpak solves this much much better + you get OTA updates independently from your distribution and get to use the shiny new stuff right on release with less bugs that affect distributions.
From a new release until its live in our repo and for everyone to use, I only need to invest 20 min..

**Comment by probonopd** [comment]
If you can compile FeedReader on a not-too-recent GNOME/Gtk+, then you can assume that all target distributions have at least that version installed, and need not bundle these things.

**Comment by radasbona** [comment]
Thanks Guys for explaining. The runtime is needed for feedreader not flatpak. 

Building by myself was not successful. libgoa1.0 is only available in version 3.18 for Ubuntumate 16.04. I guess thats is the reason, cmake don't gives me a clearly error message.
