### ISSUE TITLE
Menu bar appears when Show application menu is disabled

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#342]
When you disable show application menu under Gnome a menu bar appears :(
![screenshot from 2017-02-03 23-27-55](https://cloud.githubusercontent.com/assets/7660997/22610988/9021b184-ea68-11e6-8eb2-a480e229bfcf.png)

I've took a look and how to avoid this, it's not that complicated, we should check if the show application menu is enabled and the current desktop env is gnome before setting the app_menu for the current window.
The show application menu is stored under `org.gnome.settings-daemon.plugins.xsettings` > `overrides` > `Gtk/ShellShowsAppMenu` It's a uint32 GVariant type.

**Comment by jangernert** [comment]
Why should FeedReader work around this behavior? Either it's intended behaviour of Gtk+, or it's a bug in Gtk+. Either way, I don't see a reason to add a workaround that may be obsolete in a few months and clutters up the code.

**Comment by bil-elmoussaoui** [comment]
@jangernert Well, i wouldn't report this if the menu bar wasn't showing as with other Gtk applications! I've tried to kill feedreader, restart my system and still having the same issue..
Here's an example of how it should look like 
![screenshot from 2017-02-04 12-30-24](https://cloud.githubusercontent.com/assets/7660997/22618147/bbe619fa-ead5-11e6-8c0e-4a6efc4fa552.png)
What i was thinking of, is instead of letting Gtk to set that popover with the application icon on top left we show the settings button(the one shown on other desktop env other than Gnome) which will fix both issues.

**Comment by jangernert** [comment]
For me the menu-bar disappears after restarting FeedReader. And I still don't see FeedReader should work around the issue instead of fixing it in Gtk+. Try another app with split-headerbar. Gedit with sidebar behaves exactly the same way as FeedReader does on my system. If I activate the override while Gedit is running the menu-bar shows up, but is gone once I restart the application.

**Comment by jangernert** [comment]
Okay, this only happens on wayland, on X the menu-bar pops up if FeedReader is running but not if the application is started afterwards.
So this is definitely a bug in Gtk+. Please report it there. If you want we can keep this open and post updates here just like the webkit-issue.

**Comment by bil-elmoussaoui** [comment]
I forgot to try this on X :P I will report this upstream; we can close this one, i will comment here if anything changes in the future

**Comment by jangernert** [comment]
Took the time to report everything I have noticed so far.
Maybe you can add some more information there:
https://bugzilla.gnome.org/show_bug.cgi?id=778184
