### ISSUE TITLE
Change daemon dbus-name and UI app-ID

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#343]
@jscurtu okay let's try this again 02b9f02a8723bcdf7859edfcfb876b412a833b73 383e360770fd392b911e9defa48097eaaef92393:
I renamed the dbus-interface of the daemon: `org.gnome.feedreader` -> `org.gnome.feedreaderDaemon`
as well as changed the name of the .service-file to `org.gnome.feedreaderDaemon.service` and edited the Name-property of it accordingly.
Then I was able to change the app-ID of the UI from `org.gnome.FeedReader` to the one used everywhere else `org.gnome.feedreader`
This fixes all the icon- and desktop-issues I was having since both have been renamed to the app-ID.

Is there any reason this shouldn't work with the flatpak?

**Comment by jangernert** [comment]
Okay, once I dug into building, installing and running the flatpak myself the issue was quite obvious. The dbus-name `org.gnome.FeedReader` does not longer have to be exposed to the flatpak (dbus-name of the UI before), instead we now need to expose `org.gnome.feedreaderDaemon` (the new dbus-name of the daemon). `org.gnome.feedreader` seems to be automatically exposed, since it's the app-ID. Only difference is the name was originally owned by the daemon. Now it's owned by the Gtk.Application like it should be.
Additionally now I know how to build flatpaks and will keep it installed alongside my local build to test from time to time :)
@jscurtu can you confirm that this time everything is indeed working for you as well?

**Comment by jscurtu** [comment]
The dbus-name org.gnome.FeedReader gets exposed in the flatpak builder file with app-id. 
I will try and confirm this after my coffee :-) .. the app names and buses should be CamelCased though, i see you made them all lower now.

**Comment by jscurtu** [comment]
when building the flatpak bundle, I now get a flatpak-WARNING **: Invalid id feedreader. 
Which might be related to what I mentioned obove. 

But everything else looks like its working.. nice :-)

**Comment by jangernert** [comment]
I guess I can swing the rename-hammer one last time and camelCase everything ;)

**Comment by jangernert** [comment]
Okay I think we're good now:
AppID: org.gnome.FeedReader (that means the UI owns the same name on dbus as well)
Daemon: owns org.gnome.FeedReader.Daemon
WebExtension: org.gnome.FeedReader.ArticleView

All icons, desktop-files and service-files have been renamed accordingly. Flatpak-file is updated.
I get no errors or warnings any more compiling, installing or running the flatpak :)

**Comment by jscurtu** [comment]
Super cool.. Confirmed working! Thx :-)
