### ISSUE TITLE
Plugins don't load after installing from the latest commit

### ISSUE THREAD

**Issue by arjan-s** [jangernert/FeedReader#345]
After starting feedreader-daemon from the console, the log shows:
```
[ INFO  ] FeedReader Daemon 2.0 beta1
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "owncloud"
[ ERROR ] feedserver: couldn't load plugin owncloud
[ ERROR ] daemon: plugin 'owncloud' couldn't be loaded by feedserver
```

Using strace to find the problem, I encountered the following line:
```
open("/usr//usr/lib/FeedReader/plugins/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Looking at the source code, I found the cause in src/Backend/FeedServer.vala:43 and src/Widgets/LoginPage.vala:31 where the following construction is used:
```
m_engine.add_search_path(Constants.INSTALL_PREFIX + "/" + Constants.INSTALL_LIBDIR + "/plugins/", null);
```

Since the latest libdir changes a few commits ago, I've had to compile FeedReader with `-DCMAKE_INSTALL_LIBDIR=/usr/lib` , causing the statement above to return "/usr//usr/lib/FeedReader/plugins/", which is obviously wrong.

**Comment by jangernert** [comment]
Why did you "had" to use /usr/lib as your install prefix? The standard /usr/local or just /usr should work just fine.

**Comment by arjan-s** [comment]
Sorry, my bad! Please close this issue.
The problem was that I set "/usr/lib" instead of "lib" as LIBDIR in CMake. That causes the files to be installed in the right place, but the constants to be set wrong.
The reason for specifying LIBDIR in CMake is that the recent libdir commits have changed the default installation directory of the plugins from /usr/lib to /usr/lib64, which causes a conflict with the existing filesystem when installing the Arch Linux package.

**Comment by jangernert** [comment]
What is the conflict you're talking about? You mean you have the FeedReader-package as well as a self-compiled version on your system?

**Comment by arjan-s** [comment]
No, the conflict is in the "/usr/lib64" directory, which is a symlink made by the "filesystem" package. After those libdir commits, FeedReader now installs to "/usr/lib64" instead of the previous "/usr/lib". When the "feedreader-git" package is installed (before the -DCMAKE_INSTALL_LIBDIR addition), its "/usr/lib64" dir conflicts with the existing "/usr/lib64" symlink.
That's why I asked the "feedreader-git" package maintainer to add the `-DCMAKE_INSTALL_LIBDIR=/usr/lib` to the cmake command. Now I know it should have been `-DCMAKE_INSTALL_LIBDIR=lib` to make everythink work perfectly again.

**Comment by jangernert** [comment]
I'm quite confused. Before the changes the plugins were installed to $INSTALL_PREFIX/share/FeedReader (e.g. /usr/local/share/FeedReader/). Also shouldn't a symlink work like an existing folder?

**Comment by arjan-s** [comment]
Okay, I was mistaken on the original plugins dir, but the problem was the same. Of course the /usr/lib64 symlink normally works like a directory, but this is not the case with the Arch package manager (pacman). It sees a package that needs /usr/lib64 to be an actual directory, while another package has already installed a symlink with that name. That's what causes the conflict.
But anyway, the problem is in the packaging, not in FeedReader. Changing the packaging to install the plugins to /usr/lib (which is an real directory) fixes the packaging problem.
