### ISSUE TITLE
Add shortcut to show "Shortcuts help" dialogue

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#349]
The recommended shortcut is "Ctrl+?"

**Comment by jangernert** [comment]
F1

**Comment by hadess** [comment]
Ctrl+F1 and Ctrl+? are the recommended shortcuts for this:
https://wiki.gnome.org/Initiatives/GnomeGoals/ShortcutWindows

F1 should be used for the inline help, though there isn't one in FeedReader yet.

**Comment by julianrichen** [comment]
In addition it's documented here:
https://developer.gnome.org/gtk3/stable/GtkApplication.html

If you include the shortcuts window as a ui file aliased or located at gtk/help-overlay.ui via gresource it will automatically connect it to GtkApplication and and the accelerators Control+F1 and Control+? (Control+Shift+? for me).

Same applies for gtk/menus.ui and gtk/menu-*.ui.

**Comment by jangernert** [comment]
I'm not really a fan of .ui-files.

**Comment by jangernert** [comment]
shortcut is now also configurable and default is ctrl+F1
