### ISSUE TITLE
Add "Open in Browser" to "Share" menu

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#351]
Similarly to "e-mail". Bonus points if you add a shortcut for this specific one! (My old feed reader used "L" for this)

**Comment by jangernert** [comment]
Shortcut for this is "o" as you can see in the shortcuts-window.

**Comment by hadess** [comment]
Should there be one in the Share menu as well?

**Comment by jangernert** [comment]
I can add it there.
