### ISSUE TITLE
Use better icon for "Pocket" "Share" item

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#353]
As the account setup uses gnome-online-accounts, you should be able to use the icons offered by goa for this.

![goa icon](https://git.gnome.org/browse/gnome-online-accounts/plain/data/icons/96x96/goa-account-pocket.png)

https://git.gnome.org/browse/gnome-online-accounts/plain/data/icons/96x96/goa-account-pocket.png

vs.

https://github.com/jangernert/FeedReader/blob/master/plugins/share/Pocket/icons/32x32/actions/feed-share-pocket.svg

**Comment by bil-elmoussaoui** [comment]
@hadess We canno't use this icon by default, as FeedReader is shiped for distros other than Gnome (which doesn't have the Adwaita theme by default).
@jangernert We can use this icon, and use the one we ship as a fallback?

**Comment by hadess** [comment]
You can, given that the Pocket support is provided via gnome-online-accounts. No gnome-online-accounts, no icon, and no Pocket support, so no need to have an icon :)

**Comment by jangernert** [comment]
Pocket is also available without gnome-online-accounts. Then FeedReader provides a custom login-widget just like all the other services right now.

**Comment by hadess** [comment]
I didn't see an option to add Pocket support in my version, though that might indeed be because it's built with gnome-online-accounts support. Is it possible to use the better icon when it's present in this case?

**Comment by jscurtu** [comment]
Its built with GOA yes, but if you dont give GOA your packet account it wont use it.. then it falls back to packet from FeedReader.
