### ISSUE TITLE
Add "F11" shortcut for fullscreen

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#354]
Not that I'd use it, but for completeness' sake.

**Comment by jangernert** [comment]
Why exactly F11? FeedReader uses the system-wide fullscreen-shortcut.

**Comment by hadess** [comment]
I'm guessing that it comes from Windows using that as a standard fullscreen shortcut.

On my system, that key combo is used by gnome-terminal, totem (Videos), xchat-gnome, epiphany, and Firefox, out of my open programs.

**Comment by jangernert** [comment]
Gnome-Shell (and afaik every other DE) has a system-wide shortcut to toggle fullscreen. I don't see a reason to list that exact same shortcut again in FeedReader.

![screenshot from 2017-02-06 21-13-02](https://cloud.githubusercontent.com/assets/12012494/22664500/45f170cc-ecb1-11e6-99dc-2d0e6044d4d6.jpg)

**Comment by hadess** [comment]
Usually applications also provide their own.
