### ISSUE TITLE
Add empty state placeholder when cache is not available

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#355]
To be able to test FeedReader easily, I created a Flatpak for the latest version. Upon starting, I thought there was a problem, as the interface was completely empty. It turns out the small "update" button had started spinning, but I didn't notice it.

(As I had used FeedReader outside of Flatpak, the accounts were stored in GSettings, and I didn't have to type them again)

It would be useful if FeedReader showed a placeholder before downloading the "Feeds and Categories", and then showed a spinner next to the feeds it's updating (though that might be a bit too ugly if it downloads from different feeds in parallel...)

**Comment by jangernert** [comment]
There already is an updating-state for the ArticleList when it's empty.
