### ISSUE TITLE
Article list doesn't update automatically

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#357]
When new articles get added in a category, the list is not updated to reflect that fact.

**Comment by jangernert** [comment]
It does for me and every other user. So you need to be a little more specific. In what circumstances does it not work?

**Comment by hadess** [comment]
5 new articles appeared in this category when I was away. Only the old Ars Technica article I already read was in the article list. That's using 2c485a085a928f38657a9c56e8d84456a26c6485 as the master.

![not-updated](https://cloud.githubusercontent.com/assets/769861/22760371/746f37d0-ee56-11e6-8080-b3dc03a048a2.png)

**Comment by hadess** [comment]
The account is "feedly".

**Comment by jangernert** [comment]
And again, works for me on tt-rss, which doesn't really matter because the functionality is not specific to any back-end. Soooooo ... need more information.

**Comment by hadess** [comment]
For it not to update, I think you need to have an article opened, but marked as read, not an empty list (which would happen if you switched to an empty category or feed).

I had an empty list opened, and it did load the new items, just like in your case.

**Comment by jangernert** [comment]
I'll try to reproduce it tomorrow.

**Comment by jangernert** [comment]
Confirmed!
But don't have time to fix it. I think I'll get to it in 1 or 2 days.

**Comment by hadess** [comment]
> But don't have time to fix it right now. I think I'll get to it in 1 or 2 days.

That's fine, at least I'm not going bananas ;)
