### ISSUE TITLE
Error while grabbing content

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#36]
[ ERROR ] //iframe
[ DEBUG ] Grabber: no body found
[ DEBUG ] GrabberUtils: repairURL xpath:"//img" attr:"src"
[ DEBUG ] GrabberUtils: save Images: 00000001b0f303b4, feed/http://www.youtube.com/feeds/videos.xml?channel_id=UCi8e0iOVk1fEOogdfu4YgfA
[ DEBUG ] GrabberUtils: postProcessing
[ DEBUG ] GrabberUtils: broken = <iframe width="640" height="390" src="https://www.youtube.com/embed/DTtQlZVYanI?wmode=transparent&amp;rel=0&amp;autohide=0&amp;showinfo=0&amp;fs=1enablejsapi=0" frameborder="0"/>
[ DEBUG ] GrabberUtils: fixed = <iframe width="640" height="390" src="https://www.youtube.com/embed/DTtQlZVYanI?wmode=transparent&amp;rel=0&amp;autohide=0&amp;showinfo=0&amp;fs=1enablejsapi=0" frameborder="0"></iframe>
[ DEBUG ] GrabberUtils: postProcessing done
[ DEBUG ] Utils: generatePreviews
[ ERROR ] generatePreviews: no Preview
Segmentation fault (core dumped)

**Comment by kanishkablack** [comment]
Found the issue with a specific thing,

if an article returned from server has empty string or empty content, app is quitting.

**Comment by bil-elmoussaoui** [comment]
It's rather a bug than a wishlist

**Comment by jangernert** [comment]
I could not reproduce this issue. Can you name the article that is being processed when the crash happened?

**Comment by kanishkablack** [comment]
@jangernert actually there is bug in server end, sending a empty article.

as of last i got error with this url http://feeds.gawker.com/~r/kotaku/full/~3/LkVyveC8eD4/story01.htm

**Comment by jangernert** [comment]
That's what I was already suspecting. Should be libVilistextum.
What is the input you are putting into the libVilistextum.parse() that causes it to crash?
How can I reproduce the bug?
Putting in a empty string does not make it crash.

**Comment by jangernert** [comment]
I think I fixed the bug with the latest commit in master branch. But since I never experienced the bug, I can't tell for sure. @kanishkablack can you please test again?
