### ISSUE TITLE
Make it possible to manage feeds in the UI

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#360]
Currently, I need to open Feedly's web interface to add new feeds. Being able to add or remove feeds directly in the interface would be useful.

**Comment by jangernert** [comment]
Already implemented

**Comment by hadess** [comment]
I completely missed those, I was expecting something nearer the top of the sidebar, because, in my setup, I have the categories, and then 3/4 of the screen's height of whitespace.

2 things I would advise are:
- use symbolic icons for the +/- buttons, so they're a bit more visible
- add a way to add feeds to the contextual menu for categories (I also looked there).
