### ISSUE TITLE
Compilation failure in ttrssUI plugin

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#361]
Tried to build a Flatpak today, with all of yesterday fixes and:
```
plugins/backend/ttrss/CMakeFiles/ttrssUI.dir/build.make:76: warning: overriding recipe for target 'plugins/backend/ttrss/ttrssUtils.c'
plugins/backend/ttrss/CMakeFiles/ttrssUI.dir/build.make:64: warning: ignoring old recipe for target 'plugins/backend/ttrss/ttrssUtils.c'
make[2]: *** No rule to make target 'FeedReaderUI.vapi', needed by 'plugins/backend/ttrss/ttrssUI_target_valac.stamp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by jangernert** [comment]
Did you try to compile with a single thread?

**Comment by hadess** [comment]
No, I just used the defaults from Flatpak.

**Comment by hadess** [comment]
Works with:
```
           "config-opts": ["-DCMAKE_INSTALL_PREFIX=/app"],
+          "make-args": [ "-j1" ],
           "sources": [{
```

**Comment by jscurtu** [comment]
no issues here though

**Comment by jangernert** [comment]
Seems to be a race condition. If your pc can generate FeedReaderUI.vapi before compiling the plugins everything is fine.
Since you seem to know your way around build-systems, I would be happy about a pull-request with a fix from you @hadess  ;)
I guess a 'add_dependencies' is missing.

**Comment by hadess** [comment]
I don't know and don't use CMake. I tried, but between CMake's syntax and the custom Vala rules, I couldn't figure it out.

**Comment by hadess** [comment]
There's also a bizarre "=2.32" file being created in the builddir.

**Comment by hadess** [comment]
For testing locally, after committing your changes locally, you can change the flatpak .json file to point to a local URL, for example:
```
-                    "url": "https://github.com/jangernert/FeedReader.git"
+                    "url": "file:///home/hadess/Projects/jhbuild/FeedReader/"
```

**Comment by jangernert** [comment]
Most of the time compilation also works with 7 threads. Just in rare occasions I hit this issue.
I will add a dependency in the next few days. Depends when I can get to it.

**Comment by jangernert** [comment]
Dependency was actually already declared. But at some point I renamed EXEC_NAME to UI_NAME (since there are more than one executable) but forgot to update the dependency in all the plugins.
