### ISSUE TITLE
Trouble running flatpak with Wayland

### ISSUE THREAD

**Issue by aryonoco** [jangernert/FeedReader#362]
I'm running Ubuntu Gnome 16.10 Yakkety with Gnome 3.20 and using Wayland. 

I have flatpak 0.8.2 installed from the official PPA. xdg-desktop-portal and xdg-desktop-portal-gtk are also installed from the official flatpak PPA

The org.gnome.Platform/x86_64/3.22 runtime is installed. 

Installation of FeedReaderwith with flatpak install --bundle feedreader-stable-20161229.x86_64.flatpak succeeds. 

However when I run FeedReader, the app opens on the screen but is completely empty and doesn't show anything. 

Running the app from terminal results in this output: 

$ flatpak run org.gnome.feedreader
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 1.6.2

(feedreader:2): Gdk-WARNING **: Wayland compositor does not support xdg_shell interface, not using Wayland display

** (feedreader:2): CRITICAL **: file /run/build/feedreader/src/DBusConnection.vala: line 177: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state

** (feedreader:2): CRITICAL **: file /run/build/feedreader/src/Widgets/MainWindow.vala: line 184: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)

(feedreader:2): GLib-GObject-CRITICAL **: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(feedreader:2): Gtk-CRITICAL **: gtk_window_set_icon_name: assertion 'GTK_IS_WINDOW (window)' failed

(feedreader:2): Gtk-CRITICAL **: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

** (feedreader:2): CRITICAL **: feed_reader_dbus_connection_connectSignals: assertion 'window != NULL' failed

** (feedreader:2): CRITICAL **: file /run/build/feedreader/src/FeedReader.vala: line 99: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)

(WebKitWebProcess:14): Gdk-WARNING **: Wayland compositor does not support xdg_shell interface, not using Wayland display
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915 

Is this a known issue? Anything I can do to resolve it?

The official FeddReader PPA doesn't seem to have been updated for Yakkety so I can't seem to use that?

**Comment by jscurtu** [comment]
I would guess this is comming from the Wayland version shipped with 16.10. 
Does it work with X?

**Comment by jscurtu** [comment]
Also, if you are ok with experimenting, can you also test development version?
The latest is this: https://github.com/jscurtu/feedreader-flatpak/releases/tag/v2.0-20170210

It has access to DRI interface .. would like to know what happens..

**Comment by jscurtu** [comment]
What you can also try is to install the 3.20 runtime.
Then run feedreader with it from commandline as so:

flatpak run --runtime-version=3.20 org.gnome.feedreader

If that helps, I will rebuild and set the minimum runtime on a new build for the 1.6 release.

**Comment by aryonoco** [comment]
My mistake. Seems like after flatpak installation, it requires a full reboot to be able to run flatpak applications.

Everything working fine now. The 1.6 flatpak runs perfectly fine under Wayland and 16.10.

**Comment by aryonoco** [comment]
Just out of interest, I also did install the 3.20 runtime and tried running feedreader with the --runtime-version=3.20 directive you mentioned above. At first glance it seemed to work fine, but then I noticed that some things don't work properly. For example the keyboard shortcut to open the article in the browser "o" didn't work.

**Comment by jscurtu** [comment]
ok, thank you for your report. 
Then everything is as expected. :-)
