### ISSUE TITLE
unlock wallet password store

### ISSUE THREAD

**Issue by linuzzz** [jangernert/FeedReader#364]
when I choose to access inoreader it ask to unlock the wallet password store but the wallet subsystem in my kde (fedora 25) is disabled so I have no password for unlocking it. I also tried my password and the root one but none works. Thanks

**Comment by jangernert** [comment]
How about some context here?
What version are you using? 1.6 used the old method of getting the access-token from inoreader. 2.0 now uses OAuth 2.0.
When did kwallet ask for the password? Only the first time logging in or every time you open FeedReader?
FeedReader does not interact with kwallet or gnome-keyring at all. All it does is ask libsecret to store a password and then read it again when it needs to.
So I have no control over any of this.

**Comment by linuzzz** [comment]
sorry :-)
ok, i'm using 1.6.2 on Fedora 25 with KDE. My system is in english and I have the italian locale just for time and money...but the message was in italian so maybe my english translation is not the correct one. I will try to replay the error, but now I cannot because I used the feedly account and when I try to switch account to the inoreader one the application wait forever to finish syncronization, do You know if I can clear the config files in order to start from scratch? Where are they? thanks for your support.

**Comment by jangernert** [comment]
We just released version 2.0 a few minutes ago. Maybe you would like to try that one. Flatpak is already available.
If you want to clear all your data go to HOME/.local/share/feedreader/data/ and delete everything. Then you can open up dconf-editor (graphical editor for gsettings) and go to org->gnome->feedreader->inoreader or feedly and delete all your tokens ;)
