### ISSUE TITLE
Add shortcuts to scroll articles

### ISSUE THREAD

**Issue by taynaud** [jangernert/FeedReader#367]
Hello,

When I use shortcuts to select next or previous articles (J/K), focus change to article list and then arrows keys do not allow to scroll in currently read article anymore: they move selection in article list. Thus it is difficult to use keyboard to read long articles.

I am using version 1.6.2 from ubuntu 16.04 ppa.

Best,

**Comment by jangernert** [comment]
Added U/I shortcut to scroll down/up. But like all shortcuts in 2.0 they can be changed in gsettings.
