### ISSUE TITLE
FeedReader and other icon themes

### ISSUE THREAD

**Issue by acutbal** [jangernert/FeedReader#368]
Hello,

Today I've updated FeedReader to 2.0 and I've noticed that now it doesn't use my system icon theme anymore:

![captura de pantalla_2017-02-14_16-37-19](https://cloud.githubusercontent.com/assets/2278584/22936009/7cd3681a-f2d4-11e6-8c72-1a46031ef3b4.png)

I'm using Manjaro Xfce and I've installed from [AUR](https://aur.archlinux.org/packages/feedreader). How could I fix the issue?

Thanks in advance and best regards.

**Comment by bil-elmoussaoui** [comment]
@acutbal The icon name was changed from `feedreader` to `org.gnome.FeedReader` see here :  https://github.com/jangernert/FeedReader/blob/master/data/org.gnome.FeedReader.desktop.in#L7
Please open an issue upstream with the icon name or create a symlink in your system.

**Comment by acutbal** [comment]
Ok, I'll open an issue upstream. 

Thank you very much and very best regards!!

**Comment by jangernert** [comment]
The change was necessary because of the name-conventions required by flatpak.

**Comment by acutbal** [comment]
Ok, thank you very much for the info!!

Best regards!! 😃
