### ISSUE TITLE
Lost some feedreader tweaks in dconf-editor

### ISSUE THREAD

**Issue by acutbal** [jangernert/FeedReader#369]
Hello,

Today I've updated FeedReader to 2.0 and I've noticed that now I can't set to quit totally when I quit the app. It seems that I have lost some settings in this tab:

![captura de pantalla_2017-02-14_16-45-46](https://cloud.githubusercontent.com/assets/2278584/22936450/da807f10-f2d5-11e6-984e-e0d6b6422f98.png)

Thanks in advance and very best regards.

**Comment by jangernert** [comment]
Yes, the option was removed during the 2.0 cycle. It's just that this was another setting that had to be tested in combination with every other setting, which causes a huge test-matrix.
To re-add this feature it would have to be maintained by someone who actually uses it. The actual code is quite trivial. But like I said every now and then some weird edge-cases appeared or I unknowingly broke the feature at some point.

**Comment by acutbal** [comment]
I understand, many thanks for the info. I don't care if FeedReader uses memory when is open, but I want to totally quit because it uses a lot of RAM of my poor laptop, 4gb is used quickly nowadays. So, how could I quit it totally? I would know because, despite closing the app, feedreader-daemon and goa-daemon are still running:

![captura de pantalla_2017-02-14_18-25-46](https://cloud.githubusercontent.com/assets/2278584/22940879/b1ba3a7c-f2e3-11e6-8aa1-9372e518a44f.png)

Thank you very much and best regards!! 😃

**Comment by jangernert** [comment]
I guess you could patch and build your own version.
As you can see the code is pretty minimal. But since I don't use the feature I don't want to maintain it myself.
b7ee4418a90df71847d4d4a3d9f807b7f062524a

**Comment by acutbal** [comment]
I don't have such skills, I'll continue closing manually.

Thank you very much for the explanations and very best regards!! 😁👍

Enviado desde mi Nexus 6

**Comment by shiba89** [comment]
I'm probably not going to maintain this, but I made an updated version (compiles with 2.0 and 2.0.1):

https://gist.github.com/shiba89/5d4d2963e10081434a3123e6f2ae7840
