### ISSUE TITLE
Use gtk_show_uri_on_window()

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#373]
Instead of simply "gtk_show_uri()", so that the portal helper is correctly parented.

See https://bugzilla.gnome.org/show_bug.cgi?id=778678

**Comment by jscurtu** [comment]
thx ..

**Comment by jscurtu** [comment]
https://valadoc.org/gtk+-3.0/Gtk.show_uri_on_window.html

I think we need to keep both implementations. right?
Would be something like this (but in vala ofcourse) : 

https://github.com/Anisharma/GSOC_polari/commit/72688ca1d152dd9a8bde006b6f46b64c39d51bd4

**Comment by jscurtu** [comment]
At the moment it will only bypass the popup window for selecting a browser, that only appears if you have more then one webbrowser.

**Comment by hadess** [comment]
> I think we need to keep both implementations. right?

Why? From the looks of it, the call can only be made if the article view is opened, so you would have a window for it. You might want to keep Gtk.show_uri() if you support older versions of GTK+ though.

> At the moment it will only bypass the popup window for selecting a browser, that only appears if you have more then one webbrowser.

I don't understand what this means. This isn't about bypassing the popup, it's about parenting that popup correctly. I expect both to work equally well (or badly) if you don't have a window to parent to.

**Comment by jscurtu** [comment]
I will implement and test it ..

**Comment by jscurtu** [comment]
Ok, works .. :-) 
will push the changes as soon as testing is done .. 

![grafik](https://cloud.githubusercontent.com/assets/590307/22980619/4daa3232-f39a-11e6-87b6-a22422356cb0.png)

**Comment by jscurtu** [comment]
#375
