### ISSUE TITLE
Can't add any services

### ISSUE THREAD

**Issue by Cybolic** [jangernert/FeedReader#377]
I've tried adding my Feedly account, but that fails with "Could not connect: Connection refused", so instead I tried just going with a local RSS account, but that also fails with infinite loading and the following terminal output:
```
[ DEBUG ] serviceSelected: Local RSS
[ DEBUG ] load icon /tmp/http:__planet_gnome_org_atom_xml.ico
[ DEBUG ] load icon /tmp/http:__blog_elementary_io_rss.ico
[ DEBUG ] load icon /tmp/https:__feeds_feedburner_com_d0od.ico
[ DEBUG ] load icon /tmp/http:__rss_golem_de_rss_php?feed=ATOM1_0.ico
[ DEBUG ] load icon /tmp/http:__www_heise_de_newsticker_heise-atom_xml.ico
[ DEBUG ] load icon /tmp/http:__rss_sueddeutsche_de_rss_Topthemen.ico
[ DEBUG ] load icon /tmp/http:__planetkde_org_rss20_xml.ico
[ DEBUG ] load icon /tmp/http:__www_phoronix_com_rss_php.ico
[ DEBUG ] load icon /tmp/http:__rss_nytimes_com_services_xml_rss_nyt_HomePage_xml.ico
[ DEBUG ] load icon /tmp/http:__feeds_bbci_co_uk_news_rss_xml.ico
[ DEBUG ] load icon /tmp/http:__feed_cnet_com_feed_topics_tech-industry.ico
[ DEBUG ] load icon /tmp/http:__feeds_gawker_com_lifehacker_full.ico
[ DEBUG ] load icon /tmp/http:__feeds_arstechnica_com_arstechnica_index?format=xml.ico
[ DEBUG ] write login data
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_NO_BACKEND
[ DEBUG ] MainWindow: show error bar - errorCode = 9
[ DEBUG ] MainWindow: show error bar
```

Trying Feedly also gave me "FEED_READER_LOGIN_RESPONSE_NO_BACKEND", so I'm thinking this is the culprit.

**Comment by jangernert** [comment]
This is the log of the UI. This only tells half of the story. FeedReader consists of the UI and a separate daemon process (feedreader-daemon). The log of the daemon would help to investigate this further.
But reading the other bug you filed I think the plugins can't be loaded.
To add a new back-end both the UI and the daemon need to be extended by a plugin. It seems like the UI-plugins could finally be located on your machine, but the daemon can't find the corresponding plugin.

**Comment by Cybolic** [comment]
Aha, I didn't realise there were two processes! Killing the FeedReader daemon (which I assume was left over from the previous installation) and starting the program again fixed the issue.
Thanks for help!
