### ISSUE TITLE
Infinite Update Feeds Spinner

### ISSUE THREAD

**Issue by kefkf** [jangernert/FeedReader#378]
When I try to update feeds, the spinner runs indefinitely and new articles stop appearing. The update popup when I click on the spinning button gets stuck at "Grabbing full content: x/y" the whole time. 

If I unsubscribe from one of my feeds mentioned in the daemon.log file (sallysbakingaddiction.com) and restart the application, the update feeds function works as expected.

I'm using archlinux and the feedreader-git package from AUR.
Logs: https://gist.github.com/kefkf/c6d96ea8815a2cb8d84ebf8b01a4696a

**Comment by jangernert** [comment]
Can you post the log of the daemon as it is trying to get the articles from said feed?

**Comment by kefkf** [comment]
This log is just me starting the app and clicking update feeds. It gets stuck at "grabbing full content: 1 / 4 ". I copied the daemon.log while the app was still running.

https://gist.github.com/kefkf/f04b6b265a87d0d1c7ce48a32a7dfced

**Comment by jangernert** [comment]
Pinterest, not only does it annoy the hell out of me when I google for images. Now it also causes bugs FeedReader...
I will try to reproduce it here on my end and see how I can fix it.

**Comment by jangernert** [comment]
Fixed.
Missing "http:" in front of the "//pinterest..." causes the Soup.Message to be NULL and to crash the daemon.

**Comment by jangernert** [comment]
@kefkf 
Btw: if you want to get the full recipes directly in FeedReader you can create a little text-file for the ContentGrabber. I use the same config files as fivefilters/ftr-site-config. If you want to, you can look into it and create a config for a few of your subscribed feeds. And since lots of projects use these config files all users will benefit from it.
https://github.com/fivefilters/ftr-site-config
http://help.fivefilters.org/customer/en/portal/articles/223153-site-patterns

**Comment by kefkf** [comment]
@jangernert I mostly use feedreader to open stuff in firefox because I don't like how fonts look in chromium (which is what I assume feedreader uses for the reading pane) so I'm not really fussed about getting full content in feedreader but I have been using fivefilters' push to kindle service to send .epub files to my reader for a while now and I had not realized that their recipes were open source.

I will definitely take look at these to see if I can improve the sites I frequently use, thanks for letting me know!

**Comment by jangernert** [comment]
FeedReader uses webkitgtk. Fonts look fine though to me since 'fedy' configured them for me on fedora.
@bil-elmoussaoui is working on making fonts configurable for articles #313
