### ISSUE TITLE
Time Stamp in articles list view

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#38]
![Image of Article](https://cloud.githubusercontent.com/assets/949292/12536846/12d735e6-c2d7-11e5-842e-a49249df6157.png)

**Comment by bil-elmoussaoui** [comment]
Can you add more informations to this?; do you want to show the timestamp or to hide it ?

**Comment by kanishkablack** [comment]
To display a time stamp, where is the article published
![screenshot from 2016-01-25 13-48-10](https://cloud.githubusercontent.com/assets/949292/12545666/5465109e-c36a-11e5-94a6-5dcf93d2acf4.png)

**Comment by jangernert** [comment]
did a first draft in master branch

**Comment by kanishkablack** [comment]
![screenshot from 2016-01-27 08-41-28](https://cloud.githubusercontent.com/assets/949292/12602739/cd687478-c4d1-11e5-9b0f-1728a2d60239.png)

i am not sure, i think there is an issue
