### ISSUE TITLE
Only 15 entries shown per feed in version 2.0

### ISSUE THREAD

**Issue by chrbayer** [jangernert/FeedReader#380]
Since version 2.0 only 15 entries per feed are displayed, even if many more are available.
In Version 1.6.x it was working as expected.

**Comment by jangernert** [comment]
So you post about 0 information and expect me to magically know what is not working for you? What back-end? Logs for the daemon during sync? Logs of the UI? So on, so on...

**Comment by chrbayer** [comment]
Sorry for the missing information... I was not sure if this behavior was intentional, because in my configuration it always behaves like that.

I'm using the Tiny Tiny RSS back-end, my system is an up-todate ARCH Linux.

It seems to me an UI problem, because all entries are shown as available, there are only not displayed...

I found the UI logfile, removed the old one and made a minimal use case for the problem to occur: In three feeds there are new entries, display is set to all entries, started FeedRunner. In the first two feeds I was able to scroll past the boundary, the third did not extend when trying to scroll past the end. I have attached the ui.log file for this test.

Thank you very much in advance!


[ui.log.txt](https://github.com/jangernert/FeedReader/files/778488/ui.log.txt)

**Comment by jangernert** [comment]
Okay, so for the 3rd feed the loadmore-function is not triggered even though the scrolledwindow is all the way at the bottom.
Is it always the same feed that behaves like this, or always the third one you click? Or maybe if you scroll down really fast? Any kind of pattern here?
I did some things that might or might not fix your issue. Is it possible for you to build master branch and test on your machine?

**Comment by chrbayer** [comment]
It seems always to be the third feed selected and scrolled, regardless in which order I try to scroll.
I managed to build the git version and it shows the same behaviour...

**Comment by jangernert** [comment]
Okay, I'll add some more debug prints to the code as soon as I get home. Maybe then we can get to the bottom of this.

**Comment by chrbayer** [comment]
Thank you very much! As soon as something is available I will run it on my machine!

**Comment by jangernert** [comment]
I added debug-prints every time I disconnect and connect the "srolledBottom"-signal. Maybe that will help to figure out when something goes wrong on your end.

**Comment by chrbayer** [comment]
Looks like the scrolledBottom-signal is not connected in third feed... The ui.log file is attached:

[ui.log.txt](https://github.com/jangernert/FeedReader/files/782806/ui.log.txt)

**Comment by jangernert** [comment]
Okay, next try please :)

**Comment by chrbayer** [comment]
Hey, how it is working again, thanks! Do you still need a log?

**Comment by jangernert** [comment]
No, if it's working we can close this issue.

**Comment by chrbayer** [comment]
Oh no, did some more testing, only working half... Now each second scrolling attempt is working... I post a log...

**Comment by chrbayer** [comment]
The first two working, then not working, working, ... regardless of the feed...

[ui.log.txt](https://github.com/jangernert/FeedReader/files/783762/ui.log.txt)

**Comment by jangernert** [comment]
Are you by any chance switching and then scrolling insanely fast? The scrolledBottom singal is only connected after the new list has completed loading again.
Does scrolling up and then down again work?

**Comment by chrbayer** [comment]
Every second scrolling attempt it works completely without issue.
Maybe the fast scrolling shows up because I have imwheel running to accelerate the scrolling speed by a factor of three. So there are three events send at once as far as I understand imwheel. I will try with the tool disabled...

**Comment by chrbayer** [comment]
After imwheel has been stopped, the problem is completely gone...

By the way, in the last git release, the "Do you want to change your account screen" appears shortly before the main screen is shown...

**Comment by jangernert** [comment]
Nothing changed regarding this in master.

Can you try again with latest code?

**Comment by chrbayer** [comment]
The strange display of the change screen does not show up any more and the scrolling finally seems to be perfect even if imwheel is running! Thank you very much!!!

Nevertheless, here is the log: 
[ui.log.txt](https://github.com/jangernert/FeedReader/files/783978/ui.log.txt)

**Comment by jangernert** [comment]
Just to be sure it does not happen again I set the transition-time of the first transition to 0 ... so hopefully you should never see the wrong page initially again.
