### ISSUE TITLE
Webview crashes

### ISSUE THREAD

**Issue by psukys** [jangernert/FeedReader#382]
When trying to view any blog post, it doesn't not get displayed. Output display an error that webview crashed.
Distribution: Fedora 25
Package: installed through default *dnf* method

**Comment by jangernert** [comment]
What WebKit version?

**Comment by jangernert** [comment]
Just checked: Fedora is still on version 2.14.3 of webkitgtk ... you'll have to wait for version 2.14.4 with a critical bug-fix.
#327
