### ISSUE TITLE
UI improvement: Allow going thru multiple feeds with Cursor key

### ISSUE THREAD

**Issue by chrbayer** [jangernert/FeedReader#384]
Here is another proposal for an UI and usability improvement:

Pressing "Cursor Up" at the top a feed select the last item of the feed prior to the current feed.

It is very handy especially in display Unread mode to select the last unread item of the last feed and than go with "Cursor Up" presses thru all unread items regardless in which feeds they are. In the current implementation I have to use the mouse every time I got to the top of a feed and select a new feed in which I use the "Cursor Up" Key to go thru the items.

**Comment by jangernert** [comment]
Not exactly what you had in mind, but serves the same purpose:
control+j/k will select the next/previous item in the feed list. So if you want get to the next feed just hit ctrl with your pinky and continue with j/k ;)
