### ISSUE TITLE
Update Flatpak to 2.0.1

### ISSUE THREAD

**Issue by jangernert** [jangernert/FeedReader#386]
Not sure if you manually have to update your flatpak repo.
All the commits are in the stable branch now. Does your build-environment automatically build every new commit in the stable branch?

**Comment by jscurtu** [comment]
Thats the plan and what I am working on, it will in the near future automate on every commit.. 

I am syncing the flatpak repo now, will be online soon

**Comment by jangernert** [comment]
Cool, just close this ticket once 2.0.1 is up :)

**Comment by jscurtu** [comment]
done
