### ISSUE TITLE
Should flatpak add menu / desktop icons?

### ISSUE THREAD

**Issue by peteruithoven** [jangernert/FeedReader#387]
I'm running Elementary OS Loki (which is based on Ubuntu 16.04) and just installed FeedReader through Flatpak. Great that that works so easilly!
I can  run it by running `flatpak run org.gnome.FeedReader`, but there is no icon in my menu? (Which is [Slingshot](https://bugs.launchpad.net/slingshot) in the case of Elementary OS). Is that normal for flatpak?

**Comment by jscurtu** [comment]
no realy.. did you try to relogon (logoff/logon)?

**Comment by jscurtu** [comment]
FYI v2.0.1 just was synced to the repo.. you can update by just doing this in the commandline:
flatpak update

**Comment by jangernert** [comment]
as far as I know the desktop-file should be in $HOME/.local/share/flatpak/exports/share/applications/

**Comment by jscurtu** [comment]
@jangernert yea, your right.. 

this might help:
http://elementaryos.stackexchange.com/questions/10752/any-way-to-include-flatpak-desktop-files-to-the-ones-scanned-by-the-application

**Comment by peteruithoven** [comment]
Awesome! After that update the icon appeared. 

(I didn't re-login btw)

**Comment by jscurtu** [comment]
fantastic, I am glad everything works as expected.
