### ISSUE TITLE
Commit 0eae996 causes compilation to fail on Ubuntu 16.10

### ISSUE THREAD

**Issue by georgelemental** [jangernert/FeedReader#390]
Commit 0eae9966b99759726fcee2abb3f70d604e254514 causes compilation to fail on Ubuntu 16. 10 with these errors: 

`/home/jules/FeedReader/src/Widgets/BackendInfoPopover.vala:154.4-154.25: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
			Gtk.show_uri_on_window(MainWindow.get_default(), m_ext.getWebsite(), Gdk.CURRENT_TIME);
			^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/ArticleRow.vala:339.4-339.25: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
			Gtk.show_uri_on_window(MainWindow.get_default(), m_article.getURL(), Gdk.CURRENT_TIME);
			^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/ArticleList/ArticleList.vala:755.4-755.25: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
			Gtk.show_uri_on_window(MainWindow.get_default(), selectedURL, Gdk.CURRENT_TIME);
			^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/ArticleView.vala:752.21-752.30: warning: Gtk.Action has been deprecated since 3.10. Use GLib.Action
/home/jules/FeedReader/src/Widgets/ArticleView.vala:975.6-975.27: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
					Gtk.show_uri_on_window(MainWindow.get_default(), url, Gdk.CURRENT_TIME);
					^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/MainWindow.vala:68.5-68.26: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
				Gtk.show_uri_on_window(this, "https://github.com/jangernert/FeedReader/issues", Gdk.CURRENT_TIME);
				^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/MainWindow.vala:80.5-80.26: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
				Gtk.show_uri_on_window(this, "https://www.bountysource.com/teams/jangernert-feedreader/issues", Gdk.CURRENT_TIME);
				^^^^^^^^^^^^^^^^^^^^^^
/home/jules/FeedReader/src/Widgets/ImagePopup.vala:190.6-190.27: error: The name 'show_uri_on_window' does not exist in the context of 'Gtk'
					Gtk.show_uri_on_window(MainWindow.get_default(), url, Gdk.CURRENT_TIME);
					^^^^^^^^^^^^^^^^^^^^^^
CMakeFiles/feedreader.dir/build.make:331: recipe for target 'feedreader_valac.stamp' failed
make[2]: *** [feedreader_valac.stamp] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/feedreader.dir/all' failed
make[1]: *** [CMakeFiles/feedreader.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

Undoing the changes fixes the issue.

**Comment by jangernert** [comment]
Then I guess the Gtk+ version on Ubuntu is too old (again). The changes are needed for the flatpak package. Can't move forward and keep compatibility with all the old stuff.
I suggest either applying your patch locally or running the flatpak package.

**Comment by jscurtu** [comment]
I thought this might happen.. 
Flatpak on the other side helps us do these changes without breaking distribution. 
So this brings us to minimum Gtk 3.22.

I think its awesome that even elementaryOS with a 16.04 base can run FeedReader 2.0.1 .
