### ISSUE TITLE
[Flatpak] Webkit has crashed

### ISSUE THREAD

**Issue by alex285** [jangernert/FeedReader#391]
It was working yesterday, but today without changing anything I can always reproduced
Arch Linux, updated GNOME 3.22 runtime

![crashed-feedreader](https://cloud.githubusercontent.com/assets/11244308/23136538/e1fe8082-f7a5-11e6-9aa5-ba9285b2951e.png)

 flatpak run org.gnome.FeedReader
 
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.1
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] MainWindow: determining state
[ DEBUG ] MainWindow: load content
[ DEBUG ] Opening Database: /home/alex/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 1
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed feed/http://www.theverge.com/rss/full.xml
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList
[ DEBUG ] HeaderBar: setButtonsSensitive true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleView.setBackgroundColor()
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: disallow signals from scroll
[ DEBUG ] ArticleList: new-rows 0
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feed/http://www.theverge.com/rss/full.xml" AND unread = 9  ORDER BY rowid COLLATE NOCASE DESC LIMIT 12 OFFSET 0
[ DEBUG ] actual articles loaded: 12
[ DEBUG ] ArticleList: switch to list2
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 0
[ DEBUG ] ArticleList: allow signals from scroll
[ DEBUG ] ArticleView: load article PSNTZO8gXFUe+cpCZyApw0vEKWPT4b14D6teBEocIAE=_15a5b700523:ea26a1e:c9473c70
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] dbBase.read_article(): PSNTZO8gXFUe+cpCZyApw0vEKWPT4b14D6teBEocIAE=_15a5b700523:ea26a1e:c9473c70
[ DEBUG ] ContentPage: set headerbar
[ DEBUG ] DBusConnection: updateFeedList
[ DEBUG ] ArticleView: WebView load html
[ DEBUG ] ArticleView: empty -> view1
[ ERROR ] dbErrorLog: 21: misuse at line 128341 of [2ef4f3a5b1]
[ DEBUG ] Opening Database: /home/alex/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db
[ DEBUG ] ArticleView: loading 10 %
[ INFO  ] ArticleView: webextension-message: on_page_created
[ DEBUG ] ArticleView: Policy decision
[ DEBUG ] WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION
[ DEBUG ] ArticleView: load STARTED
[ DEBUG ] ArticleView: load COMMITTED
[ DEBUG ] ArticleView: Policy decision
[ DEBUG ] WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION
[ INFO  ] ArticleView: webextension-message: onDocLoaded
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:16): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 193 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[ ERROR ] ArticleView: webview crashed

**Comment by bil-elmoussaoui** [comment]
@jscurtu  any idea? i don't think that's related to the latest bug on WebKit

**Comment by jscurtu** [comment]
Well, it might .. depens on what WebKit version the runtime ships, it is nvidias.. ill check

**Comment by alex285** [comment]
@jscurtu A correction. When I said yesterday it was working, but today not, without changing anything, I wasn't complete honest :/

I figure out how I can reproduce. It is working fine on Wayland but it crashes with X. Notice I use GNOME 3.24 with KMS enabled, so I run Wayland with NVIDIA proprietary drivers

**Comment by alex285** [comment]
Perhaps something with portals?

**Comment by jp7677** [comment]
I'm seeing the same crash on a standard Fedora 25 installation (x11 with proprietary nvidia driver).
I had tested the latest master from yesterday and the 2.0.1 tag, both compiled from source.

**Comment by jp7677** [comment]
PS: I don't see any libgl errors in my logs when starting feedreader on the console. just a `[ ERROR ] ArticleView: webview crashed`, nothing else that hints to an issue.

**Comment by jangernert** [comment]
Fedora still ships version 2.14.3. You have to wait for the bugfix that was shipped in 2.14.4.
Looking at the package updates, it seems they ditched 2.14.4 completely and are moving to 2.14.5 right away. That's why it is taking a bit longer.

**Comment by jp7677** [comment]
ah ok, thanks for the info.

**Comment by jangernert** [comment]
This is the original bug-report btw: #327

**Comment by jangernert** [comment]
Oh didn't see the reporter is using arch. What version of webkitgtk are you using @alex285 ?

**Comment by jscurtu** [comment]
@jangernert 

In this case it is the Webkit version in the runtime, if this is up to date: http://flatpak.org/runtimes.html then 3.22 comes with webkitgtk4 2.14.2 .

It dont mater what the host has, it is the runtime it uses.. 

@alex285 I suggest you try this:
install org.gnome.Platform//master (unstable)
then run it:
flatpak run --runtime-version=master org.gnome.FeedReader

**Comment by jangernert** [comment]
Oh this is the flatpak? Things are getting confusing :D 
I added a simple print of the webkit-version to make it easier next time d6d0f7cb82630893571fc319e02505e46e34cdb1

**Comment by jangernert** [comment]
pushed

slightly off-topic: @jscurtu do you know how gnome will handle updates to their runtimes? Will there be updates to older runtimes with bugfixes like this one?

**Comment by jscurtu** [comment]
Usualy yes, there are runtime updates.. Thats like one of the selling points of flatpak, with runtimes you woulndt have to live with the bug.

I will open a bug on flatpak.

**Comment by alex285** [comment]
@jscurtu luckily I had nightly already installed, but I didnt know you could change runtimes just like that! Cool!
and yes that fixed it too! Thank you!

**Comment by jscurtu** [comment]
@aswome that was expected :-)

**Comment by jscurtu** [comment]
new update will be up soon:
![grafik](https://cloud.githubusercontent.com/assets/590307/23140857/2ed29ed0-f7b4-11e6-9733-a5e44db50f16.png)

**Comment by jscurtu** [comment]
looks like WebKitGtk will be updated in the runtime very soon..
It now has been bumped to 2.14.5 

https://github.com/GNOME/gnome-sdk-images/commit/7da866a58b1e889f736a9e05921bc0cf75d213ab

cc: @alex285

**Comment by alex285** [comment]
@jscurtu to me is solved now as I run it on 324 anyway :)

**Comment by glaere** [comment]
I might have a related problem. With some articles it crashes and I need a program shutdown. It says Webkit has crashed in the article section.
I can use it for some articles.
I think it’s crashing because of embedded video links but works with images.

Flatpak 0.99.3
webkit webkit2gtk-4.0-37
Ubuntu 18.04.1
xorg
nvidia 390 (prop)
Gnome Shell 3.28.2

ui.log:

[ DEBUG ] ArticleView: loading 50 %
[ DEBUG ] ArticleView: loading 100 %
[ DEBUG ] ArticleView: load FINISHED
[ INFO  ] ArticleView: webextension-message: recalculate
[ ERROR ] ArticleView: webview crashed
[ DEBUG ] Running WebKit 2.14.7
[ DEBUG ] ArticleView: loading 0 %
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0.000000
[ DEBUG ] offset 0
[ DEBUG ] Shutdown!

daemon.log:

[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ ERROR ] Utils.copyAutostart: Error when getting information for file '/app/share/FeedReader/feedreader-autostart.desktop': No such file or directory
[ INFO  ] FeedReader Daemon 2.0.2
[ DEBUG ] Opening Database: /home/homeuser/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db
[ ERROR ] dbErrorLog: 283: recovered 3010 frames from WAL file /home/homeuser/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db-wal
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "feedly"

Thanks for your time.
