### ISSUE TITLE
All/Unread Bug in Title bar

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#40]
I am not sure is it implemented by design or a bug

categories are not being displayed (after activating the show only unread option)

![screenshot from 2016-01-27 11-13-34](https://cloud.githubusercontent.com/assets/949292/12605093/6c499544-c4e7-11e5-88cc-c9cec7ca9313.png)

![screenshot from 2016-01-27 11-13-45](https://cloud.githubusercontent.com/assets/949292/12605094/6e27fd06-c4e7-11e5-8a33-df3c34eef926.png)

update:  Option unread is activated 
![screenshot from 2016-01-27 11-18-39](https://cloud.githubusercontent.com/assets/949292/12605122/bec1af78-c4e7-11e5-8e69-029205b9c3d2.png)

**Comment by jangernert** [comment]
Nope, that's a feature. Only categories that contain feeds with unread articles are shown.
