### ISSUE TITLE
Gnome 3.22 Required Dependency

### ISSUE THREAD

**Issue by bslezak** [jangernert/FeedReader#400]
Hi, I just tried installing on Ubuntu 16.04.2 using instructions found here: https://jangernert.github.io/FeedReader/ using flatpak. The installer, as I'm reading it, says that Gnome 3.22 is required. (see below) The [latest version of UbuntuGnome](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes/UbuntuGNOME) that is available as of this writing is 3.18. You can imagine how I don't want to force-feed my system Gnome 3.22 in order to run FeedReader. ;) I just wanted to see if Gnome 3.22 really was required, or if this is in error. I would be disappointed to wait for 3.22 to drop only to find 3.26 is required. Thanks!

```
flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref

Installing: org.gnome.FeedReader/x86_64/stable
Required runtime for org.gnome.FeedReader/x86_64/stable (org.gnome.Platform/x86_64/3.22) is not installed, searching...
Found in remote gnome, do you want to install it? [y/n]: n
error: The Application org.gnome.FeedReader/x86_64/stable requires the runtime org.gnome.Platform/x86_64/3.22 which is not installed
```

**Comment by jscurtu** [comment]
It wants to install the runtime.. thats ok and needed for flatpak apps.. 
Your fine to continue, it should work ;-)
