### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Nemial** [jangernert/FeedReader#404]
When building this error "Package `goa-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories", although the package is installed . Can we fix it or is it a problem I have?

**Comment by jangernert** [comment]
Your goa package needs to be compiled with vala-bindings.

**Comment by bil-elmoussaoui** [comment]
@Nemial What distro are you using ?

**Comment by Nemial** [comment]
@jangernert  Thank you. I've reassembled the package vala-bindings.
