### ISSUE TITLE
[master][FeedHQ] Testmatrix & Issues 

### ISSUE THREAD

**Issue by jscurtu** [jangernert/FeedReader#407]
+ Logon works as expected.

1. <del>[failed/partial] On first run and fresh account, cannot add FeedUrl from FeedReadert, If I add one from the web browser, it works and syncs. -> then I can also add feedUrl within FeedReader to new cat.</del>
2. <del>[failed] Rename categories does not work from FeedReader.</del>
3. [failed] Import OPML file from FeedReader dont work.
4. <del>[works] Create new category in web interface then move feeds with feedreader to new cat. works.</del>
5. <del>[failed] engaget feeds no preview. : No Text available for this article. (works in feedly)</del>
6. <del>[works] Rename feed in sidebar from feedreader works (after sync).</del>
7. <del>[works] Delete feed in sidebar from feedreader works (after sync).</del>
8. <del>[works] Add FeedUrl from feedreader to existing cat. works.</del>
9. <del>[partial] All news in list show title and underneath "No Preview Available" </del>
10. <del> [failed] Add new category by feed drag and drop works first, cannot change the name "New Category" in the TextField but after drop is finished, it seems to have worked. then renamed. Push sync. Does not work. Back to previous state.</del>
11. <del>[failed/partial] Import OPML in webinterface-> wait till grabber is done-> most of the feeds: ArticleView no preview.</del>

![bildschirmfoto vom 2017-02-25 11-39-25](https://cloud.githubusercontent.com/assets/590307/23330490/42f6a9bc-fb4f-11e6-96ea-76c279195129.png)

![bildschirmfoto vom 2017-02-25 12-21-12](https://cloud.githubusercontent.com/assets/590307/23330704/03f2d460-fb55-11e6-9538-abc666892790.png)

**UI / Daemon LOGS** : [logs.zip](https://github.com/jangernert/FeedReader/files/801133/logs.zip)

**Comment by jangernert** [comment]
the feedhq API does not provide any form of text for its items, so if the grabber is not able to get the content for you, FeedReader doesn't have anything to display.

**Comment by jangernert** [comment]
> 10. [failed] Add new category by feed drag and drop works first, cannot change the name "New Category" in the TextField but after drop is finished, it seems to have worked. then renamed. Push sync. Does not work. Back to previous state.

Was this on wayland? Not being able to focus the popover should have nothing to do with the back-end. I noticed this behaviour as well on wayland. I was able to focus the popover in the end. I just had to move the mouse around a little bit (way up) where I found some sort of invisible hitbox I could click to focus the entry in the popover :D

**Comment by jangernert** [comment]
> [failed/partial] On first run and fresh account, cannot add FeedUrl from FeedReadert, If I add one from the web browser, it works and syncs. -> then I can also add feedUrl within FeedReader to new cat.

Fixed! Commit will come soon.

**Comment by jangernert** [comment]
I think I got everything. Can you please test again (as long as the demo-account is still valid :D)?

**Comment by jscurtu** [comment]
sure, I will look at it tonight..

**Comment by jscurtu** [comment]
> Was this on wayland? Not being able to focus the popover should have nothing to do with the back-end. I noticed this behaviour as well on wayland. I was able to focus the popover in the end. I just had to move the mouse around a little bit (way up) where I found some sort of invisible hitbox I could click to focus the entry in the popover :D

It was on wayland yes, but I think there is a misunderstanding.
In the left panel, where all feeds are listed and categorized.
Select one feed and start dragging, a "new category" categorie will show and you can drag it there..

**Comment by jangernert** [comment]
Yes, and if you drop the feed on the new category a popup will pop up (:D) where you can enter the name of the new category. And somehow you couldn't focus the entry of that popup, right?

**Comment by jscurtu** [comment]
Oh yea.. :-) all that works and it seems successful. But when I push sync then the new category and changes are gone.

**Comment by jangernert** [comment]
Oh, okay. With the version you tested 2 days ago or does the problem still persist with the current code?

**Comment by jscurtu** [comment]
That i will test tonight

**Comment by jscurtu** [comment]
Sorry, will have this tested for sure by latest tonight.. Unfortunatly yesterday I kinda got distracted from RocketLeague and The Walking Dead. :-)

**Comment by jscurtu** [comment]
tested with a fresh account, all works except for the import OPML from FeedReader.
