### ISSUE TITLE
Program in startup application by default, without option to change this behaviour

### ISSUE THREAD

**Issue by medeotl** [jangernert/FeedReader#408]
I personally think that start at boot option shouldn't be set on by default, and I don't understand why there's no way to disable this behaviour (I've done it via gnome tweaks)

Tested in fedora 25, feedreader 2.0.1

**Comment by bil-elmoussaoui** [comment]
@medeotl There's no way to enable/disable this as this should be done by your system...Not by the application itself. We don't have to overcomplicate things
