### ISSUE TITLE
Arictle source URL Copy to Clipboard

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#41]
Article source URL Copy to Clipboard

Probably the silliest ideal feature request

**Comment by jangernert** [comment]
You can always open the article in the browser. Then you'll have the URL right in front of you...

**Comment by TamasBarta** [comment]
This is actually a pretty good idea. In apps that have such feature I never open the browser. For example in Minitube. Opening a browser is actually sometimes a pretty expensive operation, so I'm sure it would be much appreciated.

**Comment by kanishkablack** [comment]
this feature is already implemented

**Comment by TamasBarta** [comment]
OK, sorry then, I just couldn't find it yet.

**Comment by kanishkablack** [comment]
just got to title of article, right click on title
