### ISSUE TITLE
undefined reference to `N_'

### ISSUE THREAD

**Issue by petefwalter** [jangernert/FeedReader#410]
I'm getting the following error when building feedreader for rawhide:

```
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `feed_reader_media_player_toggleMute':
/builddir/build/BUILD/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:399: undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `_feed_reader_media_player_toggleMute_gtk_button_clicked':
MediaPlayer.c:(.text+0xc3): undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `_feed_reader_media_player_togglePause_gtk_button_clicked':
MediaPlayer.c:(.text+0xca7): undefined reference to `N_'
MediaPlayer.c:(.text+0xd33): undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `___lambda58__gasync_ready_callback':
MediaPlayer.c:(.text+0x1bc0): undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o:MediaPlayer.c:(.text+0x1cfd): more undefined references to `N_' follow
collect2: error: ld returned 1 exit status
```

It builds just fine on Fedora 25 though. Not sure what has changed. Perhaps different vala version plays a role? F25 has vala 0.34.4 while rawhide has vala 0.35.6.

Full build logs at https://koji.fedoraproject.org/koji/taskinfo?taskID=18092312

**Comment by bil-elmoussaoui** [comment]
I just tried to upgrade to  the latest Vala version on Archlinux 0.35.5 and i can reproduce it too

**Comment by jangernert** [comment]
If I remove the N_, I get the same error on Fedora 25: `undefined reference to `_'`
So not sure what to do here. One way works for the old vala the other works for the new vala version.
Only solution I can imagine is to not make these strings translatable.

**Comment by bil-elmoussaoui** [comment]
Or maybe dropping support for older versions of Vala?

**Comment by jangernert** [comment]
I don't think it's smart to drop support for the version of the programming language the main developer is using :P

**Comment by bil-elmoussaoui** [comment]
@jangernert  Lol :P i will ask on IIRC and see if there's something else that can be done

**Comment by jangernert** [comment]
Don't translate these strings. It's just some tooltips for buttons like "play" and "pause"
Not really important to have them localized imo

**Comment by bil-elmoussaoui** [comment]
Well, in that case i will remove the tooltips ;) as everyone knows what a play button does!

**Comment by jtojnar** [comment]
What about screen readers? Would it be possible to translate the tooltips at the [point of use](https://github.com/jangernert/FeedReader/blob/master/src/Widgets/MediaPlayer.vala#L212)?
