### ISSUE TITLE
Shortcuts stop working after first reboot on Ubuntu

### ISSUE THREAD

**Issue by Pavel-Brilliant** [jangernert/FeedReader#417]
All the keyboard shortcuts stop working after the reboot on Ubuntu on both versions - the latest one (installed via flatpak) and the old one (installed via apt-get from the launchpad)

Ubuntu 16.04.

**Comment by bil-elmoussaoui** [comment]
@Pavel-Brilliant Do you have any output on the terminal?

**Comment by Pavel-Brilliant** [comment]
$ flatpak run org.gnome.FeedReader                         
Gtk-Message: Failed to load module "unity-gtk-module"
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
Gtk-Message: Failed to load module "unity-gtk-module"
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: determining state
[ DEBUG ] MainWindow: load content
[ DEBUG ] Opening Database: /home/pb/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 2
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList
[ DEBUG ] HeaderBar: setButtonsSensitive true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleView.setBackgroundColor()
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: disallow signals from scroll
[ DEBUG ] ArticleList: new-rows 0
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE unread = 9  ORDER BY rowid COLLATE NOCASE DESC LIMIT 12 OFFSET 0
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] actual articles loaded: 12
[ DEBUG ] ArticleList: switch to list2
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 0
[ DEBUG ] ArticleList: allow signals from scroll

This is the terminal output of FeedReeder run from terminal via flatpak.
No shortcuts used after launch (ex. J, K, ...) pass any output to the terminal.

**Comment by Pavel-Brilliant** [comment]
Maybe it will be useful.

`$ sudo apt-cache policy unity-gtk3-module 
unity-gtk3-module:
  Installed: 0.0.0+15.04.20150118-0ubuntu2
  Candidate: 0.0.0+15.04.20150118-0ubuntu2
  Version table:
 *** 0.0.0+15.04.20150118-0ubuntu2 500
        500 http://ua.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
`

**Comment by bil-elmoussaoui** [comment]
@Pavel-Brilliant The issue about unity-gtk-module has nothing to do with this issue...Anyway, i don't see any reason why those shortcuts won't work? 
@jangernert Do you have any idea?

**Comment by jangernert** [comment]
Nope, no clue :P

**Comment by bil-elmoussaoui** [comment]
@Pavel-Brilliant I'm working right now on this #418 should be on master in two days at max! once, it's ready, maybe trying to change them will help you fix it ? 
You can already do that using DConf...
Do you have this  issue with any other application?

**Comment by Pavel-Brilliant** [comment]
@bil-elmoussaoui ok, I will wait for the new version, thanks. Will it be automatically updated via flatpak or I need to update it manually? 
Other applications are OK. I'm committed to using shortcuts everywhere it is possible, so I would have noticed the issues with other apps.

**Comment by jscurtu** [comment]
@Pavel-Brilliant The flatpak will for sure get updated if the fix gets pushed to stable.. The repo also contains a master branch too, but It dont get updated that often and is used for testing development and could contain broken code..

**Comment by thiswillbeyourgithub** [comment]
Hi, none of the keyboard events that don't use `ctrl` work on my ubuntu 16.04 (macbook pro)

The debug stream (when running feedreader from a terminal) doesn't show anything more when I type on the letters, just nothing is happening. The shortcuts that don't work are : `J K R M O S` as well as `ctrl +/-,` at least. The others seem to be working fine.

I'm new to github so I'm hoping I don't disturb the normal process of reporting issues by doing it this way :)

Tell me if I can add any logs or anything else

Thanks !

**Comment by bil-elmoussaoui** [comment]
@thiswillbeyourgithub You can change the shortcuts to whatever you want using DConf. Just navigate to `org.gnome.feedreader.keybindings` and set new shortcuts, kill the UI using `pkill feedreader` and reopen it again! It might help (or not). I don't use Ubuntu, and i don't see what those shortcuts won't work....

**Comment by thiswillbeyourgithub** [comment]
Well thank you for trying but looking for `feedreader` using `dconf` and even `gesettings list-schemas` shows no such option.

In `dconf` I have : `Feedreader` as a category and `feedly` and `saved-state` as subcategories but nothing related to keyboard or keybindings.

It looks like its going to be complicated for you to correct this, so maybe it's not worth it, I don't need them all that much anyway.

**Comment by jangernert** [comment]
Not having a subcategory `keybindings` could actually be what is causing the bug.
Do any of the listed keys in this file work?
https://github.com/jangernert/FeedReader/blob/stable/schemas/org.gnome.feedreader.keybindings.gschema.xml
What also could be helpful is to just launch feedreader from the terminal `flatpak run org.gnome.FeedReader` and press a few shortcuts.
Usually every available shortcut should be listed if you press any key (regarding the search entry isn't focused)
https://github.com/jangernert/FeedReader/blob/stable/src/Widgets/MainWindow.vala#L557

**Comment by thiswillbeyourgithub** [comment]
So, the ones that work are : `ctrl+F1` (although not `F5 `nor `Fn+F5`) and `ctrl+J/K/Q/F`. All the others apparently don't.

When running it in terminal, when pressing ANY key, not just the one that are supposed to be a shortcut, it adds the following lines : 
```
[ DEBUG ] articlelist-prev
[ DEBUG ] articlelist-next
[ DEBUG ] feedlist-prev
[ DEBUG ] feedlist-next
[ DEBUG ] articleview-up
[ DEBUG ] articleview-down
[ DEBUG ] articlelist-toggle-read
[ DEBUG ] articlelist-toggle-marked
[ DEBUG ] articlelist-open-url
[ DEBUG ] feedlist-mark-read
[ DEBUG ] global-sync
[ DEBUG ] articlelist-center-selected
[ DEBUG ] global-search
[ DEBUG ] global-quit
[ DEBUG ] global-help
```

each time I press it.

Also, I don't know much about how flatpak work but doing `locate feedreader |grep xml |grep keybin` returns `/var/lib/flatpak/app/org.gnome.FeedReader/x86_64/stable/a6bb1d69c891e7497b80ef72e5bccc26848a4188f08a493daa340f5fa5d248b9/files/share/glib-2.0/schemas/org.gnome.feedreader.keybindings.gschema.xml` which seem to contain  the same things as the file you linked. Don't know if it's relevant.

**Comment by jangernert** [comment]
That's weird. I don't understand why the ones with the control modifier work when the `org.gnome.FeedReader.keybindings` schema isn't even present on your system. Seems like I have to install a Ubuntu VM at some point -.-

**Comment by thiswillbeyourgithub** [comment]
Well, I don't have THAT much time until next week or so but if I can be of any help (and if you can bear with my noobishness) I would gladly do so :) otherwise I'd say forget it, your app is precfetly usable without it and even pretty darn great :)

**Comment by jangernert** [comment]
You are not the first one to be affected by this bug. I'll put it on the bottom of my to-do list ;)
The scroll thing should be easier to fix. I'll get to that first.

**Comment by jangernert** [comment]
I think I got it fa7eec77cf13fc9f2e5ff337fca0e6bd2bbec9d5

**Comment by Pavel-Brilliant** [comment]
Returned to using the FeedReader after few months. 
Shortcuts for articles list still do not work. 
J, K, R, M.

Please, fix it. It consumes a lot of time to use the FeedReader without this option.

**Comment by psukys** [comment]
This still seems to be the case with 18.04 Ubuntu and 2.8.2 FeedReader

**Comment by stepnjump** [comment]
i am experiencing the same problem.
It started happening to me after i had to delete some cache files in /var/tmp because my /var was getting out of hand. Deleted older flatpak-cache folders... Hope this might help you guys.
