### ISSUE TITLE
Shortcut configuration

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#418]
I'm going to implement a simple setting to add the possibility to modify the default shortcuts. The default ones might not be super handy for all the users, and as we already provide the possiblity to modify them using DConf, a setting widget would be pretty nice :)

Something like what's done by Terminix 
![screenshot from 2017-02-28 15-14-06](https://cloud.githubusercontent.com/assets/7660997/23408520/9b1d160a-fdc8-11e6-8596-aac35d0fd1f4.png)

**Comment by jangernert** [comment]
I did not put the config for the shortcuts into the settings dialogue for a reason.
Imo there is already enough complexity in the settings.

**Comment by bil-elmoussaoui** [comment]
The way, Terminix does that is really a great implementation and shouldn't make stuff complicated at all ;) If you want, i can do the  same thing using Vala, in a different branch and see if it's really makes sense to merge it or it's just overcomplicating stuff

**Comment by jangernert** [comment]
Tbh I'm not a big fan of Terminix as a whole. Tried it and went back to gnome-terminal and pantheon-terminal. I much prefer the elementary approach to settings: sane defaults, keep the settings in the UI to a minimum and have everything else available in gsettings. The settings of FeedReader are already pretty stuffed.
