### ISSUE TITLE
Content grabber not working

### ISSUE THREAD

**Issue by georgelemental** [jangernert/FeedReader#419]
The content grabber is not displaying the full article content from many feeds, like the www.androidpolice.com feed (http://feeds.feedburner.com/AndroidPolice?format=xml) and the www.9to5google.com feed (https://9to5google.com/feed/), even though the online fivefilters demo is able to do so. The grabber does work with some other feeds, though, like the www.omgubuntu.co.uk feed (http://feeds.feedburner.com/d0od?format=xml).

**Comment by jangernert** [comment]
FeedReader only supports one of the 3 ways that fivefilters gets the content, namely the config-files.
Check if there is a file for the sites you just named.

**Comment by georgelemental** [comment]
There is a config file for for one of the sites  (Android Police).

**Comment by jangernert** [comment]
It seems to be outdated since there is no div element with the class 'post_content'.
