### ISSUE TITLE
How to run in background?

### ISSUE THREAD

**Issue by orschiro** [jangernert/FeedReader#420]
Dear @jangernert,

Coming from this https://github.com/jangernert/FeedReader/issues/58 discussion, how do I best run FeedReader in background and receive notifications about new unread items on Ubuntu?

Yours, 

Robert

**Comment by jangernert** [comment]
You don't have to do anything. If you start FeedReader the daemon will be started as well. And as long as the daemon is running in the background you will receive notifications about new articles.

**Comment by orschiro** [comment]
I see. Thanks, Jan!

I guess we only have OSD notification bubbles for now, correct?

Well, a tray icon would be fantastic thought...

**Comment by bil-elmoussaoui** [comment]
@orschiro I don't think that's a great idea to implement tray icon. As it's not needed. And almost every DE is making the tray icons obsolete as it's the old way of doing things

**Comment by orschiro** [comment]
So basically I don't have a persistent and permanent way of seeing whether
I have unread feed items without opening the main app window.

Well, at least it doesn't fit my workflow, I am afraid.

**Comment by bil-elmoussaoui** [comment]
If you're using Unity or Plank, a counter of unread items is shown using libunity. Sadly it's not the case with other applications.

**Comment by orschiro** [comment]
I am using Unity. :-)

Where is this counter? In the launcher sidebar?

**Comment by jangernert** [comment]
Yes, if you pin the launcher to the dock a bubble should appear on top of the icon.
With elementary OS it looks like this:
https://i.redd.it/q6bo1l3zrtjy.png

**Comment by orschiro** [comment]
Thanks!

I will test if this happens on Ubuntu 16.10 as well. :-)

**Comment by orschiro** [comment]
It's not working on Ubuntu 16.10, sadly. :-(

![image](https://cloud.githubusercontent.com/assets/170947/23696702/177a43ae-03e5-11e7-8bdb-86b14a40d620.png)

**Comment by jangernert** [comment]
Which version are you using? As far as I know the flatpak is compiled without this specific feature (dependency on libunity). So to get the feature you would either need a Ubuntu specific package or ppa (there isn't one for Ubuntu) or compile the code yourself enabling the libunity support.

**Comment by orschiro** [comment]
Correct. I use the latest flatpak package mentioned on the website.

Is it possible to provide a specific Ubuntu package either as a deb or ppa?

**Comment by jangernert** [comment]
Yes, it is possible. But appearantly nobody is interested in doing it.

**Comment by jscurtu** [comment]
Hmmm.. let me look if adding that to the flatpak would be possible. @jangernert updateBadge() is all you use right?

**Comment by jangernert** [comment]
Yes

**Comment by jscurtu** [comment]
@orschiro can you please try this attached build / flatpak.. it's compiled with libunity.
There might be more needed, please report back. 

[FeedReader-libunity-test.zip](https://github.com/jangernert/FeedReader/files/827926/FeedReader-libunity-test.zip)


thx.

**Comment by orschiro** [comment]
Thank you so much, Jason!

Is this the right way of updating it?

If so, how do I close and open it again to load the latest version?

I cannot click on Quit in the menu.

orschiro@x230:~/Desktop$ flatpak install
FeedReader-2.0.2-stable-20170308.x86_64.flatpak
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Installing: org.gnome.FeedReader/x86_64/stable from bundle
FeedReader-2.0.2-stable-20170308.x86_64.flatpak

[image: pasted1]

**Comment by jscurtu** [comment]
Kill the deamon with: 

pkill feedreader-deam

Then install the bundle with :

flatpak install --bundle THE-BUNDLE.flatpak

Run with

flatpak run org.gnome.FeedReader

**Comment by orschiro** [comment]
It's not working yet.

Can I help you debug further?

**Comment by jscurtu** [comment]
let me try something, i will post a new package then we can test again.

**Comment by orschiro** [comment]
OK, thanks!

**Comment by jscurtu** [comment]
@orschiro ready to try again? 

[FeedReader.zip](https://github.com/jangernert/FeedReader/files/833308/FeedReader.zip)

Please kill the daemon (i previously misspelled the command):

pkill feedreader-daem

then remove the icon from the launcher. 
then continue with the update process.. 

flatpak install --bundle FeedReader-2.0.2-stable-20170310.x86_64.flatpak

afterwards, re-add the icon to your launcher.

Test..

Thx.

Jason

**Comment by orschiro** [comment]
I really appreciate your effort!

However, they are still not showing in the launcher. :-(

Can I somehow test to make sure that the version loaded is actually the
latest one?

orschiro@x230:~/Desktop$ flatpak install --bundle
FeedReader-2.0.2-stable-20170310.x86_64.flatpak
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Installing: org.gnome.FeedReader/x86_64/stable from bundle
FeedReader-2.0.2-stable-20170310.x86_64.flatpak

[image: pasted1]


On Fri, Mar 10, 2017 at 9:22 AM Jason Scurtu <notifications@github.com>
wrote:

@orschiro <https://github.com/orschiro> ready to try again?

FeedReader.zip
<https://github.com/jangernert/FeedReader/files/833308/FeedReader.zip>

Please kill the daemon (i previously misspelled the command):

pkill feedreader-daem

then remove the icon from the launcher.
then continue with the update process..

flatpak install --bundle FeedReader-2.0.2-stable-20170310.x86_64.flatpak

afterwards, re-add the icon to your launcher.

Test..

Thx.

Jason

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jangernert/FeedReader/issues/420#issuecomment-285606984>,
or mute the thread

**Comment by jscurtu** [comment]
you can uninstall with "flatpak uninstall org.gnome.FeedReader" first before installing the bundle, but I dont think that is necessary as to your logs it is updating.

Now before we jump back and forth, I think I will just install Ubuntu in a VM and play with it.

**Comment by orschiro** [comment]
Yes, maybe that's the better approach.

I just performed the `flatpak uninstall` command prior to installing your
testing version but the launcher icon is still not showing the unread
number.

**Comment by jscurtu** [comment]
thx. basically it is just a dbus call to com.canonical.Unity.LauncherEntry so I dont see a reason not to get it working inside a flatpak container.
Just have to figure out what I am missing ..

**Comment by jangernert** [comment]
@jscurtu you can also install/compile plank on your system to test the unity-support
You can check if the plank process supplies the com.canonical.Unity dbus-server.
Regarding FeedReader, if libunity is detected and used you will see this line during cmake
```
-- libunity: ON
```
Plank with badges is working on my fedora box

**Comment by jscurtu** [comment]
@jangernert true... thx, that will work :-)
