### ISSUE TITLE
Support for vim style navigation shortcuts 

### ISSUE THREAD

**Issue by petruavram** [jangernert/FeedReader#421]
Other RSS clients on different platforms that I used support vim style navigation for articles. It would be nice if support for this was added and it would work independent of what pane is focused (preview or list).

**Comment by jangernert** [comment]
Shortcuts are configurable. Open up dconf editor and navigate to org->gnome->feedreader->keybindings
It is not the goal of FeedReader to be the most configurable, super l33t rss reader. If you want your rss to navigate like vim, you might not be the target audience of FeedReader and should use something that suits you better instead ;)
