### ISSUE TITLE
Impossible to reach to the start of the article lists in sorted by Date mode

### ISSUE THREAD

**Issue by sharifzadesina** [jangernert/FeedReader#422]
You can see below GIF for touching the problem.

![screencast from 17-03-08 02-15-14](https://cloud.githubusercontent.com/assets/15300551/23681947/746de46a-03a6-11e7-9b8e-a843a81857ab.gif)

Reaching to the end of the list in this mode also is buggy and needs recheck.

Tnx for great work.

**Comment by sharifzadesina** [comment]
And it seems the sorted by date mode gets disable automatically. I don't know why.

**Comment by jangernert** [comment]
Fixed an issue with sort-by-date. No idea if that was the same problem you were having, since I could never reproduce the behaviour you were experiencing.

**Comment by jangernert** [comment]
Sorting by date has undergone quite some refactoring and improvements in the last week. I don't think this exact issue still applies to the new code. If there still are similar problems in master you can open up a new issue.
