### ISSUE TITLE
All Service Docs are 404

### ISSUE THREAD

**Issue by MichaelTunnell** [jangernert/FeedReader#423]
All of the links on the main page for the difference services like https://jangernert.github.io/services/tinytinyrss.html are resulting in 404s.

I was trying to find out about the ttrss plugin api_feedreader and I assume it's suppose to be on that page.

**Comment by bil-elmoussaoui** [comment]
@MichaelTunnell There shouldn't be any links. I will fix that

**Comment by jangernert** [comment]
Link to api_feedreader works for me: https://github.com/jangernert/FeedReader/tree/master/data/tt-rss-feedreader-plugin
