### ISSUE TITLE
Make it easy to show read feeds

### ISSUE THREAD

**Issue by phw** [jangernert/FeedReader#425]
Currently I can switch in the options to show or hide the read feeds.

In general I prefer to see only the feeds with unread articles, to keep the feed list clean. But sometimes I search for an article or I accidentally mark an article as read and want to see it again. At the moment I have to change to the settings each time

I see two solutions for this:

1. Have a toggle somewhere in the UI to quickly change the setting
Maybe the easiest way to implement this. Has the disadvantage that it would always show / hide all read feeds, which makes it sometimes hard to find the correct one.

2. Have a toggle per category
E.g. in the context menu of a category add "Show read feeds". Or do it like feedly: They show only the unread feeds by default, but have a "n more feeds" button below each feed list.

**Comment by phw** [comment]
@jangernert Any more info on this? Is anything planned to make accessing read articles easier?

**Comment by jangernert** [comment]
Why not simply have all feeds shown at all times? If the list is too long you should probably categorize your feeds and collapse everything you don't want to see right now.
I really don't want to put a button/switch/etc for each and every setting into the main UI. Everyone has a different approach to using an application. If I try to make everyone happy I'll end up with something as complex as lifrea or any of the other established rss readers. And not having a over complicated UI was the original goal of writing my own application.
