### ISSUE TITLE
Unable to sign in to Feedly with Google account

### ISSUE THREAD

**Issue by corzor** [jangernert/FeedReader#429]
Upon starting FeedReader I select Feedly as the service where my RSS feeds are located. I try to select Continue with Google but it doesn't open a login page so I can't sign in using my Google account. I'm running on Fedora 25.

**Comment by jangernert** [comment]
FeedReader is just displaying the login-website of feedly.com in this case
Basically it just displays this URL:
```
http://cloud.feedly.com/v3/auth/auth?client_secret=FE012EGICU4ZOBDRBEOVAJA1JZYH&client_id=boutroue&redirect_uri=http://localhost&scope=https://cloud.feedly.com/subscriptions&response_type=code&state=getting_code
```

If this doesn't work in your browser then it won't work in FeedReader as well.

**Comment by corzor** [comment]
Thanks for the response.

I tried that URL in my Firefox browser and got to the Feedly sign in page with the three "Continue with ..." buttons for Google, Feedly, and Facebook. If I click on the Continue with Google button in the browser I get "Unable to connect" with this URL: `http://localhost/?code=A8UwM1tXZkP2GbJgevU-c-xm3cPwoWpMwE3ZIHAfwqSfe85DVqdifq3KbbcFLjCnhMDRW3-TI_0vWEgdKWbeTLQvWWymopcqO0j77rUQxJf102rhejrOz1qRJ3wlpCHO9GfF5GlRAF5APfcp_L8eEUk5SyFoUFA6y7RCsTLihr-e-1ZFaOtp4-sYCw&state=getting_code` . But trying your URL again I later succeeded in getting the initial Google sign in page, but then when I entered my Google account email address I got the Unable to connect page with the localhost address. Or if I get past that and get prompted for my password, then I once again get the Unable to connect page.

In one of my experiments with feedly.com I noticed it took two or three minutes to get a response of the Google sign in page from clicking on the website's Continue with Google button. So I tried waiting that amount of time for a response in FeedReader and sure enough I eventually got a Google sign in page in FeedReader. However when I entered my Google account email address and clicked Next, I got "Something went wrong. Check your connection and try again." My connection seems fine when I try other things.

**Comment by jangernert** [comment]
Since feedly.com took quite some time to respond for you, I guess the same is true when making API-calls. You can check out the logs of the daemon when trying to log in.
Kill the running daemon with `killall feedreader-daemon` and run a new instance in a shell.
When logging in you should either see this if FeedReader succeeded in getting the request-token:
```
Logger.debug("access-token: " + accessToken);
Logger.debug("expires in: " + expires.to_string());
Logger.debug("refresh-token: " + refreshToken);
```
or this will be printed in case of failure:
```
Logger.error("Feedly: getToken response - " + root.get_string_member("errorMessage"));
```

**Comment by corzor** [comment]
The feedreader-daemon won't stay running. This is what happened when I tried to run the new instance:

```
[rcorzo@tpyoga-localdomain bin]$ killall feadreader-daemon
feadreader-daemon: no process found
[rcorzo@tpyoga-localdomain bin]$ /usr/bin/feedreader-daemon
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ ERROR ] Utils.copyAutostart: Error when getting information for file '/usr/share/FeedReader/feedreader-autostart.desktop': No such file or directory
[ INFO  ] FeedReader Daemon 2.0.2
[ DEBUG ] Opening Database: /home/rcorzo/.local/share/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired
[WARNING] daemon: Could not aquire name (already running). Will shut down!
```

**Comment by jangernert** [comment]
hm? As you see the daemon shut down because the dbus name was already owned by another running process. Are you sure no other instance of the daemon was running at that point?

**Comment by corzor** [comment]
Doesn't the prior killall indicate ("no process found") that the daemon wasn't running? How does the daemon normally start?

**Comment by bil-elmoussaoui** [comment]
@corzor you can use `pkill feedreader-daemon`to kill the current instance of the daemon

**Comment by corzor** [comment]
OK this time I got the new instance of feedreader-daemon to run, but nothing new showed up in the log when I entered my Google account name in the Google sign-in page of FeedReader and got back  "Something went wrong. Check your connection and try again."

```
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ ERROR ] Utils.copyAutostart: Error when getting information for file '/usr/share/FeedReader/feedreader-autostart.desktop': No such file or directory
[ INFO  ] FeedReader Daemon 2.0.2
[ DEBUG ] Opening Database: /home/rcorzo/.local/share/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired

```

**Comment by jangernert** [comment]
This can't be the log that was printed during logging in. This is just the daemon starting up and waiting for some input.

**Comment by corzor** [comment]
I left the log running as I attempted to log in with my Google account. It is a two step process. First it asks for just your account name. That's where it failed (and apparently created no log messages). I never got to step two where it asks for your password, if that is what you are looking for.

**Comment by jangernert** [comment]
Weird! Can you post the log of the UI during that procedure? Maybe your login was already cached with some cookies or something and only the code-extraction from the redirect-url failed? That's the only explanation I have right now.

**Comment by trgeiger** [comment]
I'm having this same issue. I'd previously linked my Google account with no issue, however as I was poking around the settings the other day, I accidentally de-linked my account. Since then, I'm getting the same behavior described above when I try to log into Feedly with my Google account. I get the sign-in page, can enter my username, password, and 2-factor auth code, but then get this:
![screenshot from 2017-04-17 18-27-50](https://cloud.githubusercontent.com/assets/18582917/25108472/9c587b38-239b-11e7-9f2e-016b708aee9d.png)

**Comment by jangernert** [comment]
Did feedly change something on their side? I have to test this myself. I hope I find the time this week.

**Comment by trgeiger** [comment]
Here's the full trace from the daemon upon attempting to login:

```
 tayler@ahab  ~  feedreader-daemon
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ INFO  ] FeedReader Daemon 2.0.2
[ DEBUG ] Opening Database: /home/tayler/.local/share/feedreader/data/feedreader-04.db
[ ERROR ] dbErrorLog: 283: recovered 22 frames from WAL file /home/tayler/.local/share/feedreader/data/feedreader-04.db-wal
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin none
[ DEBUG ] feedserver: load plugin "feedly"
[ DEBUG ] feedserver: engine load feedly

(feedreader-daemon:11116): libpeas-WARNING **: Failed to load module 'feedly': /usr/lib/FeedReader/plugins//libfeedly.so: undefined symbol: feed_reader_response_destroy

(feedreader-daemon:11116): libpeas-WARNING **: Error loading plugin 'feedly'
[ ERROR ] feedserver: couldn't load plugin feedly
[ ERROR ] daemon: plugin 'feedly' couldn't be loaded by feedserver
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin feedly
[ DEBUG ] feedserver: load plugin "feedly"
[ ERROR ] feedserver: couldn't load plugin feedly
[ ERROR ] daemon: plugin 'feedly' couldn't be loaded by feedserver

```

**Comment by brendanlong** [comment]
@trgeiger Can you try the latest git version? I just pushed fc8cf9320cca6527627fd65aaa2a59b3b7e0ae5e earlier today, which should fix the undefined symbol error (see #456  for details).

**Comment by brendanlong** [comment]
I just tried, and it logs in but then the daemon immediately has a core dump. I'll try to figure out what's going.

**Comment by brendanlong** [comment]
So here's the log where it dies. I think the problem is that we start trying to load stuff, but then we kill the plugin and reload it:

```
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin feedly
[ DEBUG ] feedserver: plugin removed feedly
[ DEBUG ] feedserver: engine unload feedly
[ DEBUG ] feedserver: load plugin "feedly"
[ DEBUG ] feedserver: engine load feedly
[ DEBUG ] feedserver: plugin loaded feedly
[ DEBUG ] feedly backend: login
[ DEBUG ] Ping: http://feedly.com/

Thread 9 "feedreader-daem" received signal SIGSEGV, Segmentation fault.
```

**Comment by trgeiger** [comment]
I just tried the newest git version and got the same behavior, but at least I'm logged in now and it's syncing after a restart.

**Comment by trgeiger** [comment]
Thanks for your help on this. Anything you want me to test out?

**Comment by brendanlong** [comment]
I don't think I have any more time to work on this today. I might need @jangernert to look into it. Hopefully the logs will make it easier to track down.

**Comment by jangernert** [comment]
While investigating this I noticed the WebLoginPage triggered 2 logins after getting the feedly-api-code. I straightened the login and startup process a bit and prevented the double login. After this the crash was gone for me.
I wanted to dig deeper and figure out why the daemon crashed, but I guess I accidentally fixed the cause. Doing 2 login requests shouldn't crash the daemon, so we will have to get to the bottom of that later. But for now can you please test master again and see if the crash is fixed for you as well?

**Comment by brendanlong** [comment]
It works for me now.

**Comment by sharifzadesina** [comment]
This doesn't work for me, the links works on browser, do you need logs?

**Comment by sharifzadesina** [comment]
@jangernert I am now on last -git version.
acc. to UI log file I thikn the problem is in the redirect URL.
```
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/sina/.local/share/feedreader/data/feedreader-5.db
[WARNING] database uninitialized
[ DEBUG ] init database
[ DEBUG ] Table articles is empty
[ DEBUG ] Table categories is empty
[ DEBUG ] Table feeds is empty
[ DEBUG ] Table tags is empty
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[WARNING] FavIconCache: does not contain icon -76
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList
[ DEBUG ] serviceSelected: feedly
[ DEBUG ] WebLoginPage: load URL: http://cloud.feedly.com/v3/auth/auth?client_secret=FE012EGICU4ZOBDRBEOVAJA1JZYH&client_id=boutroue&redirect_uri=http://localhost&scope=https://cloud.feedly.com/subscriptions&response_type=code&state=getting_code
[ INFO  ] ArticleView: webextension-message: onDocLoaded
[ INFO  ] ArticleView: webextension-message: onDocLoaded
[ INFO  ] ArticleView: webextension-message: onDocLoaded
[ INFO  ] ArticleView: webextension-message: onDocLoaded
[ INFO  ] ArticleView: webextension-message: onDocLoaded
```

**Comment by hustler77** [comment]
It also does not work 4 me. Just an empty page after put in password appears.
