### ISSUE TITLE
All articles open in browser instead of feed view

### ISSUE THREAD

**Issue by hulsed** [jangernert/FeedReader#430]
This is on fedora 25, version 2.02. _Sometimes_, the articles will display in the feed, most of the time they open an external link in the browser. Generally, it will allow me to view them in the feed view while they are still downloading (soon after adding a feed), but afterwards will only open links in an external browser. Is there a reason for this or a way to control the behavior? I'd much prefer to read everything without opening an external browser window.

This is the UI output: 
[ DEBUG ] ArticleView: Policy decision
[ DEBUG ] WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION
[ DEBUG ] ArticleView: open https://www.reddit.com/r/linux/comments/60gkot/6_features_we_love_in_gnome_324/ in browser

**Comment by jangernert** [comment]
No, loading urls directly in the article view is not inteded. I added back the old url-check to prevent this from happening before the content-grabber has finished updating the article html-code.

**Comment by hardeep** [comment]
Is there anyway to add a preference for this? I just ran into the same scenario as above. I'd love to be able to read an article from within the reader preview pane and then if I chose to launch it in my browser.

Some feeds such as Hacker News only provide the title and a comments section link in the reader view. This makes me jump back and forth between the reader and browser quite a bit.
