### ISSUE TITLE
Taking offline status into account

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#433]
When the internet connection goes offline while syncing, the spinner still spins, and it seems that FR doesn't recognize the offline status. Could you implement some feedback from the daemon, so that the users know when the daemon is loading and when it does nothing? Would be very useful for metered connections.

**Comment by jangernert** [comment]
If you cut the connection in the middle of a sync all the soup connections are still trying to send messages. Only after they timed out the sync will finish.
The only status is only checked before each sync and when the UI starts.
Checking if the server is available before each and every step would only slow down things considerably.

**Comment by fbruetting** [comment]
Maybe it's helpful to reduce the single timeouts to say maybe 10…20 seconds and then stop the daemon-sync as a whole (for when the connection broke)? Is this accessible by interfacing the network manager (for lowering the latency)?

I sat in a café yesterday, and the spinner didn't stop spinning when the connection broke and it still spinned when the connection was available again. So I didn't know if it was fetching data again or not. In the end, it spun all the time but didn't fetch any more data.
