### ISSUE TITLE
support for singleusermode in TT-RSS

### ISSUE THREAD

**Issue by dahabakuk** [jangernert/FeedReader#436]
currently it seems theres no support for single user mode. i run a tt-rss instance with http-basic auth and singleusermode.

i installed feedreader with flatpak on debian testing.

i always have to enter a ttrss username (enter valid username error)

after providing one, i can enter the http-auth credentials which are 100% correct but i only see:
"POST /feedme/api/ HTTP/1.1" 401 188 "-" "FeedReader 2.0"

**Comment by jangernert** [comment]
Username is no longer required and parameter "user" is not added to the login-call if not present. This should make single-user-mode work. I haven't tested it myself though.
