### ISSUE TITLE
Fedora 25 - feedreader-daemon killed by SIGSEGV -abrt

### ISSUE THREAD

**Issue by 100Hamburger** [jangernert/FeedReader#439]
Hello, when I try to grab full content of my RSS-feeds in local RSS, feedreader crashes and doesnt start downloading articel content.

**Comment by jangernert** [comment]
Version and daemon logs?
Also you could try to disable the grabber in the settings and see if that fixes your issue. That would help to track down the issue further.

**Comment by 100Hamburger** [comment]
The version is: 2.0.2
Disableing the grabber doesnt change anything.
Where can I find the daemon logs?

**Comment by jangernert** [comment]
start the daemon from a shell

**Comment by 100Hamburger** [comment]
The output says folowing error: 

[ ERROR ] error writing log to file: Datenstrom hat noch einen ausstehenden Vorgang
[ ERROR ] [ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00014" AND unread = 9  ORDER BY date COLLATE NOCASE DESC LIMIT 1 OFFSET 0

Does this help?

**Comment by jangernert** [comment]
No not really. The error is totally unrelated and nothing critical. Basically just saying it can't write the logs as fast to the disk as FeedReader is logging (happens only sometimes).
Also I'm pretty sure this is just (a very small part of) the log of 'feedreader'. I need the full log of the 'feedreader-daemon' process as it is crashing.
