### ISSUE TITLE
owncloud/nextcloud offline after a while

### ISSUE THREAD

**Issue by nirik** [jangernert/FeedReader#441]
feedreader-2.0.2
nextcloud-10.0.4

Things work fine for a while, but then feedreader shows 'offline' and won't show any new items. 

[ DEBUG ] feedserver: unload plugin none
[ DEBUG ] feedserver: load plugin "owncloud"
[ DEBUG ] feedserver: engine load OwnCloud News
[ DEBUG ] feedserver: plugin loaded OwnCloud News
[ DEBUG ] OwnCloud: login
[ DEBUG ] OwnCloud URL: https://www.scrye.com/nextcloud/index.php/apps/news/api/v1-2/
[ DEBUG ] OwnCloud URL: https://www.scrye.com/nextcloud/index.php/apps/news/api/v1-2/
[ ERROR ] ownCloud Message: No response - status code: Connection terminated unexpectedly
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_NO_CONNECTION

last time this happened I was able to get it working by doing 'change account' to another owncloud account, then back again to my normal one. 

nextcloud news works fine from other devices (android app) or the web interface. 
changing to http vs https doesn't matter (and the cert should be valid anyhow). 

Is there a way to see what owncloud api calls it's sending and getting back?

**Comment by nirik** [comment]
And I am an idiot. ;) There was actually a connection issue... nothing to see here. Sorry for the noise.

**Comment by jangernert** [comment]
No problem. Happens to the best of us :D
