### ISSUE TITLE
Renamed feed titles get overwritten

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#442]
I renamed my feeds o(f Feedly), but the next sync overwrites them back. Can you please fix this, or just store the titles locally, if it isn't possible to change the feed names on the Feedly server? I don't know if this works on other servers…

**Comment by jangernert** [comment]
I don't really have time in the forseeable future to work on FeedReader. And if there are 1 or 2 quit hours during the weekend that I can spent working on FeedReader, there is already a list with stuff I want to work on.

This is the function you are looking for:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyInterface.vala#L214
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyAPI.vala#L575
And here is the feedly-documentation:
https://developer.feedly.com/v3/subscriptions/

Have fun debugging.

**Comment by brendanlong** [comment]
Are you still having this problem with Feedly? We've improved a lot of this stuff over the last few years so this may work now. Please let us know if you're still seeing this problem though.
