### ISSUE TITLE
Initial sync with Feedbin never completes

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#444]
I'm on Fedora 25 and I've tried this with the Flatpak version and also 2.0.2 from `dnf`.

1. Open FeedReader
2. Pick Feedbin
3. Enter username and password
4. "No Articles" and loading spinner goes forever.

I thought maybe my account has too many articles for it to handle, so I tried setting it to only download a week, but that doesn't seem to help.

I used this command to reset my settings, since FeedReader won't let you stop a sync or change accounts during a sync and I can't figure out how to stop the daemon gracefully:

```
pkill feedreader-daemon
gsettings reset-recursively org.gnome.feedreader
rm -r ~/.local/share/feedreader/
```

I also tried running the `feedreader-daemon` and `feedreader` in the terminal to get some logging, but nothing stands out:

### `feedreader-daemon`

```
[blong@blong-xps13 ~]$ feedreader-daemon
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ ERROR ] Utils.copyAutostart: Error when getting information for file '/usr/share/FeedReader/feedreader-autostart.desktop': No such file or directory
[ INFO  ] FeedReader Daemon 2.0.2
[ DEBUG ] Opening Database: /home/blong/.local/share/feedreader/data/feedreader-04.db
[WARNING] database uninitialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin none
[ DEBUG ] feedserver: load plugin "feedbin"
[ DEBUG ] feedserver: engine load Feedbin
[ DEBUG ] feedserver: plugin loaded Feedbin
[ DEBUG ] feedbin backend: login
[ DEBUG ] Ping: https://feedbin.com/
[ DEBUG ] Ping: status 200
[ DEBUG ] Ping successfull
[ DEBUG ] SELECT count(*) FROM main.CachedActions
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.CachedActions
[ DEBUG ] count 0
[ DEBUG ] CachedActionManager - executeActions: no actions to perform
[WARNING] resetCachedActions
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ INFO  ] daemon: initSync started
[ DEBUG ] FeedServer: initial sync
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] Utils: downloadIcon() url = "http://raganwald.com/"
```

### `feedreader`

```
[blong@blong-xps13 ~]$ feedreader
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/blong/.local/share/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList
[ DEBUG ] serviceSelected: Feedbin
[ DEBUG ] write login data
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_SUCCESS
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show content
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] HeaderBar: setButtonsSensitive true
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] DBusConnection: syncStarted
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0.000000
[ DEBUG ] offset 0
[ DEBUG ] UpdateButton: update status
[ DEBUG ] DBusConnection: updateSyncProgress
[ DEBUG ] ArticleView: size changed
[ DEBUG ] ArticleView.setBackgroundColor()
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: disallow signals from scroll
[ DEBUG ] ArticleList: new-rows 0
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles ORDER BY rowid COLLATE NOCASE DESC LIMIT 13 OFFSET 0
[ DEBUG ] actual articles loaded: 0
[ DEBUG ] ArticleList: no content, so allow signals from scroll again
[ DEBUG ] articlelist-prev
[ DEBUG ] articlelist-next
[ DEBUG ] feedlist-prev
[ DEBUG ] feedlist-next
[ DEBUG ] articleview-up
[ DEBUG ] articleview-down
[ DEBUG ] articlelist-toggle-read
[ DEBUG ] articlelist-toggle-marked
[ DEBUG ] articlelist-open-url
[ DEBUG ] feedlist-mark-read
[ DEBUG ] global-sync
[ DEBUG ] articlelist-center-selected
[ DEBUG ] global-search
[ DEBUG ] global-quit
[ DEBUG ] global-help
```

**Comment by brendanlong** [comment]
Hm maybe it is working and is just *really* slow? 8 minutes later I have:

```
[ DEBUG ] FeedServer: initial sync
[ DEBUG ] Utils: downloadIcon() url = "http://raganwald.com/"
[ DEBUG ] Utils: downloadIcon() url = "http://nymag.com"
[ DEBUG ] Utils: downloadIcon() url = "http://bearlamp.com.au"
[ DEBUG ] Utils: downloadIcon() url = "https://tonyarcieri.com"
[ DEBUG ] Utils: downloadIcon() url = "http://www.sinfest.net"
```

**Comment by brendanlong** [comment]
I thought maybe favicon.allesedv.com was being slow, but I checked the things feedreader says it's downloading and that doesn't seem to be the problem.

**Comment by jangernert** [comment]
Feedbin backend is not really polished.
It only offers a small free trail period in which I had to develop all the code. The API is the worst I have seen so far (and I have seen a fair share of feed-service APIs by now).
So no way of testing unless I register a new account with a different mail-address for every bug-report and lots of workarounds in the code because of a really lacklustre API.
So if anyone wants to step up and maintain the feedbin-code he/she is more than welcome.
Btw: every other service stores the favicons and offers clients to download them. Only feedbin gives clients the middle finger saying: "get them on your own"  :P

**Comment by brendanlong** [comment]
Ah ok. I'll try to trace through it and figure out what's taking so long 👍

Would it be helpful if I could get you a free Feedbin account? I suspect I could convince the owner to give you one if it would make it easier for you to maintain this. (It's also open source and relatively easy to run but I assume you don't want to deal with that)

**Comment by jangernert** [comment]
If you have any questions regarding the code feel free to ask. All the important code is in these 2 files:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedbin/feedbinInterface.vala
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedbin/feedbinAPI.vala

Actually I did not realize you could host it yourself. But still, if someone is using feedbin on a regular basis and has even a small understanding of programming he would be a much better maintainer of the code than I ever could :)

**Comment by brendanlong** [comment]
I've been looking into this, and it seems like the problem is that the actual favicon request is really slow (the request to `http://f1.allesedv.com/32/`). I have no idea why though, and it never takes more than a second with `curl`. If I re-use the soup session and use the https:// version, it's a lot faster most of the time but it's still slow on a few icons. I wonder if the requests are being throttled or something?

Since the problem seems to be in `Utils.downloadIcon()`, I think the same problem exists in the local account plugin, but it would be less obvious since you generally wouldn't be loading hundreds of subscriptions at once.

There are a few things that would probably help with the responsiveness of this:

 - Re-use `Soup.Session`. The class is threadsafe and this would let us avoid TCP/TLS setup costs in some cases.
 - Load icons in the background.
 - Use async requests so we can do multiple things at once.
 - Load articles as we get them instead of waiting for all of them (very useful when loading months of subscriptions).

**Comment by brendanlong** [comment]
Ah right, so switching to `https://f1.allesedv.com` helps because that site forces an https redirect, so starting with that URL avoids the redirect and lets us reuse the connection.

**Comment by brendanlong** [comment]
Something weird must be going on with my installation of libsoup since I can't understand why random requests are taking so long. I'll try to figure that out, but I think the changes in my pull request will be good even if I can make libsoup work right.

**Comment by jangernert** [comment]
Great work so far :) Especially now since I only have very limited time to work on the code.
The `https://favicon.allesedv.com/` was basically just a quick workaround for not getting the favicons from feedbin. Maybe it would be better to do a little GET-request to the feeds website and parse the HTML to get the favicon ourself. And only rely on allesedv.com as a fallback?
As long as all sites follow some consistent pattern with their favicons, it shouldn't be to hard to get them with a simple xpath query.
```
<link rel="icon" type="image/x-icon" href="https://assets-cdn.github.com/favicon.ico">
```
For github this would be `//link[@rel='icon']`.

edit: Okay, maybe not as simple as golem.de does it like this
```
<link rel="shortcut icon" href="/favicon.ico">
```

**Comment by brendanlong** [comment]
Aha, so my actual problem was that f1.allesedv.com and several other domains support IPv6, and apparently my router's IPv6 support is broken. :D Re-using these sessions should still make things faster so ¯\_(ツ)_/¯

**Comment by brendanlong** [comment]
Oh and I'll look into fetching favicons ourselves. The algorithm would be:

 - Look for `<link rel="shortcut icon">`
 - If not found, look for `<link rel="icon">`
 - If not found, request `domainname/favicon.ico`

Using `favicon.allesedv.com` might actually be the most reasonable thing to do though, since it's less work for us, fewer HTTP requests for us, possibly faster (if favicons are cached on the site), and less load on individual websites. The only downside is that we're relying on a site outside of our control (which is a pretty big downside, but possibly worth it in this case).

**Comment by jangernert** [comment]
Hm, currently the downside of having more requests and bandwith requirements also applies rarely. Once the favicon is saved on disc, FeedReader does not try to download it the next sync but just loads the file from disc. This is of course a problem if the icon changes at some point (new branding). But since it's not a huge dealbreaker, I haven't put much thought into it, yet. Maybe do a HEAD request and check against a changed 'Content-MD5' attribute or something.
So I would be in favor of only relying on `favicon.allesedv.com` if everything you mentioned fails.
If you have some time and motivation on your hand feel free to implement the idea. Otherwise I will go for it on friday (long weekend from fr-mo here in germany). Sounds like something fun to implement :D
