### ISSUE TITLE
Nextcloud Failed login

### ISSUE THREAD

**Issue by wompydomp** [jangernert/FeedReader#449]
Hi,

I have a current nextcloud installation with 11.0.2 and I am running feedreader. I am gettng stuck in the login step. My url that I am using has the form asdf.tld/nextcloud.

Please let me know if you need additional info.

```

[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/xxx/.local/share/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOnline
[ DEBUG ] serviceSelected: ownCloud News
[ DEBUG ] OwnCloud URL: xxxx
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL:xxxx
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
[ DEBUG ] MainWindow: show error bar - errorCode = 7
[ DEBUG ] MainWindow: show error bar
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList

(feedreader:32229): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(feedreader:32229): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(feedreader:32229): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(feedreader:32229): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL:xxxxx
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
[ DEBUG ] MainWindow: show error bar - errorCode = 7
[ DEBUG ] MainWindow: show error bar
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] ArticleList: get State
[ DEBUG ] scrollpos 0,000000
[ DEBUG ] offset 0
[ DEBUG ] Shutdown!

```

**Comment by jangernert** [comment]
Please post the log of the feedreader-daemon.

**Comment by wompydomp** [comment]
```
feedreader-daemon
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] daemon: Notification actions supported
[ ERROR ] Utils.copyAutostart: Error when getting information for file '/usr/share/FeedReader/feedreader-autostart.desktop': No such file or directory
[ INFO  ] FeedReader Daemon 2.0
[ DEBUG ] Opening Database: /home/xxx/.local/share/feedreader/data/feedreader-04.db
[ ERROR ] dbErrorLog: 283: recovered 193 frames from WAL file /home/xxx/.local/share/feedreader/data/feedreader-04.db-wal
[ DEBUG ] database already initialized
[ DEBUG ] database already initialized
[ DEBUG ] daemon: constructor
[ DEBUG ] daemon: new FeedServer and login
[WARNING] feedserver.unloadPlugin: no plugin loaded
[ DEBUG ] feedserver: load plugin "none"
[ ERROR ] feedserver: couldn't load plugin none
[ ERROR ] daemon: plugin 'none' couldn't be loaded by feedserver
[ DEBUG ] daemon: bus aquired
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] Daemon: checkOnlineAsync
[ DEBUG ] Daemon: checkOnline
[ DEBUG ] daemon: symbolicIcon
[ DEBUG ] feedserver: symbolicIcon
[ DEBUG ] daemon: new FeedServer and login
[ DEBUG ] feedserver: unload plugin none
[ DEBUG ] feedserver: load plugin "owncloud"
[ DEBUG ] feedserver: engine load OwnCloud News
[ DEBUG ] feedserver: plugin loaded OwnCloud News
[ DEBUG ] OwnCloud: login
[ DEBUG ] OwnCloud URL: https://xxxxx.com/nextcloud/index.php/apps/news/api/v1-2/
[ DEBUG ] OwnCloud URL: https://xxxxx.com/nextcloud/index.php/apps/news/api/v1-2/
[ ERROR ] Could not load response from Message to owncloud
[ DEBUG ] {}
[ ERROR ] <data>:1:1: Parse error: unexpected character `<', expected value
[ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
```

**Comment by jangernert** [comment]
I don't see anything wrong from the side of FeedReader here. At the end of the login FeedReader tries to get the status from ownCloud. But apparently the response from the server isn't parseable json.
So to investigate further the easiest way would be to have an account on your server to test everything myself.
Also you should install the latest version. There were 2 bugfix-releases that fixed some nasty bugs.

**Comment by wompydomp** [comment]
Sorry for the delayed reply. How can I contact you with a private message to provide you a sample login. Sorry, I am not really an experienced github user.

**Comment by jangernert** [comment]
I think email would be the easiest: jangernert@gmail.com

**Comment by jangernert** [comment]
I tracked down the problem, but I'm not really sure what to do about it.
As soon as the message to the nextcloud-server contains any data in the body it returns with status code 400.

So this works:
```
curl -H "Authorization: Basic dGVzdHVzZXI6amFuZ2VybmVydA==" https://rasppi.asuscomm.com/nextcloud/index.php/apps/news/api/v1-2/status
```

But this doesn't:
```
curl -d '{}' -H "Authorization: Basic dGVzdHVzZXI6amFuZ2VybmVydA==" https://rasppi.asuscomm.com/nextcloud/index.php/apps/news/api/v1-2/status
```

Just removing the body from the message makes the login work again. But this is no option for other GET requests like `items/updated` as they require some json parameters in the body.

@brendanlong you know more about all this http-stuff than me. Do you have any idea why that is?

**Comment by jangernert** [comment]
@wompydomp did you try to use any other owncloud clients? Maybe it's something wrong with the server?

**Comment by wompydomp** [comment]
All other clients work, I have the nextcloud app connecting, webdav works, caldav..

**Comment by jangernert** [comment]
I meant owncloud news clients ;)

**Comment by jangernert** [comment]
Tried RSS guard on the office pc and it worked. Already have an idea I'll implement and test tonight.

**Comment by brendanlong** [comment]
Is owncloud just rejecting body content in requests that shouldn't have any, or does it also send you a 400 if you try a request to `items/updated`?

**Comment by jangernert** [comment]
Same with `items/updated`. The documentation states nextcloud doesn't differentiate between json in the body and url-encoded parameters, but recommends url-encoding for GET requests. In the past that worked fine. I guess in a recent release that was changed and the doc hasn't been updated yet. I'll try wit url-encoded parameters again. That's how RSS guard does it as well.

**Comment by jangernert** [comment]
Works with url-encoded parameters. Don't know when that changed though and why the docs weren't updated =/

> In general the input parameters can be in the URL or request body, the App Framework doesnt differentiate between them.
So JSON in the request body like `{ "id": 3 }` will be treated the same as `/?id=3`
It is recommended though that you use the following convention:
GET: parameters in the URL
POST: parameters as JSON in the request body
PUT: parameters as JSON in the request body
DELETE: parameters as JSON in the request body

**Comment by wompydomp** [comment]
Success! I took a the update through pacaur -Syu feedreader-git and was able to connect. Thank you so much for the quick troubleshooting and this beautiful piece of software!
