### ISSUE TITLE
Flatpak and Pocket

### ISSUE THREAD

**Issue by vayan** [jangernert/FeedReader#453]
I have no option to use Pocket to share articles.

feedreader 2.0.2 on Ubuntu 17.04

![screenshot from 2017-04-19 08-52-56](https://cloud.githubusercontent.com/assets/2945291/25166881/a1589062-24dd-11e7-8773-5d78ad50757d.png)

Do I have something to do except 
`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref` ?

**Comment by jangernert** [comment]
If gnome-online-accounts are detected the custom account-setup is disabled. Please use the panel in your system settings ;)
Sadly gnome doesn't support a lot of accounts, so I still have to keep the button around for all the other account types.

**Comment by vayan** [comment]
Oh I see, so it doesn't work on Ubuntu :/

**Comment by jangernert** [comment]
If ubuntu ships libgoa but not the configuration-panel in the settings, then no.
But since they are abandoning the unholy mess called unity in the future it will work again :D

**Comment by jangernert** [comment]
As far as I see there are 3 possible workarounds for your situation:
- get the gnome-online-accounts panel working on your system
- remove libgoa from your system so FeedReader doesn't detect it
- patch FeedReader itself (just return false in this function https://github.com/jangernert/FeedReader/blob/master/plugins/share/Pocket/PocketAPI.vala#L243)

**Comment by vayan** [comment]
Ok I made it work! Thanks. 

For people reading this before Ubuntu 18.04 :) 

`sudo apt install gnome-online-accounts` 

`gnome-control-center online-accounts`
