### ISSUE TITLE
Only starred articles displayed from TT-RSS

### ISSUE THREAD

**Issue by viq** [jangernert/FeedReader#455]
I'm running checkout of tt-rss as of a couple days ago, with your api_feedreader plugin enabled. FeedReader logged in, sees the list of feeds, but Unread shows me nothing, while both All and Starred shows me only my starred articles.

FeedReader installed from flatpak on Arch

**Comment by jscurtu** [comment]
is this a self built flatpak from master? The official flatpak hasent been updated since 24 Feb.

**Comment by viq** [comment]
I followed instructions on site, I'm not sure which version that gets me.

> --

viq

**Comment by jscurtu** [comment]
that will give you whatever is set in the Makefile.config, which is basicly the same as installing from our repo, the last state of the stable git branch.
If you want master, change these settings in Makefile.config.
 
VERSION=2.0.2
BRANCH=master
GIT=master

VERSION is just for the filename and nothing about the actual build process. 
BRANCH is the ostree branch (binary for flatpak to work)
GIT is the git branch you are actually building FeedReader from.
