### ISSUE TITLE
Flatpak support for GNOME 3.24

### ISSUE THREAD

**Issue by aleksandar-todorovic** [jangernert/FeedReader#457]
With Ubuntu GNOME 17.04 already out, I thought about installing my favorite RSS reader.

However, the Flatpak installation seems to try to download the `org.gnome.Platform/x86_64/3.22` package, which seems to me like it tries to download the 3.22 version of GNOME, which is definitely something I do not want to do.

I can't say if the FeedReader is completely unavailable with GNOME 3.24, or is it just the Flatpak version of it.

**Comment by jscurtu** [comment]
It will install the 3.22 flatpak GNOME runtime, not GNOME its self. 
Dont get mix'ed it up with GNOME 3.24, in terms of flatpak, that is something you need to do.  

You can safely install FeedReader with the wanted runtine without any concerns, that is the good thing about flatpak. They coexist without interfering.
