### ISSUE TITLE
Support Debian 8 without ubuntu repository

### ISSUE THREAD

**Issue by Huskynarr** [jangernert/FeedReader#46]
I want integrate e seperate Ubuntu Repository to my Source List.
Can you also support Debian alone?

**Comment by jangernert** [comment]
I don't do packaging (only the ubuntu ppa's). So if you want to have a package for debian, you have to build one yourself.

**Comment by Huskynarr** [comment]
Then please Fix the Readme, there stand that this ppa is usable for Debian. 
If it vor Debian 7 usable, than please write it explicit.

**Comment by jangernert** [comment]
:D @bil-elmoussaoui did the readme file
no idea why he added debian there :P 
I will remove it ;)

**Comment by bil-elmoussaoui** [comment]
I've never used Debian before, i thought the Ubuntu packages will work on Debian too (as Ubuntu is based on Debian :p)

**Comment by JHGitty** [comment]
I talked with @Huskynarr about this issue. There are dependencies that are not in the default Debian 8 repository but in the ubuntu repository. That because feedreader is by default not compatible with Debian 8 yet. You may need to find all dependencies manually and then compile it yourself.

**Comment by Huskynarr** [comment]
@bil-elmoussaoui  ... Debian Based does not mean that it is Debian Compatible.
I have already had with various Third Apps that led to the problem of system instability.
Different versions of both operating systems can cause fatal errors.
I've had enough systems crashed thereby any packets suddenly no longer be supported and not lead support.

**Comment by JHGitty** [comment]
@Huskynarr is right. The main reason is that ubuntu has it own repository with own software versions and Patches.

**Comment by JHGitty** [comment]
@Huskynarr Could you check which dependencies are really required? As I understand the dependency ``lib-unity`` is optional if you compile it with the parameter ``-DWITH_LIBUNITY=OFF``.

If compiling on Debian 8 works fine without adding extra repositories it could be easy to provide an official debian package.

**Comment by Huskynarr** [comment]
The manual compile the packet is not at issue here.
It was just a matter that was not the Debian repositories compatibility means available.

The compile himself is something else.

**Comment by JHGitty** [comment]
So if compiling on Debian 8 works fine this software just needs a mantainer for an official debian package.

**Comment by dererk** [comment]
c&p from https://github.com/jangernert/FeedReader/issues/706#issuecomment-407587700

> I've prepared FeedReader native Debian's package. They are currently in NEW queue. So we should have news pretty soon.
