### ISSUE TITLE
Wordpress blog posts are truncated

### ISSUE THREAD

**Issue by nekohayo** [jangernert/FeedReader#463]
For some reason it seems any Wordpress blog feed's items get shown truncated (with a "Continue reading blah blah" link appended) instead of showing the full post contents, like Liferea does.

An example of an affected blog: https://feaneron.com/feed/ (the contents are fully visible in the feed's source code)

**Comment by bil-elmoussaoui** [comment]
Take a look at https://github.com/jangernert/FeedReader/tree/master/data/GrabberConfig

**Comment by jangernert** [comment]
This feed is providing it's full content in the custom tag `<content:encoded>`. The standard `<description>` only contains the truncated version. Apparently content is not supported by libmrss that is used for the local backend.

**Comment by nekohayo** [comment]
This is a bug in your backend then. I don't see why this would be closed. Users shouldn't be expected to go hack around configuration files to make a third of the Internet's websites work with their feed reader!

**Comment by brendanlong** [comment]
@nekohayo It looks like content:encoded is an extension to RSS. I might look into that, but for now you could try using the ATOM versions of feeds, since ATOM is a lot easier to parse: https://feaneron.com/feed/atom/

**Comment by nekohayo** [comment]
Well for what it's worth it exhibits the same issue when parsing a Wordpress Atom feed ;)

**Comment by brendanlong** [comment]
Hm :(

**Comment by brendanlong** [comment]
I'm going to look into this since `<content:encoded>` seems like standard-ish behavior: https://developer.mozilla.org/en-US/docs/Web/RSS/Article/Why_RSS_Content_Module_is_Popular_-_Including_HTML_Contents

**Comment by brendanlong** [comment]
So libmrss does look for `<content>` in ATOM feeds, it just uses the same memory location as `<summary>`, and whatever comes first wins (which is usually `<summary>`). It wouldn't be too hard to make it prefer `<content>` (and add `<content:encoded>` for RSS). The better solution is to just use libxml for this, but it would be a lot of work to change a backend that I have no interest in.

**Comment by brendanlong** [comment]
Adding `<content>` in ATOM is relatively easy, but for some reason libnxml doesn't want to parse `<content:encoded>`. I wonder if it doesn't like the `:` or something.

**Comment by brendanlong** [comment]
I created a pull request to fix this in ATOM, but I don't know what's wrong with libnxml. I did some logging and it seems to randomly create either a `<content>` or `<encoded>` tag out of `<content:encoded>` but I don't know why.

Fixing it in ATOM is about the most  effort I'm willing to put in with C code :\

**Comment by brendanlong** [comment]
Ohhh I think I know what it is. In a tag like `<content:encoded>`, `content` is a namespace and the tag name is just `encoded`. I doubt we want to deal with namespaces but I can make it check for an `<encoded>` tag.
