### ISSUE TITLE
Remove dependency on libunity-dev

### ISSUE THREAD

**Issue by JHGitty** [jangernert/FeedReader#47]
Is it possible to remove the dependency on ``libunity-dev`` ?

As I understand it is a library for the Desktop environment Unity for Ubuntu, right? But what if I use something else like just Gnome3 on Arch Linux?

I have not checked for which features ``libunity-dev`` is used. It would be helpful if this dependency would be optional to support Debian 8.

**Comment by JHGitty** [comment]
Oh, ehm.. maybe this is a mitake. Does ``(optional: disable with -DWITH_LIBUNITY=OFF)`` mean that if I compile with this parameter the dependency will be optional?

**Comment by Huskynarr** [comment]
This could be changed from Dependency in the Readme.md to Optional.
Now its "required".

**Comment by JHGitty** [comment]
The documentation contains this line:
``libunity-dev (optional: disable with -DWITH_LIBUNITY=OFF)``

But I agree with you that this is not fully understandable for everybody.
