### ISSUE TITLE
Command line option to add feed

### ISSUE THREAD

**Issue by nick87720z** [jangernert/FeedReader#471]
Previous issue #470 was wrongly named and explained, so creating new.
I looked, how it is did in liferea: it has option --add-feed for main executable, as well as separate binary liferea-add-feed. This way it is possible to add it from browsers, that support it (not all have it, though).

**Comment by jangernert** [comment]
What is the expected behavior of this? Open up the UI with the popup showing with the rss-url already filled in? Or silently add the feed as uncategorized.

**Comment by nick87720z** [comment]
Though i'm incompletely sure, "add to uncategorized" might better match to elementary work style - result is almost instant; if necessary, feed may be moved and renamed later.

**Comment by brendanlong** [comment]
Since we have the daemon in the background, it might make more sense for it to be a separate executable, so we don't have to load the whole program just to tell the daemon to add a feed?

**Comment by nick87720z** [comment]
Did not notice dbus daemon, this should be essential... i thought it must invoke main executable :)
Sorry for long delay, was a bit busy...
After some thinks i'm unsure now about only instant adding with default properties.

Taking for example process of bookmark creation on some web browsers, there are both cases, when dialog is used (epiphany - Name, Url, Category), and not (firefox and palemoon - first add with defaults, and only on second click show dialog... btw, editing button might be added in one row with +/- buttons).
