### ISSUE TITLE
block javascript and frames

### ISSUE THREAD

**Issue by WhatsThePlan** [jangernert/FeedReader#472]
hi. is it possible to block external requests like javascript and youtube iframes from loading? i dont like google and others spying on me while reading rss posts

**Comment by jangernert** [comment]
WebKit.Settings can dis- or enable javascript. But I'm not aware of any setting preventing iframes from loading.
https://valadoc.org/webkit2gtk-4.0/WebKit.Settings.enable_javascript.html

If you want to see the javascript setting implemented, the fastest way would be to send in a pull request with the changes. It should be added to the tweaks-section in the gsettings. Then it's just 2 additional lines of vala ;)

**Comment by jangernert** [comment]
You can now disable javascript in the tweaks. But this will break all functionality that relies on setting and getting the scroll position of the article view from the code.
