### ISSUE TITLE
ownCloud/nextCloud News

### ISSUE THREAD

**Issue by bheerssen** [jangernert/FeedReader#473]
I can't add my ownCloud/NextCloud News account. The error I get on the command line is:

`[ DEBUG ] OwnCloud URL: https://cloud.heerssen.tk/index.php/apps/news/api/v1-2/`
`[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_NO_CONNECTION`
`[ DEBUG ] MainWindow: show error bar - errorCode = 11`
`[ DEBUG ] MainWindow: show error bar`
`[ DEBUG ] DBusConnection: setOffline`

I'm using:

* The latest FeedReader from https://sdk.gnome.org/gnome.flatpakrepo (as of this morning)
* NextCloud version 11.0.3 (stable)
* News version 10.2.0
* Flatpak 0.9.2
* Ubuntu Gnome 17.04 (fully updated)

Interestingly, when I plug the above OwnCloud URL into my browser, I get redirected to the main files page.

**Comment by bheerssen** [comment]
Please let me know if you need more information, or if this is a PEBKAC error.

**Comment by jangernert** [comment]
We had a similar report a few days ago. Turns out nextcloud changed the way it treats get-requests at some point. Is there a way for you to build the latest code from master and see if it is fixed for you as well? I can't say for sure, but it looks like the same issue to me.

**Comment by bheerssen** [comment]
I'll give it a shot. I only have about 45 minutes to work on it right now. (BRB)

**Comment by bheerssen** [comment]
I got the same result:

bruce@nemesis:~$ feedreader
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: maximize
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/bruce/.local/share/feedreader/data/feedreader-5.db
[WARNING] database uninitialized
[ DEBUG ] init database
[ DEBUG ] Table articles is empty
[ DEBUG ] Table categories is empty
[ DEBUG ] Table feeds is empty
[ DEBUG ] Table tags is empty
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[WARNING] FavIconCache: does not contain icon -76
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList

(feedreader:19193): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
[ DEBUG ] serviceSelected: ownCloud News
[ DEBUG ] OwnCloud URL: https://cloud.heerssen.tk/index.php/apps/news/api/v1-2/
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL: https://cloud.heerssen.tk/index.php/apps/news/api/v1-2/
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_NO_CONNECTION
[ DEBUG ] MainWindow: show error bar - errorCode = 11
[ DEBUG ] MainWindow: show error bar
[ DEBUG ] DBusConnection: setOffline

**Comment by bheerssen** [comment]
I uninstalled the previous installation using "flatpak uninstall org.gnome.FeedReader", then I downloaded the zip file from github and followed the INSTALL.md instructions. That went perfectly. Unfortunately, it still can't log into my nextcloud news account.

I even removed the feedreader directory from .local/share to make sure there weren't any left over settings to interfere with the new installation.

**Comment by jangernert** [comment]
Did you kill the running instance of feedreader-daemon​?

**Comment by bheerssen** [comment]
Nope. I'll try that. ...

**Comment by bheerssen** [comment]
That worked! Thanks for your help. Can I do anything else for you?

**Comment by jangernert** [comment]
Nope. I'll try to tie up all loose ends in master and release a stable update as soon as possible. Not great if all newer nextcloud versions are currently broken with stable.

**Comment by bheerssen** [comment]
Thanks again. Closing this issue.
