### ISSUE TITLE
Feedly login

### ISSUE THREAD

**Issue by Alexis6307** [jangernert/FeedReader#474]
Hi,
I can't connect FeedReader with Feedly account:

- When I try to connect with Feedly account I get `Could not connect: Connection refused`  and in terminal I get:
`[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_NO_BACKEND`
`[ DEBUG ] MainWindow: show error bar - errorCode = 9`
`[ DEBUG ] MainWindow: show error bar`

- When I try to connect Feedly with Google Account I put my username and password but I only get a blank screen and no error msg in the terminal. (I have 2-factor authentication, maybe could be the reason?)

I'm running in Arch x64, FeedReader installed with yaourt.

**Comment by jangernert** [comment]
Which version are you running? The `feedreader`-package (2.0.2 at the moment) or `feedreader-git`.
Also I never tested the login with 2-factor auth. But I believe it worked for others in the past.

**Comment by Alexis6307** [comment]
Ok, before I was trying with `feedreader` package. Now I install `feedreader-git` and still I can't log in with Google Account (Blank screen again after entering user and pass), but Feedly login don't refuse the connection, so I can log in. It's something. Thanks @jangernert

**Comment by jangernert** [comment]
Does feedly login use the same username and pw as your google account? If so, does the feedly login require 2-factor-auth as well?

**Comment by Alexis6307** [comment]
Nope, Feedly account only requires username and password and doesn't have 2-fact-auth asap, I created this account to try in FeedReader. You can add different accounts kinds to log into Feedly (Google, Feedly, Fb, Twitter, Windows or Evernote).

**Comment by jangernert** [comment]
I guess I have to try and debug with a 2-factor-auth google account then.

**Comment by jangernert** [comment]
Can confirm the behavior with 2-factor-auth. The same thing happens if you try to add your google-account to gnome-online-accounts. So maybe google changed a few things? :P 
Lets see when I have time to investigate further.

**Comment by Alexis6307** [comment]
Yep, you're right! I'm in KDE but I have tried with Gnome in Vbox and that seems to be the problem, same error when I try to add Google to Gnome Accounts. So, it's a Gnome problem/bug. It's reported here for Ubuntu, so, the issue can be closed:
[https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/1687019?comments=all](https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/1687019?comments=all)
Thanks!

**Comment by jangernert** [comment]
This seems to be a bug in webkit2gtk that was fixed with version 2.16.2 and 2.14.7

> Update user agent quirks to make Youtube and new Google login page work

https://webkitgtk.org/2017/05/09/webkitgtk2.16.2-released.html

There is already a commit to update the flatpak gnome sdk https://github.com/GNOME/gnome-sdk-images/commit/997249a12b6435c9f4e7afa9b898c9373f038de1
However I'm not sure if this commit only affects the latest runtime 3.24, or if webkitgtk 2.16.2 will also be included in an updated version of the 3.22 runtime.
@jscurtu do you by any chance know if the fix will be out for 3.22 as well and where we can track if the updates are already live? :)

**Comment by jangernert** [comment]
@Alexis6307 By now the webkit2gtk package should have been updated to version 2.16.2 on arch. Can you please update your system (confirm that you have the latest version of webkit) and try to log in with google again?

**Comment by 0x6d686b** [comment]
Under Fedora 25 it's broken too (installed from the system repository), even though there's no such clear error message as mentioned in the opening report. Awaiting the update for the package webkitgtk4 to jump to 2.6.12 (currently 2.6.11).

**Comment by jangernert** [comment]
You can check the status here:
https://bodhi.fedoraproject.org/updates/?packages=webkitgtk4

**Comment by jangernert** [comment]
Anyone tried with the updated gnome 3.22 runtime?
If nobody is reporting back I guess everything is working again and I can close this.

**Comment by bil-elmoussaoui** [comment]
Webkit2gtk 2.16.2 is now on Archlinux (not sure if it's already on stable or not, as i use unstable repo) but this issue is fixed on FeedReader/GOA

**Comment by Alexis6307** [comment]
Confirmed, in ArchLinux updated today it works.
