### ISSUE TITLE
g++ undefined reference

### ISSUE THREAD

**Issue by awissu** [jangernert/FeedReader#475]
Hi! 
I bumped into rpmlint erros when building rpm in OBS:
Build with flags '-Wl,--no-undefined'

> [   98s] /usr/bin/cc  -fPIC -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -O2 -g -DNDEBUG -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libowncloudUI.so -o libowncloudUI.so CMakeFiles/owncloudUI.dir/OwncloudNewsLoginWidget.c.o CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o CMakeFiles/owncloudUI.dir/owncloud.gresource.c.o -ljson-glib-1.0 -lgee-0.8 -lsqlite3 -lsecret-1 -lnotify -lrest-0.7 -lxml2 -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -ljavascriptcoregtk-4.0 -lgstpbutils-1.0 -lgstreamer-1.0 -lpeas-1.0 -lgmodule-2.0 -lgirepository-1.0 -lcurl -lgoa-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm 
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsLoginWidget.c.o: In function `feed_reader_own_cloud_news_login_widget_class_init':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsLoginWidget.vala:18: undefined reference to `feed_reader_logger_get_type'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsLoginWidget.c.o: In function `_feed_reader_login_interface_writeData_gtk_entry_activate':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsLoginWidget.vala:107: undefined reference to `feed_reader_login_interface_writeData'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsLoginWidget.c.o: In function `feed_reader_own_cloud_news_login_widget_register_type':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/build/plugins/backend/owncloud/OwncloudNewsLoginWidget.c:1084: undefined reference to `feed_reader_login_interface_get_type'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsLoginWidget.c.o: In function `peas_register_types':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsLoginWidget.vala:209: undefined reference to `feed_reader_login_interface_get_type'
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsLoginWidget.vala:209: undefined reference to `feed_reader_login_interface_get_type'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `__lambda4_':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:141: undefined reference to `feed_reader_logger_error'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_getURL':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:39: undefined reference to `feed_reader_logger_debug'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_getPasswd':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:89: undefined reference to `feed_reader_logger_error'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_setPassword':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:114: undefined reference to `feed_reader_logger_error'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_resetAccount':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:120: undefined reference to `feed_reader_utils_resetSettings'
> [   98s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_getHtaccessPasswd':
> [   98s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:164: undefined reference to `feed_reader_logger_error'
> [   99s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_setHtAccessPassword':
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:196: undefined reference to `feed_reader_logger_error'
> [   99s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_downloadIcon':
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:215: undefined reference to `feed_reader_logger_debug'
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:249: undefined reference to `feed_reader_logger_error'
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:245: undefined reference to `feed_reader_logger_error'
> [   99s] CMakeFiles/owncloudUI.dir/OwncloudNewsUtils.c.o: In function `feed_reader_owncloud_news_utils_countUnread':
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:264: undefined reference to `feed_reader_feed_getCatIDs'
> [   99s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/owncloud/OwncloudNewsUtils.vala:269: undefined reference to `feed_reader_feed_getUnread'
> [   99s] collect2: error: ld returned 1 exit status

**Comment by jangernert** [comment]
Have you tried building on your local machine first?

**Comment by awissu** [comment]
I added target_link_libraries to link libraries in plugins/backend/ttrss/CMakeLists.txt:
[  328s] /usr/bin/cc  -fPIC -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -O2 -g -DNDEBUG -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libttrssUI.so -o libttrssUI.so CMakeFiles/ttrssUI.dir/ttrssLoginWidget.c.o CMakeFiles/ttrssUI.dir/ttrssUtils.c.o CMakeFiles/ttrssUI.dir/ttrss.gresource.c.o -ljson-glib-1.0 -lgee-0.8 -lsqlite3 -lsecret-1 -lnotify -lrest-0.7 -lxml2 -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -ljavascriptcoregtk-4.0 -lgstpbutils-1.0 -lgstreamer-1.0 -lpeas-1.0 -lgmodule-2.0 -lgirepository-1.0 -lcurl -lgoa-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm ../../../libVilistextum/libvilistextum.a ../../../libgtkimageview/libgtkimageview.a ../../../libgd/libgd.a ../../../libFeedReaderCommon.a -ljson-glib-1.0 -lgee-0.8 -lsqlite3 -lsecret-1 -lnotify -lrest-0.7 -lxml2 -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -ljavascriptcoregtk-4.0 -lgstpbutils-1.0 -lgstreamer-1.0 -lpeas-1.0 -lgmodule-2.0 -lgirepository-1.0 -lcurl -lgoa-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm ../../../libVilistextum/libvilistextum.a 
[  329s] CMakeFiles/ttrssUI.dir/ttrssLoginWidget.c.o: In function `feed_reader_ttrss_login_widget_register_type':
[  329s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/build/plugins/backend/ttrss/ttrssLoginWidget.c:1156: undefined reference to `feed_reader_login_interface_get_type'
[  329s] CMakeFiles/ttrssUI.dir/ttrssLoginWidget.c.o: In function `peas_register_types':
[  329s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/ttrss/ttrssLoginWidget.vala:210: undefined reference to `feed_reader_login_interface_get_type'
[  329s] /home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/plugins/backend/ttrss/ttrssLoginWidget.vala:210: undefined reference to `feed_reader_login_interface_get_type'
Build without '-Wl,--no-undefined':
[  107s] make: Leaving directory '/home/abuild/rpmbuild/BUILD/FeedReader-2.0.2/build'
[  107s] + install -Dm0644 data/feedreader.appdata.xml /home/abuild/rpmbuild/BUILDROOT/feedreader-2.0.2-10.1.i386/usr/share/appdata/feedreader.appdata.xml

**Comment by jangernert** [comment]
I'm on mobile right now and can't read the logs very well. Is it working without no-undefined?

**Comment by awissu** [comment]
I'm not a user.
Most likely, yes.

**Comment by brendanlong** [comment]
It's possible that this is the same problem as #456

**Comment by brendanlong** [comment]
How are you running this build? I'm not very familiar with CMake so I don't know how to set the compiler flags like this.

**Comment by awissu** [comment]
> How are you running this build?
I don’t have a clue.
>  I'm not very familiar with CMake so I don't know how to set the compiler flags like this.

rpm --eval %cmake
```

    find . -name CMakeLists.txt \
        -exec sed -i -re '/^[[:blank:]]*[sS][eE][tT][[:blank:]]*\([[:blank:]]*(CMAKE_BUILD_TYPE|CMAKE_COLOR_MAKEFILE|CMAKE_INSTALL_PREFIX|CMAKE_VERBOSE_MAKEFILE).*\)/{s/^/#IGNORE /}' {} + 
    mkdir -p build 
    cd build 
    /usr/bin/cmake $OLDPWD/. \
%if "/usr/bin/make" == "/usr/bin/make" 
        -G"Unix Makefiles" \
%else 
        -GNinja \
%endif 
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_FLAGS="${CFLAGS:--O2 -g -m32 -march=i586 -mtune=i686 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_CXX_FLAGS="${CXXFLAGS:--O2 -g -m32 -march=i586 -mtune=i686 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_Fortran_FLAGS="${FFLAGS:--O2 -g -m32 -march=i586 -mtune=i686 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
        **-DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now"** \
        -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
%if "lib" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DCMAKE_SKIP_RPATH:BOOL=ON \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_COLOR_MAKEFILE:BOOL=OFF \
        -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
        -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules
```

**Comment by brendanlong** [comment]
Ok so to reproduce this we'd need to run `mkdir build && cd build && cmake .. -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" && make`

**Comment by brendanlong** [comment]
I'm not sure if running with `--no-undefined` makes sense in this case? It's complaining that the plugin doesn't define various `db_daemon` functions, but the daemon is what's loading it. I don't have any experience with this option or what it's trying to protect us from, so can you explain what the problem is?
