### ISSUE TITLE
Small issue when changing font size by ctrl + scroll

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jangernert/FeedReader#477]
Hi !

Ubuntu 16.04 on a macbook pro trackpad, I'm pretty sure this has nothing to do with my hardware given that feedreader is the only application affected.

It's just that when I use `ctrl+scroll` it changes the size of the font of the feed's text but WAY TOO FAST, moving maybe a few millimetres will set it to maximum or minimum size, which is kinda unuseable.

Let me know if I can provide anything to help you.

**Comment by jangernert** [comment]
> Let me know if I can provide anything to help you.

Donate a laptop or trackpad to me :D 
Currently every scroll event will be processed and in- or decreases the zoom level, which makes perfectly sense on a mouse with scroll wheel.
There are 2 possible solutions I can think of right now:
1. implement some sort of cool-down, so the zoom can only happen once every second or so
2. use the `delta_y` value and set the zoom according to that
However without a trackpad I can only implement these things with some dummy values. Someone would have to build the code and tweak the values a bit.

Btw: you can also zoom with `ctrl` `+/-`

**Comment by thiswillbeyourgithub** [comment]
Well thank you, I think it would be easier to stick with `ctrl+/-` then, but none of the keyboard events work with me so far, including this one. I'll close this issue and take a look if I find the issue with the keyboard on github.

Thanks !

**Comment by jangernert** [comment]
#417

**Comment by jangernert** [comment]
Can someone with a touchpad test the latest commit? It's working okay with a mouse, but I have no way of testing this on a touchpad.
This is the line to tweak:
https://github.com/jangernert/FeedReader/blob/master/src/Widgets/ArticleView.vala#L639

**Comment by bil-elmoussaoui** [comment]
@jangernert Just tried your commit, works perfectly fine!
