### ISSUE TITLE
Daemon not connected correctly by the Flatpak version

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#478]
Every time I start FR as Flatpak after the first time, the daemon spinner already spins but nothing happens. I have to kill FR and it’s pre-existing daemon and start FR again (and click on the spinner) for it getting to work correctly. So it seems to me, that an oder daemon isn't connected to a new Flatpak instance of FR.

**Comment by fbruetting** [comment]
Thanks!

**Comment by jscurtu** [comment]
Do you have a other installation running besides the flatpak version? Its probably in the autostart

**Comment by fbruetting** [comment]
Uninstalling the regualar version has left `/usr/local/share/FeedReader` and `/usr/local/lib64/FeedReader` on the system, I'll try again with these folders deleted. But this also happens when I quit FR and open it later again, so autostart cannot be the root of this problem.

Due to Jan’s reaction, this behaviour seems to be normal, though. I don't get why he pretends that some of my (far too much) filed bug reports don't exist – with me doing nothing else than just installing and updating it. What honestly shows, that the release channel just provides very poor and seemingly untested quality… 🙄. Never ever used a program showing this many bugs.
