### ISSUE TITLE
How can I use this translation po file in launchpad?

### ISSUE THREAD

**Issue by bagjunggyu** [jangernert/FeedReader#481]
I have already translated for feedreader last year, for Korean in my case.
Why don't you import those po files from launchpad?
https://translations.launchpad.net/feedreader/trunk/+lang/ko

**Comment by bil-elmoussaoui** [comment]
We don't use Launchpad anymore, translations are now here https://www.transifex.com/dev-feedreader/feedreader
You don't need anything, just log in with your Github Account and request to join a translation team; i will accept it, and just after that you can translate the application.
+ The source code on Launchpad is out of date. We can't keep using that tool anymore, it just sucks in every possible way
