### ISSUE TITLE
FeedReader 2.0.2 build is broken with vala-0.36

### ISSUE THREAD

**Issue by Gottox** [jangernert/FeedReader#485]
Build output: https://github.com/voidlinux/void-packages/issues/6408

Workaround for vala-0.36: https://github.com/voidlinux/void-packages/commit/3d4df7571d627e5f16d1acd1b1cca5ee3e8ec13c (breaks gettext support for those strings, though)

**Comment by jangernert** [comment]
Already like your patch in master ;) https://github.com/jangernert/FeedReader/blob/master/Constants.vala.in#L46
If you know a better way to fix this issue let us know :)
