### ISSUE TITLE
It is not possible to connect feeds, there is no choice of services.

### ISSUE THREAD

**Issue by romanstepanov** [jangernert/FeedReader#487]
It is not possible to connect feeds, there is no choice of services.
![2017-05-21 12-57-34](https://cloud.githubusercontent.com/assets/28838417/26282967/018435b6-3e26-11e7-9375-f7b082a8973b.png)

**Comment by jangernert** [comment]
This is most likely the fault of packaging.
FeedReader looks for plugins in $LIBDIR/plugins. If none are installed the list will be empty.
