### ISSUE TITLE
Cannot add any account

### ISSUE THREAD

**Issue by simonnam** [jangernert/FeedReader#491]
Hi,
I've installed FeedReader on Debian Sid using Flatpak. First issue - FeedReader is not added to application menu (GNOME 3).
I run FeedReader via a terminal:
`flatpak run org.gnome.FeedReader`
In terminal I see some debug info with some errors (see attached file: [debug_info.txt](https://github.com/jangernert/FeedReader/files/1026735/debug_info.txt)).
If I want to add a new account (_New account_ button) nothing happens and below error is showed in the terminal:
`[ ERROR ] ResetPage.resetAllData: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files`
Could you have a look, please?

Thanks,
Szymon

**Comment by jangernert** [comment]
Did you restart or log out after installing the flatpak?
For whatever reason this seems to solve these kinds of problems for other people.

**Comment by simonnam** [comment]
It seems that restart helped. Thank you very much :)

**Comment by bil-elmoussaoui** [comment]
@jangernert What causes this issue? Flatpak? If so, i will report it upstream :)

**Comment by jangernert** [comment]
No idea. @jscurtu mentioned the workaround at some point.

**Comment by jscurtu** [comment]
Its caused when flatpak is fresh installed and not initialized.  Sofar only seen this on debian.
