### ISSUE TITLE
Get it on AppCenter

### ISSUE THREAD

**Issue by Philip-Scott** [jangernert/FeedReader#494]
You should look into pushing your app into elementary's AppCenter :) 

Here's the link were you can do so: developer.elementary.io

Feel free to ask for any questions you might have

**Comment by jangernert** [comment]
Then my first question would be, can we expect an update to the gnome stack in elementary any time soon? :D
https://plus.google.com/+CassidyJames/posts/LwAu71E8Mqw

**Comment by Philip-Scott** [comment]
Oh darn... I think that will be next cycle since we are currently based on ubuntu's LTS...


I'm not sure what you're using show_uri_on_window for, but if that's your only blocker maybe you could use compilation flags to enable/disable chunks of code depending the version you have.

**Comment by jangernert** [comment]
`show_uri_on_window` is for the flatpak. Then there is the CSS thing and some gdk screen code. It surely is possible to ifdef all these things. But that sounds like a lot of work for nearly 2 year old gnome release.

**Comment by Philip-Scott** [comment]
oh, i understand. Hopefully we will support flapak or something soon so gtk versions won't matter :) For now, feel free to close this report

**Comment by aleksandar-todorovic** [comment]
It's been a while since this issue was opened, but maybe it's time to reconsider this?

elementary OS 5.0 (Juno) is in [second beta](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb), and as far as I can tell, it's based on Gtk v3.22:

```bash
$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version        Architecture   Description
+++-==================-==============-==============-==========================================
ii  libgtk-3-0:amd64   3.22.30-1ubunt amd64          GTK+ graphical user interface library
ii  libgtk2.0-0:amd64  2.24.32-1ubunt amd64          GTK+ graphical user interface library
```

I know I would pay at least $5 for it in the store.

**Comment by bilelmoussaoui** [comment]
It's up to @jangernert to set up the account. I might take care of the rest

**Comment by bilelmoussaoui** [comment]
I don't think they allow such things. @danrabbit @cassidyjames any ideas guys?

**Comment by bilelmoussaoui** [comment]
@jangernert Yeah still a student! That would be awesome & it will allow me to work more on open source stuff

**Comment by jangernert** [comment]
I just logged into the appcenter dashboard and submitted v2.3 of FeedReader. The bot should probably file some issues against the repository. Once we sort them out we can publish the app I guess. @bilelmoussaoui payment is done via 'Stripe'. After publishing we can figure out how to connect your bank data to it.

**Comment by bilelmoussaoui** [comment]
@jangernert elementary Appcenter will force us to use `com.github.jangernert.feedreader` as an appID. We already use that everywhere, even Flatpak....

**Comment by Philip-Scott** [comment]
I'd recommend setting the Stripe thing as early as possible, when you first publish an app it will be in the front page, and it's usually when you get the biggest influx of purchases :) 

I think if you make @bilelmoussaoui an owner of this repo, he should be able to login and set up the Stripe stuff

**Comment by bilelmoussaoui** [comment]
@Philip-Scott I was able to set my Stripe account without any issues. The only missing part is the possibilty to use `org.gnome.FeedReader` instead of `com.github.jangernert.FeedReader` as an appID

**Comment by brendanlong** [comment]
Looks like #764 is related to this.
