### ISSUE TITLE
Make it easy to copy feed URLs

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#496]
Would be nice to have a way to copy the feed's URL, or open the attached website when right-clicking on the feed's list entry.

**Comment by jscurtu** [comment]
@hadess you could double click on the feed's list entry..

**Comment by hadess** [comment]
That doesn't do anything in the stable version.

**Comment by hadess** [comment]
> Would be nice to have a way to copy the feed's URL, or open the attached website when right-clicking on the feed's list entry.

Do you mind if I open a new bug to have the `<link>` from the RSS feed also added as a menu item (probably just to open that link though)?

For example, in :
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Planet GNOME</title>
<link>http://planet.gnome.org/</link>
<language>en</language>
<description>Planet GNOME - http://planet.gnome.org/</description>
<atom:link rel="hub" href="http://pubsubhubbub.appspot.com/"/>
<atom:link rel="self" href="http://planet.gnome.org/rss20.xml" type="application/rss+xml"/>
```

This would open the website `<link>` URL, rather than copy the feed URL.

**Comment by bil-elmoussaoui** [comment]
I don't know, let's see what @jangernert thinks about that
