### ISSUE TITLE
Cannot sync with ttrss

### ISSUE THREAD

**Issue by giovi321** [jangernert/FeedReader#497]
I tried for the first time to configure FeedReader with my ttrss instance, but I cannot get it to sync for the first time. The sync button just show the wheel stuck in the same position and no articles appear (although the categories and the feeds list is available on the left).
Info:
Tiny Tiny RSS version: v17.4 (07d3431)
FeedReader version: 2.0.2 installed through flatpak
OS: Debian 8

**Comment by jangernert** [comment]
Can't do much without logs of the feedreader-daemon process.

**Comment by giovi321** [comment]
Is this the log needed?
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getTitle: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_fullscreen_header_setTitle: assertion 'title != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getMarked: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getUnread: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getHTML: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getTitle: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getURL: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getAuthor: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getDateNice: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_article_getFeedID: assertion 'self != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: feed_reader_utils_ui_buildArticle: assertion 'html != NULL' failed
Jun  5 16:55:04 01PC feedreader[20391]: void webkit_web_view_load_html(WebKitWebView*, const gchar*, const gchar*): assertion 'content' failed
Jun  5 16:55:32 01PC org.gnome.FeedReader.desktop[20380]: #033[94m[ DEBUG ] #033[0mOpening Database: /home/giovi/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-04.db

**Comment by jangernert** [comment]
nope

**Comment by giovi321** [comment]
Could you explain where is the log you would like to see, please? I cannot find in in syslog

**Comment by jangernert** [comment]
No, no idea how to do that with flatpak. With a normal install you just run 'feedreader-daemon' from shell.

**Comment by jscurtu** [comment]
I will give instructions later on today how to do it with flatpak when I am on a computer.

**Comment by jscurtu** [comment]
the easiest way is, from a terminal do : 

cat .var/app/org.gnome.FeedReader/data/feedreader/daemon.log

or

1. Enable hidden files in Nautilus (Files) or any other Filemanager.
2. Go to: .var/app/org.gnome.FeedReader/data/feedreader/
3. Find 2 files: daemon.log and ui.log 

if that is not enough, let me know.
Thanks. 

Jason
