### ISSUE TITLE
Adding support for a custom feed aggregator

### ISSUE THREAD

**Issue by urandom** [jangernert/FeedReader#501]
Hi,

I have my own feed aggregator (https://github.com/urandom/readeef) which I would look to see support of in FeedReader.  My big problem is that I have no idea how to work with Vala, so I can pretty much only go by using examples of other implementations in here. The api is also through a websocket, and from what I saw before, the others were REST based (though that could've changed now, seeing as there are quite a few more imeplementations). 

Are there any tips as to how I can start with this, and maybe resources for how to do websockets and crypto in Vala?

**Comment by jscurtu** [comment]
Hi Victor, to get started Valadoc might be a good starting point. 
https://valadoc.org/libsoup-2.4/Soup.WebsocketConnection.html

Also, looking at other implementations done in feedreader help alot, if you know C#/Java a little you will find its similar in the syntax and I am sure if you have any questions feel free to join us here:
https://gitter.im/Feedreader-dev/Lobby

**Comment by jangernert** [comment]
Also libpeas supports plugins in C and python just as well. Although I have never written a single line of python and can't really tell you how that would work :D
