### ISSUE TITLE
Add support for OS X

### ISSUE THREAD

**Issue by xfbs** [jangernert/FeedReader#503]
Hey, is it possible to publish builds and package it as an .app for OS X users?

**Comment by jangernert** [comment]
Well, you would at least have to own a mac and be somewhat familiar with how to build gtk+ applications on OSX.
I never owned a mac and don't plan to change that.

**Comment by rodneyrod** [comment]
Would you be open to accepting pull requests to enable OSX support?

**Comment by brendanlong** [comment]
I think at this point, probably not. We're sort of low on maintainers as-is, and I don't think we can realistically add support for a platform we don't use without creating a bad user experience. FeedReader is also very GNOME specific, so I suspect this is harder than you might think. For example, we depend on gnome-keyring and certain features of GNOME's networking and configuration.

**Comment by brendanlong** [comment]
It's not free, but Reeder for Mac is pretty nice: http://reederapp.com/mac/

**Comment by jangernert** [comment]
MacOS has probably the largest selection of good RSS readers. I haven't tried any of them, but as @brendanlong mentioned there is reeder, [ReadKit](https://readkitapp.com/), [Vienna](https://www.vienna-rss.com/), [NetNewsWire](http://netnewswireapp.com/), [Leaf](https://itunes.apple.com/us/app/leaf-the-news-reader/id576338668?mt=12) and tons more

**Comment by rodneyrod** [comment]
@brendanlong Thanks for that, I can see this wouldn't be an easy task.

Was more so asking since this seems to be the only feed reader that supports DecSync, but I might see if the Vienna devs might be open to implementing support for it. Thanks for your help.
