### ISSUE TITLE
Impossible to select service on setup, not visible

### ISSUE THREAD

**Issue by eldelacajita** [jangernert/FeedReader#504]
When I load the app, I get the service selection screen but it's blank, so I cant' select any service. 

![captura de pantalla de 2017-06-25 12-48-17](https://user-images.githubusercontent.com/2880679/27515520-5dd68e64-59a5-11e7-8e33-1b2b37f2285c.png)

This is what I get when I run it from the terminal:

[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/jt/.local/share/feedreader/data/feedreader-04.db
[ DEBUG ] database already initialized
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -76
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList

I'm running version 2.0.2-3 from antergos repository in Antergos.

**Comment by GitHubNemo170216** [comment]
I have precisely the same problem also in Antergos.

**Comment by jangernert** [comment]
Same as #510
Search path for the plugins can be configured at build time. So the package maintainer should fix this.

**Comment by bil-elmoussaoui** [comment]
It's an upstream issue for Antergos please use the AUR repository (that i maintain myself)
