### ISSUE TITLE
Unable to login FreshRSS

### ISSUE THREAD

**Issue by KINFOO** [jangernert/FeedReader#505]
Hi,

I run _FeedReader_ from __Debian Testing__ installed with `flatpak`.
Looks good.

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27630969-62cb2e26-5bf7-11e7-9efd-dfd9c3c5db0e.png"/></p>

# Issue

When I try to login, my credential always seem to be invalid 😞

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27631073-a01cd78e-5bf7-11e7-87a3-874e7a4181ef.png"/></p>

# Tracking issue

## My FreshRSS server

I host my _FreshRss_, so I check my configuration:

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27631227-28233ef2-5bf8-11e7-8db2-4c885f4535ad.png"/></p>

> Configuration page shows

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27631259-4400cf36-5bf8-11e7-94c2-435d435a1b6e.png"/></p>

> Full server configuration __fails__.

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27631344-738d1cc8-5bf8-11e7-8225-37afe09019a4.png"/</p>

> Partial server configuration __works__.

## %2F support

Checking my configuration, it appears __%2F is not working__.
Going deeper, I get it is an [Apache configuration parameter](http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes).
My FreshRSS instance lives on a __shared server__. I do not have access to Apache configuration. I can only specify some `.htaccess`, they are useless in our case.

So I start to wonder why is important to support URLs that appear faulty to me...

Then, I read jangernert/FeedReader#59, more precisely [this comment](https://github.com/jangernert/FeedReader/issues/59#issuecomment-246190756) from @Alkarex which contains:

    [REQUEST_URI] => /api/greader.php/reader/api/0/stream/contents/user%2F-%2Fstate%2Fcom.google%2Freading-list?client=newsplus&ck=1473611612571&xt=user/-/state/com.google/read&n=1000&r=n

> Several `%2F` there 😸 

# Conclusion

_FeedReader_ might manage to connect my _FreshRSS_ better if my server could handle `%2F`.
Still, I wonder, why does _FeedReader_ API calls explicitly use `%2F` instead of plain `/`?

Thanks for the good work

**Comment by Alkarex** [comment]
If the client avoids doing the %2F encoding, it works also when the server blocs %2F.

* Could you please check your Web server logs, and show what precise URL gives a 404?
* Could you please try typing your full API address (including the `greader.php` part)?

For the record, FeedReader attempts to guess the full API URL, but the code might have to be improved:
https://github.com/jangernert/FeedReader/blob/3d25bd8d10231e9642d0c645f54216c61d959ac8/plugins/backend/fresh/freshUtils.vala#L30-L34

**Comment by KINFOO** [comment]
Hi,

## Trying with server address

![screenshot_20170629_120942](https://user-images.githubusercontent.com/154818/27682761-0adca9ba-5cc4-11e7-96f8-e8aa57f66fed.png)


## Trying with full API address

<p align="center"><img src="https://user-images.githubusercontent.com/154818/27682536-3c406574-5cc3-11e7-9000-16163bdb7d90.png"/></p>

## Server logs

None of the previous generated sever logs.
And still, UI display different error messages😕

If I directly enter `http://feed.kinfoo.fr/p/api/greader.php` in a browser, I get this response:

    Bad Request!

And it generates this Apache log:

    84.14.163.130 - - [29/Jun/2017:12:10:43 +0200] "GET /p/api/greader.php HTTP/1.1" 400 32 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "20170629121043"

Do you think a `%2F` ➡️ `/` string replace would do the trick in the portion of code you mentioned above?

Thank for your fast answer

P.S.: i would gladly avoid exposing `/p`, but behind my dedicated domain lives a _shared hosting_ which serves what is under `htdocs`. I found no documentation allow to change this...

**Comment by Alkarex** [comment]
The error 400 could be if your Apache server does not process this .htaccess file:
https://github.com/FreshRSS/FreshRSS/blob/master/p/api/.htaccess

**Comment by KINFOO** [comment]
I edited this file trying to activate `AllowEncodedSlashes`.
My attempts made this directory unavailable to browsing.
Do you want me to try again without `.htaccess`?

**Comment by Alkarex** [comment]
@KINFOO Sorry for the delay. No, the `.htaccess` is needed. Could you please check that mod_rewrite is enabled on your server? A quick test is to remove the `if` on lines 1 and 4 of https://github.com/FreshRSS/FreshRSS/blob/master/p/api/.htaccess

**Comment by KINFOO** [comment]
I removed them, same result.

![screenshot_20170716_150649](https://user-images.githubusercontent.com/154818/28247815-7aac0e3a-6a38-11e7-87aa-ec847587a943.png)

**Comment by Alkarex** [comment]
Sorry for the delay. Did you check whether mod_rewrite is well enabled on your Apache server?

**Comment by jangernert** [comment]
@KINFOO @Alkarex Thx for helping out with this problem here.
I just read over the code and am wondering why only the labelID has the `/` encoded as %2F.
It gets defined here:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/fresh/freshInterface.vala#L297
Added to the path here:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/fresh/freshAPI.vala#L189
And is finally sent here:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/fresh/freshConnection.vala#L108
No URL encoding as far as I can see is being done.

Or was the 
```
[REQUEST_URI] => /api/greader.php/reader/api/0/stream/contents/user%2F-%2Fstate%2Fcom.google%2Freading-list?client=newsplus&ck=1473611612571&xt=user/-/state/com.google/read&n=1000&r=n
```
just an example?

If so, the only thing I can think of is the forward slash in the message being encoded to %2F.
In this case you could change this line:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/fresh/freshConnection.vala#L145
to:
```
request += GLib.Uri.escape_string(val, "/");
```
to encode everything but the forward slash.

Does that help?

**Comment by Alkarex** [comment]
I think there is probably more than one problem with @KINFOO 's server, but yes @jangernert it would be nice to avoid `%2F` encoding to simplify the interaction with Apache.

**Comment by Alkarex** [comment]
👍

**Comment by mappu** [comment]
Hi,

How to install the updated version?

The flatpak installation gives me an older version `a6bb1d69` (is it 2.0.2?) that is still affected by this issue,

**Comment by jscurtu** [comment]
currently the flatpak build only contains stable releases.
