### ISSUE TITLE
Unable to log in to InoReader

### ISSUE THREAD

**Issue by mnmlguy** [jangernert/FeedReader#506]
Hi!
I'm using the git package from AUR on Arch Linux (Gnome) and the application freezes when clicking the InoReader service on startup. The app is showing a blank page and the terminal is spamming this message:

`** (feedreader:13291): DEBUG: ooops! Looks like FeedReader crashed
onCrash
`

After a couple of seconds I have to force quit.

Other RSS services work fine.

**Comment by jangernert** [comment]
Confirmed and fixed. Somehow a print to `GLib.log_structured` was crashing the application =/
