### ISSUE TITLE
Debug always enabled

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#507]
Using the stable Flatpak bundle, debug is always enabled and tons of data is dumped in the journal:
```
$ uptime
 13:52:24 up 5 days, 23:52,  2 users,  load average: 1.41, 1.36, 1.21
$ journalctl -b | grep org.gnome.FeedReader.Daemon | wc -l
23863
```

That's an average of 2 lines per minute, all the time.

**Comment by jscurtu** [comment]
do you have org.gnome.FeedReader.Debug installed?

**Comment by raczkow** [comment]
I'd like to refresh this issue. I've build Ubuntu package from sources (git from master branch) and my syslog is flooded with feedreader data:

`
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: actual articles loaded: 0
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: ArticleListScroll: scrolled down off cooldown
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: ArticleListScroll: trigger scrolledBottom()
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: ArticleList.loadmore()
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: load articles from db
Nov 23 15:32:46 pooh org.gnome.FeedReader.desktop[16866]: ** (feedreader:16866): DEBUG: SELECT count(*) FROM articles WHERE rowid < (SELECT rowid FROM articles WHERE articleID = "20005" ) AND unread = 9  ORDER BY rowid COLLATE NOCASE ASC
`

Out of 628k lines of syslog 625k lines are prodeuced by feedreader.

Is there a way to disable DEBUG logging?

**Comment by brendanlong** [comment]
Hm so the way we have logging setup uses this:

https://developer.gnome.org/glib/stable/glib-Message-Logging.html#g-log-writer-standard-streams

So the easy fix would be to  only log stderr. I'm not sure how easy that would be for you to do.

I'm fine with having an option to completely disable debug logs but I don't know what it should look like.

**Comment by bil-elmoussaoui** [comment]
@brendanlong We can easily add a --verbose argument, and only enable logs if the user starts the application using feedreader --verbose?

**Comment by jangernert** [comment]
9ae3f35004f4d7b5f63e93bf78b30b3ca9a61ebc

**Comment by kouwex** [comment]
With the 2.9.2 flatpak version FeedReader spams the system log with INFO and DEBUG messages on feed update.
Also, GdkPixbuf-DEBUG messages show up with the FeedReader window in background with no (visible) activity

**Comment by brendanlong** [comment]
It would be nice to get rid of those GdkPixbuf logs since we never use them. I'm tempted to call the rest "not a bug" though, since the logs are pretty important for debugging and it's already hard enough to figure out problems without backtraces :\

**Comment by kouwex** [comment]
I see your point. I may be too sensitive about my syslog, but it would be nice to have a visible button to toggle it on the user side if that's default behaviour
