### ISSUE TITLE
Loads of JSON errors

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#509]
Using Flatpak stable, I see loads of those when sync starts:
```
Jul 04 13:45:13 classic feedreader-daem[2982]: json_object_get_string_member: assertion 'node != NULL' failed
Jul 04 13:45:13 classic feedreader-daem[2982]: string_contains: assertion 'self != NULL' failed
```

**Comment by jangernert** [comment]
Well, I don't see them. So .... ?

**Comment by hadess** [comment]
You use the stable version? How can I get information about why it's failing? Run feedreader-daemon under gdb?

**Comment by jangernert** [comment]
Nah, I'm on master. Also I use ttrss and this is most likely something in the feedly back-end.
The position where the errors appear in the log also can give a lot of information.
FeedReader gets thinks in the following order (from the top of my head):
1. [categories](https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyAPI.vala#L148)
2. [feeds](https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyAPI.vala#L193)
3. [tags](https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyAPI.vala#L266)
4. [articles](https://github.com/jangernert/FeedReader/blob/master/plugins/backend/feedly/feedlyAPI.vala#L302)
depending on that you can narrow down the problem.

If you need more help to help yourself just hop on gitter and I'll try to answer any questions.
