### ISSUE TITLE
openSUSE package is looking in an invalid location for plugins.

### ISSUE THREAD

**Issue by AmandaCameron** [jangernert/FeedReader#510]
I'm seeing an empty sources list with the openSUSE packaged version of this.

Ran it through an strace and found the following:

    open("/usr//usr/lib64/FeedReader/pluginsUI/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by jangernert** [comment]
Then you should report that to the openSUSE package maintainer ;)
