### ISSUE TITLE
Always "Offline"

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#511]
In the stable Flatpak version:
```
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] feedly backend: login
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping: http://feedly.com/
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping: status 200
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] Ping successfull
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ ERROR ] Feedly: getToken response - missing code
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] refresh token
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
Jul 05 10:29:31 classic org.gnome.FeedReader.Daemon[1703]: [ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
```

Running `flatpak run -d --command=/bin/bash org.gnome.FeedReader`:
```
$ gsettings list-recursively org.gnome.feedreader.feedly
org.gnome.feedreader.feedly refresh-token ''
org.gnome.feedreader.feedly api-code ''
org.gnome.feedreader.feedly access-token ''
org.gnome.feedreader.feedly email 'email@address'
org.gnome.feedreader.feedly access-token-expires 1499720411
```

(the address is obfuscated)

This changes nothing:
```
$ gsettings reset org.gnome.feedreader.feedly refresh-token
$ gsettings reset org.gnome.feedreader.feedly api-code
$ gsettings reset org.gnome.feedreader.feedly access-token
```

**Comment by hadess** [comment]
Would be great to have some feedback here, or hints as to what info to get for that problem, as I haven't been able to use FeedReader since that bug.

**Comment by jangernert** [comment]
Both refresh-token and access-token were lost, you have to log in again to get new ones.
If you can tell me how you ended up without tokens I can try to fix it. Never happened to me or other devs that use feedly.

**Comment by hadess** [comment]
There's no way to just "re-log in". I need to click "Change Account" which tells me it will delete all the local data for the old account.

**Comment by jangernert** [comment]
Since everything (except the downloaded full articles/images) is also stored on the feedly server that doesn't sound too bad.
But you can still backup all your data and manually copy it over once you logged in again.
`$HOME/.local/share/feedreader/data`

**Comment by bil-elmoussaoui** [comment]
I would really love to know if this issue only happens with Feedly. I use Feedly myself and i can reproduce it, so if it can be reproduced with other plugins it would be great to know. It will make the tracking of the issue easier

**Comment by brendanlong** [comment]
It would be nice if the UI could prompt people to log back in if their credentials stop working. It would fix this, and also fix cases where a user's password actually changes.

**Comment by hadess** [comment]
> But you can still backup all your data and manually copy it over once you logged in again.

FWIW, that didn't work as expected, as it re-downloaded a lot of things for a couple of hours (at least 1, then I went to bed).

**Comment by gicmo** [comment]
> I would really love to know if this issue only happens with Feedly. I use Feedly myself and i can reproduce it, so if it can be reproduced with other plugins it would be great to know. It will make the tracking of the issue easier

I had this happen recently with feedbin. So I guess the answer sadly is no.

**Comment by qazip** [comment]
It's happening with nextcloud as well.

**Comment by hadess** [comment]
This is with the current FeedReader stable from Flathub (commit `2583f0cf1abca22debdfba5ebae50a29d2a69e1a066bc50000b1db932c9ced90`):
```
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] feedly backend: login
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] Ping: http://feedly.com/
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] Ping: status 200
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] Ping successfull
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ ERROR ] Feedly: getToken response - missing code
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [WARNING] FeedlyUtils: access token expired
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] refresh token
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [WARNING] FeedlyUtils: access token expired
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ ERROR ] Feedly: refreshToken response - missing refresh_token parameter
Apr 13 11:34:06 classic org.gnome.FeedReader.Daemon[2743]: [ DEBUG ] daemon: login status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
```

**Comment by hadess** [comment]
Note that my credentials didn't change, the token expired, as per the log above.

**Comment by hadess** [comment]
It seems to work as expected now. I launched FeedReader (from Flathub) and it offered to log me in again to my Feedly account. It then updated all my feeds. I'll reopen if it happens again.

**Comment by brendanlong** [comment]
Thanks for the update!
