### ISSUE TITLE
Can't login to feedly with google account

### ISSUE THREAD

**Issue by egor-h** [jangernert/FeedReader#512]
I see only blank screen
https://i.imgur.com/MnClxTg.png
I have this in terminal
https://pastebin.com/CBHFM77w

**Comment by bil-elmoussaoui** [comment]
This is a webkit2gtk issue (the library we use to show the article content). And it has been already fixed upstream. Please upgrade to the latest version of webkit2gtk (unless you're using the flatpak version)

**Comment by RafaelLinux** [comment]
Still same problem. 
1 - Installed FeedReader 2.6.0 in OpenSUSE 15 thru Discover (Plasma)
2- Launch FeedReader
3- Select "Feedly", then "Google account"
4- Wait forever with the FeedReader windows in blank.

Any fix for this? Thank you
