### ISSUE TITLE
Port from CMake to Meson

### ISSUE THREAD

**Issue by bilelmoussaoui** [jangernert/FeedReader#514]
Meson is a "new" build system. Which supports GNOME Natively with a Gnome plugin. And also has 0 dependencies. It's a lot faster than Autotools and more readable by humans. I have been converting few projects lately to use Meson instead.

I can work on this if everyone agrees. The build time will be much shorter.

**Comment by jangernert** [comment]
Meson/ninja isn't that much faster than CMake.
I personally don't care if CMake or Meson is used.
If you want to, you can port the project. But on the other hand you could spend the time on the themes branch :D

**Comment by bil-elmoussaoui** [comment]
@jangernert The base of themes is already working as expected (I guess?). The only missing part is writing some HTML/CSS code :P 
There are few improvements that I would like to add. But the build time is taking too much on my laptop. I will try porting the project to Meson if this improves the situation I will open a PR.

**Comment by brendanlong** [comment]
I'm not really a fan of CMake so if you think Meson is better it's fine with me.

**Comment by bil-elmoussaoui** [comment]
A lot of projects were ported recently to Meson. Which has an active development status compared to CMake or Autotools. 
I will try to finish this up by the next week i hope

**Comment by bil-elmoussaoui** [comment]
It took more time than i expected, i will create a PR this weekend :smile:

**Comment by AsavarTzeth** [comment]
Looking forward to this. I could not help but notice that the data files are still not translatable. In my experience it is a great deal simpler with Meson to provide i18n with appdata and desktop entries.

**Comment by AsavarTzeth** [comment]
By the way, @bil-elmoussaoui if you need help with anything in order to finish this, I am at your service.

**Comment by matthewdias** [comment]
now that we've switched over, what are the steps to build from source? maybe we should update the README as well.

**Comment by jangernert** [comment]
Instead of 
```
cmake ..
make
sudo make install
```

it is now (`ninja` may be named `ninja-build` depending on the system)
```
meson ..
ninja
sudo ninja install
```

**Comment by AsavarTzeth** [comment]
Actually, meson will create the build directory for you. So you could also do it the following way:

```
meson build
cd ./build
ninja
sudo ninja install
```

or:

```
meson build
ninja -C build
sudo ninja -C build install
```

**Comment by bilelmoussaoui** [comment]
Fixed on master. Finally :1st_place_medal:
