### ISSUE TITLE
Coding style?

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#516]
Our code style is pretty random right now so I was hoping to run it through [`uncrustify`](http://uncrustify.sourceforge.net/), but I don't know what the coding style should be since we're currently not consistent.

Is it ok to go with this GNOME Vala style: https://wiki.gnome.org/Projects/Vala/Hacking#Coding_Style

- tab indent
- CamelCase types
- under_score variables
- open brace on same line

The only really weird things that are the space before `(` in function declarations and function calls, and tabs for indentation. I'm fine with it though since it seems to be "the Vala style".

What do you think?

**Comment by bil-elmoussaoui** [comment]
The tab indent case is already handled with the .editorconfig file. We only need to fix that on the rest of files;

**Comment by brendanlong** [comment]
Ugh I had to revert the uncrustify thing since it wanted to add spaces around `?` in nullable types and doesn't seem to have any way to turn it off:

https://github.com/uncrustify/uncrustify/issues/1290

**Comment by jangernert** [comment]
@brendanlong I'm guessing just had to revert one specific thing? Because most of the changes still landed in master?

**Comment by brendanlong** [comment]
@jangernert Sorry I forgot to push somehow :\ I just reverted the whole commit. I'll try to think of a better way to fix this, since `uncrustify` seems to not work right with Vala.

**Comment by bil-elmoussaoui** [comment]
@brendanlong I have started fixing some code styling stuff. I have converted spaces to tabs and removed empty spaces on almost all files https://github.com/jangernert/FeedReader/pull/534. 
Next step would be cleaning files one by one to make sure everything is correctly respected :+1:

**Comment by brendanlong** [comment]
Awesome!

**Comment by brendanlong** [comment]
Opened https://github.com/uncrustify/uncrustify/issues/2090 to make it so we can just use Uncrustify

**Comment by brendanlong** [comment]
It seems like uncrustify is having some trouble with lambdas, classes and namespaces. I opened https://github.com/uncrustify/uncrustify/issues/2189 with upstream to see if they can help figure out what's going on.
