### ISSUE TITLE
When full sized a portion of the window flashes

### ISSUE THREAD

**Issue by egladman** [jangernert/FeedReader#520]
I suspect this is an issue with xwayland (Fedora 25), but I'll go ahead and report this here anyway just in case. I'm using the default binary in the fedora repository. Whenever I maximize the window, the bottom right portion of the screen continuously flashes until the window is unfocused or unmaximized. 

![screenshot_1](https://user-images.githubusercontent.com/8713153/28831184-e732243e-76a6-11e7-8df7-0a7a22329379.png)
![screenshot_2](https://user-images.githubusercontent.com/8713153/28831182-e67e6980-76a6-11e7-9e30-3fc0ab8713d3.png)

**Comment by jangernert** [comment]
Pretty sure this is not specific to FeedReader. Did you try the same thing with similar Gtk+ applications? Like Gedit with activated sidebar.

**Comment by egladman** [comment]
I figured that was the case. I'm unable to reproduce the same behavior with Gedit.

**Comment by jangernert** [comment]
With activated sidebar? (this way gedit also has a split headerbar)

**Comment by egladman** [comment]
I don't use gedit. But from my understanding activated sidebar can be enabled with `F9`. If so, yes.

**Comment by bil-elmoussaoui** [comment]
I can't reproduce this at all. Are you using wayland ? or xorg?

**Comment by egladman** [comment]
@bil-elmoussaoui Wayland

The application only exhibited the problem when it was **ran the first time**. When I killed the process and reran the program the issue went away. I've since been unable to replicate the issue.

**Comment by bil-elmoussaoui** [comment]
Must be a Wayland issue i guess. Please open an issue about that upstream unless you're able to reproduce it on xorg
