### ISSUE TITLE
Linking C executable build error.

### ISSUE THREAD

**Issue by Justinzobel** [jangernert/FeedReader#523]
[ 49%] Linking C executable feedreader
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `feed_reader_media_player_toggleMute':
/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:399: undefined reference to `N_'
/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:392: undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `feed_reader_media_player_togglePause':
/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:220: undefined reference to `N_'
/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:212: undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o: In function `feed_reader_media_player_buildUI':
/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:132: undefined reference to `N_'
CMakeFiles/feedreader.dir/src/Widgets/MediaPlayer.c.o:/home/build/YPKG/root/feedreader/build/FeedReader-2.0.2/src/Widgets/MediaPlayer.vala:145: more undefined references to `N_' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/feedreader.dir/build.make:1857: feedreader] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/feedreader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by jangernert** [comment]
I guess you are building with a very recent vala version?
https://github.com/flathub/org.gnome.FeedReader/blob/master/fix-vala.patch

**Comment by Justinzobel** [comment]
vala 0.36.3

**Comment by Justinzobel** [comment]
Yup that patch fixed, it. Sorry for not searching and adding to your workload. Same issue as #410
