### ISSUE TITLE
Image enlargement window doesn’t respect screen size limit

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#524]
I use the current Flatpak version on Fedora 26 with Wayland and an 15" UHD screen. If I click on the image of [this article](https://nextcloud.com/blog/app-store-updates/), the window of the enlarged image has more height than my screen. I made the following screenshot after disconnecting my external monitor and restarting FR. Before disconnecting the external monitor, the image was scaled to fill the whole window somehow, but the window had the same size. But could be a bug in Wayland…?

![einzeln](https://user-images.githubusercontent.com/10520767/29182394-ffe04024-7dfe-11e7-8991-2220df1d9aef.png)

**Comment by jscurtu** [comment]
what resolution is your external monitor? and your UHD screen?

**Comment by fbruetting** [comment]
Internal: 3840x2160 (UHD)
External: 1920x1080 (HD)
