### ISSUE TITLE
Getting FeedReader into Debian repository

### ISSUE THREAD

**Issue by fredddii** [jangernert/FeedReader#527]
While I do not have any experience with Debian packaging myself, would it be possible for anyone who would be up for it to get it in the Debian repository?

**Comment by jangernert** [comment]
If the gnome stack of the debian version targeted is recent enough, I don't see a reason why it shouldn't be possible ;)

**Comment by bil-elmoussaoui** [comment]
I don't think anyone is using Debian here (the guys who works on FeedReader). But if someone can get that done and send a PR with the steps to install it that would be awesome. 
As we don't have any idea how Debian packaging works, we won't sadly be able to maintain it; There was an Ubuntu PPA at some moment, but the gnome stack was too old to use.
