### ISSUE TITLE
Ensure the uniqueness of the feeds

### ISSUE THREAD

**Issue by tchoutri** [jangernert/FeedReader#531]
Hi! Perhaps adding one or two unique constraints in the database schema could be useful in case we import the same OPML file twice :)
(BTW, thanks again for this marvelous piece of software, the UI is fantastic!)

**Comment by bil-elmoussaoui** [comment]
Hey,
thanks for the report. That seems to be something that should be fixed indeed. Currently, I don't think someone has the time to fix it. But here's the line of code where it should be added
https://github.com/jangernert/FeedReader/blob/master/src/dbBase.vala#L70

This might require some modification in the local plugin too. Here's the line where the addFeed is handled
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/local/localInterface.vala#L171
If you think you can send a PR with a fix, that would be great ! :+1:

**Comment by tchoutri** [comment]
@bil-elmoussaoui Hi! Thanks for the quick answer! I actually do not know anything about Vala, so I may need some guidance, if you're available, about what should be done for the local plugin. :)
Thanks!

**Comment by bil-elmoussaoui** [comment]
We have a [Gitter](https://gitter.im/Feedreader-dev/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel, so don't hesitate to ask whatever questions there
