### ISSUE TITLE
Conversion filter

### ISSUE THREAD

**Issue by WhatsThePlan** [jangernert/FeedReader#536]
Hi, i would like to ask support for conversion filters like liferea does. with conversion filters feedreader passes raw source/html of url to executable script or command line (stdin). script will then produce actual rss feed via stdout.

this allows making rss feeds for sites that dont have any (bugzilla etc), try to force users to subscribe via mail or user account or own API (instagram, twitter) or just allows user to perform additional filtering or transformation. thanks.

**Comment by jangernert** [comment]
This seems way out of scope of what FeedReader is trying to be. And if there already are solid tools to archive this goal, why reinvent the wheel here?

**Comment by WhatsThePlan** [comment]
i do not understand: what solid tools do this? maybe my explanation was not so clear. feed reader does not do any converting, feed reader downloads url specified by feed as for other feeds but pipe content to executable X first. executable will output actual rss feed xml. is the same as standard rss feeds, only executable gets chance to process downloaded data before being read by feed reader as rss.

allows any url to be turned into rss feed by user writing own conversion script or app in any language and entering path in feed reader. is no more than call to executable like pipe in shell: download_feed_content_by_feed_reader | user_executable | process_rss_by_feed_reader

**Comment by jangernert** [comment]
You mentioned liferea yourself. What is keeping you from just using that?

**Comment by brendanlong** [comment]
This seems potentially useful, but I agree with @jangernert that it's probably not something we want to write. I wonder if our plugin interface could support it, or what it would take to have general-purpose plugins like this. I imagine a plugin interface where we notify you every time we receive something and you have an opportunity to mutate it might be useful. Just an idea though -- I don't know if that would actually be useful in general?

**Comment by jangernert** [comment]
I never envisioned FeedReader to have all the bells and whistles of every similar application out there. I created FeedReader because I personally wanted something simple and more streamlined. Not the next emacs of RSS.
If someone drops off a finished pull request implementing this and promises to maintain the feature I would probably merge it. But other than that it's a no from me.
