### ISSUE TITLE
[Feature Request] Possibility to automatically filter the feeds

### ISSUE THREAD

**Issue by logos88** [jangernert/FeedReader#539]
Hi. I really like FeedReader in many ways. You are doing a great job. 

I think that It would be really useful if FeedReader had an option to filter the content of the feeds so we could mark automatically a new like read or simple remove it if it feets some parameters.

In quiterss for instance you have the option to choose if one new in the feed contains a particular word in its title, description, content ... to automatiqually be erased, marked as read, ...

Another approach could be implementing something like a blacklist and whitelist of words for each feed channel. This way, when a feed had a word in the blacklist, it wouldn't download the new updates which would have the word listed in the title.

For example, if I have a recipes feed but I don't like fish, I could go to the feed or folder properties and in a new "filter" tag or something like that put the next commands: -fish, -tuna. And then, in my recipes feeds will never appear recipes which contains the words fish and tuna in the title.

Another example. If I have a sports feed but I don't like football and basket, but I want to know the news about my national team I could put the next commands: -football, -basket, +"Spanish team", +national. This way, I wouldn't have new news with football and basket, but despite it would say football or basket at the title, if it speaks about Spanish team or national they will appear.

Feednotifier uses a similar system to this
https://www.feednotifier.com/support/keyword-filtering-guide/

I really think this would be a great tool to personalize our feeds and to save time not to reading news that we aren't intersted in. It could be a step ahead in our rss feeds way of reading.

**Comment by jangernert** [comment]
There is already way to much to do and way to little free time. I don't plan on adding any new features in the foreseeable future.

**Comment by logos88** [comment]
Oks, is completely understandable. Thanks anyways! ; )

**Comment by brendanlong** [comment]
Depending on the feed reading service you use, you might be able to do this with IFTTT :\
