### ISSUE TITLE
Properly initialize gettext to support non-default locale directories

### ISSUE THREAD

**Issue by AsavarTzeth** [jangernert/FeedReader#540]
Currently you don't initialize `gettext` correctly which results in localisations not working if the application is installed in a prefix. The best example of this is Flatpak, which uses the `/app` prefix.

You need to use at least the `bindtextdomain` and `textdomain` functions. I am unfamiliar with Vala but I believe `setlocale` is also required. See the linked GNU gettext manual pages.

If your build system supports a localedir option that should be used. If you are indeed about to move to Meson that will make it very easy to support this.

- https://www.gnu.org/software/gettext/manual/html_node/Vala.html
- https://www.gnu.org/software/gettext/manual/html_node/Triggering.html#Triggering
- https://developer.gnome.org/glib/stable/glib-I18N.html

**Comment by bil-elmoussaoui** [comment]
Thanks for pointing that out, i will take care of that once i have done with the meson migration; should happen by the next week

**Comment by AsavarTzeth** [comment]
Ah excellent. I preferred it to happen in that order, since it does tie in to the build system after all.

**Comment by brendanlong** [comment]
I think ccb7a52d67d9fe78f663cf6cc991ea51882f453e should have fixed this (and some other stuff that got smashed into 6f91c37f470b923efa8f8cc5435a33e545b4523f).
