### ISSUE TITLE
Unable to add feeds to LocalRSS

### ISSUE THREAD

**Issue by Yotaanit** [jangernert/FeedReader#541]
Hey
currently I am unable to get any feeds into my Feedreader.
After adding them Feedreader starts to load them but nothing happens.
I get a System notification that I have 108 new articles but none are shown.
Categories are added but stay empty.

I am only able to get the default feeds to work.

Linux: Solus 3
Installation: Software Center / Flatpak (both yield the same results)
![screenshot from 2017-08-29 16-45-23](https://user-images.githubusercontent.com/31347307/30128420-e76af882-9342-11e7-811b-e783ea287526.png)

**Comment by jangernert** [comment]
Have you tested master? I started using local on master recently and fixed some issues along the way.

**Comment by Venemo** [comment]
I've seen this issue too on latest master. Actually you can add new feeds, but they won't show up on the GUI until you restart it.
