### ISSUE TITLE
Can't see how to import OPML file

### ISSUE THREAD

**Issue by rosavi** [jangernert/FeedReader#545]
I'm gonna use just a desktop RSS client and stop using feedly. As such, I exported my feeds. Feedreader doesn't prompt me for it, though, it just shows some random assortment of stuff based on popularity I guess?

I'm on elementaryOS Loki, installed by flatpak as per the instructions. I'm not very good a flatpak though, I have no idea where the executable ends up, it just shows up on the menu.

Despite the fact that I cannot make it load my feeds, though, it left a very good impression, good job, I really want to be able to try your app out.

**Comment by jangernert** [comment]
If you don't want any web service to sync with just select "local RSS". The next page just offers a few suggested feeds you could subscribe to. In FeedReader there is a plus at the bottom of the feed list where you can either subscribe to a single feed or import an opml file. However I think there are a few bugs there that have been solved in master. So not sure how well that'll work.
