### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#55]
Hello,
I have troubles with Russian translation. 
![2016-02-05 13-27-34](https://cloud.githubusercontent.com/assets/4980269/12845110/4e1c3c26-cc0c-11e5-9d15-bf2e41ecf74a.png)

For example items `All` `Unread` `Starred` and `No unread articles could be found` not translated. I don't found this strings in `po` directory. Where are the translations for these lines?

**Comment by bil-elmoussaoui** [comment]
The Russian translation is incomplete as you can see in [Transifex](https://www.transifex.com/dev-feedreader/feedreader/language/ru/); Can you help us changing that? :)

**Comment by horosgrisa** [comment]
@bil-elmoussaoui Yes

**Comment by horosgrisa** [comment]
But I can't found Russian language in list.

**Comment by bil-elmoussaoui** [comment]
Just added you as a translator ;)

**Comment by bil-elmoussaoui** [comment]
@horosgrisa https://www.transifex.com/dev-feedreader/feedreader/translate/#ru/rssreaderpot/72913673

**Comment by horosgrisa** [comment]
But some strings missing, such as `No unread articles could be found`

**Comment by bil-elmoussaoui** [comment]
I will take a look at this evening !

**Comment by horosgrisa** [comment]
For example `src/Widgets/ReaderHeaderbar.vala:80`
```vala 
		m_modeButton.append_text("All", _("Show all articles"));
```
The string `All` can not be translated.

**Comment by horosgrisa** [comment]
@jangernert You can merge russian translations from transifex? I would like to check it.

**Comment by bil-elmoussaoui** [comment]
Just merged the Russian translation, there's still few strings to translate. Can you do that too? :)

**Comment by horosgrisa** [comment]
@bil-elmoussaoui Yes

**Comment by horosgrisa** [comment]
@bil-elmoussaoui Can you check now?

**Comment by bil-elmoussaoui** [comment]
Thanks! Just updated the russian translation file.
