### ISSUE TITLE
Article scrolling is slower than scrolling any other part of the UI

### ISSUE THREAD

**Issue by jplatte** [jangernert/FeedReader#554]
I previously thought this was just the smooth scrolling, but I have now found out that I can disable that with dconf, and the scrolling is still annoyingly slow, at least on my desktop.

On my laptop, disabling "smooth scrolling" has allowed me to scroll pixel-wise with my touchpad as in any other Gtk3 application, which I'd argue is much smoother than what FeedReader does by default.
EDIT: Actually, it's the same as Firefox with `MOZ_USE_XINPUT2=1`, not the same as other Gtk3 applications. Pixel-wise scrolling works, but the scrolling always stops once my finger leaves the touchpad, contrary to other Gtk3 programs where the scrolling gradually slows down afterwards if my finger left the touchpad in motion (I hope it's clear what I mean by that, couldn't think of a better description)

On my desktop however, I now see why it felt slow before and that is because each scroll step is only scrolls about half as far in the article view as everywhere else. Could this be fixed please?

**Comment by jacekmigacz** [comment]
I confirm it (2.2-dev). I would say that scroll smoothness scale with content height. The longer page the slower page scrolls.

**Comment by jangernert** [comment]
Scroll speed is up to webkitgtk+. You will find the same behaviour in gnome web, geary and any other application making use of it.
You can however use a real mouse and drag the content with the scroll wheel.

**Comment by brendanlong** [comment]
For more info: There seems to be a lot of bugs related to this WebKitGTK and xorg. These might be useful:

https://bugs.freedesktop.org/show_bug.cgi?id=85064
https://bugs.webkit.org/show_bug.cgi?id=155334

The only workaround suggested is try setting `export LIBGL_DRI3_DISABLE=1`

**Comment by gtrak** [comment]
Ah, I managed to fix it for myself not five minutes later by removing my custom intel X.org config for uxa and defaulting to the modesetting driver.

This was the errant config, which I assume must have been to work around a different modesetting bug in the past:
```
Section "Device"
 Identifier "Card0"
 Driver "Intel"
 Option "AccelMethod" "uxa"
EndSection
```
