### ISSUE TITLE
Fully quit FeedReader via Ctrl+Q

### ISSUE THREAD

**Issue by jplatte** [jangernert/FeedReader#555]
I can live with FeedReader running in the background when I close its main window, but when I explicitly exit the whole application, I don't want it to send me notifications 10 minutes later. Currently I have to use `pkill feedreader` to quit FeedReader properly, which isn't very nice.

**Comment by brendanlong** [comment]
@jangernert What would you think of just merging the daemon into the UI process? It seems to mostly be annoying people and making it hard for us to get logs for bug reports.

**Comment by saildata** [comment]
It's very annoying to have to either (1) write a script to `trap`/`kill` on exit or (2) `killall` on exit. I even looked into patching FeedReader to remove the daemon and just manually updating it. I'm glad to see I'm not the only one who cares about this. Thanks for a great product and keep up the good work -

**Comment by brendanlong** [comment]
This was implemented in pull request #560
