### ISSUE TITLE
Marking as read when focus is lost.

### ISSUE THREAD

**Issue by jacekmigacz** [jangernert/FeedReader#559]
I think it would be nice to mark entry as read when main windows losses its focus.
In my case, when I have "Unread" filter on and draining all message on notify; the last message always stays, since there is no action that triggers read/unread refresh status (unless explicit filter pane change).

**Comment by brendanlong** [comment]
Hm or maybe we should mark things read on focus instead of when it loses focus?

**Comment by jangernert** [comment]
@brendanlong articles are marked as read as soon as you click on them. However they are not removed from the list as long as they are still selected. And since you can't unselect the last article in the list, it stays there. But on the other hand, what are you going to do with an empty list anyway?

**Comment by jacekmigacz** [comment]
@jangernert I think "No unread articles" is better than dangling orphan. Let's say (as mentioned before in my use case) I'm draining all-except-one messages by marking it read and switch to another application; when I go back (or view windows in gnome expose) I need to deal with that orphan before I can read a new content.
Right now - kind of workaround - is to switch filter setting _All_ and then _Unread_ to get the clean list.

**Comment by brendanlong** [comment]
So I actually don't want FeedReader to hide articles that I'm reading when I tab away, but it might be reasonable to have a [x] icon to close the current article. That's what Reeder does. See the X in the top left of the article pane: https://twitter.com/reederapp/status/584086156905738241

**Comment by jangernert** [comment]
@brendanlong we just have to find a nice way to integrate that close button and not confuse users. On default gnome the close button of the window is also above the article.

**Comment by brendanlong** [comment]
This should be fixed by #906
