### ISSUE TITLE
Not finding favicon for lesserwrong.com

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#567]
<view-source:https://www.lesserwrong.com/>

It has:

```
<link data-react-helmet="true" name="favicon" rel="shortcut icon" href="http://res.cloudinary.com/lesswrong-2-0/image/upload/v1497915096/favicon_lncumn.ico"/>
```
But the log says:

```
** (feedreader:9753): DEBUG: Utils.downloadIcon: url = https://www.lesserwrong.com/favicon.ico

** (feedreader:9753): WARNING **: Couldn't find a favicon for feed LessWrong 2.0
```

I need to figure out why it's not finding that..

**Comment by bil-elmoussaoui** [comment]
It seems to be somehow related to this? 
https://github.com/jangernert/FeedReader/blob/cf70c85e026c66c66213b6e967f9723a2b187270/src/Utils.vala#L619-L621

**Comment by bil-elmoussaoui** [comment]
It's the fallback, so i guess that the shortcut icon rel type is not detected/does not work at all :/

**Comment by brendanlong** [comment]
Yeah, for some reason it's not detecting the <link rel="shortcut icon">. I'll look into it tonight; I just wanted the issue to remind me :)

**Comment by jangernert** [comment]
You could disable the NOERROR and NOWARNING for the libxml2 parsing. It works with a lot of random things you throw at it. But it completely failed to parse the html of `filmstarts.de`. Maybe there is something in the html that libxml2 doesn't like.

**Comment by brendanlong** [comment]
Hmm there's something super weird going on with that site. `curl` shows me the full source, but our debug logs only show some JavaScript app setup. I'll look into it more but I doubt it's a bug on our side.
