### ISSUE TITLE
Load favicons on-demand

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#571]
This is writeup of something me and @jangernert were talking about (feel free to edit if you think this should be done differently).

Right now we load favicons at the end of each sync, by looking through every feed and trying to download their favicon (with checks to make sure we don't do it too often), then reloading all favicons.

This isn't ideal:

 - We download icons we're not going to use (for example, if a feed has no unread articles and the user has chosen to only show unread)
    - Arguably, this could be a feature, if a user is reading offline and then decides to look through 'all' articles
 - When we add a new feed, we have to reload all icons instead of just loading the new one
 - It's hard for us to download icons in parallel, since Vala doesn't seem to have a way to run multiple async functions at once and wait for them all (although maybe this exists and I just can't find it)

Proposal:

1. Move favicon downloading object from Utils.vala to FavIconCache.vala
2. Change `FavIconCache.load()` to call `downloadFavIcon()` before trying to load the icon
3. Add a callback `FavIconCache.loaded(string feed_id, Gdk.Pixbuf pixbuf)`
4. Make `FavIconCache.load` trigger `loaded` when a new icon is downloaded
5. Make sure we only try to download each icon once (`Set<string> m_loading_icons`?)
6. Remove all of the code to trigger favicon downloading after a refresh

Things that would be nice but probably aren't required in the initial version:

 - Remove pixbufs from the cache when feeds are deleted (using a `Map<string, WeakRef<Gdk.Pixbuf>>` might work)
 - Only notify subscribers if the icon they want is loaded (have a way to subscribe to "feed 3's icon was loaded" instead of "some feed's icon was loaded")
 - A way to trigger downloading all favicons for offline mode?

**Comment by jangernert** [comment]
I started working on this in the icon_refactor branch. I probably have to entertain the girlfriend for the rest of the weekend. So if you have some time on your hands you could pick it up from there ;)

**Comment by brendanlong** [comment]
Cool! I also have a lot going on this weekend but I'll take a look if I have time
