### ISSUE TITLE
Content grabber and internal video player don't work

### ISSUE THREAD

**Issue by titanium12345** [jangernert/FeedReader#572]
I'm using it on ubuntu 17.04. 

This is in console it never endingly repeats itself. I tried a Youtube video here. In the window there's only the RSS content.

[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ ERROR ] error writing log to file: Az adatfolyam hátralévő művelettel rendelkezik
[ ERROR ] [ DEBUG ] load articles from db

[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows
[ DEBUG ] new rowCount: 2
[ DEBUG ] ArticleList: loadNewer(2)
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash, media FROM main.articles WHERE feedID = "feedID00024"  ORDER BY date COLLATE NOCASE DESC LIMIT 2 OFFSET 0
[ DEBUG ] actual articles loaded: 2
[WARNING] ArticleListbox2: row with ID yt_video_BS044GhnKFM is already present
[WARNING] ArticleListbox2: row with ID yt_video_FnM6pBhD8CI is already present
[ DEBUG ] ArticleListbox2: all articles added to the list
[ DEBUG ] ArticleListbox2: loadDone()
[ DEBUG ] ArticleList: checkForNewRows

**Comment by jangernert** [comment]
This would be more helpful if you stated anything about your setup and what you are doing.
Youtube doesn't provide rss feeds with video attachments. So the internal video player shouldn't be involved in any of this.

**Comment by titanium12345** [comment]
For example from the BBC News feed only the RSS text appears when the Content grabber is on.

My PC:      
     
 OS: Ubuntu 17.04 x86_64 
 Model: 80T7 Lenovo ideapad 110-15IBR 
Kernel: 4.10.0-37-generic 
 Uptime: 2 hours, 17 mins 
Packages: 2588 
Shell: bash 4.4.7 
 Resolution: 1366x768 
  DE: MATE 
   WM: Compiz 
  WM Theme: Ambiance 
 Theme: Radiance [GTK2/3] 
  Icons: Humanity [GTK2/3] 
  Terminal: gnome-terminal 
   CPU: Intel Pentium N3710 (4) @ 2.5GH 
     GPU: Intel HD Graphics 405 
      -+sssssssssssssssssyyyssss+-         Memory: 1303MiB / 3862MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.

**Comment by jangernert** [comment]
I mostly meant the version of FeedReader you are using. For the content grabber to work there has to be a config file for the specific website (which does exist for bbc.co.uk and bbc.com). The content grabber only downloads the text and images of articles (even mutlipage articles). The video player can only play attached media files. If an articles has such an attachment there should be a play icon in the headerbar above the article that then launches the player widget. If the video player is turned off in the settings FeedReader just launches the url of the video with the default application of the system.

**Comment by titanium12345** [comment]
Ahh sorry for omiting the version. It's 2.0.2

**Comment by jangernert** [comment]
Like I said: there should be a play icon above the article in the headerbar.
![screenshot from 2017-10-15 20-11-56](https://user-images.githubusercontent.com/12012494/31587621-2fbb16c4-b1e5-11e7-9d6f-11d8ff9ba5fa.png)
It's not like there is a video popping up once you click on the article or something.

**Comment by titanium12345** [comment]
Okay. I will look for the play icon. But still the issue is that the content grabber should still work with BBC and the default feeds I suppose.

**Comment by jangernert** [comment]
Depends. If the website recently changed its layout or structure and the config file hasn't been updated, then it won't work. The fivefilters guys are reliant on the community keeping the configs up to date.
The last modification on the bbc config was 8 months ago.
https://github.com/fivefilters/ftr-site-config
I can test the feed myself when I get home to see if the config is out of date or there is indeed a bug in my implementation. I just need the feed url for that ;)

**Comment by bilelmoussaoui** [comment]
@titanium12345 Any updates?

**Comment by bilelmoussaoui** [comment]
As we didn't receive any updates on this for at least 4 months, I'm going to close this. Please re-open if you have any more details on how to reproduce this.
