### ISSUE TITLE
Win+left and Win+right GNOME hotkeys don't work

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#575]
Holding the Win key and left or right should cause any window to move to the left or right side of the screen and take up half the screen. For some reason that doesn't work in FeedReader. Do we override that hotkey by accident?

**Comment by jangernert** [comment]
I think the minimal width of the window could be larger than width/2 of your screen?

**Comment by jangernert** [comment]
What is the resolution of the display you tried this on? Or virtual resolution if you use HIDPI scaling. Works for me on 1920x1200.

**Comment by brendanlong** [comment]
Hm. I think it was similar to yours. I'll try it again when I get home. I think if the minimum size is too big, it still should have moved the window over and changed the vertical height though?

**Comment by jangernert** [comment]
>  it still should have moved the window over and changed the vertical height though?

I don't think so. Afaik it straight up doesn't work if the window can't shrink down enough.

**Comment by jangernert** [comment]
Confirmed!

Just take this code and compile with `valac --pkg gtk+-3.0 test.vala`. Set different widths in the size request and see what happens.

```
using Gtk;

int main (string[] args) {
    Gtk.init (ref args);

    var window = new Window ();
    window.title = "First GTK+ Program";
    window.window_position = WindowPosition.CENTER;
    window.set_size_request(600, 600);
    window.destroy.connect (Gtk.main_quit);
    window.show_all ();

    Gtk.main ();
    return 0;
}
```

**Comment by brendanlong** [comment]
Yup, looks like you're right. Maybe sometime I'll make the interface change as we resize like I did here: https://www.brendanlong.com/fluid-css-design-and-feedbins-mobile-interface.html
