### ISSUE TITLE
Redownload icons in FaviconManager when they expire

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#576]
Right now we only attempt to download an icon once per FeedReader process:

1. When a sync starts, we check if the map contains a future for the icon. If there is, we wait and get its value.
2. If the map does not contain a future for the icon, we attempt to load it and set the future to either the pixmap or `null`
3. The download checks if the future is null, not if the contents are null, so we will never redownload an icon until we close and restart FeedReader

In general, the impact of this should be minimal, since we intentionally won't attempt to download an icon again for at least a week, but this could be improved:

 - Make the future contain both a pixmap and an expires time
 - When getting an icon, reload the icon if its not in the map *or if the expires time has passed*

Doing that would make us load the new icon for any newly displayed rows. To update existing rows:

 - Add a signal for updating the icon
 - Fire that signal every time we load an icon (after putting the new value in the map)
 - Hook up signal handlers in the places where we use feed icons (ArticleRow, FeedRow?).

**Comment by jangernert** [comment]
Ah, the content of the future being `null` and the future itself being `null` got me  :D 
The part with the signal was already in place, but you removed it again. I though that was intentional^^
Okay so basically have the expiration timestamp with the future and readd the signal + handlers.
Doesn't seem too hard.

**Comment by brendanlong** [comment]
Yeah, I removed the signal because my current version didn't actually use it (since we would never fire the signal more than once). I think we should add it back if we make this change.

**Comment by jangernert** [comment]
#577
