### ISSUE TITLE
Notifications Icon in Systray

### ISSUE THREAD

**Issue by Tuchkata** [jangernert/FeedReader#58]
Hi, is there an option to add a system tray notification icon? I haven't found one yet.

**Comment by jangernert** [comment]
Nope
Gnome as well as elementary's Pantheon are ditching traditional system trays. Even Ubuntu's "indicators" are no longer supported. So no plans to add this to FeedReader.
There is however support for unity's launcher API to display a badge on the icon in the dock. Ubuntu's Unity, Plank (the dock used by elementary) and some KDE plasmoids support this.
