### ISSUE TITLE
Support high DPI favicons

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#582]
We always load favicons as 24x24 pixbufs (see `Favicon.vala:load`), but on high DPI displays, we should be using 48x48 icons. Unfortunately if we load the icon as 48x48, it gets resized to be bigger but still blurry.

This task is to figure out how to load high res icons and have them still be the right size.

**Comment by brendanlong** [comment]
(This is pretty low priority, but I figured I'd document it in case someone else is interested, and to signal to outside contributors that we would accept a patch fixing this)

**Comment by jangernert** [comment]
https://gist.github.com/matzipan/d4e78f3e5ea95890f403871b50d63b76#to-make-gtkpixbuf-work-with-hidpi

**Comment by jangernert** [comment]
#583
