### ISSUE TITLE
How to connect FeedReader to my Nextcloud

### ISSUE THREAD

**Issue by schiessle** [jangernert/FeedReader#584]
I just installed FeedReader 2.0.2 via flatpak. If I start it I see the "Change Account?" screen. Nothing happens if I click on "New Account" and I assume that this is what I have to do in order to connect FeedReader to my Nextcloud because if I click on "I changed my mind" I get to a empty feed reader where I can add feed manually.

Any idea what's wrong here?

**Comment by jangernert** [comment]
You should only see the "Change Account?" page if you were previously logged in to another account. Did you have FeedReader installed before?
Usually you see a list with options for the backend FeedReader should use. And when you choose one you get to a page that asks you for your user name and password.

**Comment by schiessle** [comment]
I was also confused my the "Change Account" dialog but it is the first time I installed FeedReader. I also looked for the config file to delete it and start from scratch but I couldn't find it. Where is the config located?

**Comment by jangernert** [comment]
On a normal install it would be $HOME/.local/feedreader/. I don't know the path for a flatpak install on the top of my head. That's where the database, icons and images are located.
All other settings are stored within dconf. Afaik this is not sandboxed for flatpak. So you should be able to fire up dconf-editor and go to org->gnome->feedreader. The most important setting is `plugin` which should be `none`.

**Comment by schiessle** [comment]
@jangernert I still couldn't find the config but I checked dconf, there is no "plugin" setting. This is how it looks on my system:

![feedreader](https://user-images.githubusercontent.com/1589737/32044503-086245d2-ba3e-11e7-92d4-ba4e3688fde1.png)

**Comment by jangernert** [comment]
You are in the `saved-state` subcategory. Just move up one level to /org/gnome/feedreader ;)

**Comment by Larx** [comment]
I have the same situation. There is only the "saved-state" subcategory available, nothing else. I had used FeedReader before and now try to use it again, but it doesn't work as I only get to the screen where I should be able to select the service I want to subscribe to. But as it offers only a blank list, I cannot go on :-(.

**Comment by jangernert** [comment]
That sounds like something went wrong with your installation. Not a bug with the actual software.

**Comment by schiessle** [comment]
interesting. I just learned that there is a flatpak command "flatpak run" if I use this to start FeedReader it works. If I use the icon added to the gnome "apps menu" I have the problems described above. So it seems there is a bug in how the desktop file is created and how it starts feedreader.

**Comment by jangernert** [comment]
@schiessle what does your desktop file say?
Maybe @jscurtu knows something if he is still around :)

**Comment by Larx** [comment]
I don't think it's the desktop file, as you can easily launch FeedReader from a command line. For me the result is the same.
I'm using openSUSE packages and cannot launch the programm, as I'm always getting stuck on the empty page with no service to select. I resetted the dconf tree and deleted .local/share/feedreader.
Using the Flatpak packages gives me the possibility to select from the different feed providers. However, when I select "owncloud" and enter the credentials for my Nextcloud-Instance, I cannot go on. The prgram says "Select a servie first"?!?!?!

**Comment by jangernert** [comment]
@Larx opensuse packages are broken for a lot of people. But I really can't or don't want to give support for packages created by someone else for distribution X or Y.
The issue you are having with the flatpak version sounds like the same issue you were having with the opensue packages. Only it just happening in the daemon.
Did you kill the running `feedreader-daemon` process after uninstalling the package and installing the flatpak version?

**Comment by Larx** [comment]
OK, the flatpak was installable after removing all traces of the previous RPM. Thanks.
