### ISSUE TITLE
Replace ownCloud with Nextcloud

### ISSUE THREAD

**Issue by schiessle** [jangernert/FeedReader#586]
The maintainer of the news app decided to move to Nextcloud, see https://github.com/nextcloud/news. ownCloud no longer maintain/develop the app at all, seehttps://github.com/owncloudarchive

Therefore I would suggest to replace ownCloud with Nextcloud, both in the app and on the webpage.

**Comment by jangernert** [comment]
@schiessle I would be happy to merge a pull request that does that.
Basically need new icons and change all the strings in the UI. Renaming the files and classes would be nice but is imo optional ;)

https://github.com/jangernert/FeedReader/tree/master/plugins/backend/owncloud
