### ISSUE TITLE
Unable to "Change Account" on first start

### ISSUE THREAD

**Issue by raketenhunddev** [jangernert/FeedReader#592]
Running on Debian Stretch

Today I installed FeedReader for the first time. On every start, FeedReader show the "Change Account?"-View (with "I Changed my mind" / "New account" buttons). Console output is:

> [ INFO  ] Everything is logged. Used to debug!
> [ INFO  ] FeedReader 2.0.2
> [ DEBUG ] MainWindow: setupCSS
> [ DEBUG ] ContentPage: setup FeedList
> [ ERROR ] checkDaemonVersion: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files
> [ ERROR ] FeedListFooter.constructor: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files
> [ DEBUG ] UpdateButton: update status
> [ DEBUG ] UpdateButton: setSensitive true
> [ DEBUG ] HeaderBar: showArticleButtons true
> [ ERROR ] ColumnViewHeader.showArticleButtons: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files
> [ DEBUG ] UpdateButton: update status
> [ DEBUG ] UpdateButton: setSensitive true
> [ DEBUG ] UpdateButton: update status
> [ DEBUG ] UpdateButton: setSensitive true
> [ DEBUG ] MainWindow: determining state
> [ ERROR ] MainWindow.constructor: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files
> [ ERROR ] FeedReader.activate: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files

The following console output is repeated every time I hit the "New account" button:
> [ ERROR ] ResetPage.resetAllData: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.FeedReader.Daemon was not provided by any .service files

Installation via flatpack:
> sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk flatpak
> flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref
> flatpak run org.gnome.FeedReader

**Comment by JKingweb** [comment]
See issue #322. I encountered this, myself, and a reboot did indeed "fix" it.

**Comment by raketenhunddev** [comment]
Tried again today and it worked. Thanks @JKingweb
