### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by aleksandar-todorovic** [jangernert/FeedReader#6]
Working on a new website design (code at the [2.0 branch](https://github.com/jangernert/feedreader/tree/2.0)) specific for FeedReader (instead of using a template), so I'm opening up an issue to track my progress. Once this issue is resolved, the branch will be ready for merging with the `gh-pages` branch.

## Current look

![screenshot from 2015-10-17 19 46 57](https://cloud.githubusercontent.com/assets/4890548/10560314/eb1cf2c4-7507-11e5-9e8f-ce799012b972.png)

## To do

- [x] Implement every section.
- [x] Make a navbar.
- [x] Remove the background from the jumbotron.
- [ ] Come up with a better design of the Features section.
- [x] Move the slider buttons a bit lower.
- [x] Make a footer.
- [x] Make the navbar fixed.
- [x] Installation instructions could be a bit bigger and have more text.
- [x] Fix left and right glyphicon in the screenshot section.
- [x] Merge the screenshot section with the jumbotron.
- [ ] Make sure the page looks good on mobile devices.

**Comment by jangernert** [comment]
Awesome :)
Is there a way to test it?

**Comment by aleksandar-todorovic** [comment]
You can clone that branch specifically by using:

    git clone https://github.com/jangernert/feedreader -b 2.0 --single-branch

...and then open the index file. Note that I have spent the last couple of days traveling so I still have some things to fix. I think I'll finish everything listed here in the next 24 hours. If there's something else you'd like me to do, feel free to add it to the list. :smile:

**Comment by jangernert** [comment]
Are you still working on this? :)

**Comment by aleksandar-todorovic** [comment]
Crap, I have completely forgot about this. Thanks for pinging me. I'll finish the job very soon. :)

P.S. will it be okay to put the changelog on a separate page? There's absolutely no way to design the changelog properly.

**Comment by jangernert** [comment]
Yeah, that is totally fine. I was just going for the single-page design because it was the easiest way for me :D

**Comment by bil-elmoussaoui** [comment]
@aleksandar-todorovic Are you still working on this? if not, i would like to assign it to myself :+1:

**Comment by aleksandar-todorovic** [comment]
@bil-elmoussaoui Feel free to tackle the things that still needs to be done. The code is in the `2.0` branch and you can see the issues that still need to be resolved here.

**Comment by bil-elmoussaoui** [comment]
I will do asap
