### ISSUE TITLE
Translation for notifications

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#60]
Please, add posibility to translate notifications, and title for settings window.

**Comment by jangernert** [comment]
I will add the option to translate the settings-dialog title. But the notifications are already translatable.

**Comment by horosgrisa** [comment]
Posibble this is bug. Translation into Russian is done by 100%.
![2016-02-15 15-21-36](https://cloud.githubusercontent.com/assets/4980269/13049847/5f3c4d5e-d3f8-11e5-9e75-1ccd94d14779.png)

**Comment by jangernert** [comment]
Just because the string is translated on transifex doesn't mean the translations are instantly imported to github and and installed on your computer.

**Comment by bil-elmoussaoui** [comment]
The russian translation is up to date on Github

**Comment by jangernert** [comment]
this is part of the ru.po on my system
`#: ../src/Backends/FeedServer.vala:889
msgid "New Articles"
msgstr "Новые статьи"

#: ../src/Backends/FeedServer.vala:901
msgid "There is 1 new article"
msgstr "1 новая статья"

#: ../src/Backends/FeedServer.vala:903
msgid "There are %u new articles"
msgstr "%u новых статей"`

So no idea why it isn't working on your system.

**Comment by bil-elmoussaoui** [comment]
Works fine here too
