### ISSUE TITLE
unable to login to inoreader when using ssh -X command

### ISSUE THREAD

**Issue by bakul693** [jangernert/FeedReader#603]
unable to login to inoreader when using ssh -X command:
daemon.log
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ ERROR ] Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
[ ERROR ] Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
^R
[ ERROR ] Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
[ DEBUG ] MainWindow: show error bar - errorCode = 6
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: updatebutton status false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -4
[ DEBUG ] ArticleList: newList
[ DEBUG ] ArticleList: create
[ DEBUG ] ArticleList: offset 0
[ DEBUG ] limit: 20
[ DEBUG ] load articles from db
[ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles ORDER BY rowid DESC LIMIT 20 OFFSET 0
[ DEBUG ] actual articles loaded: 0

(feedreader:22446): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
[ DEBUG ] ArticleList: insert new rows
[ DEBUG ] ArticleList: create finished

(feedreader:22446): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(feedreader:22446): Gtk-CRITICAL **: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
[ DEBUG ] write login data

[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_UNKNOWN_ERROR
[ DEBUG ] MainWindow: show error bar - errorCode = 5
[ DEBUG ] MainWindow: show error bar
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: feed -4

**Comment by jangernert** [comment]
If you're not on master FeedReader actually consits of 2 processes. Looks like you can't start the daemon via dbus activation when on another mashine. You could try if it works with master. Otherwise I'll close this.

**Comment by bakul693** [comment]
no i have been master on that server i run feedreader by sudo feedreaer and
iam able to login to feedly
Thanks for your reply

On Tue, Nov 21, 2017 at 9:15 PM, Jan Lukas Gernert <notifications@github.com

**Comment by brendanlong** [comment]
This might actually work now since we merged the two processes.
