### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by yotamN** [jangernert/FeedReader#604]
The deamon still showed me new articles but the window didn't open so I tried from the terminal, this is the output:

[feedreader.log](https://github.com/jangernert/FeedReader/files/1501761/feedreader.log)

Sorry about the terminal coloring, not sure how to disable it.

**Comment by brendanlong** [comment]
Hm the log says something is wrong with `vilistextum`, but that's a complicated library so I'm not sure how to track this down further without a line number from the debugger :(

Do you see this problem on the latest version (from git)?

**Comment by brendanlong** [comment]
We removed libvilistextum so this should be fixed now.
