### ISSUE TITLE
Missing icon with nextcloud account

### ISSUE THREAD

**Issue by mobybit** [jangernert/FeedReader#607]
With feedreader-git (AUR) and nextcloud the icon is missing in the main window. I think this issue is caused by a wrong icon size:

-feed-service-nextcloud.svg (128x128)
-feed-service-nextcloud-symbolic.svg (256x128)

The first icon works but I think we need 64x64px for both.

![feedreader missing icon](https://user-images.githubusercontent.com/10283551/33326715-f65d7848-d455-11e7-82dd-95a77d672bc4.png)

**Comment by jangernert** [comment]
old owncloud icon name was not updated in the code
