### ISSUE TITLE
Error during Innoreader autorization

### ISSUE THREAD

**Issue by mkrawiec** [jangernert/FeedReader#609]
Tested on latest flatpak version: I'm unable to add new Innoreader account - once I pass the login step and click 'Authorize' the app ends up in this state:

![screenshot_20171210_222751](https://user-images.githubusercontent.com/142805/33809585-90371332-ddf9-11e7-8eb3-0db0c97aed36.png)

**Comment by brendanlong** [comment]
I'm going to close this since FeedReader has changed substantially in the last 2 years. Please let us know if you see this problem again with the latest Flatpak.
