### ISSUE TITLE
Images broken in "Astronomy Picture of the Day" feed

### ISSUE THREAD

**Issue by mbarbar** [jangernert/FeedReader#616]
This RSS feed ([https://apod.nasa.gov/apod.rss](https://apod.nasa.gov/apod.rss)) has a problem where images show the HTML rather than the image itself (see attached image). The whitespace between a and href seems to be a tab (or something that isn't a standard space), which may have something to do with the issue.
![feedreader_ahref](https://user-images.githubusercontent.com/12083002/34482582-0252caae-f00d-11e7-8868-d585b43a5981.png)
 
Question is essentially - is it the feed's fault, or would it be a bug in the app?

**Comment by bil-elmoussaoui** [comment]
It seems to be a bug on the application. As we need to replace the html entities to the correct html tags in order to be rendered by Webkit2Gtk

**Comment by brendanlong** [comment]
I think `libnxml` isn't properly unescaping strings. I think we should probably look into removing libnxml and using libxml2 exclusively.

**Comment by brendanlong** [comment]
@mbarbar I think this should be fixed now with the commit I just merged. If you rebuild and then wait for the next update of the feed tomorrow it should work (I think the local plugin doesn't update feed content when the parser changes since it would override the content grabber's changes).

**Comment by bil-elmoussaoui** [comment]
It works correctly now, thanks @brendanlong ! The images are so small. But then it's the content of the RSS file. If you want to get the real content of each feed, you can create a PR here https://github.com/fivefilters/ftr-site-config
![screenshot from 2018-01-03 11-40-04](https://user-images.githubusercontent.com/7660997/34517328-dddffb1a-f07a-11e7-840c-5af3d343d5ed.png)

**Comment by mbarbar** [comment]
Thanks @brendanlong, just rebuilt and will wait for tomorrow.
@bil-elmoussaoui wow they are tiny. I'll look to make a PR in the next few days.
