### ISSUE TITLE
There seems to be no way to mark all articles read

### ISSUE THREAD

**Issue by mulle-nat** [jangernert/FeedReader#620]
Right clicking on "All Articles", I would expect to see a menu with "Mark as read". Similiar to when I right-click on the "folder" headings. Instead nothing happens. I don't know if this is a bug or a missing feature.

**Comment by jangernert** [comment]
Neither!
The default way to mark something as read is to hover over the unread counter and click the appearing check.

**Comment by mulle-nat** [comment]
Yes, that works. Thanks. It's a UI inconsistency nevertheless.
