### ISSUE TITLE
Request AppImage

### ISSUE THREAD

**Issue by 4goodapp** [jangernert/FeedReader#624]
This app looks very polished & modern.
It would be great to provide am AppImage file so anyone can use or test it (fast) without the need to install anything else first (like Flatpack).

**Comment by bilelmoussaoui** [comment]
I'm going to close this as we are focused on using the latest GNOME stack which is provided by Flatpak through their runtimes. It's already pretty easy to just download and install the application.
AppImages are not as easy as Flatpak to build or to debug. We don't want to support yet another packaging format just to support it. Flatpak works perfectly for us and it can be used everywhere on Linux. No need for us to maintain yet another packaging format.
If someone is willing to do the work and keep it up to date we can merge it.
