### ISSUE TITLE
'make uninstall" requires up-to-data Vala

### ISSUE THREAD

**Issue by avh-on1** [jangernert/FeedReader#625]
I built FeedReader from scratch a while ago on Debian 9 stable. Recently, I decided to try a newer version. I `git pull`ed and tried to build. Unsurprisingly, building from source now requires a newer version of Vala -- newer than Debian stable offers. No problem, I can install the flatpak image once I've uninstalled what I currently have.

Unfortunately, `make uninstall` results in this error:
```
-- checking for a minimum Vala version of 0.36
CMake Error at cmake/ValaVersion.cmake:88 (message):
  Vala version 0.36 or greater is required.
Call Stack (most recent call first):
  CMakeLists.txt:31 (ensure_vala_version)

-- Configuring incomplete, errors occurred!
```

I was able to run `make uninstall` by manually commenting out lines 87 through 91 of `cmake/ValaVersion.cmake`. (I also could have reverted my git repo to where it had been earlier.) However, I shouldn't have had to do this. Uninstalling should not require Vala at all.

**Comment by bil-elmoussaoui** [comment]
We are moving to meson see #563 
This will not be needed anymore.

**Comment by bil-elmoussaoui** [comment]
Plus those cmake files comes from elementary. So it must be an upstream issue for them. But they are switching to meson too so no need for that neither

**Comment by DroWnThePoor** [comment]
So, for the uninitiated like myself, the best way to un-install is?

**Comment by brendanlong** [comment]
In general we recommend using the Flathub package, so you'd uninstall with `flatpak uninstall org.gnome.FeedReader`.

If you've built from source, you should be able to go back into the source directory and run:

```
make
sudo make uninstall
```

(Which is really just a wrapper around `ninja -C builddir && sudo ninja -C builddir uninstall`
