### ISSUE TITLE
Don't send notification when everything is read

### ISSUE THREAD

**Issue by hadess** [jangernert/FeedReader#626]
Or maybe add an option for it.

I currently receive notifications that say (on top of my head) "1 new article (0 unread)". But this is a case where I'd rather not have any notifications, as I already read the article on another device.

**Comment by brendanlong** [comment]
I'd be happy to review a pull request that fixes this, or I can look into it myself when I have free time (although I can't guarantee when that will be). I'd say an option is overkill for this but I'd be ok with one existing.

**Comment by jangernert** [comment]
Do we want to send a notification only if there are unread articles that were added during the last sync, or if there are unread articles in general?

**Comment by brendanlong** [comment]
Probably only if there are new unread articles, if that's possible

**Comment by brendanlong** [comment]
Hm it's a little tricky since the `(x unread)` is actually the total:

```
	public static void send(uint newArticles)
	{
		string message = "";
		string summary = _("New articles");
		uint unread = DataBase.readOnly().get_unread_total();

		if(newArticles > 0)
		{
			if(newArticles == 1)
				message = _("There is 1 new article (%u unread)").printf(unread);
			else
				message = _("There are %u new articles (%u unread)").printf(newArticles, unread);

			var notification = new GLib.Notification(summary);
			notification.set_body(message);
			notification.set_priority(GLib.NotificationPriority.NORMAL);
			notification.set_icon(new GLib.ThemedIcon("org.gnome.FeedReader"));

			GLib.Application.get_default().send_notification("feedreader_default", notification);
		}
	}
```

So just switching to `if (unread > 0)` won't work. We need to change how we calculate the unread number.

**Comment by jangernert** [comment]
Yes, the total unread amount was intended: You have 3 new articles and now have 20 unread in your library. At least that was the idea behind it.
For the check we need another query. We already know the rowid of the newest article before the sync:
https://github.com/jangernert/FeedReader/blob/master/src/Backend/FeedServer.vala#L232
Now we only have to query all unread articles with and rowid bigger than that.
```
SELECT count(*) FROM articles WHERE unread = ArticleStatus.UNREAD AND rowid > saved_rowid
```
I'll try to implement that tonight ;)

**Comment by jangernert** [comment]
Haven't actually tested it with the described scenario because I'm on local back-end currently. But for me there is no change in behaviour like it is supposed to be.

**Comment by hadess** [comment]
Thanks! I'll test this as soon as it lands in Flatpak.
