### ISSUE TITLE
Plugins not loading, path and constraints wrong?

### ISSUE THREAD

**Issue by malcolmlewis** [jangernert/FeedReader#627]
Hi
Building 2.2-dev on openSUSE Tumbleweed (x86_64) the plugins aren't loading because the compiled path to the plugins is wrong.

In Constants.vala;
INSTALL_PREFIX/@CMAKE_INSTALL_PREFIX@ gets set to /usr
INSTALL_LIBDIR/@PKGLIBDIR@ gets set to /usr/lib64/FeedReader

In src/Backend/FeedReader.vala is;

Constants.INSTALL_PREFIX + "/" + Constants.INSTALL_LIBDIR + "/plugins/", null)

Which becomes /usr/usr/lib64/FeedReader/plugins/

So either the INSTALL_LIBDIR reference is created incorrectly on the openSUSE Build Service cmake side, or should the FeedReader.vala line just be;

Constants.INSTALL_LIBDIR + "/plugins/", null

**Comment by jangernert** [comment]
Not sure which is the technically correct implementation, but on most distros is set to just "lib" or "lib64".

**Comment by jangernert** [comment]
At least I haven't had this issue with Ubuntu and Fedora. But I'm not sure how to find a generic solution that works for all distors (other than specifically checking for the '/usr/ prefix and cropping it off)

**Comment by malcolmlewis** [comment]
Hi
OK, I'll delve into on the openSUSE side, at least this is a reference if someone else comes across the issue in the future.

**Comment by Larx** [comment]
Any workaround for this problem? Symlinking from /usr/lib64/FeedReader to /usr/lib does not work (openSUSE Leap here).

**Comment by bilelmoussaoui** [comment]
This should be fixed with the new Meson build system. Can you guys try the meson PR?

**Comment by bilelmoussaoui** [comment]
Fixed on master.
