### ISSUE TITLE
Where to find FeedReader after installation?

### ISSUE THREAD

**Issue by KimLudvigsen** [jangernert/FeedReader#637]
So, call me stupid. I cannot find FeedReader anywhere on my system (Linux Mint 18.2) The installation seems to be successful, please see below; however, neither flatpack nor FeedReader is found when I search for programs.

The terminal:
flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref
This application depends on runtimes from:
  https://sdk.gnome.org/repo/
Configure this as new remote 'gnome' [y/n]: y
Installing: org.gnome.FeedReader/x86_64/stable
Required runtime for org.gnome.FeedReader/x86_64/stable (org.gnome.Platform/x86_64/3.22) is not installed, searching...
Found in remote gnome, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.22 from gnome
[####################] 9 delta parts, 73 loose fetched; 178829 KiB transferred i
Installing: org.freedesktop.Platform.GL.nvidia-384-90/x86_64/1.4 from gnome
[####################] Downloading: 46.1 MB/46.1 MB (1.9 MB/s)                 
Installing: org.gnome.Platform.Locale/x86_64/3.22 from gnome
[####################] 10 metadata, 43 content objects fetched; 841 KiB transfer
Installing: org.gnome.FeedReader/x86_64/stable from org.gnome.FeedReader-origin
[####################] 1 delta parts, 3 loose fetched; 1731 KiB transferred in 8
Installing: org.gnome.FeedReader.Locale/x86_64/stable from org.gnome.FeedReader-origin
[####################] 7 metadata, 3 content objects fetched; 13 KiB transferred

**Comment by jangernert** [comment]
`flatpak run org.gnome.FeedReader` should do the trick. + there should be a desktop file in your applications folder.

**Comment by KimLudvigsen** [comment]
Thanks, that opened the program. I did not get a desktop file in my applications folder.

**Comment by KimLudvigsen** [comment]
However, I cannot use the program. I get two buttons in the program window: 
"New Account" - nothing happens when I click it 
And "I changed my mind", which does open the feed window; however, I am not able to add a feed. The throbber keeps working to no avail. I have tried with several feeds in different formats and it is the same for all of them.

**Comment by pokgak** [comment]
That is similar to #322 and #491. If you have just installed flatpak, try restarting the computer.  
If you want to dig more into the problem, run `flatpak run org.gnome.Feedreader` from terminal and look if there is any error in the output.

**Comment by bil-elmoussaoui** [comment]
It seems that either you should restart your computer or your distro doesn't really support flatpak apps. The desktop files should be fetched from XDG_DATA_DIRS. But sometimes, few launchers hardcode the default values... We can't do anything about this.
