### ISSUE TITLE
Article preview sometimes doesn't update when clicking a new article

### ISSUE THREAD

**Issue by Stunkymonkey** [jangernert/FeedReader#638]
i am having some weird behavior with the article-preview. Sometimes i click on an article, but the Preview does not change.
![screenshot2018-02-05-18 54 41](https://user-images.githubusercontent.com/1315818/35832304-1345d0a6-0acd-11e8-8c92-2b071d9de7d7.png)

I installed it via aur `feedreader-git` and i am using it with ttrss-api.
Tha last time i compiled it was around the 24. of november

**Comment by jangernert** [comment]
I fixed an issue with the articleview where one of the two stacks (the articleview has two views between which it switches back and forth to have nice animations) would somehow not get properly reset and was kind of blocked. That was on 30. of november^^
https://github.com/jangernert/FeedReader/commit/1e41562d7c51063e73911e2876ca5ebc536d1d85#diff-6dd95153b53e972d34825777780917b3
If you're experiencing something else I need logs and if possible a way to reproduce it.

**Comment by Stunkymonkey** [comment]
i did not yet check the commit, but here is some verbose output:
```
(feedreader:11956): feedreader-DEBUG: TTRSS Message: ping successful
(feedreader:11956): feedreader-DEBUG: CachedActionManager - executeActions: no actions to perform
(feedreader:11956): feedreader-DEBUG: FeedReader: setOnline
(feedreader:11956): feedreader-DEBUG: ArticleView: size changed
(feedreader:11956): feedreader-DEBUG: ArticleView.setBackgroundColor()
(feedreader:11956): feedreader-DEBUG: ArticleList: newList
(feedreader:11956): feedreader-DEBUG: ArticleList: disallow signals from scroll
(feedreader:11956): feedreader-DEBUG: load articles from db
(feedreader:11956): feedreader-DEBUG: actual articles loaded: 4
(feedreader:11956): feedreader-DEBUG: ArticleList: switch to list2
(feedreader:11956): feedreader-DEBUG: ArticleListbox2: all articles added to the list
(feedreader:11956): feedreader-DEBUG: ArticleListbox2: loadDone()
(feedreader:11956): feedreader-DEBUG: ArticleList: checkForNewRows
(feedreader:11956): feedreader-DEBUG: new rowCount: 0
(feedreader:11956): feedreader-DEBUG: ArticleList: allow signals from scroll
(feedreader:11956): feedreader-DEBUG: ArticleView: load article 250733
(feedreader:11956): feedreader-DEBUG: HeaderBar: showArticleButtons true
(feedreader:11956): feedreader-DEBUG: DataBaseReadOnly.read_article(): 250733
(feedreader:11956): feedreader-DEBUG: ContentPage: set headerbar
(feedreader:11956): feedreader-DEBUG: ArticleView: WebView load html
(feedreader:11956): feedreader-DEBUG: ArticleView: empty -> view1
(feedreader:11956): feedreader-DEBUG: ArticleView: loading 10 %
(feedreader:11956): feedreader-DEBUG: ArticleView: webextension-message: on_page_created
(feedreader:11956): feedreader-DEBUG: ArticleView: Policy decision
(feedreader:11956): feedreader-DEBUG: WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION
(feedreader:11956): feedreader-DEBUG: ArticleView: load STARTED
(feedreader:11956): feedreader-DEBUG: ArticleView: load COMMITTED
(feedreader:11956): feedreader-DEBUG: FeedReader: refreshFeedListCounter
(feedreader:11956): feedreader-DEBUG: ArticleView: webextension-message: onDocLoaded
(feedreader:11956): feedreader-DEBUG: ArticleView: loading 10 %
(feedreader:11956): feedreader-DEBUG: ArticleView: loading 100 %
(feedreader:11956): feedreader-DEBUG: ArticleView: load FINISHED
(feedreader:11956): feedreader-DEBUG: ArticleView: webextension-message: recalculate
(feedreader:11956): feedreader-DEBUG: ArticleView: load article 250734
(feedreader:11956): feedreader-DEBUG: ArticleView: currently busy - next article in line is 250734
(feedreader:11956): feedreader-DEBUG: HeaderBar: showArticleButtons true
(feedreader:11956): feedreader-DEBUG: ContentPage: set headerbar
(feedreader:11956): feedreader-DEBUG: FeedReader: refreshFeedListCounter
```
and yes the header-bar is changed, but not the article-preview

**Comment by Stunkymonkey** [comment]
i tested the 1e41562d7c51063e73911e2876ca5ebc536d1d85 a few days
and the issue was gone
so in the next days i will test the next commit

**Comment by Stunkymonkey** [comment]
wait, this means the error occured after this commit.
so the error is somewhere else

**Comment by Stunkymonkey** [comment]
do you need more logs?

**Comment by jangernert** [comment]
That and / or a way to reproduce the issue. Btw: 1e41562 was the last commit that affected the article view.

**Comment by Stunkymonkey** [comment]
With 1e41562 everything is working fine
maybe you have to use feedreader via ttrss
the only thing i do is: clicking my feeds in the unread tab
the biggest problem, i only experienced it after some time feedreader was runnning...

**Comment by brendanlong** [comment]
> With 1e41562 everything is working fine

Is this fixed then? I'm confused about if this problem still exists or not

**Comment by Stunkymonkey** [comment]
right now i am using the latest `master` and the problem only reoccurred once.
 but i am not able to give a reproducible example

**Comment by bilelmoussaoui** [comment]
You can still reproduce this issue using the latest version (2.2)?

**Comment by Stunkymonkey** [comment]
i am waiting for the aur to update `feedreader-git` or `feedreader`
my own attempt did compile, but i was unable to run it

**Comment by Stunkymonkey** [comment]
unable to reproduce

**Comment by bilelmoussaoui** [comment]
Thanks for the update
