### ISSUE TITLE
The same article appears multiple times after refresh

### ISSUE THREAD

**Issue by jvanz** [jangernert/FeedReader#64]
If I keep the FeedReader open and it updates my feed list, the new articles appear multiple times. See:

![feedreader_issue](https://cloud.githubusercontent.com/assets/1514798/13464036/f39e5e8e-e06d-11e5-84d2-d8c602cf4480.png)

After reopen the application, everything go back to normal

**Comment by jangernert** [comment]
First of all what version ae you using?
Second: how to reproduce this bug reliably? Cant seem to make the article-list misbehave on my machine.

**Comment by jvanz** [comment]
It's version 1.4.3
In my environment I just keep the FeedReader opened until it refreshes the feed

**Comment by jangernert** [comment]
Do you think you can test this again with the new beta (or better yet, master) to see if this is still an issue?

**Comment by bil-elmoussaoui** [comment]
This was fixed as far as i remember ;)

**Comment by jangernert** [comment]
@bil-elmoussaoui just want to make sure it is definitely gone
