### ISSUE TITLE
Can't log into Tiny Tiny RSS

### ISSUE THREAD

**Issue by jplatte** [jangernert/FeedReader#645]
Hi. As the title says, I can't log into my Tiny Tiny RSS (version 17.4) instance via FeedReader; the web interface works fine. All I get is the error message

> The server reported an API-error.

in the UI and

> [ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_API_ERROR
> [ DEBUG ] MainWindow: show error bar - errorCode = 6

on the command line.

How can I debug this further?

**Comment by jangernert** [comment]
The `feedreader` process won't give you much in tel on the issue. Try running the `feedreader-daemon` process yourself in a shell (obviously you have to kill the running instance first).
Alternatively you could try the master branch. The two binaries have been merged there, so you don't have to deal with that any longer.
Also did you install the [tt-rss API plugin](https://github.com/jangernert/FeedReader/tree/master/data/tt-rss-feedreader-plugin)?

**Comment by jplatte** [comment]
Thanks! Running `feedreader-daemon` gave me the required hint: tt-rss has a switch in the settings that you need to toggle for the API to be usable at all. I also hadn't installed the tt-rss API plugin yet, but for that there was a more useful error message in FeedReader. After installing that, everything seems to be working fine! :smile:
