### ISSUE TITLE
Crash on successfull Wallabag plugin connect

### ISSUE THREAD

**Issue by bipox** [jangernert/FeedReader#646]
I'm on manjaro linux using the latest feedreader version on the AUR repository.

If I make a mistake in the wallabag login page the message "something went wrong" appears, but if I enter correctly the credentials the app hangs for a second then crashes.

I will provide logs if you tell me how to.

Also I'm paying for wallabag hosting (https://app.wallabag.it), so I'm on whatever version they're using.

**Comment by svseidel** [comment]
The same here on Fedora 27. Cli-Output is given:

`(feedreader:8856): GLib-GIO-ERROR **: Settings schema 'org.gnome.feedreader.share.wallabag' does not contain a key named 'wallabag'`

I think, it´s similar to #405 - just without flatpak.

**Comment by brendanlong** [comment]
Hm so we have a schema.xml here: https://github.com/jangernert/FeedReader/blob/master/plugins/share/Wallabag/org.gnome.feedreader.share.wallabag.gschema.xml

I wonder if it's not getting installed for some reason?

**Comment by svseidel** [comment]
I´m not sure - I got the package from the original Fedora-Repository. The Flathub-package instead does.

**Comment by brendanlong** [comment]
Based on the comments on #405, it sounds like there was a bug that's fixed on master now.

It seems like there's a `feedreader-git` package in AUR that might be more up to date?
