### ISSUE TITLE
Wrong placement of Application Menu

### ISSUE THREAD

**Issue by peterychuang** [jangernert/FeedReader#647]
In GNOME Shell, when Application Menu on the top panel is disabled (using GNOME Tweak Tool), an "Application" menu appeared just below the header bar, which is redundant, as the same menu can be access with the app icon at the top left-hand corner of the header bar.

![screenshot from 2018-03-21 10-56-56](https://user-images.githubusercontent.com/13787892/37704634-9e3aa256-2cf9-11e8-81ce-625efb8bf41d.png) ![screenshot from 2018-03-21 10-13-59](https://user-images.githubusercontent.com/13787892/37704631-9ca5ce8e-2cf9-11e8-86f6-3eddcd872a2a.png)

Comparing this to the screenshot [here](https://raw.githubusercontent.com/jangernert/feedreader/gh-pages/images/gallery/Screenshot4.png), it appears the menu button has disappeared from the right of the search box.
![screenshot from 2018-03-21 11-37-47](https://user-images.githubusercontent.com/13787892/37705476-6eb55aa0-2cfc-11e8-865b-5219afa1c868.png)

**Comment by jangernert** [comment]
Gtk+ bug they labeled as won't fix.

**Comment by peterychuang** [comment]
So soon?

Well I've a workaround somehow, and it's probably incorrect, but it works for me:

```
 src/Widgets/ColumnViewHeader.vala | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/Widgets/ColumnViewHeader.vala b/src/Widgets/ColumnViewHeader.vala
index 6345c0c3..cfb705f7 100644
--- a/src/Widgets/ColumnViewHeader.vala
+++ b/src/Widgets/ColumnViewHeader.vala
@@ -91,7 +91,7 @@ public class FeedReader.ColumnViewHeader : Gtk.Paned {
 		m_header_left.get_style_context().add_class("titlebar");
 		m_header_left.set_size_request(500, 0);
 
-		if(GLib.Environment.get_variable("XDG_CURRENT_DESKTOP").down() != "gnome")
+		if(GLib.Environment.get_variable("XDG_CURRENT_DESKTOP").down() != "GNOME")
 		{
 			var menubutton = new Gtk.MenuButton();
 			menubutton.image = new Gtk.Image.from_icon_name("emblem-system-symbolic", Gtk.IconSize.MENU);
@@ -101,7 +101,7 @@ public class FeedReader.ColumnViewHeader : Gtk.Paned {
 			menubutton.set_tooltip_text(_("Settings"));
 			m_header_left.pack_end(menubutton);
 		}
-		else if(GLib.Environment.get_variable("XDG_CURRENT_DESKTOP").down() == "gnome")
+		else if(GLib.Environment.get_variable("XDG_CURRENT_DESKTOP").down() == "GNOME")
 		{
 			FeedReaderApp.get_default().app_menu = Utils.getMenu();
 		}
```

**Comment by jangernert** [comment]
You could open a PR and. Maybe someone (maybe even me) can test your change, so I can merge it ;)
