### ISSUE TITLE
Feed items are sorted in random order

### ISSUE THREAD

**Issue by City-busz** [jangernert/FeedReader#655]
Using the local backend, the new feed items are sorted in random order rather than by date.

Steps to reproduce:

1. Start feedreader.
2. Switch to the local backend.
3. Add some feeds.
4. See that the feed items are sorted in random order.

Tested with the latest git version as of 2018.04.19.

**Comment by City-busz** [comment]
Sorry, now I see that there is a setting to sort articles by date or when they are received. Anyway, it's a bit odd that the items of the newly added feeds are displayed in random order when they received at once.

**Comment by City-busz** [comment]
> during a single sync, it sets the received dates in such a way that it's the same as date order.

Yes, this is what I would like to see.

**Comment by brendanlong** [comment]
I'm thinking about how to do this, and I think the simplest thing is probably to make the default be "sort by date". It's the setting I use, since for the most part feeds set their dates correctly.
