### ISSUE TITLE
In current Flatpak on first launch asks to Change Account, doesn't allow New Account

### ISSUE THREAD

**Issue by sirredbeard** [jangernert/FeedReader#657]
I installed FeedReader on Pop_OS! 18.04 Beta, based on Ubuntu 18.04 Beta, via Flatpak:

`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref`

When I launch FeedReader, I get the following prompt, instead of the selection of RSS providers:

![screenshot from 2018-04-21 01-37-16](https://user-images.githubusercontent.com/33820650/39080868-dcd6edee-4504-11e8-8f9c-4e4632d795a8.png)

Furthermore, clicking "New Account" doesn't do anything. It clicks but nothing happens.

I tried scrounging around in the Flatpak to see if there was a config file somewhere I could delete to reset the app but I couldn't find anything definitive.

**Comment by sirredbeard** [comment]
Until the flatpak behaves, the workaround for Ubuntu and Ubuntu-derivates like Pop_OS is to build from source.
I have created a script and submitted it [here](https://github.com/jangernert/FeedReader/pull/660).

**Comment by brendanlong** [comment]
Ohh the Flatpak uses the `stable` branch, which hasn't been updated in about a year. Maybe this is just an old bug that has been fixed? I didn't even realize this branch existed.

**Comment by bilelmoussaoui** [comment]
Are you still able to reproduce this using the latest Flatpak package? v2.2 from Flathub!

**Comment by bilelmoussaoui** [comment]
Can you try the latest flatpak package from flathub ?
