### ISSUE TITLE
Issue building snap version of FeedReader 

### ISSUE THREAD

**Issue by sirredbeard** [jangernert/FeedReader#661]
I am attempted to build a snap version of FeedReader.
This is my first foray into making snaps.
Arch, OpenSUSE, Fedora, Solus all seem to be set with Feedreader with rpms or their own community packages.
Debian/Ubuntu/Pop_OS/elementary though currently rely on the wonky Flatpak or the temporary build-from-source script.
What Debian/Ubuntu users really need is a snap file, which is really the new packaging system those distros are adopting.
My current version of the Snapcraft.yaml file is [here](https://github.com/sirredbeard/FeedReader.git).

Unfortunately, the build fails partway through the snap installation even though it otherwise builds on this system.
It doesn't like something.
There is probably a parameter or path I need to pass to make it work but I am stumped.

I was wondering if you could take a look, see if anything comes to mind. If we can get it building in snap we can automate the process to build snap releases from your github, push them out to Debian/Ubuntu/Pop_OS/elementary users.

This is the build error I'm running into during the snapcraft process:

> [ 11%] Built target gtkimageview
> [ 11%] Linking C static library librss-glib.a
> [ 11%] Building C object libVilistextum/CMakeFiles/vilistextum.dir/unicode_entities.c.o
> [ 11%] Building C object libVilistextum/CMakeFiles/vilistextum.dir/util.c.o
> [ 11%] Built target i18n
> [ 11%] Building C object libIvy/CMakeFiles/ivy.dir/Stacktrace.c.o
> [ 12%] Building C object libVilistextum/CMakeFiles/vilistextum.dir/vilistextum.c.o
> [ 12%] Built target rss-glib
> [ 12%] Linking C static library libvilistextum.a
> [ 12%] Built target vilistextum
> [ 12%] Linking C static library libgd.a
> [ 12%] Built target gd
> [ 13%] Linking C static library libivy.a
> [ 13%] Built target ivy
> [ 14%] Linking C shared library libwebextension.so
> [ 14%] Built target webextension
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
> Failed to run 'make -j8' for 'feedreader': Exited with code 2.
> Verify that the part is using the correct parameters and try again.

Line 140 of the cmake-generated Makefile:

all: cmake_check_build_system
 	**$(CMAKE_COMMAND) -E cmake_progress_start /home/hayden/Documents/Projects/FeedReader/parts/feedreader/build/CMakeFiles /home/hayden/Documents/Projects/FeedReader/parts/feedreader/build/CMakeFiles/progress.marks**
 	$(MAKE) -f CMakeFiles/Makefile2 all
 	$(CMAKE_COMMAND) -E cmake_progress_start /home/hayden/Documents/Projects/FeedReader/parts/feedreader/build/CMakeFiles 0
 .PHONY : all

Any thoughts?

**Comment by sirredbeard** [comment]
Steps to reproduce:
1. install snapcraft on your distro
2. mkdir feedreadersnap
3. cd feedreadersnap
4. $ wget https://raw.githubusercontent.com/sirredbeard/FeedReader/master/snap/snapcraft.yaml
5. $ snapcraft
Expected results:
The snap is built and installed.
Actual results:
The build fails because of an error 2 when recipe for target 'all' fails.

**Comment by sirredbeard** [comment]
Here is the build log from the snapcraft automated build server:

Cloning into '787c26a72984a7ba1c265294ba8ef197-xenial'...
Submodule 'data/GrabberConfig' (https://github.com/fivefilters/ftr-site-config) registered for path 'data/GrabberConfig'
Cloning into 'data/GrabberConfig'...
Submodule path 'data/GrabberConfig': checked out '563925676d110a51197025aad8ddcac14d18e36a'
Running pull phase...
Sorry, Snapcraft ran into an error when trying to running through its
lifecycle that generated the following traceback:
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 9, in <module>
    load_entry_point('snapcraft==2.41', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 66, in pull
    _execute('pull', parts, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 33, in _execute
    lifecycle.execute(command, project_options, parts)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 61, in execute
    config = project_loader.load_config(project_options)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/__init__.py", line 25, in load_config
    return Config(project_options)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_config.py", line 98, in __init__
    snapcraft_yaml = _snapcraft_yaml_load(self.snapcraft_yaml_path)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_config.py", line 270, in _snapcraft_yaml_load
    return yaml.safe_load(fp)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "snap/snapcraft.yaml", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "snap/snapcraft.yaml", line 19, column 4
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 247, in run
    self.pull()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 206, in pull
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 96, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 456, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'http_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'https_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/787c26a72984a7ba1c265294ba8ef197-xenial && linux64 snapcraft pull']' returned non-zero exit status 1
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/slavebin/in-target scan-for-processes --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-197763
Scanning for processes to kill in build SNAPBUILD-197763
RUN: /usr/share/launchpad-buildd/slavebin/in-target umount-chroot --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-197763
Stopping target for build SNAPBUILD-197763
/usr/lib/python2.7/dist-packages/pylxd/model.py:116: UserWarning: Attempted to set unknown attribute "description" on instance of "Container"
  key, self.__class__.__name__
RUN: /usr/share/launchpad-buildd/slavebin/in-target remove-build --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-197763

**Comment by sirredbeard** [comment]
I have been tinkering with snap trying to get this to work.
Simply pulling in the git and using snap's built-in cmake generates the issue above.
Building from the Fedora RPM doesn't work very well.
Now simply trying embedding my entire script into the snap.

**Comment by brendanlong** [comment]
I don't think I can run this build on my distro (Fedora). Building from source is definitely the right way to go though. I think the Fedora RPM is ancient..

**Comment by brendanlong** [comment]
I can't get Snapcraft to work on my machine :(

You might to running in a more verbose mode to see what's actually failing. I think `make VERBOSE=1` will print the commands it's running.

**Comment by sirredbeard** [comment]
I am going to hold off on trying to get a new snap built until it's matured a bit, 18.04 has been finalized, and more people are running the latest valac.

In the mean time I have opened a formal package request in Ubuntu requesting an actual distro package and documenting my efforts: https://bugs.launchpad.net/ubuntu/+bug/1766086

**Comment by brendanlong** [comment]
Hm I just noticed something might be wrong with parallel builds sometimes. Does it work if you do just `make`?

We're in the middle of switching meson, so hopefully that should be better soon..

**Comment by sirredbeard** [comment]
I will try again with just make eventually. I made [this](https://github.com/sirredbeard/FeedReaderSnap) to document my efforts to date.

**Comment by sirredbeard** [comment]
I opened a bug at Snapcraft to get some help from them, https://bugs.launchpad.net/snapcraft/+bug/1766101

**Comment by brendanlong** [comment]
#662 Might make this easier

**Comment by brendanlong** [comment]
Hm it sounds like Snapcraft is confused about our dependencies so it isn't copying gcc, glib and zlib into the final snap? I'm confused about why it would do that though.

**Comment by brendanlong** [comment]
Is the problem with the first one that the command should be fully spelled out (/usr/bin/feedreader or /usr/local/bin/feedreader)?

**Comment by sirredbeard** [comment]
feedreader or /usr/bin/feedreader doesn't seem to make a difference on the first one.

Only the binaries and libraries from vala are carried over into the snap, see listing [here](https://gist.github.com/sirredbeard/58a715487266feba69c594f4667dc1b5).
 
No response in snapcraft IRC or RocketChat, so I posted [this](https://forum.snapcraft.io/t/snapcraft-breaking-over-nested-cmake-not-moving-built-files-into-staging-prime-and-dependency-issues/5084) on their forum.

**Comment by brendanlong** [comment]
In the second one, what is the `snap:` section? I don't see it in the syntax documentation:

https://docs.snapcraft.io/build-snaps/syntax

Should that be `stage` or `prime`?

Also, I wonder if we need to copy `/lib` and not just `/usr/lib` maybe, since zlib and glibc are plausibly libraries that would be there and not /usr/lib?

**Comment by sirredbeard** [comment]
Snap: is a deprecated form of prime: that seemed to work better. It probably should be prime. 

I am just getting inconsistent results out of prime: on the other files, so I tried snap: and it seemed to work.

Nothing there downloads or builds glibc or zlib, not sure putting it under prime would add it to snap.

I have forwarded this thread, my snapcraft forum post, and the bug report to a contact at Canonical.

**Comment by brendanlong** [comment]
We switched to the meson build, so hopefully that makes this easier.

**Comment by bilelmoussaoui** [comment]
Any progress on this? Honestly, I don't think we should bother ourselves by providing as much packaging solutions as possible. Flatpak does the job very well for us right now. No need nor the time to keep everything maintained by us. Especially that Snap makes it very hard for third party devs to package their apps. See what Peek developer thinks about that https://www.reddit.com/r/Ubuntu/comments/870bcn/snap_support_for_peek_screen_recorder_discontinued/

**Comment by bilelmoussaoui** [comment]
Closing as no answer from the author in a while.
