### ISSUE TITLE
Flatpak theming is broken

### ISSUE THREAD

**Issue by maxichan** [jangernert/FeedReader#663]
FeedReader is my only one application, which doesn't theme properly.
I installed arc-dark theme from flathub and another flatpak apps like Polari and Glade just works.
I run version 2.0.2

![zrzut ekranu z 2018-04-23 20-07-51](https://user-images.githubusercontent.com/25281105/39144866-62def56a-4732-11e8-803f-3bdd6ad4d4f6.png)

![zrzut ekranu z 2018-04-23 20-07-26](https://user-images.githubusercontent.com/25281105/39144915-7b8c1656-4732-11e8-8d88-a46dec367cf8.png)

**Comment by bilelmoussaoui** [comment]
It's definitely due to the old GNOME SDK that we do use for the current flatpak version https://github.com/jangernert/FeedReader/blob/master/flatpak/Makefile.config#L7. We will be switching to the latest runtime in the next version!

**Comment by glaere** [comment]
Is there any progress on this front? Feedreader is still not theming correctly for me.

Flatpak. Feedreader 2.8.2.
Kubuntu 18.04. Standard theme.

**Comment by bilelmoussaoui** [comment]
@glaere You need to install the gtk theme you're using as a flatpak too. The reason is that the flatpak might not use the gtk version installed on your system, which means that you might have a broken theme that might not work for an old or a recent gtk version.

**Comment by pecigonzalo** [comment]
This still does not work for me, not for flatpak or direct package in Arch.
