### ISSUE TITLE
Endless Syncing

### ISSUE THREAD

**Issue by JonnyCodewalker** [jangernert/FeedReader#669]
Solus 3.9995
Feedreade 2.0.2.2292
Feedreader is unable to fetch new feeds since it is endlessly syncing. Even after reinstalling and purging any files I could find the issue persisted. After reinstalling the button still is spinning and nothing happens.
When setting up a new account the recommendations seem to load, however upon adding one (e.g. OMG!Ubuntu) the endless spinning happens again.

**Comment by brendanlong** [comment]
Which backend are you using?

**Comment by JonnyCodewalker** [comment]
Feedreader is version 2.0.2.2292
How would i check which backend it is using?

**Comment by brendanlong** [comment]
I mean what RSS service is it using (or is it using the local version)? Like on that first page where it asks if you want to use Feedly, TT-RSS, Feebin, Local, etc.

**Comment by brendanlong** [comment]
Unfortunately version 2.0.2 is so long ago that I doubt we'll be fixing problems with it. We're planning to do a new release soon (none of the contributors to this project have a lot of free time).

**Comment by JonnyCodewalker** [comment]
Ah, i tried local RSS. On the next page where it recommends some (like OMG!Ubuntu) they seemed to load. However upon adding one it went into the endless spinning (wich interestingly persists after reinstalling, wich I find confusing)

**Comment by brendanlong** [comment]
Hm I suspect something weird is going on with the background process which we removed a while ago.

Can you try running [the script on our README](https://github.com/jangernert/FeedReader#ubuntu--) to install the latest version (remove the apt-get package first):

```
curl https://raw.githubusercontent.com/jangernert/FeedReader/master/scripts/install_ubuntu.sh | bash
```

**Comment by brendanlong** [comment]
Oh wait, that script needs one change.. just a second.

**Comment by JonnyCodewalker** [comment]
Am not on Ubuntu, so no apt. However i could try compiling it from source.

**Comment by brendanlong** [comment]
Ah I see. The instructions are probably similar to what that script does.

**Comment by JonnyCodewalker** [comment]
TBh i am not sure if they are up to date. Considering that there is no CMakeList.txt but the instructions call for cmake.

**Comment by JonnyCodewalker** [comment]
Instead of source i installed the flatpack-image. Interestingly it hangs on "waiting for current sync to finish", indicating that some program feerdeader calls might be the issue.

**Comment by brendanlong** [comment]
(I fixed the README with the meson updates)

**Comment by arcooke** [comment]
For what it's worth, I'm having this issue as well, and I'm also on Solus.  

I have an AWS instance of TinyTinyRSS and using FeedReader.  It connects to my instance fine, but the little update spinner just keeps on spinning forever.   Even if I click cancel on it, the icon turns dim and keeps on perpetually spinning.

I managed to get it to stop spinning at one point, and did a manual refresh from within FeedReader, and it said something like "we're syncing, it should appear in a few seconds" and it just never stopped syncing.

FeedReader:
```
Version: 2.2-dev
Git Commit: b60a7da212e65a9e2f42f50a524015c52bf527a4
```
TTRSS:
```
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1055-aws x86_64)
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|

  *** Welcome to the Bitnami Tiny Tiny RSS 17.4-4 ***
  *** Documentation:  https:/docs.bitnami.com/aws/apps/tiny-tiny-rss/ ***
  ***                 https:/docs.bitnami.com/aws/ ***
  *** Bitnami Forums: https://community.bitnami.com/ ***
```

**Comment by brendanlong** [comment]
Hmm you're using a commit from back in October, and the error reminds me of some stuff we ran into with the Meson build, so I'm curious if you still see this on the latest commit.

**Comment by brendanlong** [comment]
I also just fixed a problem that caused sync issues with the Feedbin plugin in 13e745bcf675aa8a5e9bf28996477b5a8e7eaf0d

**Comment by arcooke** [comment]
Ok thank you for the reply.  I may try building from source today if I have time, and see if a build from master solves the issue, and if so ask them to update their package on the solus repo

**Comment by oakbrad** [comment]
This seems to be the same issue I was having in #665 I am also on Solus 3.9995, I am not able to build from source on my machine so let us know how it goes @arcooke

**Comment by JonnyCodewalker** [comment]
Package got updated to 2.2, no need to keep this issue open.
