### ISSUE TITLE
Installing from source code error!

### ISSUE THREAD

**Issue by alchehabii** [jangernert/FeedReader#671]
After entering the command "cmake .." in Terminal, I received the following error:

"CMake Error: The source directory "/home/ma/FeedReader" does not appear to contain CMakeLists.txt."

So i went the FeedReader dir and i added a blank file with name "CMakeLists.txt"

Then i entered the same command again "cmake .." and i think it worked!

I moved to the next step and i typed "make" in terminal then i pressed enter, this step was successful performed as i believe.

During performing the last step "sudo make install", terminal showed unfortunately this message:

"make: *** No rule to make target 'install'.  Stop."

Is there any solution for this problem?
![screenshot from 2018-05-06 09 46 57](https://user-images.githubusercontent.com/10380737/39671186-b7bbdcac-5113-11e8-987d-0ac48ea49c42.png)

**Comment by bilelmoussaoui** [comment]
We don't use CMake anymore. I have created a PR to update the build instructions. 
```
meson builddir --prefix=/usr
ninja -C builddir test
sudo ninja -C builddir install
```
