### ISSUE TITLE
Upload a Flatpak for v2.2

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#676]
Just a note to myself to build a Flatpak and upload it here: https://github.com/jangernert/FeedReader/releases/tag/v2.2

I might try to build an RPM too if it's not too difficult.

**Comment by bilelmoussaoui** [comment]
I don't think it's needed, we can grab them from flathub! https://github.com/flathub/org.gnome.FeedReader/pull/3

**Comment by jscurtu** [comment]
Flathub does not create standalone flatpaks .. it’s more like a binary based git. I had a makefile that creates flatpak standalone packages in the flatpak folder before it was removed :)

**Comment by bilelmoussaoui** [comment]
Yeah, expect that we can't just build the flatpak package for each arch. We should just tell the people to use flathub instead. Btw, nothing is really removed with git

**Comment by jscurtu** [comment]
I know, all good.
32 bit is IMHO considered obsolete and being removed from distributions already today. So we only really need intel/and 64Bit. it’s also possible to build both at once ..

**Comment by bilelmoussaoui** [comment]
We can make the build automatic using Travis or circle CI

**Comment by brendanlong** [comment]
I'm fine with just pointing people at FlatHub if that will be up-to-date.

**Comment by bilelmoussaoui** [comment]
Flathub will be kept up to date by me. We just need to always update the AppData.
