### ISSUE TITLE
Hangs on install

### ISSUE THREAD

**Issue by erik-sk** [jangernert/FeedReader#678]
Having an issue with install. I made sure I had the required
    xdg-desktop-portal
    xdg-desktop-portal-gtk
Also have other Flatpak parts installed.
When I run 'flatpak install feedreader.flatpakref' (had also tried 'flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref) it gets to 
'Installing: org.freedesktop.Platform.GL.nvidia-375-82/x86_64/1.4 from gnome
Scanning metadata: 0'
I let it sit for a long time and nothing. 
Running Debian Stretch / Nvidia GeForce GT 730 (so I am thinking Nvidia stuff shouldn't be a problem)
This is the first time I have tried to install something with Flatpak, so I am not really up on what I could be missing here.

**Comment by jscurtu** [comment]
Unfortunatly the Flatpak instructions are out of date and need to be updated, the only supported flatpak is from flathub. 

https://flathub.org/home

please install from that repository ..

The one you listed will be removed and its not updated.

**Comment by erik-sk** [comment]
Thanks. I will give that a try.

**Comment by brendanlong** [comment]
I don't know what the new instructions would look like, but if someone wants to make a pull request I can review it.

**Comment by jscurtu** [comment]
I’ll do it, don’t worry.. just won’t be until the weekend

**Comment by bilelmoussaoui** [comment]
Updated that
