### ISSUE TITLE
Download full articles

### ISSUE THREAD

**Issue by gtrak** [jangernert/FeedReader#680]
Is it possible to detect and expand annoying articles like this one? Just following a link without opening a new browser would be nice.

![image](https://user-images.githubusercontent.com/852666/39899485-2e43578c-548a-11e8-84fe-b1f2629a570c.png)

**Comment by bilelmoussaoui** [comment]
We do use https://github.com/fivefilters/ftr-site-config To download the full article content. If the feeds you're using are not included. You can push a PR upstream.
