### ISSUE TITLE
Removed Feedly Feed reappears on sync

### ISSUE THREAD

**Issue by gtrak** [jangernert/FeedReader#681]
I think the intent would be to also remove it from the feedly account, or at least have a way to disable syncing in the reader app?

**Comment by brendanlong** [comment]
Something similar happened with the Feedbin plugin a while back. I'll look into this to see if Feedly has the same problem (and the other plugins..).

**Comment by brendanlong** [comment]
2aa023ebf01d1c01a9a0367fb23c9556974a4565 fixes this specific issue but the Feedly API probably needs more work..
