### ISSUE TITLE
Is it possible to scroll article by spacebar directly after press J-key.

### ISSUE THREAD

**Issue by lunarjoll** [jangernert/FeedReader#684]
I want to read easily, but now I have to left-client mouse to active article window after press J-key. then I can use pagedown or spacebar to scroll.

**Comment by jangernert** [comment]
Default settings are `u` and `i` to scroll the article. Directly above `j` and `k`.
You can change the keybindings with dconf-editor.
https://github.com/jangernert/FeedReader/blob/master/schemas/org.gnome.feedreader.keybindings.gschema.xml#L12

**Comment by lunarjoll** [comment]
But u and i is to slowly to scroll, I want some shortcut like pagedown. And now use pagedown need to active articleview window by mouse left click.
