### ISSUE TITLE
Feedreader website needs to be updated with new meson instructions

### ISSUE THREAD

**Issue by sirredbeard** [jangernert/FeedReader#685]
The page at https://jangernert.github.io/FeedReader/ still has the previous cmake instructions.

**Comment by bilelmoussaoui** [comment]
Oups:p Completly forgot about that!

**Comment by brendanlong** [comment]
Looks like we also need to change OwnCloud to NextCloud, and probably change the install instructions to just always tell people to use Flatpak.

**Comment by sirredbeard** [comment]
I agree, once Flatpak automatic generation is established. See #675.

Flathub has a build service that could pull from GitHub.

You could ship nightly Flatpaks as testing and then point releases as stable.

I would normally recommend Snaps too because they are generally lighter but you see all the hassle I went through trying to get build Feedreader, even with the conversion to meson.
