### ISSUE TITLE
feedreader.xarbit.net not found

### ISSUE THREAD

**Issue by matze** [jangernert/FeedReader#695]
I was trying to install the flatpak from the website but the URL is broken. If the flathub version is recommended, please update the installation instructions.

**Comment by jscurtu** [comment]
yes, that repository is no longer supported.

**Comment by Qwerty-Space** [comment]
So how do I install it?

**Comment by bilelmoussaoui** [comment]
Already fixed

**Comment by brendanlong** [comment]
@Qwerty-Space Follow the FlatHub setup instructions here: https://flatpak.org/setup/

Then install this: https://flathub.org/apps/details/org.gnome.FeedReader
