### ISSUE TITLE
Article read status not synced back to FreshRSS

### ISSUE THREAD

**Issue by rsolvang** [jangernert/FeedReader#699]
Problem; the articles I have read is changing status to unread when syncing with FreshRSS, possibly indicating a failure to sync changes back to the server. Have anyone else experienced this?
On my Android phone I use FeedMe, and the sync works as expected there.

**Comment by klausenbusk** [comment]
I spent some time debugging this, and I think it was incorrectly implemented.

So I added `file_put_contents('../../data/f', print_r($_POST, true). "\n", FILE_APPEND); ` to the top of `p/api/greader.php`, and this is the POST fields I got.

Staring a article:
```

Array
(
    [T] => <long-token>
    [a] => user/-/state/com.google/starred
    [r] => -/00056ed6de994908
)
```
Unstaring a article:
```
Array
(
    [T] => <long-token>
    [r] => -/00056ed6de994908
)

```

I think this line:
https://github.com/jangernert/FeedReader/blob/778b056c3b24fb8701ca3d245e614ccae78af36b/plugins/backend/fresh/freshAPI.vala#L295
Should be: `msg.add("i", "-/" + id);`

@Alkarex Can you confirm?

cc @jangernert as you implemented it.

**Comment by klausenbusk** [comment]
PR opened: https://github.com/jangernert/FeedReader/pull/705

**Comment by Alkarex** [comment]
Looks good and thanks for the PR 👍
