### ISSUE TITLE
all my icons are youtube logos

### ISSUE THREAD

**Issue by TheScrawl** [jangernert/FeedReader#700]
For some reason, all of my icons are youtube logos
[Screenshot](https://i.imgur.com/LtKy6cD.png)

I did previously import my youtube subscriptions from the opml provided by youtube, but i deleted those feeds, Im assuming it has something to do with this.

Im running Manjaro with XFCE on an Acer Aspire R3-471TG

**Comment by dikel** [comment]
I have similar problem. All of my icons are shuffled.

**Comment by laolux** [comment]
My icons were also shuffled. I solved the problem by deleting the contents of the `feed_icons` folder. On linux you find it at `~/.local/share/feedreader/data/feed_icons`. After deleting the old icons I had to completely quit feedreader (`kill`) and then restart it. Then it releoaded my icons and now it looks perfect :-)

**Comment by TheScrawl** [comment]
@laolux I would try this, however I have since uninstalled feedreader.

Hopefully that solution would help anyone else who is facing this issue though.
