### ISSUE TITLE
Unable to Log Into Feedbin

### ISSUE THREAD

**Issue by RemyPorter** [jangernert/FeedReader#704]
I use Feedbin for cross-device syncing. When I attempt to log in, I get an error: "Either your username or password is incorrect". They are correct. I can log in via the Feedbin website with those credentials, or I can even `curl` to the Feebin API endpoint with those credentials- which more or less seems to be the approach the Feedbin plugin code takes.

I'm on Manjaro, and this error happens no matter what install source I use for FeedReader- from KDE's Discover to yaourt's feedreader-git.

**Comment by RemyPorter** [comment]
I decided to throw on `httpry` and see what was happening that way- it doesn't appear that FeedReader is even sending an HTTP request.

**Comment by brendanlong** [comment]
Can you run FeedReader from the terminal and include the logs? I wonder if something else is going on :\

Using the latest git version is most likely to work.

**Comment by RemyPorter** [comment]
[feedreader.log](https://github.com/jangernert/FeedReader/files/2180093/feedreader.log)

[feedreader.error.log](https://github.com/jangernert/FeedReader/files/2180094/feedreader.error.log)

This is from the latest in Manjaro's standard repo.

**Comment by brendanlong** [comment]
I don't think we have a 2.2.1 release.. :\ Can you try the latest version from git (under the "manual" section here: https://github.com/jangernert/FeedReader#manual-installation)?

**Comment by RemyPorter** [comment]
2.2-1 is the version in the Manjaro repo, but that would explain a bit about why it's not working. I'll do a manual install tonight.

**Comment by brendanlong** [comment]
It looks like you're missing a "secret service". This should be installed automatically in most environments (I think GNOME and KDE both have one). I would try installing `libsecret`, and if that doesn't work, try installing `gnome-keyring` (this bug report on a different piece of software suggests KDE's secret service doesn't always work: https://github.com/Foundry376/Mailspring/issues/681)

**Comment by RemyPorter** [comment]
Looks like it's the KDE secret service which doesn't play nice. Thanks!
