### ISSUE TITLE
FeedReader on Debian (official request to debian package maintainers)

### ISSUE THREAD

**Issue by farshee90** [jangernert/FeedReader#706]
in order to get a deb package on Debian I opened a bug on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902304 ... please support it... maybe some package maintainer could take care of it if many people reply to this link...

**Comment by brendanlong** [comment]
I would recommend using the Flatpak, since it will be updated immediately on new releases and won't need to go through a second set of maintainers to get packaged.

**Comment by farshee90** [comment]
honestly, installing an app of 5mb with a gnome sdk dependencies of 250 mb from a package manager installed from a package manager it's a non-sense to me.

**Comment by dererk** [comment]
@jangernert @farshee90  I've prepared FeedReader native Debian's package. They are currently in NEW queue. So we should have news pretty soon.

**Comment by farshee90** [comment]
that's a great news !! !! !! thank you so much !! !! !! i hope that the collaboration betwenn developers and package mantainer will be easy and productive...
