### ISSUE TITLE
Flatpak unavailable

### ISSUE THREAD

**Issue by mlopezgva** [jangernert/FeedReader#711]
trying to install using
`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref`

returns a server not found error:

```
$ flatpak install https://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref
error: Can't load uri https://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref: Error al resolver «feedreader.xarbit.net»: Nombre o servicio desconocido

```

**Comment by brendanlong** [comment]
The Flatpak is on Flathub now: https://github.com/jangernert/FeedReader#via-flathub

**Comment by bilelmoussaoui** [comment]
We should merge https://github.com/jangernert/FeedReader/pull/697 ASAP

**Comment by bilelmoussaoui** [comment]
Fixed.
