### ISSUE TITLE
An error occured (SIGSEGV) after refreshing feeds

### ISSUE THREAD

**Issue by carbolymer** [jangernert/FeedReader#713]
I've added tt-rss server and after first import of links I am getting the segfault. Log here:
[feedreader.log](https://github.com/jangernert/FeedReader/files/2184871/feedreader.log)

**Comment by brendanlong** [comment]
Is this using the latest git commit? It might be more libvilistextum stuff but I can't reproduce it and I'm not really sure what's wrong (besides libvilistextum being a hard-to-use C library..). :\

**Comment by carbolymer** [comment]
There's different error for the latest master (053bf6a): 
[feedreader.log](https://github.com/jangernert/FeedReader/files/2194985/feedreader.log)

**Comment by brendanlong** [comment]
Hm, looks like an issue with the TT-RSS plugin (or the TT-RSS API -- it's always hard to tell). I haven't had time to work on this much and I don't have any experience with the TT-RSS plugin, but I can review pull requests if someone else figures out what's wrong.

**Comment by brendanlong** [comment]
Can you try v2.8.0? I just made a bunch of improvements to our TT-RSS plugin (both the FeedReader account plugin and the api_feedreader plugin on the TT-RSS side), not to mention the fixes in the v2.7 series that improved generic crashes.

I'm assuming this is working now but please re-open this if the latest doesn't work for you!
