### ISSUE TITLE
Set Default Browser Option

### ISSUE THREAD

**Issue by jasonscalia** [jangernert/FeedReader#718]
Hello,

I would like to request the ability to set your default browser to open articles in vs. just using the system default. For example, someone running running feedreader on an employer provided workstation may wish to open an article in a separate browser than what they use for work-related activities.

Thanks.

**Comment by bilelmoussaoui** [comment]
I don't think we are willing to implement such a thing. We are using portals to open the links and I don't think they allow us to select the browser to use. 
The portals are used to communicate with the system from a sandboxed application, Talking about flatpak here as it's our primary distribution system!

**Comment by bilelmoussaoui** [comment]
For me it's a wontfix. What do you guys think about this one @brendanlong @jangernert ?

**Comment by brendanlong** [comment]
I agree. I understand the use-case, but this seems like an uncommon case and I don't think we want to create single-user features (and since Flatpak is our primary packaging format, having a feature that doesn't work with it doesn't make sense for us).
