### ISSUE TITLE
Broken encoding 

### ISSUE THREAD

**Issue by acidhunter** [jangernert/FeedReader#719]
on arch linux, feedreader installed from repos i get this result with local rss & nextcloud news

![image](https://user-images.githubusercontent.com/8077558/43043446-5d56c03e-8d94-11e8-9e2b-ebb922f1aecf.png)

right pane with content does not get loaded

**Comment by naraesk** [comment]
Just installed feedreader on Arch Linux and have the same problem.

**Comment by brendanlong** [comment]
Can someone check if this still happens with the latest commit? I just merged #736 which could potentially fix a lot of encoding-related issues.

**Comment by bilelmoussaoui** [comment]
A new flatpak version should be available soon. Please try that and let us know if you still have this issue

**Comment by brendanlong** [comment]
See #712
