### ISSUE TITLE
Add support for microdonations

### ISSUE THREAD

**Issue by haeckle** [jangernert/FeedReader#72]
As the title says it would be really nice to have a dedicated button to give a tip to supported blogs.
Possible options are [Flattr](https://flattr.com/), [ChangeTip](https://www.changetip.com/) or [tibit](https://tibit.com/)

**Comment by jangernert** [comment]
And what about donations for FeedReader? :'(

**Comment by haeckle** [comment]
@jangernert hm, what about a link in the info-widget?
