### ISSUE TITLE
Add feed popup should assume http:// if a URL with no scheme is given

### ISSUE THREAD

**Issue by sianhulo** [jangernert/FeedReader#720]
every other feed I've tried worked, but I can't add defunctgames.com/feeds/medley/, when I click "add" it does nothing, the popup remains there as if I hadn't clicked anything, closing the application (with ctrl q) didn't work. I'm using feedreader 2.4-dev

**Comment by brendanlong** [comment]
I'll try to look into this more when I have time, but if someone else wants to look, I think it's very likely that we're getting an error somewhere an ignoring it. Most likely the problem is in the local plugin, but it could be in the DB layer or something.

**Comment by sianhulo** [comment]
Sorry for late reply. I didn't mean to say that ctrl+q doesn't work, what I tried to say was that even after fully closing the application (using ctrl+q) I still couldn't add the feed. And I can confirm that the application works fine after, I could add feeds even after failing to add this and I still got new articles.

**Comment by sianhulo** [comment]
This is just a hunch, as I haven't checked the code, but when i took a valid feed and removed a few characters, it'd attempt to add the feed but notify me it failed, whereas with this it doesn't even try, the same happens when the input is just a string with no domain or anything else (like 'test', for example) so, going by a hunch, maybe feedreader considers the url not valid or incomplete which is why it doesn't even attempt to load it

**Comment by sianhulo** [comment]
well, going by my hunch I did some testing and found a workaround, knowing that some feeds end with '?rss' or '?atom' I decided to add a '?' at the end of my url, as that in itself wouldn't break its functionality, and with that addition, feedreader correctly added the feed to my list!

**Comment by arthurazs** [comment]
Hey, I'm also facing a similar issue, I'm unable to add [this feed](http://feeds.bbci.co.uk/news/science_and_environment/rss.xml). It doesn't output any feedback.

How can I check the log? Cheers

**Comment by sianhulo** [comment]
if you start feedreader from the terminal you can see the log

**Comment by arthurazs** [comment]
It didn't do anything for me.
Opened from the terminal, try adding the rss feed but it didn't output anything, see below

![image](https://user-images.githubusercontent.com/3771055/43168840-1077cf0a-8f75-11e8-8439-b34db6100244.png)

**Comment by arthurazs** [comment]
Ctrl+Q worked, now I can see the log, thanks!

I'm using `FeedReader 2.4-dev`. See video below:

![Trying to add RSS](https://thumbs.gfycat.com/MinorOffensiveGoldenretriever-size_restricted.gif)

log:
```
arthurazs@inspiron:~$ feedreader 
feedreader-INFO: 19:56:41.913: FeedReader 2.4-dev
(feedreader:20603): Gtk-DEBUG: 19:56:41.962: Connecting to session manager
feedreader-INFO: 19:56:42.002: Plugin Name: Local RSS Backend
feedreader-INFO: 19:56:42.002: Plugin Version: 0.1
feedreader-INFO: 19:56:42.002: Plugin Website: http://jangernert.github.io/FeedReader/
feedreader-INFO: 19:56:42.002: Plugin Dir: /usr/lib/x86_64-linux-gnu/feedreader/plugins/
feedreader-INFO: 19:56:48.873: addFeed: ID = feedID00016
```

**Comment by sianhulo** [comment]
that's a very odd error because it doesn't even tell you it fails, it's just a blank notification, I recommend you recompile and try again, because the feed is working for me

**Comment by brendanlong** [comment]
Is this problem still happening? There were a bunch of changes to make our encoding work better, but I'm not sure if anything we've done solved this.

**Comment by sianhulo** [comment]
I updated to 2.7.1, but I'm still seeing the same behavior with the original comment's url: `defunctgames.com/feeds/medley/`

**Comment by brendanlong** [comment]
Thanks,  I'll try to reproduce this as soon as I can.

**Comment by brendanlong** [comment]
It works for me if I add the feed `http://www.defunctgames.com/feeds/medley/`. Is the problem just that we don't seem to automatically add http:// at the beginning?

**Comment by brendanlong** [comment]
I think #850 will fix this, if I'm understanding things right. Please let me know if there are other problems besides not automatically assuming http:// when there's no scheme given.

**Comment by brendanlong** [comment]
And #851 should make the error messages when adding feeds more helpful.
