### ISSUE TITLE
Replace ownCloud with Nextcloud on the webpage

### ISSUE THREAD

**Issue by schiessle** [jangernert/FeedReader#722]
After replacing ownCloud with Nextcloud in the config settings (https://github.com/jangernert/FeedReader/pull/589) I think it would make sense to replace it also on the webpage, what do you think?

Hope it is OK to create the issue here but I couldn't find a repository for the webpage. If there is a public repository I would be also happy to provide a pull request if you like. :slightly_smiling_face:

**Comment by jangernert** [comment]
The website is also in this repository in the [gh-pages](https://github.com/jangernert/FeedReader/tree/gh-pages) branch.
Looking forward to a PR :)

**Comment by schiessle** [comment]
here it is: https://github.com/jangernert/FeedReader/pull/723

**Comment by schiessle** [comment]
This was fast... already merged :slightly_smiling_face:

**Comment by brendanlong** [comment]
I rarely have time to work on FeedReader but reviewing pull requests is easy :)
