### ISSUE TITLE
"Please enter a valid password" when connecting to NextCloud

### ISSUE THREAD

**Issue by Yoshi2889** [jangernert/FeedReader#724]
When logging in to NC News, when you use a generated password, FeedReader won't login but will instead prompt the user with 'please enter a valid password'.

**Comment by naraesk** [comment]
Same here. Console output:

> ** Message: 12:11:22.157: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
> 
> (feedreader:19765): feedreader-CRITICAL **: 12:11:22.157: Password.setPassword: Cannot create an item in a locked collection
> feedreader-INFO: 12:11:22.157: Plugin Name: Nextcloud News
> feedreader-INFO: 12:11:22.157: Plugin Version: 0.1
> feedreader-INFO: 12:11:22.157: Plugin Website: http://jangernert.github.io/FeedReader/
> feedreader-INFO: 12:11:22.157: Plugin Dir: /usr/lib/feedreader/plugins/

**Comment by WisdomCode** [comment]
Although I do not know how and why this occurs, resetting the gnome keyring is helping with this error. It basically means that the FeedReader is not able to create a new key.

from the [Arch Wiki](https://wiki.archlinux.org/index.php/GNOME/Keyring#Resetting%20the%20keyring)
Remove "login.keyring" and "user.keystore" from /home/{username}/.local/share/keyrings/. After removing the files, simply log out and log in again. 
Obviously, this will remove your saved keys. 
This will however delete all previously saved keys on the keyring! However it worked for me.

**Comment by WisdomCode** [comment]
Sad to hear that.
This error has to be associated with the way the gnome keyring treats the user login data, so resetting it sounded like a reasonable idea.
@jangernert My solution was however only a workaround, not a solution, as this seems to be definetely a bug. It involved deleting all saved passwords, a process that should not be necessary but has proven to be a normal process for several users. I do not know how the interaction with the gnome keyring service is done, but it seems that there are some problems involved...
BTW nice profile picture, always great to meet a fellow Gothic Fan :D

**Comment by bilelmoussaoui** [comment]
We are using libsecret to interact with GNOME Keyring or any alternative that's supported by libsecret. If it doesn't work out of the box, it has to be an issue with the DE you're currently using.

**Comment by WisdomCode** [comment]
How exactly does the DE influence the way passwords are retrieved from the GNOME Keyring (or alternative)? Is there a library missing? 
Unfortunately the error report is not too precise about that...

**Comment by qazip** [comment]
Surely, if all the other software that store passwords work correctly in whatever DE one's using, something could be done in feedreader to fix this issue. If not, you should probably add a note in the README stating that feedreader only works in very specific DEs..

**Comment by bipox** [comment]
So this will most probably never work on KDE, meaning no feedreader for a huge part of linux users. 

This is the first program I can't run because of my DE choice.

Bummer, it's a great piece of software.

**Comment by bilelmoussaoui** [comment]
It's up to WM to unlock the keyrings and not to the app itself... other apps might not use libsecret. Please report it upstream instead

**Comment by brendanlong** [comment]
Are we missing code to prompt to unlock the keyring if it's not already? How do other apps do this?

Maybe we just need to call `secret_service_unlock`? https://developer.gnome.org/libsecret/unstable/SecretService.html#secret-service-unlock

**Comment by brendanlong** [comment]
(I can take a look at this.. sometime, but if someone else wants to do it first, I'd be happy to just review a pull request instead)

**Comment by brendanlong** [comment]
#793 has a sort-of fix for this, where we try to unlock the keyring at startup. It won't handle cases where the keyring gets locked again though.

**Comment by brendanlong** [comment]
I just released v2.5.0 which will attempt to unlock the keyring at startup. It should be on Flathub with an hour or so.

Please let us know if this doesn't fix it.

**Comment by bipox** [comment]
I can connect with nextcloud and inoreader, but in both cases feeds don't appear, it just says "OFFLINE" (even though authentification went fine)

**Comment by qazip** [comment]
I am having the same issue as @bipox, though mine is not resolved. I am using the package feedreader-git from aur and after login, it stays offline and never syncs. I also tried local-RSS and I still can't see feeds. Also, --verbose mode doesn't work, it just detaches..

**Comment by brendanlong** [comment]
@qazip Can you try running `pkill feedreader` and then try the --verbose version? It sounds like it's still running in the background.

I don't think the local plugin needs a password so I'm guessing you're seeing a different issue.

**Comment by qazip** [comment]
(feedreader:4806): feedreader-CRITICAL **: 15:09:24.899: Could not load response from Message to Nextcloud
(feedreader:4806): feedreader-DEBUG: 15:09:24.899: 

(feedreader:4806): feedreader-CRITICAL **: 15:09:24.899: <data>:1:1: Parse error: unexpected character `<', expected value

The local RSS also seems to work now, so it's most likely an url issue with the nextcloud instance. I am using disroot.org (https://cloud.disroot.org/apps/news/) but it's not working. What is the form of a nextcloud url? Should I explicititely point it to the news?

**Comment by brendanlong** [comment]
@qazip Can you give me an example of the kind of text we should we add? I'm not really very familiar with NextCloud. An example of good/bad URL's would be helpful (replace your domain with example.com for privacy).

**Comment by qazip** [comment]
You need to add, for example, "cloud.example.com" and not "cloud.example.com/apps/news".
