### ISSUE TITLE
Is the full content grabber working properly?

### ISSUE THREAD

**Issue by sianhulo** [jangernert/FeedReader#729]
this 8bithorse.blogspot.com/2018/07/rifter.html for example is displayed truncated by feedreader:
![feedreader 2018-08-05 19 30 05_6](https://user-images.githubusercontent.com/9102033/43691166-4a430518-98e6-11e8-88aa-db81b4cd6a51.png)
however, using five filters website the feed appears fully http://ftr.fivefilters.org/makefulltextfeed.php?url=http%3A%2F%2F8bithorse.blogspot.com%2F2018%2F07%2Frifter.html&max=3

**Comment by jangernert** [comment]
FeedReader only implements the config file aided approach to grab the full content. And as far as I can see there is no `8bithorse` config in their [repo](https://github.com/fivefilters/ftr-site-config). Their full-text-rss parser also implements some more general approaches. Maybe those are responsible for successfully  grabbing the article.

**Comment by sianhulo** [comment]
there's nothing for 8bithorse in particular. but there is for .blogspot.com that I'd expect to cover this. I also did a fork of this a ftr's project and added my own rules for it but I'm getting the same result. (though, admittedly, I don't know how to test my configs by themselves)

**Comment by jangernert** [comment]
Config files go to `$INSTALL_PREFIX/share/feedreader/GrabberConfig/`.
If you place a file there you can call `feedreader --grabArticle $URL` from the command line to just execute the [content grabber](https://github.com/jangernert/FeedReader/blob/master/src/ContentGrabber/grabber.vala) for that one url. Output should be written to `$HOME/.local/share/feedreader/debug-article`.
If you find some sort of problem we would be happy to review a pull request ;)

**Comment by sianhulo** [comment]
so excuse me, when you say "If you place a file there", do you mean a site specific file? those with the xpath rules and all that? I ask because it is empty, I don't know if it's normally meant to be empty as the rules are loaded from somewhere else and these would just be "custom" rules or if it should already have the ones from ftr-site-config.

**Comment by jangernert** [comment]
Yes, the ones with the xpath rules. And yes, the directory should contain lots of those. Did you compile from source? If so did you do a recursive clone of the repository? Otherwise `data/GrabberConfig` in your project folder might be empty.

As far as I remember if the `process()` call fails the default content of the feed is used.

**Comment by sianhulo** [comment]
[8bithorse.blogspot.com.txt](https://github.com/jangernert/FeedReader/files/2263088/8bithorse.blogspot.com.txt)
with these rules and this url http://8bithorse.blogspot.com/2018/08/flat-heroes.html I'm getting the following error in console:
[console-output.txt](https://github.com/jangernert/FeedReader/files/2263108/console-output.txt)

and the following file
[NULL.txt](https://github.com/jangernert/FeedReader/files/2263109/NULL.txt)

**Comment by jangernert** [comment]
This log is not that helpful. I guess you do need to do `feedreader --verbose --grabArticle $URL`, sorry.

**Comment by sianhulo** [comment]
sorry for the delay, here's the full log 
[better output.txt](https://github.com/jangernert/FeedReader/files/2263281/better.output.txt)

**Comment by jangernert** [comment]
I don't see any error in there. Looking at the html of the site everything looks okay too. The article ends with the sentence

> The game was published by Deck 13

And the text in your txt file ends with the same sentence as well. You haven't posted the content of the html file the grabber creates, but I'm assuming it'll have the full content of the article as well.

btw:
I almost applied for an internship at deck13 as a teenager :D 3D Art & level design is one of my hobbies.

**Comment by jangernert** [comment]
Looking at the html you could get the title either by `title: //title` which should get you:
> 8 Bit Horse: Flat Heroes

Or a tad more complex `title: //div[@class='title']/h2/text()` which should just yield:
> Flat Heroes

**Comment by sianhulo** [comment]
I thought those validity errors would be shows toppers. I thought the html had been uploaded, but now that I retired it seems that github doesn't allow for uploading them. Title parameter added as I somehow missed that aaaaand removing the feed and readding it yields... a crash? so, this time I launch from terminal to actually see what's happening and I'm getting a couple of 
`(feedreader:9235): feedreader-CRITICAL **: 12:45:08.555: localInterface.getArticles: Could not parse data contents
`
this time it didn't crash, but there's no feeds shown for 8bithorse, the content of the html https://pastebin.com/h52ES7fB
Annexed how the .html looks on the browser 
![screenshot_2018-08-06 screenshot](https://user-images.githubusercontent.com/9102033/43729867-9a7bb160-9977-11e8-8c2b-ca858c41d0b0.jpg)

Yeah, I modified it to use 
`title: //div[contains(concat(' ',normalize-space(@class),' '),' title ')]//h2`
Unfortunately, I can't get feedreader to parse the urls, and the .html file is grabbing the images from other articles somehow.

PS: had never heard of deck13, but I guess that just shows how much I know of european game development studies.

**Comment by sianhulo** [comment]
Ok, so half a success. Readretro.com is using my rules and giving me full articles, however, for some reason it is using 8bithorse's favicon instead of its own. 
![feedreader 2018-08-06 13 14 26_7](https://user-images.githubusercontent.com/9102033/43730843-b41698f8-997a-11e8-8e0d-7bba65340f16.png)

**Comment by sianhulo** [comment]
been gone some time. So, I've added rules for a few sites, and they all work fine except 8bithorse, I can't find out why. FeedReader adds the feed to my feed list, but the articles never appear. 
![feedreader 2018-08-06 21 28 13_1](https://user-images.githubusercontent.com/9102033/43748848-a5d13bfa-99bf-11e8-9784-40947248fd72.png)

the rules I'm currently using [8bithorse.blogspot.com.txt](https://github.com/jangernert/FeedReader/files/2264609/8bithorse.blogspot.com.txt)

**Comment by bilelmoussaoui** [comment]
A new flatpak version should be available soon. Please try that and let us know if you still have this issue

**Comment by sianhulo** [comment]
sorry for not replying until now. I compile from master and I could solve the no feeds problem by editing the database (the "all articles" number didn't match up the number of articles available on my section lists) as the 8bithorse horses actually existed.

After removing the articles manually and re-adding the feed the articles appeared. Without the full content, however, they show exactly the same the feed itself allows, even though using `--grabArticle` grabs the full article, something I'll have to live with, I guess.

**Comment by jangernert** [comment]
FeedReader does not parse articles again which it already tried to get the content for. There should be a flag column in the article table for that. Try resetting the flag for all articles of that feed with some SQL and let FeedReader update again. Then it should at least attempt to redownload the content again.

**Comment by sianhulo** [comment]
The feed was removed completely, so feedreader hadn't at that point fetched the article. However, I think I found the problem, and I don't think it can be "fixed" on FeedReader's site.

`http://feedproxy.google.com/~r/blogspot/jqoc/~3/mZtIfergLgc/dead-cells.html`seems to be what the feed gives you for the last article, while FeedReader is expecting `http://8bithorse.blogspot.com/2018/08/dead-cells.html` while the former leads to the latter it is still something FeedReader can't work with, so it essentially has no "rules" for the links the feed provides

**Comment by jangernert** [comment]
hmm, in theory that should be accounted for in the grabber:
https://github.com/jangernert/FeedReader/blob/master/src/ContentGrabber/grabber.vala#L124
here you can see that if no config was found, the grabber tries to download the url anyway and check if a redirect happens during that. It updates the `m_articleURL ` to the last redirect and looks for a fitting config file a 2nd time. If there is still no match the grabber just returns unsuccessful.

**Comment by sianhulo** [comment]
well, running again from console  I seem to have grabbed something relevant.

[log.txt](https://github.com/jangernert/FeedReader/files/2329160/log.txt)
I think there's more than one problem, starting with `http://8bithorse.blogspot.com/feeds/5334532026106483873/comments/default`as this doesn't seem to really be a valid url for what we want, then FeedReader attempts to apply rules to `feedproxy.google.com` and lastly it seems possible that here might be some problem going with the fact that another feed also uses feedproxy (elchiguirebipolar).
