### ISSUE TITLE
Removing a tag leads to crash

### ISSUE THREAD

**Issue by haeckle** [jangernert/FeedReader#73]
Trying to remove a tag from an article gives following error-output:
> [ DEBUG ] daemon: remove tag: -1035 from article: 111281
> [ DEBUG ] daemon: tagstring = -1035,-1037,-1039,-1040,-1028,
> [ DEBUG ] daemon: set tag string: -1037,-1039,-1040,-1028,
> **
> ERROR:arraylist.c:957:gee_array_list_real_get: assertion failed: (index < _size)
> Abgebrochen (Speicherabzug geschrieben)

The last one is german for
> Cancelled (Dump written)

I use the last version from git (850fb71a19d081d6dc89569bf04b8a2e6db24858) installed via AUR

**Comment by jangernert** [comment]
Which backend? And how to reproduce 100% reliably? FeedReader doesn't crash on my machine with tt-rss backend.

**Comment by jangernert** [comment]
Found the issue. It only happens when there are multiple tags on one article and you remove a tag other than the last one.
Btw: you should start the daemon and the ui separately when testing and logging ;)
That way it is clear which message is from the daemon and which is from the ui.

**Comment by haeckle** [comment]
Okay I will try to make better bug-reports in the future. I also run the ttrss-backend and with b9fb21df42f5267acd9e469beb57cf733a3b1b2b I can confirm it works now. Thanks a lot!
