### ISSUE TITLE
Lost all feeds after update on Arch

### ISSUE THREAD

**Issue by jschmidt** [jangernert/FeedReader#735]
![screenshot from 2018-08-23 08-10-46](https://user-images.githubusercontent.com/400806/44524566-17e0e300-a6ac-11e8-88a5-97f6abfc291b.png)

No feeds and as the screenshot shows, the All Articles heading contains garbage characters.

**Comment by bilelmoussaoui** [comment]
What does happen when you open the application from terminal? Copy/Paste the output here please

**Comment by bilelmoussaoui** [comment]
We have fixed some issues with encoding on the latest version (2.2.1) can you that out?

**Comment by jschmidt** [comment]
Sure, the encoding on "All Articles" works fine now, but it still lost all my feeds.


(gst-plugin-scanner:5893): GStreamer-WARNING **: 18:43:02.325: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstfluidsynthmidi.so': libfluidsynth.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5893): GStreamer-WARNING **: 18:43:02.490: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstopencv.so': libopencv_bgsegm.so.3.4: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5893): GStreamer-WARNING **: 18:43:02.523: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstlv2.so': liblilv-0.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:5893): GStreamer-WARNING **: 18:43:02.523: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory
feedreader-INFO: 18:43:02.645: FeedReader 2.2.1
(feedreader:5891): Gtk-DEBUG: 18:43:02.682: Connecting to session manager
feedreader-INFO: 18:43:02.834: Plugin Name: Local RSS Backend
feedreader-INFO: 18:43:02.834: Plugin Version: 0.1
feedreader-INFO: 18:43:02.834: Plugin Website: http://jangernert.github.io/FeedReader/
feedreader-INFO: 18:43:02.834: Plugin Dir: /usr/lib/feedreader/plugins/

**Comment by asm0dey** [comment]
@jschmidt is it possible to recreate them by reconnecting account again? ( I'm maintainer of feedreader-git package from AUR, so possibly I'm interested in solution too)

**Comment by jschmidt** [comment]
It was a local RSS account, so nothing to reconnect to.

**Comment by jangernert** [comment]
You can maybe scalvage your data from `$HOME/.local/share/feedreader/data` together with an application that can open sqlite database files.

**Comment by brendanlong** [comment]
Unfortunately I don't think there's anything more we can do here :(
