### ISSUE TITLE
FeedReader does not start - Failed to register: Timeout was reached

### ISSUE THREAD

**Issue by a-the** [jangernert/FeedReader#743]
FeedReader does not start anymore after crash. I wanted to change the active Feedly account to FreshRSS. During the process FeedReader crashed. Tried to run it with 'flatpak run' and got the message "Failed to register: Timeout was reached".

**Comment by a-the** [comment]
Not an issue anymore.

**Comment by brendanlong** [comment]
Thanks for updating the bug report! :)
