### ISSUE TITLE
Garbage as part of the summary of articles

### ISSUE THREAD

**Issue by sianhulo** [jangernert/FeedReader#745]
after updating to current master today (2.2.1) I have some garbage as part of summaries
![feedreader 2018-08-28 13 16 21_1](https://user-images.githubusercontent.com/9102033/44739078-cf1e9500-aac4-11e8-95c0-29c6df58e835.png)

This only affects articles fetched after the update, previously fetched articles still showing fine, and the articles themselves (both pre and post update) show fine.

The following shows in console:
`Feedreader:19279): Gtk-WARNING **: 13:19:55.521: Failed to set text 'Trump acusa a Google de manipular sus resultados para fomentar la L&#x3;&#x2;L&#x1; &#x4;\xfc\xbc\xa4\xa8\x93\x97缋&#x1;&#x1;&#x7;&#x1;&#x1;información negativa sobre él' from markup due to error parsing markup: Error en la línea 1, carácter 163: Texto codificado como UTF-8 en el nombre no válido; «Trump acusa a Google de manipular sus resultados para fomentar la L\u0003\u0002L\u0001 \u0004\xfc\xbc\xa4\xa8\x93\x97缋\u0001\u0001\u0007\u0001\u0001información negativa sobre él» no es válido
`

**Comment by brendanlong** [comment]
Probably related to #712 and #741 :\

**Comment by sianhulo** [comment]
Well, there's a workaround, if you launch the program using the environment variable `LANG=C`I won't get garbage with new feeds.

**Comment by brendanlong** [comment]
See #712
