### ISSUE TITLE
Flatpak - Schemas and favicons not working.

### ISSUE THREAD

**Issue by Dvlnst** [jangernert/FeedReader#754]
I just installed FeedReader from Flatpak on Debian 9.

dconf-editor:
![screenshot from 2018-09-07 19-16-18](https://user-images.githubusercontent.com/36289254/45233296-8a6bd880-b2d2-11e8-9326-2ee2b63b45ac.png)
![screenshot from 2018-09-07 19-29-26](https://user-images.githubusercontent.com/36289254/45233857-5c879380-b2d4-11e8-81b0-5ab525ddd8fb.png)

Any idea why schemas are not working?

Also, favicons doesn't work. Articles load fine but with favicons I get this message:
**(feedreader:3): feedreader-DEBUG: 19:27:09.652: Network not available, skipping favicon download**

I think both errors might be related, that's why I just created only one issue.

**Comment by Dvlnst** [comment]
Maybe it's related to schemas path: **/usr/local/share/glib-2.0/schemas**
Here this directory doesn't exist. I should be: **/usr/share/glib-2.0/schemas**

is it possible?

**Comment by bilelmoussaoui** [comment]
If you're still having an issue with the favicon download, please try the latest flatpak update from Flathub and reopen the issue if you're still facing the same issue.
