### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by reganto** [jangernert/FeedReader#758]
Wen run feed reader with this command ==> flatpak run org.gnome.FeedReader 
I get this error ==>
feedreader-INFO: 11:30:04.572: FeedReader 2.3.0
(feedreader:2): Gtk-DEBUG: 11:30:04.618: Connecting to session manager
(feedreader:2): Gtk-DEBUG: 11:30:04.619: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(feedreader:2): Gtk-DEBUG: 11:30:04.619: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(feedreader:2): feedreader-CRITICAL **: 11:30:29.926: FeedServer: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
feedreader-INFO: 11:30:29.926: Plugin Name: Feedbin
feedreader-INFO: 11:30:29.926: Plugin Version: 0.1
feedreader-INFO: 11:30:29.926: Plugin Website: http://jangernert.github.io/FeedReader/
feedreader-INFO: 11:30:29.926: Plugin Dir: /app/lib/feedreader/plugins/

** (feedreader:2): CRITICAL **: 11:30:29.926: feedbin_api_login: assertion 'self != NULL' failed

(feedreader:2): GLib-CRITICAL **: 11:30:30.069: g_utf8_strdown: assertion 'str != NULL' failed

(feedreader:2): GLib-CRITICAL **: 11:30:30.069: g_utf8_strdown: assertion 'str != NULL' failed

(feedreader:2): feedreader-CRITICAL **: 11:30:30.151: dbErrorLog: 283: recovered 3 frames from WAL file /home/morteza/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-7.db-wal

** (feedreader:2): CRITICAL **: 11:30:30.152: feed_reader_feedbin_utils_getUser: assertion 'self != NULL' failed

** (feedreader:2): CRITICAL **: 11:30:30.153: feed_reader_string_utils_split: assertion 's != NULL' failed
**
ERROR:linkedlist.c:1024:gee_linked_list_real_get: assertion failed: (index < this._size)
Error while executing 'addr2line -f -e /app/bin/feedreader 0x3ecfe3447a': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGABRT)
   The reason is likely a failed assertion (assert...).
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

**Comment by brendanlong** [comment]
Do you have gnome-keyring installed?

**Comment by reganto** [comment]
> Do you have gnome-keyring installed?

yes
