### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by yotamN** [jangernert/FeedReader#76]
I'm using the version from the Software Center on Fedora 23 and I have weird problems with the text, I attached an example from Fedora Magazine.
![screenshot from 2016-03-18 21-43-18](https://cloud.githubusercontent.com/assets/5249239/13890164/bbaa1d3c-ed52-11e5-8caf-8cdf4b07399c.png)
The FeedReader version is 1.4.3

**Comment by jangernert** [comment]
Like I said in #68: thats WebKitGtk+, I just throw in the HTML and CSS.

**Comment by jangernert** [comment]
Since this is very likely a duplicate, I will close this.
