### ISSUE TITLE
[UI] Cannot disable syncing

### ISSUE THREAD

**Issue by TimsManter** [jangernert/FeedReader#762]
Label says `0 = OFF` but UI is preventing to set 0 and the lowest value is 5 on both `2.3.0` and git versions.

![screenshot from 2018-09-27 15-19-07](https://user-images.githubusercontent.com/5507688/46148853-4765ab00-c269-11e8-813c-597a344335b9.png)

**Comment by KillianKemps** [comment]
I'm having the same issue on FeedReader `2.6.0`. 
I would like to disable the automatic syncing, but it's impossible to set 0 (OFF) as described in @TimsManter screenshot.

**Comment by brendanlong** [comment]
Thanks for the bug report, this is fixed in by 939ea589838492dfa2971047cb1b51a2099ff749.

I'll try to do a new release soon.

**Comment by KillianKemps** [comment]
Thank you!
