### ISSUE TITLE
Wrong favicon

### ISSUE THREAD

**Issue by marcolonna** [jangernert/FeedReader#763]
Many times the favicon of the new RSS added is replaced with a favicon of another feed; for example, I added _American Science_ to the reader, and from that moment, any other feed I add, the _American Science_ favicon appears and **not the correct favicon**.

**Comment by sianhulo** [comment]
I have had this problem, but it hasn't happened consistently for me to report, but it seems to happen more often when I remove a feed. you can replace the offending files on `~/.local/share/feedreader/data/feed_icons`

Notice that there should be an icon and text file with the same name per each favicon, generally the offending feeds will only have a text file with no corresponding icon, and I've had luck deleting said text files and restarting feedreader to force it to refetch said favicons.

**Comment by marcolonna** [comment]
> Are you using Flatpak? Which version exactly are you using?

I not have **flatpak** installed, I can install the version 1.0.4-24 _(2018-10-12)_

**Comment by bilelmoussaoui** [comment]
Well, you should because it's the only officially supported package.

**Comment by marcolonna** [comment]
> Well, you should because it's the only officially supported package.

I use **Solus OS** at moment, and the installation did not call **flatpak** as dependence, for this reason, I not installed yet.

**Comment by brendanlong** [comment]
Which server backend are you using (or are you using the local version)?

Just to confirm, you're seeing this issue on the latest version of FeedReader install from Flatpak? Can you please remove other versions to make sure you're not accidentally using a different one?

(Sorry if it seems weird that we're so focused on the Flatpak thing, but it's impossible for us to support distro packages since they tend to be old and frequently have the wrong dependencies)

**Comment by brendanlong** [comment]
Hm I can't reproduce this using either the Feedbin or local backends, and and looking at the code, I don't see anything obviously wrong. I also tried deleting a random icon but not the .txt, and that just caused it to have a default icon, not the icon of a different feed.

This code used to be much worse in an older version, so definitely trying the latest FeedReader is my best guess at a solution.

Does the problem go away if you restart FeedReader or do the bad icons stay even after a restart?

**Comment by marcolonna** [comment]
I only know that I have installed **FeedReader** in **Solus OS**, and I am not asked for the _flatpak_ package as a dependency; however, I installed it, and I continue to find the same problem: the feed favicons are wrong.

**Comment by jangernert** [comment]
I don't think you understand what a flatpak is. This has nothing to do with the FeedReader package in Solus or whatever distro you're using. It is a OS agnostic way of packaging applications. So you'll have to remove the Solus package and install the flatpak one instead.

**Comment by brendanlong** [comment]
You can find installation instructions here: https://flathub.org/apps/details/org.gnome.FeedReader

**Comment by marcolonna** [comment]
> I don't think you understand what a flatpak is. This has nothing to do with the FeedReader package in Solus or whatever distro you're using. It is an OS agnostic way of packaging applications. So you'll have to remove the Solus package and install the flatpak one instead.

Now I understand... ok no problem, I use another reader.

**Comment by brendanlong** [comment]
@sianhulo Which backend do you use? We store feed icons using their ID, but I wonder if some of the backends are capable of re-using ID's (like the local one?).

**Comment by marcolonna** [comment]
I don't know which backend I use in SOlu OS, I'm a beginner.

**Comment by brendanlong** [comment]
In the initial setup screen it should have asked if you want to connect to a service like Feedly, Feedbin, Owncloud, etc, or if you want to just do everything locally. I'm guessing you're using the local plugin (you didn't need to sign into anything)?

**Comment by marcolonna** [comment]
> In the initial setup screen it should have asked if you want to connect to a service like Feedly, Feedbin, Owncloud, etc, or if you want to just do everything locally. I'm guessing you're using the local plugin (you didn't need to sign into anything)?
No, I do not have to log-in in **FeedReader**.

**Comment by brendanlong** [comment]
I think I found the error:

```
		feedID = "feedID00001";

		if(!m_db.isTableEmpty("feeds"))
		{
			feedID = "feedID%05d".printf(int.parse(m_db.getMaxID("feeds", "feed_id").substring(6)) + 1);
		}
```

In the local client, when we set feed ID's, we use 1+highest current ID, and we use that ID for icons, so if you add a feed, then delete it, then add another feed, you'll get the same favicon.

There are probably two fixes we should do here:

 - Delete favicons when feeds are removed
 - Don't re-use feed ID's, either increment based on all historical ID's (SQLite AUTOINCREMENT) or just use random GUID's (or use the feed URL?)

**Comment by marcolonna** [comment]
I'm glad to have been able to help you show this bug, even if I regret not being able to help you, given my skills, in resolving it.

**Comment by sianhulo** [comment]
sorry for late reply, but I'm using the local backend, so that seems to be exactly the error I've been hit with.

**Comment by brendanlong** [comment]
Looks like I can reproduce it with the method described above:

![screenshot from 2018-10-27 11-40-43](https://user-images.githubusercontent.com/1447206/47606082-3d0c0d80-d9dd-11e8-84b5-a0a7c4d7110d.png)

Working on a fix now.

@marcolonna Thanks for the bug report. Actually fixing bugs is easy; getting enough information that we can reproduce them is really hard.

**Comment by brendanlong** [comment]
I think the pull request I just merged should fix this. I'll look into doing a release as soon as I can. As a workaround, this will fix the issue:

```
rm -r ~/.local/share/feedreader/data/feed_icons/
# then restart feedreader
```

(This will re-download all favicons)

**Comment by brendanlong** [comment]
I just finished a new FlatPak release.

@marcolonna @sianhulo If you update to the latest Flatpak release, this shouldn't happen anymore. For feeds with this existing problem, you can either remove and re-add them, or run this:

```
rm -r ~/.local/share/feedreader/data/feed_icons/
```

.. and then restart FeedReader.

**Comment by sianhulo** [comment]
well, I don't use flatpak (I compile my own), but I can confirm the issue isn't happening any longer.
