### ISSUE TITLE
Convert app menu to primary menu

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#766]
See:

https://blogs.gnome.org/aday/2018/10/09/farewell-application-menus/
https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

Looks like we should move our main menu from the app menu to a hamburger menu.

**Comment by bilelmoussaoui** [comment]
We already do that in elementary. We just need to remove the check we had for GNOME.
