### ISSUE TITLE
Support RSS feeds behind project shield

### ISSUE THREAD

**Issue by sianhulo** [jangernert/FeedReader#769]
sites like http://infodio.com/rss.xml use project shield to protect against ddos, and this causes javascript to be needed, but only the first time. It appears the site relies con cookies and if the cookies are set it won't trigger the project shield redirect. So if we can get optional cookies working on feedreader it should be able to read the rss feed (and crawl in case of ftr). Admittedly, I have no idea how much work this would require.

**Comment by brendanlong** [comment]
There are a few reasons I wouldn't want to do this:

 - Feed readers generally strip all JavaScript for security and performance reasons, and this would require us to execute arbitrary JavaScript for every feed
 - Loading feeds in a web view and executing JavaScript would be substantially slower than parsing XML
 - It's not even clear to me how we would detect how the project shield JavaScript has finished executing, so implementing this might involve flaky arbitrary-timeout code (which would make the performance even worse)

Unfortunately, RSS feeds are supposed to be XML and not Javascript, so these sites are just broken, and it's probably not reasonable for us to work around that.

**Comment by brendanlong** [comment]
(It sounds like CloudFlare can cause similar problems)

**Comment by sianhulo** [comment]
well, to be precise, the the feed is xml and not generated by the javascript. It is, unfortunately, guarded by javascript, though. I understand your reasons for not implementing this so you may close it. I'll try if I have any luck contacting the ones in charge of the website...
