### ISSUE TITLE
Endless Spinner

### ISSUE THREAD

**Issue by d0od88** [jangernert/FeedReader#77]
Not sure if it's an issue or by design but the top of the sidebar has a spinning graphic that doesn't seem to serve any purpose.

It's not related to 'syncing' (as even with no internet connection it carries on spinning).

In screenshots of the app on Github this spinner is replaced by an owncloud logo. I use FeedReader with Feedly. 

![screen shot 2016-03-20 at 21 23 22](https://cloud.githubusercontent.com/assets/869982/13907268/768aa230-eee2-11e5-908c-90fd587923e0.png)

**Comment by jangernert** [comment]
That should not happen. The feedly logo and your account name should appear as soon as the information has been fetched from the server. Could you open up dconf-editor and see if org->gnome->feedreader->feedly->email has your correct email address?

**Comment by d0od88** [comment]
Dconf was missing my e-mail address (possibly because I auth through Evernote?). 

I removed the existing account and created a new Feedly account using an e-mail. FeedReader's sidebar displays as expected: feedly logo and the e-mail address.

**Comment by jangernert** [comment]
Never tried Evernote. Does feedly know your email address when you create your account via Evernote?

Okay should have read the docs more carefully:

> email
    Optional string the email address extracted from the OAuth profile. Not always available, depending on the OAuth method used.

When logging in with Evernote, what is your account called? Pretty much every parameter other than the id is [optional](https://developer.feedly.com/v3/profile/). So something like: "if we don't have a email, try twitterUserId nex, if that is also not available then there will definitely be a facebookUserId". That way I could go down the list of possible account names and have something I can display beneath the feedly logo at the end :)

**Comment by jangernert** [comment]
Now I fetch the user information in this order

* userEmail
* givenName
* fullName
* google
* reader
* twitterUserId
* facebookUserId
* wordPressId
* windowsLiveId

this should be more than enough to display something useful in the sidebar
