### ISSUE TITLE
Crash with 2.3.0 flatpak & tt-rss on Fedora 28

### ISSUE THREAD

**Issue by jamespo** [jangernert/FeedReader#774]
Gets list of feeds but updating them consistenly segfaults

End of the debug log looks like:

(feedreader:2): feedreader-WARNING **: 19:43:29.877: Utils.UTF8fix: string is NULL

** (feedreader:2): CRITICAL **: 19:43:29.877: feed_reader_article_getHTML: assertion 'self != NULL' failed

** (feedreader:2): CRITICAL **: 19:43:29.877: feed_reader_article_getPreview: assertion 'self != NULL' failed

(feedreader:2): feedreader-WARNING **: 19:43:29.877: Utils.UTF8fix: string is NULL

** (feedreader:2): CRITICAL **: 19:43:29.877: feed_reader_article_getAuthor: assertion 'self != NULL' failed

** (feedreader:2): CRITICAL **: 19:43:29.877: feed_reader_article_getDate: assertion 'self != NULL' failed
(feedreader:2): GLib-DEBUG: 19:43:29.877: posix_spawn avoided (fd close requested) 
Error while executing 'addr2line -f -e /app/bin/feedreader 0x7f43655392cf': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

**Comment by Othko97** [comment]
Testing again with `flatpak run --devel org.gnome.FeedReader` will give access to `addr2line` and other debug tools for a more informative stack trace.

**Comment by bilelmoussaoui** [comment]
Thanks for letting me know about this. Will make sure to let the uses know about it in the future.

**Comment by jamespo** [comment]
trying to run with devel I get:

james@bigfed ~]$ flatpak run --devel org.gnome.FeedReader
error: runtime/org.gnome.Sdk/x86_64/3.30 not installed

**Comment by brendanlong** [comment]
Do you still see this in the latest version (v2.7.0)? We've made a lot of improvements to the string handling and threading code since you opened this bug report.

**Comment by jamespo** [comment]
Sadly no I still get


** (feedreader:2): CRITICAL **: 22:16:39.718: feed_reader_article_getDate: assertion 'self != NULL' failed
(feedreader:2): GLib-DEBUG: 22:16:39.719: posix_spawn avoided (fd close requested) 
Error while executing 'addr2line -f -e /app/bin/feedreader 0x7fd1c310fa7e': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

**Comment by valmar** [comment]
I am also affected by this error. I get this when fetching stuff from my self-hosted TT-RSS installation. The feed categories are fetched correctly, but I get this error when fetching the feeds

**Comment by brendanlong** [comment]
I think this should be fixed by v2.8.0 (specifically a52474a7fea023abc6ff9b873db6a0067f091254). Sorry for all the back and forth but can you try this again with the latest version?

**Comment by brendanlong** [comment]
I'm going to close this since it should be fixed in v2.8.0, but please re-open if you see this again

**Comment by jamespo** [comment]
Seems to be closed in 2.8.2. Thanks!
