### ISSUE TITLE
Various errors on executing flatpak version on Debian Stretch and doesn't launch

### ISSUE THREAD

**Issue by zombieramboz** [jangernert/FeedReader#781]
Installed Feedreader via flatpak today, and worked the first time I started it, but since then seeing the below in terminal:

xxxxxx@xxxxxx:~$ flatpak run org.gnome.FeedReader
feedreader-INFO: 13:44:24.008: FeedReader 2.3.0
(feedreader:3): GVFS-RemoteVolumeMonitor-DEBUG: 13:44:24.011: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(feedreader:3): GVFS-DEBUG: 13:44:24.011: cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
(feedreader:3): dconf-DEBUG: 13:44:24.020: watch_fast: "/org/gnome/feedreader/saved-state/" (establishing: 0, active: 0)
(feedreader:3): dconf-DEBUG: 13:44:24.020: change_fast
(feedreader:3): dconf-DEBUG: 13:44:24.020: change_notify: /org/gnome/feedreader/saved-state/currently-updating
(feedreader:3): dconf-DEBUG: 13:44:24.021: watch_established: "/org/gnome/feedreader/saved-state/" (establishing: 1)

(feedreader:3): dbind-WARNING **: 13:44:24.030: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
(feedreader:3): GVFS-DEBUG: 13:44:24.034: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(feedreader:3): dconf-DEBUG: 13:44:24.078: watch_fast: "/org/gnome/feedreader/" (establishing: 0, active: 0)
(feedreader:3): dconf-DEBUG: 13:44:24.079: watch_established: "/org/gnome/feedreader/" (establishing: 1)

(feedreader:3): feedreader-CRITICAL **: 13:44:24.103: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:3): dconf-DEBUG: 13:44:24.103: watch_fast: "/org/gnome/feedreader/feedly/" (establishing: 0, active: 0)
(feedreader:3): dconf-DEBUG: 13:44:24.103: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 0)
(feedreader:3): dconf-DEBUG: 13:44:24.103: watch_established: "/org/gnome/feedreader/feedly/" (establishing: 1)
feedreader-INFO: 13:44:24.104: Plugin Name: feedly
feedreader-INFO: 13:44:24.104: Plugin Version: 0.1
feedreader-INFO: 13:44:24.104: Plugin Website: http://jangernert.github.io/FeedReader/
feedreader-INFO: 13:44:24.104: Plugin Dir: /app/lib/feedreader/plugins/
(feedreader:3): dconf-DEBUG: 13:44:24.104: watch_established: "/org/gnome/feedreader/tweaks/" (establishing: 1)
feedreader-INFO: 13:44:25.103: feedly: userID = 9308a317-6dd6-4793-b2ff-92a21b6c801c
(feedreader:3): dconf-DEBUG: 13:44:25.103: change_fast
(feedreader:3): dconf-DEBUG: 13:44:25.103: change_notify: /org/gnome/feedreader/feedly/email
(feedreader:3): dconf-DEBUG: 13:44:25.103: change_fast
(feedreader:3): dconf-DEBUG: 13:44:25.103: change_notify: /org/gnome/feedreader/plugin
(feedreader:3): GLib-DEBUG: 13:44:25.110: posix_spawn avoided (automatic reaping requested) (child_setup specified) 
(feedreader:3): GLib-DEBUG: 13:44:25.113: posix_spawn avoided (automatic reaping requested) (child_setup specified) 

(WebKitWebProcess:13): dbind-WARNING **: 13:44:25.183: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
(feedreader:3): dconf-DEBUG: 13:44:25.200: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)

(process:15): GLib-GIO-WARNING **: 13:44:25.207: Failed to get the 'connectivity' property

(process:15): GLib-GIO-WARNING **: 13:44:25.208: Failed to get the 'metered' property

(process:15): GLib-GIO-WARNING **: 13:44:25.208: Failed to get the 'available' property

(feedreader:3): feedreader-CRITICAL **: 13:44:25.262: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:3): feedreader-CRITICAL **: 13:44:25.265: dbErrorLog: 283: recovered 578 frames from WAL file /home/adrian/.var/app/org.gnome.FeedReader/data/feedreader/data/feedreader-7.db-wal
**
ERROR:arraylist.c:967:gee_array_list_real_get: assertion failed: (index < _size)
(feedreader:3): GLib-DEBUG: 13:44:25.269: posix_spawn avoided (fd close requested) 
Error while executing 'addr2line -f -e /app/bin/feedreader 0x7f1022d81504': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGABRT)
   The reason is likely a failed assertion (assert...).
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

**Comment by brendanlong** [comment]
I think the recent threading-related fixes may have solved this. Can you let us know if this is still happening?

(I'm closing this just so I can keep track of what's still happening but feel free to re-open it if your problem is still occuring)
