### ISSUE TITLE
We have both FeedReader.pot and feedreader.pot in translations

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#783]
Just opening this to check with @bilelmoussaoui: Is this a mistake? I'm having trouble editing FeedReader on OS X because the file system isn't case sensitive so it won't let both files exist at the same time.

I can't tell if one of these files doesn't need to exist or not?

**Comment by bilelmoussaoui** [comment]
We are using the lower case `feedreader`  see
https://github.com/jangernert/FeedReader/blob/98dd749faf8e12d75d31955d0d9d64bc209629ed/po/meson.build#L1
https://github.com/jangernert/FeedReader/blob/98dd749faf8e12d75d31955d0d9d64bc209629ed/meson.build#L1

**Comment by bilelmoussaoui** [comment]
Fixed
