### ISSUE TITLE
Can't launch the app from flatpak Fedora 29 

### ISSUE THREAD

**Issue by ibanha** [jangernert/FeedReader#787]
Hi everyone. Just installed Feed Reader from flathub on Fedora 29 and can't launch the app. 
In attached file is that I'm seeing when trying to launch it from terminal.

xdg-desktop-portal and xdg-desktop-portal-gtk are installed.

[log.zip](https://github.com/jangernert/FeedReader/files/2553804/log.zip)

**Comment by bilelmoussaoui** [comment]
Could you copy and paste the logs here instead?

**Comment by ibanha** [comment]
`
➜  ~ flatpak run org.gnome.FeedReader 
feedreader-INFO: 17:09:47.380: FeedReader 2.4.0
(feedreader:2): GVFS-RemoteVolumeMonitor-DEBUG: 17:09:47.382: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(feedreader:2): GVFS-DEBUG: 17:09:47.382: cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
(feedreader:2): dconf-DEBUG: 17:09:47.389: watch_fast: "/org/gnome/feedreader/saved-state/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.389: change_fast
(feedreader:2): dconf-DEBUG: 17:09:47.389: change_notify: /org/gnome/feedreader/saved-state/currently-updating
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_established: "/org/gnome/feedreader/saved-state/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.390: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.393: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.394: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.394: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.394: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.394: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
(feedreader:2): GVFS-DEBUG: 17:09:47.446: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(feedreader:2): dconf-DEBUG: 17:09:47.509: watch_fast: "/org/gnome/feedreader/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.510: watch_established: "/org/gnome/feedreader/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.535: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.535: watch_fast: "/org/gnome/feedreader/inoreader/" (establishing: 0, active: 0)

(feedreader:2): feedreader-WARNING **: 17:09:47.536: Utils.gsettingReadString: failed to read org.gnome.feedreader.inoreader username

(feedreader:2): feedreader-WARNING **: 17:09:47.536: Utils.gsettingReadString: failed to read org.gnome.feedreader.inoreader access-token
(feedreader:2): dconf-DEBUG: 17:09:47.536: watch_established: "/org/gnome/feedreader/inoreader/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.544: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.545: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.545: watch_fast: "/org/gnome/feedreader/feedly/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.545: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.547: watch_established: "/org/gnome/feedreader/feedly/" (establishing: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.547: watch_established: "/org/gnome/feedreader/tweaks/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.551: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.552: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.552: watch_fast: "/org/gnome/feedreader/oldreader/" (establishing: 0, active: 0)

** (feedreader:2): WARNING **: 17:09:47.552: invalid type for attribute type

(feedreader:2): feedreader-WARNING **: 17:09:47.552: Utils.gsettingReadString: failed to read org.gnome.feedreader.oldreader username

(feedreader:2): feedreader-WARNING **: 17:09:47.552: Utils.gsettingReadString: failed to read org.gnome.feedreader.oldreader access-token

(feedreader:2): feedreader-WARNING **: 17:09:47.552: Utils.gsettingReadString: failed to read org.gnome.feedreader.oldreader username
(feedreader:2): dconf-DEBUG: 17:09:47.552: watch_established: "/org/gnome/feedreader/oldreader/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.558: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.558: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.558: watch_fast: "/org/gnome/feedreader/bazqux/" (establishing: 0, active: 0)

(feedreader:2): feedreader-WARNING **: 17:09:47.558: Utils.gsettingReadString: failed to read org.gnome.feedreader.bazqux username

(feedreader:2): feedreader-WARNING **: 17:09:47.558: Utils.gsettingReadString: failed to read org.gnome.feedreader.bazqux access-token

(feedreader:2): feedreader-WARNING **: 17:09:47.558: Utils.gsettingReadString: failed to read org.gnome.feedreader.bazqux username
(feedreader:2): dconf-DEBUG: 17:09:47.559: watch_established: "/org/gnome/feedreader/bazqux/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.589: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.589: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.594: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.594: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.595: watch_fast: "/org/gnome/feedreader/feedhq/" (establishing: 0, active: 0)

(feedreader:2): feedreader-WARNING **: 17:09:47.595: Utils.gsettingReadString: failed to read org.gnome.feedreader.feedhq username

(feedreader:2): feedreader-WARNING **: 17:09:47.595: Utils.gsettingReadString: failed to read org.gnome.feedreader.feedhq access-token

(feedreader:2): feedreader-WARNING **: 17:09:47.595: Utils.gsettingReadString: failed to read org.gnome.feedreader.feedhq username
(feedreader:2): dconf-DEBUG: 17:09:47.595: watch_established: "/org/gnome/feedreader/feedhq/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.602: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.602: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.603: watch_fast: "/org/gnome/feedreader/ttrss/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.604: watch_established: "/org/gnome/feedreader/ttrss/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.610: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.610: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.610: watch_fast: "/org/gnome/feedreader/feedbin/" (establishing: 0, active: 0)

(feedreader:2): feedreader-WARNING **: 17:09:47.610: Utils.gsettingReadString: failed to read org.gnome.feedreader.feedbin username

(feedreader:2): feedreader-WARNING **: 17:09:47.610: Utils.gsettingReadString: failed to read org.gnome.feedreader.feedbin username
(feedreader:2): dconf-DEBUG: 17:09:47.611: watch_established: "/org/gnome/feedreader/feedbin/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.616: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.616: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.616: watch_fast: "/org/gnome/feedreader/fresh/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.616: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:2): dconf-DEBUG: 17:09:47.617: watch_established: "/org/gnome/feedreader/fresh/" (establishing: 1)

(feedreader:2): feedreader-CRITICAL **: 17:09:47.621: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]

(feedreader:2): feedreader-CRITICAL **: 17:09:47.622: dbErrorLog: 21: misuse at line 147157 of [c7ee083322]
(feedreader:2): dconf-DEBUG: 17:09:47.622: watch_fast: "/org/gnome/feedreader/owncloud/" (establishing: 0, active: 0)
(feedreader:2): dconf-DEBUG: 17:09:47.622: watch_established: "/org/gnome/feedreader/owncloud/" (establishing: 1)
(feedreader:2): GLib-DEBUG: 17:09:47.630: posix_spawn avoided (automatic reaping requested) (child_setup specified) 
(feedreader:2): GLib-DEBUG: 17:09:47.637: posix_spawn avoided (automatic reaping requested) (child_setup specified) 
(feedreader:2): dconf-DEBUG: 17:09:47.712: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 2)

(feedreader:2): Gtk-WARNING **: 17:09:47.773: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Paper/16x16/status/image-missing.png: Error opening file /run/host/share/icons/Paper/16x16/status/image-missing.png: No such file or directory (g-io-error-quark, 1)
(feedreader:2): GLib-DEBUG: 17:09:47.779: posix_spawn avoided (fd close requested) 
Error while executing 'addr2line -f -e /app/bin/feedreader 0x7f9e6ab1c515': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGABRT)
   The reason is likely a failed assertion (assert...).
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?`

**Comment by ibanha** [comment]
I found out why the app doesn't launching. The problem is my icon pack. I've changed my current icon pack to the default Gnome icon pack. Now the app is working

**Comment by jangernert** [comment]
That is weird indeed. If Gtk+ can't find a specific icon in the icon theme it uses some sort of broken page icon as a replacement. Maybe this works differently for flatpaks?
