### ISSUE TITLE
FreshRSS URL Scheme

### ISSUE THREAD

**Issue by Wdavery** [jangernert/FeedReader#789]
What URL is FeedReader looking for in a FreshRSS? 

- https://rss.site.com
- rss.site.com
- [https://] rss.site.com/p/
- [https://] rss.site.com/p/api/greader.php

I had it working previously but had to reinstall do to the spring-cleaning bug. I remember having a hard time getting it to find the server before but eventually found the right URL. 

Server configuration passes on FreshRSS. 
#505 and #640 seem to be of no help.

**Comment by jangernert** [comment]
I don't really remember, but looking at the code it should be something like:
`https://abc.com/api/greader.php/`
