### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by mimi89999** [jangernert/FeedReader#790]
After running FeedReader for several days connected to my Nextcloud news instance, receiving and reading several articles per day, FeedReader is using 700 MB of RAM. Memory usage seems to be growing with time and with the number of articles I've read. I find that this memory usage is quite high and suspect that there might be a memory leak somewhere.

**Comment by jangernert** [comment]
Yep, you'll get a cookie from me if you find it :)
Already fixed a good bunch of leaks a good while ago. But none of them were the main cause of this problem.

**Comment by jangernert** [comment]
Every leak I could make out in valgrind is already fixed. Everything that is left doesn't make too much sense to me either.

**Comment by brendanlong** [comment]
I wonder if this is still-reachable psuedo-leaks? Do we have any big static caches? I know we cache favicons forever but they should never take up that much space (and that cache would fill up pretty much instantly when the app finishes starting).

**Comment by jangernert** [comment]
I noticed the leak is at least in part related to the sync. This was also true back when UI and background process were still separated.
Nevertheless I also don't 100% trust that all old widgets are properly destroyed or some signals not being disconnected keep objects alive unintentionally. Vala is not really all that transparent about its memory management. I believe I do understand it better than a few years ago. But still hard to find the culprit in tons of old code.
One more reason to <3 Rust =)

**Comment by brendanlong** [comment]
At least in the short term, memory usage seems pretty constant to me:

![screenshot from 2018-11-23 13-45-52](https://user-images.githubusercontent.com/1447206/48957356-25fe0400-ef26-11e8-9171-2fc21b230629.png)

(The spikes are when  I was flipping through articles or running syncs)

I'll leave this running as long as I can to see if anything happens.

I'm using the Feedbin plugin (the plugin I'm most confident about) so it would be interesting to see heaptrack data from other backends.

**Comment by bilelmoussaoui** [comment]
@brendanlong you can use sysprof from Builder ;) it could get you a lot of interesting data.

**Comment by brendanlong** [comment]
I'm not seeing this problem, so I'm going to close it for now. Maybe we fixed in some of the DB changes?
