### ISSUE TITLE
Feedbin isn't proprietary or GPL

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#794]
I just noticed that the Feedbin plugin marks it as proprietary:

```
	public BackendFlags getFlags()
	{
		return (BackendFlags.HOSTED | BackendFlags.PROPRIETARY | BackendFlags.PAID);
	}
```

But the source code of Feedbin is released under the MIT license, which qualifies as Free Software. I'm not sure if I should switch to BackendFlags.FREE_SOFTWARE though since that causes us to show a "GPL" logo, and it's not GPL.

Any idea what we should do here?

**Comment by jangernert** [comment]
I was not aware that Feedbin is free software at the time. You'll have to admit it's not very prominent on the website.

**Comment by brendanlong** [comment]
I'm just not sure how to handle this, since the only two options are proprietary and GPL, and Feedbin is neither :\

**Comment by brendanlong** [comment]
What if our options were "proprietary" and "open source" and we use the OSI icon? https://opensource.org/logo-usage-guidelines

I know Free Software and Open Source are different, but I can't find a general-purpose Free Software icon.
