### ISSUE TITLE
Handle submodules in Flatpak

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#813]
The latest release isn't working because it needs a git submodule to load and I'm not sure how to do that in Flatpak. Maybe we should just add it as a separate source but I'm not sure how to link it into the build directory.

I wonder if this also caused problems with grabber configs since those are also a submodule?

**Comment by brendanlong** [comment]
You can install libdecsync-vala using a module like this:

```

    {
      "name": "libdecsync-vala",
      "buildsystem": "meson",
      "sources": [{
        "type": "git",
        "url": "https://github.com/39aldo39/libdecsync-vala.git",
        "commit": "30681106cf38c4017e428630ee365e1a15eed318"
      }]
    },
```

I don't know how to get that copied into the build directory for feedreader though.

**Comment by bilelmoussaoui** [comment]
Will take a look

**Comment by petefwalter** [comment]
Same thing here: can't build the fedora package any more due to this.

**Comment by brendanlong** [comment]
I just did a new v2.6.1 release which merges all of this stuff into our repo. Can you take a look and see if that works for you?

**Comment by petefwalter** [comment]
It does. Thanks!
