### ISSUE TITLE
Problem with embedded youtube videos and whitespace

### ISSUE THREAD

**Issue by sianhulo** [jangernert/FeedReader#817]
I updated earlier this week and noticed that a site where I'm using full content grabber with custom rules, is now adding whitespace before every video which didn't use to happen before (last time I updated prior that should be 10 days ago), old articles still appear normally, so it seems to be the way new articles are fetch rather than the parsing of said fetch articles. 

this is visible for me with the following feed https://feeds.feedburner.com/nichegamer using the following configuration 
[nichegamer.com.txt](https://github.com/jangernert/FeedReader/files/2658511/nichegamer.com.txt)

**Comment by brendanlong** [comment]
I wonder if this is related to #818

**Comment by brendanlong** [comment]
Did you see this with version v2.5.1?

**Comment by sianhulo** [comment]
I'm currently on 2.6.0, my previous version was 2.5.0 and I don't think it happened there, let me rollback to confirm.

**Comment by sianhulo** [comment]
Strangely enough, the problem seems to persist now on 2.5.0 as well, old feeds are fine, new feeds are not, even though they were working fine before, and unfortunately something like youtube videos isn't something that can be loaded from the files one obtained from --grabArticle.

**Comment by jangernert** [comment]
What does the grabbed html document look like?
I don't really know CSS apart from styling Gtk+ with it, but apparently these classes are used to generate some kind of grid layout. Could this be the problem here?
```
<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12" id="generated-content">
```

**Comment by sianhulo** [comment]
I can confirm that the video container is inside in one such element inside a tested article but I wouldn't know if that's the problem as I can't see the videos in the preview.

**Comment by sianhulo** [comment]
Ok, so the problem is in the html, but I don't think it's that class, inside of video container we seem to have an element we shouldn't have, there's `.videoWrapper`(which contains and iframe with the video) and an iframe`.lazy` which also supposedly contains the video, or at least it seems that way initially, cause it ends up being an empty space. 

![screenshot_2018-12-12 screenshot](https://user-images.githubusercontent.com/9102033/49914502-e2812080-fe67-11e8-81cc-8dd08caee066.png)
but if we remove .lazy it looks normally (well, beside the aspect ratio, but I wouldn't mind that much) 
![screenshot_2018-12-12 screenshot 1](https://user-images.githubusercontent.com/9102033/49914535-05133980-fe68-11e8-9985-8922e17295c5.png)

**Comment by sianhulo** [comment]
as the element at fault was found, I added an extra rule to my config file:
`strip: //*[contains(concat(" ",normalize-space(@class)," ")," lazy ")] `

the remove the element when fetching, and so the empty space has disappeared, unfortunately as I don't have any other feeds that embed youtube videos, it'll be hard to find where the fault lies, if this could end up affecting every feed where content grabber is used and youtube embeds are present, or if it might have been a change on the site itself.

You might want to leave this one open in case someones wants to confirm or deny that this problem is present with other feeds where content grabber is used with pages with youtube embeds.

**Comment by jangernert** [comment]
I'm guessing the first iframe tag needs javascript to work properly? It has the link to the video in `data-src` instead of `src`. The second iframe is the Noscript version.
So most likely there was a change on the website at some point that introduced this.
I don't think this can be classified as a 'bug' in the content grabber.
Btw: why not `iframe` instead of `*` in your xpath expression? Are there more of these lazy load elements on the page apart from the video iframe?

**Comment by sianhulo** [comment]
I guess you could say that was me... being lazy. It was just to point out the problem and the workaround. Also, alternatively to the site changing something, I guess it is possible that youtube might have changed how their embeds work?

Anyway, as it is very unlikely this was a feedreader bug to begin with, I'll be closing the issue.
