### ISSUE TITLE
Full text grabber not working on most feeds (--grabArticle on the command line works)

### ISSUE THREAD

**Issue by ksl1989** [jangernert/FeedReader#818]
I am only getting the summary on the rss feed on most of my feeds, although there is a text grabber config that I can confirm as working through the command line "--grabArticle" argument. At first I assumed this was just happening on the configs I wrote myself and assumed I was doing something wrong, but even on the NYTimes feed I'm just getting a short summary although there is a working config file by default.

## Example with a config file I wrote:
**Feed:** https://www.scmp.com/rss/4/feed
**Config:** [scmp.com.txt](https://github.com/jangernert/FeedReader/files/2666688/scmp.com.txt)
`$ feedreader --verbose --grabArticle https://www.scmp.com/economy/china-economy/article/2177421/chinas-vice-president-vows-keep-strategic-focus-amid-mounting`
[smcp terminal.txt](https://github.com/jangernert/FeedReader/files/2666733/smcp.terminal.txt)
**Result:**
[China’s vice-president vows to keep ‘strategic focus’ amid mounting challenges of trade war.html](https://github.com/jangernert/FeedReader/files/2666697/China.s.vice-president.vows.to.keep.strategic.focus.amid.mounting.challenges.of.trade.war.html.txt)
[China’s vice-president vows to keep ‘strategic focus’ amid mounting challenges of trade war.txt](https://github.com/jangernert/FeedReader/files/2666695/China.s.vice-president.vows.to.keep.strategic.focus.amid.mounting.challenges.of.trade.war.txt)

On FeedReader:
![screenshot_20181211_165449](https://user-images.githubusercontent.com/40713728/49788963-b7160d00-fd65-11e8-9961-45e0df903f38.png)

## Example with config file included by default:
**Feed:** https://www.nytimes.com/services/xml/rss/nyt/World.xml
`feedreader --verbose --grabArticle "https://www.nytimes.com/2018/12/10/world/europe/macron-france-yellow-vests.html?partner=rss&emc=rss"`
[nytimes terminal.txt](https://github.com/jangernert/FeedReader/files/2666767/nytimes.terminal.txt)
**Result:**
[NULL.html](https://github.com/jangernert/FeedReader/files/2666771/NULL.html.txt)
[NULL.txt](https://github.com/jangernert/FeedReader/files/2666774/NULL.txt)

On FeedReader:
![screenshot_20181211_170901](https://user-images.githubusercontent.com/40713728/49789766-bb432a00-fd67-11e8-84f2-687a4a395753.png)

Version:
FeedReader 2.6.0 on Manjaro, compiled from AUR (https://aur.archlinux.org/packages/feedreader-git/), Local RSS
Also present on the version on Manjaro's repository (2.3.0)

**Comment by brendanlong** [comment]
50e50e67216dc9d3556afae5f7bef7e4b290ee73 changed the version of the grabber configs in our repo, but that was in v2.6.0, so if this is the same in v2.3.0 then it must be something different.

I need to look into this more since I don't use the content grabber (it was way too slow when I started using FeedReader).

**Comment by ksl1989** [comment]
Just to confirm: I have been using v2.3.0 for some time because it is the most recent version on Manjaro's repositories, with the results I mentioned. I only tried the version on AUR (2.6.0) today to check if the issue is still present. I saw no difference.

**Comment by sianhulo** [comment]
pages may change, if the elements on a page change, the previous configuration will stop working, that's on https://github.com/fivefilters/ftr-site-config (which this project pulls from).

**Comment by sianhulo** [comment]
also, testing with your config file I got the full article for the supplied scmp link, tested on 2.6.0, also from aur. do you see any `feedreader-CRITICAL`entries when running `feedreader --verbose --grabArticle https://www.scmp.com/economy/china-economy/article/2177421/chinas-vice-president-vows-keep-strategic-focus-amid-mounting` ?

**Comment by brendanlong** [comment]
I wonder if we should add an option somewhere to "re-grab" all articles to make things like this easier to debug. For now, it looks like this is working though?

**Comment by ksl1989** [comment]
This last few days it has been working but I have noticed it occasionally failing to load the content, when I can confirm with `--grabArticle` the config is working. One e.g.:

[HTML content from `--grabArticle`](https://github.com/jangernert/FeedReader/files/2683460/Seven.Civilians.Killed.as.Indian.Police.Fire.on.Kashmir.Protesters.html.txt)
Article on FeedReader:
![screenshot_20181216_184925](https://user-images.githubusercontent.com/40713728/50052747-d77a0900-0163-11e9-9b30-2290f4894de6.png)

I have several articles like this on the NYTimes Feed, but several other with full content, from the same feed, without changing any setting. I can't really reproduce this consistently and it's working well for the most part. I don't even know if it's the same issue that was preventing any content from being shown before.

I say keep this issue closed (unless more people report similar problems) and, yes, maybe working on making this this kind of issue easier to debug would be a good idea.

**Comment by sianhulo** [comment]
well, if a regrab function is under consideration I don't think it should be "regrab all", I think that'd bee to straining considering how many articles one may have. something for the current article, or maybe the current site feed might be preferable on that front.
