### ISSUE TITLE
All articles counter not updated

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#82]
All articles counter is not updated when i read an article, i have to update the article list to see the modification

**Comment by jangernert** [comment]
Could you elaborate further? I can not reproduce this behavior. And how do you update the article list manually?

**Comment by bil-elmoussaoui** [comment]
I'm using Feedly, when i read the an article by clicking on it on the article list or the keyboard shortcut, the all article counter changes but not the category/feed counter. I need to refresh the whole feed list in order to see the new counter

**Comment by jangernert** [comment]
Works for me. Is the feed in any of the special "global" categories of feedly and/or does it belong to multiple categories?
