### ISSUE TITLE
Article dates in article view showing up as the epoch

### ISSUE THREAD

**Issue by crackwilding** [jangernert/FeedReader#830]
Dates show up properly in the article list, but in the article view pane, they all show up as 1969-12-13, 7:00PM.

![listview](https://user-images.githubusercontent.com/1148293/50995628-9e784e80-14ed-11e9-806b-4ae9e876d379.png)

![articleview](https://user-images.githubusercontent.com/1148293/50995635-a2a46c00-14ed-11e9-87c6-125c0042e9dd.png)

**Comment by rusty-snake** [comment]
My version: 2.6.0.
What distro?

**Comment by crackwilding** [comment]
Pop OS

**Comment by crackwilding** [comment]
This might be of use:

fletch@elwood:/usr/bin$ apt-cache policy feed*
feedreader:
  Installed: 2.2-1
  Candidate: 2.2-1
  Version table:
 *** 2.2-1 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
        100 /var/lib/dpkg/status

I don't know who maintains the repos -- is there some way to prod them into updating?

**Comment by crackwilding** [comment]
Well, I installed flatpak and reinstalled feedreader that way. 2.6 now, all's well.

**Comment by brendanlong** [comment]
Just to confirm -- it seems like this was a problem with an old PopOS package and the latest version works? Closing this but let me know if I read that wrong.
