### ISSUE TITLE
Connecting with TT-RSS Instance not working - Server offline

### ISSUE THREAD

**Issue by Zocker1999NET** [jangernert/FeedReader#831]
- FeedReader Version: 2.6.1-1 from Debian Repository
- TT-RSS Version: Commit [70d9c7849a](https://git.tt-rss.org/fox/tt-rss/commit/70d9c7849a27d313a08bfbb7676ce16a5a2f2b4a) from Official Repository
- Using Nginx as reverse proxy and PHP-FPM as Interpreter
- Nginx is configured to only accept TLS requests, but forwards HTTP requests with status code 301 to the correct url with "https://" prefix

After installing FeedReader for the first time, I tried to sync it up with my own TT-RSS instance, therefore enabled the plugin for FeedReader. So I launched FeedReader, selected "Tiny Tiny RSS", inserted my url and login credentials, FeedReader changed to the main view and showed that my server is offline, which of course is not the case.
I tried to reconfigure FeedReader, used different formats for the url (`https://example.com/` vs `example.com`), but FeedReader cannot access my server.
The access and error log of Nginx do not show any access to TT-RSS while (re-)configuring FeedReader or pushing/spamming the "Reload" button. Direct access to the TT-RSS instance with Firefox was logged as expected.
I could not find any logs of FeedReader in my home directory, I only found the directories `.local/share/feedreader` and `.cache/feedreader` nearly empty.

--------

Screenshot of "Offline"-Screen in German:
![Screenshot](https://user-images.githubusercontent.com/1645646/51154231-69fced80-1873-11e9-96a6-b486565670c1.png)

Tree of `.local/share/feedreader`:
```
`-- data
    |-- feed_icons
    |   `-- LTc2.txt
    |-- feedreader-7.db
    |-- feedreader-7.db-shm
    `-- feedreader-7.db-wal
```

Tree of `.cache/feedreader`:
```
`-- WebKitCache
    `-- Version 13
        |-- Blobs
        `-- salt
```

**Comment by brendanlong** [comment]
I just made a bunch of TT-RSS improvements in v2.8.0 which should show up on Flathub within an hour or so. Can you see if this works for you now? The correct URL format should be something like `https://example.com/`

**Comment by brendanlong** [comment]
I'm going to close this since I think v2.8.0 should fix it, but please re-open this if you still see this problem.

**Comment by whoiscoos** [comment]
re-opening this issue. I am experiencing the same problem.
