### ISSUE TITLE
xsession-errors Inoreader (KDE Neon)

### ISSUE THREAD

**Issue by bipox** [jangernert/FeedReader#833]
Nextcloud articles are shown multiple times, so I tried connecting with an Inoreader account for testing. It detected the feeds but would show them as empty.

fatrace showed xsession-errors caused by Feedreader (85gb, until the ssd was full)

`(feedreader:2): feedreader-CRITICAL **: 00:23:08.005: dbErrorLog: 787: abort at 12 in [INSERT OR REPLACE INTO main.taggings (articleID, tagID) VALUES ($ARTICLEID, $TAGID)]: FOREIGN KEY constraint failed`

**Comment by brendanlong** [comment]
Which version of FeedReader are you using?

**Comment by bipox** [comment]
The flatpak version

org.gnome.FeedReader/x86_64/stable

**Comment by 39aldo39** [comment]
Since the error is caused by a failed `FOREIGN KEY constraint`, it should be fixed with #823 (after deleting `.local/share/feedreader` or similar in flatpak). But it looks like it isn't on flathub yet?

**Comment by brendanlong** [comment]
Is this fixed now? #823 and several other commits are released in Flathub now (the latest version is v2.7.1, which fixes a bunch of other database issues too).

**Comment by brendanlong** [comment]
Going to close this since it seems to be fixed. Please re-open if this is still a problem.
