### ISSUE TITLE
Crash when scrolling to the bottom of the article list

### ISSUE THREAD

**Issue by crackwilding** [jangernert/FeedReader#834]
Scroll to the bottom of the article list and (most of the time) the application quits. FeedReader 2.6.0 on Pop OS 18.10 / Gnome 3.30.2. I tailed the syslog and fiddled with it until it crashed. Results below:

Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.290: gdk_pixbuf_from_pixdata() called on:
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.291: #011Encoding raw
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.291: #011Dimensions: 14 x 14
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.291: #011Rowstride: 56, Length: 808
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.291: #011Copy pixels == false
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.348: gdk_pixbuf_from_pixdata() called on:
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.348: #011Encoding raw
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.348: #011Dimensions: 14 x 14
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.348: #011Rowstride: 56, Length: 808
Jan 18 09:58:09 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): GdkPixbuf-DEBUG: 09:58:09.348: #011Copy pixels == false
Jan 18 09:58:11 elwood org.gnome.FeedReader.desktop[2203]: Memory pressure relief: Total: res = 85463040/85434368/-28672, res+swap = 81170432/81170432/0
Jan 18 09:58:14 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): Gdk-WARNING **: 09:58:14.283: Can't set ParentRelative background for window 0x580f3a2, depth of parent doesn't match
Jan 18 09:58:14 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): Gdk-WARNING **: 09:58:14.360: Can't set ParentRelative background for window 0x5800007, depth of parent doesn't match
Jan 18 09:58:17 elwood /usr/lib/gdm3/gdm-x-session[1942]: (EE) event8  - SynPS/2 Synaptics TouchPad: kernel bug: Touch jump detected and discarded.
Jan 18 09:58:17 elwood /usr/lib/gdm3/gdm-x-session[1942]: See https://wayland.freedesktop.org/libinput/doc/1.12.1/touchpad-jumping-cursors.html for details
Jan 18 09:58:20 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): Gdk-WARNING **: 09:58:20.030: Can't set ParentRelative background for window 0x5810950, depth of parent doesn't match
Jan 18 09:58:20 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): Gdk-WARNING **: 09:58:20.269: Can't set ParentRelative background for window 0x5800007, depth of parent doesn't match
Jan 18 09:58:20 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): dconf-DEBUG: 09:58:20.321: change_fast
Jan 18 09:58:20 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): dconf-DEBUG: 09:58:20.321: change_notify: /org/gnome/feedreader/saved-state/articlelist-row-offset
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): feedreader-CRITICAL **: 09:58:23.666: dbErrorLog: 1: statement aborts at 1: [BEGIN TRANSACTION] cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: ** (feedreader:2): ERROR **: 09:58:23.666: SQLite.vala:76: Failed to execute simple query: 1: cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: SQL is: BEGIN TRANSACTION
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): feedreader-CRITICAL **: 09:58:23.666: dbErrorLog: 1: statement aborts at 1: [BEGIN TRANSACTION] cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: ** (feedreader:2): ERROR **: 09:58:23.666: SQLite.vala:76: Failed to execute simple query: 1: cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: SQL is: BEGIN TRANSACTION
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): feedreader-CRITICAL **: 09:58:23.697: dbErrorLog: 1: statement aborts at 1: [BEGIN TRANSACTION] cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: ** (feedreader:2): ERROR **: 09:58:23.697: SQLite.vala:76: Failed to execute simple query: 1: cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: SQL is: BEGIN TRANSACTION
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): feedreader-CRITICAL **: 09:58:23.697: dbErrorLog: 1: statement aborts at 1: [BEGIN TRANSACTION] cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: ** (feedreader:2): ERROR **: 09:58:23.697: SQLite.vala:76: Failed to execute simple query: 1: cannot start a transaction within a transaction
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: SQL is: BEGIN TRANSACTION
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (feedreader:2): feedreader-WARNING **: 09:58:23.703: FeedList.refreshCounters: counts don't match - allCount: 8 - feedCount: 7
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: message repeated 7 times: [ (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)]
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: DEBUG (recursed)(process:: 2): GLib-DEBUG (recursed)posix_spawn avoided (fd close requested) : posix_spawn avoided (fd close requested)
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: message repeated 13 times: [ (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)]
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (process:
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: 2(process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested) ): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:23 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: message repeated 30 times: [ (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)]
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: (process:
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: 2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested) (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: message repeated 60 times: [ (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)]
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: (process:
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: 2(process:): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested) 2(process:): 2GLib-): DEBUG (recursed)GLib: -posix_spawn avoided (fd close requested) DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: message repeated 122 times: [ (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested)]
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: (process:2): GLib-DEBUG (recursed): posix_spawn avoided (fd close requested) Error while executing 'addr2line -f -e /app/bin/feedreader 0x7fb721769525': Too many open files
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: Something went very wrong. Your stacktrace cannot be displayed
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: #033[2;37;41mAn error occured #033[1;37;41m(SIGABRT)#033[2;37;41m#033[0m
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]:    The reason is likely #033[1;37ma failed assertion (assert...)#033[0m.
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]:    #033[1;37mNote#033[0m: no file path and line numbers can be retrieved. Are you sure #033[1;37myou added -g -X -rdynamic#033[0m to valac command line?
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: Error while executing 'addr2line -f -e /app/bin/feedreader 0x7fb721769525': Too many open files
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: Something went very wrong. Your stacktrace cannot be displayed
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]: #033[2;37;41mAn error occured #033[1;37;41m(SIGABRT)#033[2;37;41m#033[0m
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]:    The reason is likely #033[1;37ma failed assertion (assert...)#033[0m.
Jan 18 09:58:24 elwood org.gnome.FeedReader.desktop[2203]:    #033[1;37mNote#033[0m: no file path and line numbers can be retrieved. Are you sure #033[1;37myou added -g -X -rdynamic#033[0m to valac command line?

**Comment by brendanlong** [comment]
Which backend plugin are you using?

**Comment by Strubbl** [comment]
I had the same bug with local feeds only

**Comment by crackwilding** [comment]
I'm sorry, where would I find which backend plugin I'm using?

**Comment by brendanlong** [comment]
You would have picked it when you first started using FeedReader. The options are local, Feedbin, Feedly, NextCloud, etc.

**Comment by crackwilding** [comment]
I'm about 99% certain I chose local; is there a way to determine for certain?

**Comment by jangernert** [comment]
The sidebar on the left has a big icon on top representing the backend. The local backend has just a generic RSS icon.

**Comment by crackwilding** [comment]
Oh, duh. It's huge, guess I should have noticed that. So yeah, local it is.

**Comment by brendanlong** [comment]
I made a major change in #843 to try to address crashes like this. Can you check if you get this error in the latest (v2.7.0)?

**Comment by brendanlong** [comment]
Cool, thanks!
