### ISSUE TITLE
Crash while opening image

### ISSUE THREAD

**Issue by haeckle** [jangernert/FeedReader#84]
I tried to view the last picture on http://www.basteiblog.de/2016/04/wie-war-das-noch-gleich-mit-dem-wiederaufbau/

This was the console-output:
 > [ DEBUG ] SELECT ROWID, feedID, articleID, title, author, url, preview, unread, marked, tags, date, guidHash FROM main.articles WHERE feedID = "284" AND unread = 9  ORDER BY date DESC LIMIT 20 OFFSET 0
> [ DEBUG ] actual articles loaded: 1
> [ DEBUG ] ArticleList: createHeadlineList finished
> [ DEBUG ] ArticleList: restore ScrollPos
> [ DEBUG ] contentPage: set headerbar
> [ DEBUG ] ArticleView: load article 118041
> [ DEBUG ] ArticleView: load STARTED
> [ DEBUG ] ArticleView: load COMMITTED
> [ DEBUG ] ArticleView: load FINISHED
> [ DEBUG ] path: /home/haeckle/.local/share/feedreader/data/images/284/118041/10
> [ DEBUG ] sizeX: 600,000000 sizeY: 604,000000
> [ DEBUG ] path: /home/haeckle/.local/share/feedreader/data/images/284/118041/10
> [ DEBUG ] sizeX: 600,000000 sizeY: 607,000000
> [ DEBUG ] path: /home/haeckle/.local/share/feedreader/data/images/284/118041/10
> [ DEBUG ] sizeX: 600,000000 sizeY: 635,000000
> 
> (feedreader:625): Gdk-WARNING **: feedreader: Fatal IO error 11 (Die Ressource ist zur Zeit nicht verfügbar) on X server :0.

last thing means "ressource not available"

> ~$ feedreader --version
> Version: 1.5 dev
> Git Commit: 5b28de4dd20c4dbc9d16cc38d01f9d6024801856
Using the git-package from AUR

**Comment by jangernert** [comment]
I can confirm the crash by spamming the imagepopup. But right now there are still bugs in the js-code that spawn multiple instances (in this case 4) of the imagepopup at once, which should not be possible at all. So I will close this down and you can report again if we finally figure out how to properly implement #34 ;)
