### ISSUE TITLE
No window shadow in Unity on Xenial

### ISSUE THREAD

**Issue by tsbarnes** [jangernert/FeedReader#85]
There doesn't seem to be a window background or shadow in Unity on Xenial, with the default Ambiance theme.  I've attached a screenshot and circled an area where you can see through the window (in the headerbar) and where you can clearly tell there's no shadow (bottom right corner).
![screenshot from 2016-04-20 19-51-06](https://cloud.githubusercontent.com/assets/429099/14693949/ee35066a-0731-11e6-9e86-d509448936b3.png)

**Comment by tsbarnes** [comment]
It's worth noting that no other applications do this, even if they use client-side decorations.

**Comment by jangernert** [comment]
"No other application"? What applications did you test with? In my experience this happens with all applications that use a split-headerbar. So for example gnome-tweak-tool. Can you test and see if you have the same issues with gnome-tweak-tool?

**Comment by tsbarnes** [comment]
I'll check, I hadn't tried GNOME Tweak Tool under Unity :)  For applications using header bars, I've tried gnome-calendar, gnome-todo, corebird, gnome-maps, gnome-weather, nautilus 3.18, geary, and go-for-it.  I had thought at least corebird and geary used split header bars, but looking at their code apparently they don't.

The Change Account page does have shadows, as you mentioned, so it is most likely just an issue with split header bars in general.  I'll assume it's a theme bug and close this issue :heavy_check_mark:

**Comment by jangernert** [comment]
Corebird does not use a split-headerbar, and geary in ubuntu has it's split-headerbar, but they act more like toolbars because there is another headerbar above that (guess some custom geary patches in ubuntu?)
![screenshot from 2016-04-21 22-55-15](https://cloud.githubusercontent.com/assets/12012494/14724185/d5948d04-0814-11e6-981b-fe58a9b9f359.jpg)
