### ISSUE TITLE
RSS 'author' is an email. 'dc:creator' is the author name

### ISSUE THREAD

**Issue by sdjacobs** [jangernert/FeedReader#853]
If "Local RSS" is selected, and you add an RSS feed, the author of the post will not be visible in the header next to the date.

This is because the "author" tag is being read for the post author in the RSS parser, but actually, "author" is the tag for the author's email. The correct tag for the author is "dc:creator:" See:
http://www.lowter.com/blogs/2008/2/9/rss-dccreator-author
https://cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt

I have a PR to fix this which I can submit, in the libmrss dependency. But I wonder why this library is included in the source -- should this be fixed upstream instead (e.g. at https://www.autistici.org/bakunin/libmrss/doc/)?

**Comment by brendanlong** [comment]
I think your fix makes sense, although it would be ideal if we could use `author_email` as a backup if we don't find an `author`. I'm happy to merge this PR though.

I agree that submitting the PR upstream makes sense too. I have no idea why we inlined this; maybe just to make FeedReader easier to build?
