### ISSUE TITLE
New articles cause the current article to be unselected

### ISSUE THREAD

**Issue by hfiguiere** [jangernert/FeedReader#869]
When FeedReader download new articles the currently being read article is deselected. And of course disappear from the list if you only show "Unread"

**Comment by brendanlong** [comment]
I think there's some generally-confusing behavior where whenever you change screens, articles that are marked as read are hidden. This is normally fine, but there are a few cases where switching screens is automatic (like when new articles appear).

Although the currently selected article generally shouldn't be removed. I'll try to make time to look into this sometime and see if I can make this less confusing. As a workaround, you can unmark the article you're currently reading until you're done reading it (unfortunately I don't think we have an option for that yet).

**Comment by hfiguiere** [comment]
In that case I had an article from the current feed display, but a FeedReader told me "there is a new article" and the current one I was reading disappeared (because marked as read AND deselected).

This also happened after I did add a new feed subscription.

**Comment by hfiguiere** [comment]
Also another situation is when FeedReader defer loading the articles. I have a feed that indicate 25 articles unread. I select it, there is one in the list, but when it loads the 24 others, the first one that I started reading gets deselected, thus interrupting my reading.

**Comment by brendanlong** [comment]
This should get fixed in #907

**Comment by brendanlong** [comment]
This will be released in v2.10
