### ISSUE TITLE
Gap between collapsed categories

### ISSUE THREAD

**Issue by pank** [jangernert/FeedReader#87]
Hi,

Collapsed categories have unequal space between them.  It seems to grow with the number of feeds in the category.  As I can open feeds in a category, it might be a feature.

Here's a screenshot:

![screenshot from 2016-04-26 18-01-58](https://cloud.githubusercontent.com/assets/666845/14825224/48fabc4c-0bd9-11e6-8c7f-450268831890.png)

Thanks,
Rasmus

**Comment by bil-elmoussaoui** [comment]
It's an issue with Gtk 3.20! I'm working on it
