### ISSUE TITLE
Version 2.8.2 hangs when press Settings

### ISSUE THREAD

**Issue by tim77** [jangernert/FeedReader#875]
FeedReader 2.8.1 was fine and now when i press `Settings` app hangs.

https://bodhi.fedoraproject.org/updates/FEDORA-2019-187890a1df#comment-894177

**Comment by tim77** [comment]
Sorry after reboot it seems like it works but this is weird. I am sure app was closed when updating it. 🤷‍♂️

**Comment by brendanlong** [comment]
Hm works for me too. I'm going to assume something weird happened during the update. Let me know if you see this again.
