### ISSUE TITLE
open in browser button

### ISSUE THREAD

**Issue by pank** [jangernert/FeedReader#89]
Hi,

I can double click on an entry or on the title to open an article in the browser.
I would be nice to have a dedicated button for opening in the browser, e.g. next to the tagging and sharing icons.

Thanks,
Rasmus

**Comment by jangernert** [comment]
As you already listed, there are 2 ways to open the current article in the browser. 3 if you count copying the URL and pasting it into the browser. I don't think there needs to be a 4th way to do the same thing. Also this would unnecessarily clutter the headerbar.
