### ISSUE TITLE
cant add rss feed from specific website after i already added two feeds from the same website

### ISSUE THREAD

**Issue by klein-benjamin** [jangernert/FeedReader#899]
I tried adding several feeds from the website sueddeutsche.de: [link to feeds](https://www.sueddeutsche.de/service/updates-mit-rss-uebersicht-aller-rss-feeds-fuer-szde-sz-magazin-und-jetztde-1.393950)
I was able to add two feeds (Topthemen and Politik) but after that [this](https://imgur.com/a/WA8hxvT) happens when I add another feed from the website. Other feeds from different sites work fine. I tried ading the same two Feeds again that wroked before. Same error.

[System info](https://imgur.com/a/Nv1z91J)

**Comment by LuisReinoso** [comment]
I had the same error. :crying_cat_face:

**Comment by brendanlong** [comment]
Hm in the latest version we get a better error, that it thinks the feed already exists. I'm trying to figure out why though:

![Screenshot from 2019-05-24 14-14-55](https://user-images.githubusercontent.com/1447206/58348303-53246400-7e2e-11e9-9f9d-62bb8d27344f.png)

**Comment by brendanlong** [comment]
I changed the logic in ef4a9c618c287af7ea87f6eba14a9e0b2cedc7ee to just use the link we're given instead of looking at the one in the RSS feed. This should be available in the v2.9.0 release
