### ISSUE TITLE
Add Inoreader service

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#9]
It would be great if you can add Inoreader service like you did for Feedly.

https://www.inoreader.com/developers/

**Comment by kanishkablack** [comment]
Just kick started development to support inoreader

**Comment by jangernert** [comment]
@kanishkablack did you see the inoreader branch?
The backend is nearly complete. Only deleting/creating new tags is missing. After that maybe see if the article-sync code can be improved more.

**Comment by bil-elmoussaoui** [comment]
Fixed in #33
