### ISSUE TITLE
Article Oldest First sorting doesn't work

### ISSUE THREAD

**Issue by tobip** [jangernert/FeedReader#901]
In Settings, under Article List, when I change the "Oldest First" switch, nothing happens at all.
Articles are sorted newest-first in my window, and I would like to have them oldest-first.

**Comment by brendanlong** [comment]
Hmm this may be a bug in the "All" tab. It looks like this works correctly on the "Unread" tab.

**Comment by brendanlong** [comment]
It looks like this was intentional, but I agree that it's confusing. I opened #902 to get @jangernert's opinion on this.

**Comment by tobip** [comment]
> Hmm this may be a bug in the "All" tab. It looks like this works correctly on the "Unread" tab.

Ah true! Yes it works in the Unread tab, which is perfect for me.
Maybe just a small hint in the settings would already be enough to avoid any confusion.
