### ISSUE TITLE
Support podcast

### ISSUE THREAD

**Issue by pank** [jangernert/FeedReader#91]
Hi,

It would be nice if FR would indicate when an article contains a podcast and maybe offer to open it an audio player.

Thanks,
Rasmus

**Comment by jangernert** [comment]
Never subscribed to any podcasts via tt-rss but it seems like the media-links are in the article-json of feedly, inoreader and tt-rss (still have to test owncloud)

* tt-rss

`{
	"seq":0,
	"status":0,
	"content":
	[
		{
			"id":"124222",
			"title":"Raab Privat (01): Fr\u00fchst\u00fcck",
			"link":"http:\/\/www.swr3.de\/comedy\/comedy-archiv\/Raab-Privat-01-Fruehstueck\/-\/id=47438\/did=3404356\/y9cy8n\/index.html",
			"labels":[],
			"unread":true,
			"marked":false,
			"published":false,
			"comments":"",
			"author":"",
			"updated":1438588500,
			"content":"<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?>\n<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD HTML 4.0 Transitional\/\/EN\" \"http:\/\/www.w3.org\/TR\/REC-html40\/loose.dtd\">\n<html><head><meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\"\/><\/head><body><p>Raab Privat (01): Fr\u00fchst\u00fcck\n...<\/p><\/body><\/html>\n",
			"feed_id":"128",
			"attachments":
			[
				{
					"id":"18138",
					"content_url":"http:\/\/mp3-download.swr3.de\/comix\/raab-privat\/20150803\/801506.12844s.mp3",
					"content_type":"audio\/mpeg",
					"title":"",
					"duration":"0",
					"post_id":"124222"
				}
			],
			"score":0,
			"feed_title":"SWR3 Raab privat | SWR3.de",
			"note":null,
			"lang":""
		}
	]
}`

**Comment by jangernert** [comment]
Feature is almost done. Attachments-links are extracted and written to the database, there is now a new button in the headerbar that launches a popover with all attachments listed and there is a small overlay-player to stream audio- or video-attachments.

All that is missing is: a option to decide whether to use the internal overlay or to open it up in the default system player.

![screenshot from 2016-08-05 01-17-03](https://cloud.githubusercontent.com/assets/12012494/17421569/0dec6c92-5aab-11e6-91a9-83dc2629f1ac.png)

**Comment by jangernert** [comment]
done
