### ISSUE TITLE
tt-rss protected with basic auth does not work

### ISSUE THREAD

**Issue by yann-soubeyrand** [jangernert/FeedReader#917]
Hi,

Connecting to a tt-rss instance protected by basic auth does not seem to work.

Feedreader does not allow the couple username + password to be empty, which is however possible in tt-rss if you use external authentication from basic auth.

In addition, it doesn't seem to send the basic auth credentials it has asked after the first authentication attempt failed. I keep getting `"POST /api/ HTTP/1.1" 401 932 "-" "FeedReader 2.9.2"` in Apache logs.

**Comment by brendanlong** [comment]
The "accept empty user name and password" thing seems like it's probably easy to fix. I'm not sure how hard the second part will be.

**Comment by auscompgeek** [comment]
I took a look - it looks like the HTTP auth inputs aren't being saved at all.

**Comment by jangernert** [comment]
I think basic auth was only tested with owncloud, so writing of the auth data is missing:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/ttrss/ttrssInterface.vala#L183
compared to here:
https://github.com/jangernert/FeedReader/blob/master/plugins/backend/owncloud/OwncloudNewsInterface.vala#L64

**Comment by brendanlong** [comment]
Hm I think there's just a bug where we're mixing up the htaccess user and normal user. I think I can fix this.

**Comment by brendanlong** [comment]
Ahh I see. We have some stuff setup for this but there's now way to view the input box.

**Comment by brendanlong** [comment]
I think the problem is that the Htmlclean library is being too aggressive, and removing even escaped HTML :\

**Comment by auscompgeek** [comment]
Still doesn't work for me.

**Comment by auscompgeek** [comment]
Never mind, helps if I actually install what I built.
