### ISSUE TITLE
Sandbox DConf settings in Flatpak

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#920]
When you use the Flatpak version of Feedreader, it has its own database, separate from any non-Flatpak install, but the settings (including who you're logged in as) are stored globally. This is particularly annoying for testing, although it's also convenient in some ways (easier to change these settings).

This blog post suggests a new method for sandboxing the settings:

https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

I think we should probably do this, although we may need to figure out how to edit these settings if people ask. I know I use dconf directly to set keybindings (I keep meaning to add a way to do this in the normal settings).

**Comment by bilelmoussaoui** [comment]
Actually, we won't need to do anything other than removing the permissions. This will break Inspector for us but we can remove dconf access only from Flathub's manifest for now.

**Comment by bilelmoussaoui** [comment]
Fixed here https://github.com/flathub/org.gnome.FeedReader/pull/14
