### ISSUE TITLE
Support Server Side Decoration (SSD) layout

### ISSUE THREAD

**Issue by alxlg** [jangernert/FeedReader#930]
Would it be possible to do the same of Drawing app ([link](https://flathub.org/apps/details/com.github.maoschanz.drawing)) i.e. detect if the current DE/WM uses Server Side Decoration, disable Client Side Decoration (CSD), and make the header bar look and feel like a toolbar?

This is how Drawing looks on KDE Plasma/KWin that uses SSD Instead of CSD (while it's still possible to drag the window from the headerbar/toolbar the right click menu on it is disabled):
![immagine](https://user-images.githubusercontent.com/26327475/62355229-e05ef580-b50e-11e9-85a5-c7fda792180f.png)

**Comment by bilelmoussaoui** [comment]
I'm not sure we want to have this. What do you think @brendanlong?

**Comment by alxlg** [comment]
Why shouldn't you want it? Would you accept pull requests?

**Comment by bilelmoussaoui** [comment]
@alxlg the difference between Drawing & FeedReader is that Drawing basically uses UI files. Switching between a file that uses a layout to another one is pretty straightforward. While on FeedReader we write the widgets "manually", it would require a bit of work and none of the three maintainers have enough time to look at it currently.

**Comment by bilelmoussaoui** [comment]
Closing this as a won't fix. FeedReader is in maintenance mode anyway, it won't gain any new features.
