### ISSUE TITLE
Link-on-hover is unreadable (white on white)

### ISSUE THREAD

**Issue by trwnh** [jangernert/FeedReader#932]
Steps to reproduce:
1. Hover over a link in an article

Expected behavior:
- The link is readable

Actual behavior:
- The link is white text with no background, thus unreadable

---

The only theme that the text is readable on is the Midnight theme.

**Comment by jangernert** [comment]
The overlay uses the `osd` style class. I'm guessing a custom theme you are using is messing things up here.
Basically: users are allowed to theme their desktop the way they like, but should not hold app developers accountable for complications with `random theme X`.
https://stopthemingmy.app/

**Comment by trwnh** [comment]
IMO app developers should use GTK stylesheets ( related: https://github.com/jangernert/FeedReader/issues/299#issuecomment-521345016 ) which would also solve the issue.

**Comment by trwnh** [comment]
FWIW I've gone ahead and filed https://github.com/nana-4/materia-theme/issues/419 and made https://github.com/nana-4/materia-theme/pull/420 for Materia, so I'm fine with closing this issue as a duplicate of https://github.com/jangernert/FeedReader/issues/299#issuecomment-521345016 for now.

To anyone else reading this, my current workaround is to add the following to `~/.config/gtk-3.0/gtk.css`:

```css
label.osd {background: #2C2C2C; opacity: 0.9}
```
