### ISSUE TITLE
Moving from one entry to another in the feed is extremely slow

### ISSUE THREAD

**Issue by Sesivany** [jangernert/FeedReader#944]
After the last update to v2.10 moving from one entry to another in the feed is very slow, looks like there is some performance issue. Not sure if it's caused by changes in FeedReader itself or in one of its dependencies (WebKit...), but I experience it both in FeedReader from Fedora 31 repositories and Flathub.

**Comment by bilelmoussaoui** [comment]
Nothing was updated from our side other than updating the dependencies & the runtime. Probably something changed in WebKit.

**Comment by Sesivany** [comment]
Could it by any chance be problems with the same API changes in WebKit Evolution is having now? Just wondering... https://gitlab.gnome.org/GNOME/evolution/issues/587

**Comment by jangernert** [comment]
Do we want to solve this? I guess it's an unavoidable problem for traditional packaged versions. For the flatpak we could just revert to the previous Gnome runtime.

**Comment by bilelmoussaoui** [comment]
Seems to be a webkit issue here https://bugs.webkit.org/show_bug.cgi?id=201451
