### ISSUE TITLE
2.10.0: build fails

### ISSUE THREAD

**Issue by kloczek** [jangernert/FeedReader#949]
<pre>[54/316] valac -C --debug --vapidir=/home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi --pkg linux --pkg posix /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/gd-1.0.vapi /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/htmlclean.vapi /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/gtkimageview.vapi --pkg posix --pkg goa-1.0 --pkg libxml-2.0 --pkg libpeas-1.0 --pkg gstreamer-pbutils-1.0 --pkg gstreamer-1.0 --pkg webkit2gtk-4.0 --pkg rest-0.7 --pkg libsecret-1 --pkg gee-0.8 --pkg sqlite3 --pkg libsoup-2.4 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg glib-2.0 --color=always --directory FeedReader@sha --basedir ../ --library FeedReader --header FeedReader.h --vapi ../FeedReader.vapi --enable-experimental --target-glib 2.52 --enable-deprecated ../src/FavIcon.vala ../src/FeedReader.vala ../src/Password.vala ../src/SQLite.vala ../src/Widgets/AddPopover.vala ../src/Widgets/ArticleRow.vala ../src/Widgets/ArticleView.vala ../src/Widgets/ArticleViewHeader.vala ../src/Widgets/ArticleViewLoadProgress.vala ../src/Widgets/ArticleViewUrlOverlay.vala ../src/Widgets/BackendInfoPopover.vala ../src/Widgets/CategorieRow.vala ../src/Widgets/ColorCircle.vala ../src/Widgets/ColorPopover.vala ../src/Widgets/ColumnView.vala ../src/Widgets/ColumnViewHeader.vala ../src/Widgets/FeedList.vala ../src/Widgets/FeedListFooter.vala ../src/Widgets/FeedRow.vala ../src/Widgets/FullscreenButton.vala ../src/Widgets/FullscreenHeader.vala ../src/Widgets/HoverButton.vala ../src/Widgets/ImagePopup.vala ../src/Widgets/InAppNotification.vala ../src/Widgets/InfoBar.vala ../src/Widgets/LoginPage.vala ../src/Widgets/LoginRow.vala ../src/Widgets/MainWindow.vala ../src/Widgets/MediaPlayer.vala ../src/Widgets/MediaButton.vala ../src/Widgets/MediaRow.vala ../src/Widgets/ModeButton.vala ../src/Widgets/RemovePopover.vala ../src/Widgets/ResetPage.vala ../src/Widgets/ServiceSettingsPopover.vala ../src/Widgets/ShareRow.vala ../src/Widgets/ShortcutsWindow.vala ../src/Widgets/ServiceInfo.vala ../src/Widgets/Setting.vala ../src/Widgets/SettingsDialog.vala ../src/Widgets/SharePopover.vala ../src/Widgets/SimpleHeader.vala ../src/Widgets/SpringCleanPage.vala ../src/Widgets/TagRow.vala ../src/Widgets/TagPopover.vala ../src/Widgets/TagPopoverRow.vala ../src/Widgets/UpdateButton.vala ../src/Widgets/WebLoginPage.vala ../src/Widgets/ArticleList/ArticleList.vala ../src/Widgets/ArticleList/ArticleListBox.vala ../src/Widgets/ArticleList/ArticleListEmptyLabel.vala ../src/Widgets/ArticleList/ArticleListScroll.vala ../src/Share/share.vala ../src/Share/ServiceSetup.vala ../src/Share/ShareAccountInterface.vala ../src/Logger.vala ../src/Enums.vala ../src/DataBaseReadOnly.vala ../src/ListUtils.vala ../src/Rfc822.vala ../src/Settings.vala ../src/StringUtils.vala ../src/Structs.vala ../src/Utils.vala ../src/QueryBuilder.vala ../src/ContentGrabber/grabberUtils.vala ../src/ContentGrabber/stringPair.vala ../src/Model/Feed.vala ../src/Model/Category.vala ../src/Model/Enclosure.vala ../src/Model/Article.vala ../src/Model/Tag.vala ../src/Model/CachedAction.vala ../src/Model/InterfaceState.vala ../src/Model/ShareAccount.vala ../src/ActionCache.vala ../src/Backend/Backend.vala ../src/DataBaseWriteAccess.vala ../src/Notification.vala ../src/CachedActionManager.vala ../src/Backend/FeedServer.vala ../src/Backend/FeedServerInterface.vala ../src/Backend/OPMLparser.vala ../src/ContentGrabber/grabberConfig.vala ../src/ContentGrabber/grabber.vala Constants.vala libraries/libIvy/ivy.vapi
FAILED: FeedReader@sha/src/FavIcon.c FeedReader@sha/src/FeedReader.c FeedReader@sha/src/Password.c FeedReader@sha/src/SQLite.c FeedReader@sha/src/Widgets/AddPopover.c FeedReader@sha/src/Widgets/ArticleRow.c FeedReader@sha/src/Widgets/ArticleView.c FeedReader@sha/src/Widgets/ArticleViewHeader.c FeedReader@sha/src/Widgets/ArticleViewLoadProgress.c FeedReader@sha/src/Widgets/ArticleViewUrlOverlay.c FeedReader@sha/src/Widgets/BackendInfoPopover.c FeedReader@sha/src/Widgets/CategorieRow.c FeedReader@sha/src/Widgets/ColorCircle.c FeedReader@sha/src/Widgets/ColorPopover.c FeedReader@sha/src/Widgets/ColumnView.c FeedReader@sha/src/Widgets/ColumnViewHeader.c FeedReader@sha/src/Widgets/FeedList.c FeedReader@sha/src/Widgets/FeedListFooter.c FeedReader@sha/src/Widgets/FeedRow.c FeedReader@sha/src/Widgets/FullscreenButton.c FeedReader@sha/src/Widgets/FullscreenHeader.c FeedReader@sha/src/Widgets/HoverButton.c FeedReader@sha/src/Widgets/ImagePopup.c FeedReader@sha/src/Widgets/InAppNotification.c FeedReader@sha/src/Widgets/InfoBar.c FeedReader@sha/src/Widgets/LoginPage.c FeedReader@sha/src/Widgets/LoginRow.c FeedReader@sha/src/Widgets/MainWindow.c FeedReader@sha/src/Widgets/MediaPlayer.c FeedReader@sha/src/Widgets/MediaButton.c FeedReader@sha/src/Widgets/MediaRow.c FeedReader@sha/src/Widgets/ModeButton.c FeedReader@sha/src/Widgets/RemovePopover.c FeedReader@sha/src/Widgets/ResetPage.c FeedReader@sha/src/Widgets/ServiceSettingsPopover.c FeedReader@sha/src/Widgets/ShareRow.c FeedReader@sha/src/Widgets/ShortcutsWindow.c FeedReader@sha/src/Widgets/ServiceInfo.c FeedReader@sha/src/Widgets/Setting.c FeedReader@sha/src/Widgets/SettingsDialog.c FeedReader@sha/src/Widgets/SharePopover.c FeedReader@sha/src/Widgets/SimpleHeader.c FeedReader@sha/src/Widgets/SpringCleanPage.c FeedReader@sha/src/Widgets/TagRow.c FeedReader@sha/src/Widgets/TagPopover.c FeedReader@sha/src/Widgets/TagPopoverRow.c FeedReader@sha/src/Widgets/UpdateButton.c FeedReader@sha/src/Widgets/WebLoginPage.c FeedReader@sha/src/Widgets/ArticleList/ArticleList.c FeedReader@sha/src/Widgets/ArticleList/ArticleListBox.c FeedReader@sha/src/Widgets/ArticleList/ArticleListEmptyLabel.c FeedReader@sha/src/Widgets/ArticleList/ArticleListScroll.c FeedReader@sha/src/Share/share.c FeedReader@sha/src/Share/ServiceSetup.c FeedReader@sha/src/Share/ShareAccountInterface.c FeedReader@sha/src/Logger.c FeedReader@sha/src/Enums.c FeedReader@sha/src/DataBaseReadOnly.c FeedReader@sha/src/ListUtils.c FeedReader@sha/src/Rfc822.c FeedReader@sha/src/Settings.c FeedReader@sha/src/StringUtils.c FeedReader@sha/src/Structs.c FeedReader@sha/src/Utils.c FeedReader@sha/src/QueryBuilder.c FeedReader@sha/src/ContentGrabber/grabberUtils.c FeedReader@sha/src/ContentGrabber/stringPair.c FeedReader@sha/src/Model/Feed.c FeedReader@sha/src/Model/Category.c FeedReader@sha/src/Model/Enclosure.c FeedReader@sha/src/Model/Article.c FeedReader@sha/src/Model/Tag.c FeedReader@sha/src/Model/CachedAction.c FeedReader@sha/src/Model/InterfaceState.c FeedReader@sha/src/Model/ShareAccount.c FeedReader@sha/src/ActionCache.c FeedReader@sha/src/Backend/Backend.c FeedReader@sha/src/DataBaseWriteAccess.c FeedReader@sha/src/Notification.c FeedReader@sha/src/CachedActionManager.c FeedReader@sha/src/Backend/FeedServer.c FeedReader@sha/src/Backend/FeedServerInterface.c FeedReader@sha/src/Backend/OPMLparser.c FeedReader@sha/src/ContentGrabber/grabberConfig.c FeedReader@sha/src/ContentGrabber/grabber.c FeedReader@sha/x86_64-redhat-linux-gnu/Constants.c FeedReader.h FeedReader.vapi 
valac -C --debug --vapidir=/home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi --pkg linux --pkg posix /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/gd-1.0.vapi /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/htmlclean.vapi /home/tkloczko/rpmbuild/BUILD/FeedReader-2.10.0/vapi/gtkimageview.vapi --pkg posix --pkg goa-1.0 --pkg libxml-2.0 --pkg libpeas-1.0 --pkg gstreamer-pbutils-1.0 --pkg gstreamer-1.0 --pkg webkit2gtk-4.0 --pkg rest-0.7 --pkg libsecret-1 --pkg gee-0.8 --pkg sqlite3 --pkg libsoup-2.4 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg glib-2.0 --color=always --directory FeedReader@sha --basedir ../ --library FeedReader --header FeedReader.h --vapi ../FeedReader.vapi --enable-experimental --target-glib 2.52 --enable-deprecated ../src/FavIcon.vala ../src/FeedReader.vala ../src/Password.vala ../src/SQLite.vala ../src/Widgets/AddPopover.vala ../src/Widgets/ArticleRow.vala ../src/Widgets/ArticleView.vala ../src/Widgets/ArticleViewHeader.vala ../src/Widgets/ArticleViewLoadProgress.vala ../src/Widgets/ArticleViewUrlOverlay.vala ../src/Widgets/BackendInfoPopover.vala ../src/Widgets/CategorieRow.vala ../src/Widgets/ColorCircle.vala ../src/Widgets/ColorPopover.vala ../src/Widgets/ColumnView.vala ../src/Widgets/ColumnViewHeader.vala ../src/Widgets/FeedList.vala ../src/Widgets/FeedListFooter.vala ../src/Widgets/FeedRow.vala ../src/Widgets/FullscreenButton.vala ../src/Widgets/FullscreenHeader.vala ../src/Widgets/HoverButton.vala ../src/Widgets/ImagePopup.vala ../src/Widgets/InAppNotification.vala ../src/Widgets/InfoBar.vala ../src/Widgets/LoginPage.vala ../src/Widgets/LoginRow.vala ../src/Widgets/MainWindow.vala ../src/Widgets/MediaPlayer.vala ../src/Widgets/MediaButton.vala ../src/Widgets/MediaRow.vala ../src/Widgets/ModeButton.vala ../src/Widgets/RemovePopover.vala ../src/Widgets/ResetPage.vala ../src/Widgets/ServiceSettingsPopover.vala ../src/Widgets/ShareRow.vala ../src/Widgets/ShortcutsWindow.vala ../src/Widgets/ServiceInfo.vala ../src/Widgets/Setting.vala ../src/Widgets/SettingsDialog.vala ../src/Widgets/SharePopover.vala ../src/Widgets/SimpleHeader.vala ../src/Widgets/SpringCleanPage.vala ../src/Widgets/TagRow.vala ../src/Widgets/TagPopover.vala ../src/Widgets/TagPopoverRow.vala ../src/Widgets/UpdateButton.vala ../src/Widgets/WebLoginPage.vala ../src/Widgets/ArticleList/ArticleList.vala ../src/Widgets/ArticleList/ArticleListBox.vala ../src/Widgets/ArticleList/ArticleListEmptyLabel.vala ../src/Widgets/ArticleList/ArticleListScroll.vala ../src/Share/share.vala ../src/Share/ServiceSetup.vala ../src/Share/ShareAccountInterface.vala ../src/Logger.vala ../src/Enums.vala ../src/DataBaseReadOnly.vala ../src/ListUtils.vala ../src/Rfc822.vala ../src/Settings.vala ../src/StringUtils.vala ../src/Structs.vala ../src/Utils.vala ../src/QueryBuilder.vala ../src/ContentGrabber/grabberUtils.vala ../src/ContentGrabber/stringPair.vala ../src/Model/Feed.vala ../src/Model/Category.vala ../src/Model/Enclosure.vala ../src/Model/Article.vala ../src/Model/Tag.vala ../src/Model/CachedAction.vala ../src/Model/InterfaceState.vala ../src/Model/ShareAccount.vala ../src/ActionCache.vala ../src/Backend/Backend.vala ../src/DataBaseWriteAccess.vala ../src/Notification.vala ../src/CachedActionManager.vala ../src/Backend/FeedServer.vala ../src/Backend/FeedServerInterface.vala ../src/Backend/OPMLparser.vala ../src/ContentGrabber/grabberConfig.vala ../src/ContentGrabber/grabber.vala Constants.vala libraries/libIvy/ivy.vapi
<b>../src/Backend/Backend.vala:318.4-318.20:</b> <font color="#75507B"><b>warning:</b></font> delegates with scope=&quot;async&quot; must be owned
			ThreadFunc&lt;void*&gt; run = () =&gt; {
			<font color="#4E9A06"><b>^^^^^^^^^^^^^^^^^</b></font>
<b>../src/Backend/FeedServer.vala:60.98-60.148:</b> <font color="#CC0000"><b>error:</b></font> The name <b>`COLLECTION_CREATE_NONE&apos;</b> does not exist in the context of <b>`Secret.CollectionCreateFlags&apos;</b>
					secrets = Secret.Collection.create_sync(secret_service, &quot;Login&quot;, Secret.COLLECTION_DEFAULT, Secret.CollectionCreateFlags.COLLECTION_CREATE_NONE);
					                                                                                            <font color="#4E9A06"><b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
Compilation failed: 1 error(s), 1 warning(s)
ninja: build stopped: subcommand failed.
</pre>

**Comment by bilelmoussaoui** [comment]
https://github.com/jangernert/FeedReader/pull/943

**Comment by kloczek** [comment]
Thank you :)
