### ISSUE TITLE
Why did I migrate to Rust?

### ISSUE THREAD

**Issue by gavr123456789** [jangernert/FeedReader#979]
Can you please describe the pros and cons of vala development that you encountered? And why he left in the end. I am now considering this language.

**Comment by jangernert** [comment]
The biggest plus of Vala in my opinion is the great experience when writing Gtk interfaces or generally interacting with gnome libraries. However, it is quite easy to write bad code in Vala that e.g. leaks memory. When everything works as intended Vala is great. But as soon as something goes wrong I find it quite hard to understand what goes on behind the scenes.
Rust on the other hand forces you to handle errors and the compiler makes sure you're not doing obviously bad things. For better or for worse. So it is quite a bit more work to write rust if you're not used to it. But it teaches you how things in your program actually work and how memory is handled.
Also the crate ecosystem is pretty cool. You'll find a crate for pretty much everything you need.
The downside of rust is definitely doing things for which you need to work around rusts ownership model. And GUIs are one example for this.
